### ISSUE TITLE
Leeches

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#100]
Neutral mob. Has two states, hungry and full, each with a different model. Uses the thin model when hungry, and in this state will attack the player and any other mob nearby. It will stick onto them as if draining blood, and drains half a heart for 10 seconds or something like that. It would be cool if it used redstone particles when doing this to look like blood. It then becomes full and switches to it's fatter looking model. When full, it just wanders around not really doing anything, but becomes hungry again after a period of time. Maybe 5 minutes.

**Comment by vadis365** [comment]
I did something very similar for the Erebus with leeches - I'll port the code and we can change it to fit this. You don't actually need 2 models the size is changed in the rendering.
I'll get on this tonight (Tuesday 24th).

**Comment by MrCompost** [comment]
Ah ok. I'll make a mental note to self to remember that.

**Comment by PCAwesomeness** [comment]
Is the Leech 100% done?

**Comment by MrCompost** [comment]
I think so =)

**Comment by MrCompost** [comment]
On second thoughts, just a couple of minor things. I think they become hungry again too quickly atm.
