### ISSUE TITLE
Client Failed to start- -java.lang.NoClassDefFoundError: thebetweenlands/core/TheBetweenlandsPreconditions

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#1000]
#### Betweenlands version: 

TheBetweenlands-3.5.7-universal

#### Forge version:

forge-1.12.2-14.23.5.2847-universal

#### Singleplayer or Multiplayer:

Starting the game, have not logged in yet.

#### Installed mods:

https://www.curseforge.com/minecraft/modpacks/ancient-towncraft

## Link to full crash log

https://gist.github.com/ProsperCraft/a4803e6e96b46b7a55819365c02f15fd

#### How to reproduce:

1. This started right after I updated Ancient TownCraft on the first load, 
2. The second load did not have this issue.

**Comment by pau101** [comment]
Why have you posted this as a new issue, making a duplicate? You contributed in #995
