### ISSUE TITLE
Roguelike adventures and dungeons problem caused by The Betweenlands mod.

### ISSUE THREAD

**Issue by ciptnis** [TheCyberBrick/The-Betweenlands#1001]
#### Betweenlands version:
i dont know what version of this mod roguelike adventures and dungeons uses.

#### Forge version:
14.23.5.2838

#### Installed mods:
i dont know what mods it has but here is the website : https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons

## Link to full crash log
https://paste.dimdev.org/lacimofaro.mccrash

## Description of the problem

I tried to download and play the mod pack Roguelike Adventures and dungeon, but after i downloaded it and started it up it said that there was a problem that was caused by the mod The Betweenlands and it told me to send you this crash report to find the problem.

**Comment by TheCyberBrick** [comment]
Please send us your log.
1)
![](https://i.imgur.com/K4BUivG.png)
2)
![](https://i.imgur.com/Qrcl3Va.png)
3)
![](https://i.imgur.com/RyNGbDt.png)
You can then upload it to somewhere like e.g. https://pastebin.com/, or send it to us on our discord.

**Comment by Guxxish** [comment]
Fixed.. Download the latest release from the website here, then replace the one in the mod folder (Go to Twitch app, open RAD folder, go to mods folder, drag in new download of Betweenlands, replace). Fixed it for me.

**Comment by TheCyberBrick** [comment]
Which website? The development builds on github are not intended for regular use, they are unfinished and may break stuff
