### ISSUE TITLE
custom Item models don't load

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1003]
I tried everything, the textures load but the .json model doesn't. resource

 pack attached 
[betweenlands keyblade.zip](https://github.com/Angry-Pixel/The-Betweenlands/files/4371625/betweenlands.keyblade.zip)

**Comment by TheCyberBrick** [comment]
The folder must be called "thebetweenlands" not "betweenlands"

**Comment by TheCyberBrick** [comment]
And the model file names are also incorrect.

**Comment by TheCyberBrick** [comment]
There's only one valonite sword model file: https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/resources/assets/thebetweenlands/models/item/valonite_sword.json

**Comment by TheCyberBrick** [comment]
There is one main model file for the sword: https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/resources/assets/thebetweenlands/models/item/valonite_sword.json.
And this model selects the others depending on which gem it has and how corroded it is.

**Comment by ghost** [comment]
thanks
