### ISSUE TITLE
Suggestion: Config options for frequency/duration of world events

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#1004]
It's always either dark, raining, or foggy. Rarely, it seems, do I ever get some clear weather in the dimension. I'd like to be able to adjust how often/long these weather events appear/last. 

Some things aren't necessarily weather-related, e.g., blood skies and auroras. It'd be nice to be able to adjust these as well, say, for the dedicated players who want more of a challenge. ;)

**Comment by TheCyberBrick** [comment]
Going to C&P this from somewhere else:
> The BL config is already getting quite large and imo a bit out of hand, so I'd rather avoid adding more (at least non-compat) config options.

Now that there is a gamerule to disable events changing it should be possible to achieve what you want with command blocks.
