### ISSUE TITLE
Server Restart from Show Terrain Gen

### ISSUE THREAD

**Issue by Nonsanity** [TheCyberBrick/The-Betweenlands#1006]
# Versions
#### Betweenlands version:
3.5.6

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Multiplayer - server crash

#### Installed mods:
Included in crash log (318)

## Link to full crash log
https://pastebin.com/sFXDEL9F

#### How to reproduce:
Was near a small ruin with my inventory open, sorting through some loot from broken jars when the server watchdog was triggered and auto-rebooted.

**Comment by Nonsanity** [comment]
The server has restarted several times now while exploring as it seems the terrain gen, and all it contains, is taking so long the server watchdog is tripped. This can be accounted for by adjusting the server configuration: 
    max-tick-time=90000
So this isn't so much a crash bug as it is a report that the generation is running slow on what is otherwise a very good server.

**Comment by TheCyberBrick** [comment]
There is unfortunately nothing we can do about that except rewriting some of the terrain gen. And we're definitely not doing that considering that we'll have to rewrite everything for an update to newer MC versions anyways.  
As you've already discovered, the way to fix this is to set the watchdog's timeout to some high value, or disable it altogether.
