### ISSUE TITLE
Mobs not spawning in custom modpack

### ISSUE THREAD

**Issue by Muqatil5217** [TheCyberBrick/The-Betweenlands#1007]
1.12.2
## Betweenlands version: 
3.5.7

## Forge version: 
14.23.5.2768

## Singleplayer or Multiplayer:
Singleplayer

## Installed mods:
[Mod List.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/4385556/Mod.List.txt)

## Description of the problem
Mobs not spawning in the betweenlands dimension, mobs will only spawn out of pots and spawners 
#### How to reproduce:

1. Go to the betweenlands
2. Look for mobs
3. There is no mobs :(

**Comment by TheCyberBrick** [comment]
I see you have at least one mod installed that changes mob spawning (CustomMobSpawner). Please make sure that all your mod configurations are correct and not preventing our mobs from spawning.
Also, is there any reason to have CustomMobSpawner if you don't have DrZhark's Mo'Creatures installed?
