### ISSUE TITLE
[Suggestion] Rift Altar

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#1008]
The rift altar, would be a new addition to the mod, in which the player would be able to fuel said altar with something, potentially sulfur or valonite. (item fuels configurable, or optionally none at all)
The altar would keep the rift in the sky open, for either keeping track of the time in the overworld, or for keeping the dimension bright whenever you so wish.
The rift being open would probably have negative effects over time, if not allowed to close, like increasing spawns of wights, weakening swamp hags as a benefit, strengthening sludge mobs, and so on. (configurable)

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
