### ISSUE TITLE
[Request] Config option to change/disable ore gen amount

### ISSUE THREAD

**Issue by SeriousCreeper** [TheCyberBrick/The-Betweenlands#1010]
Heya,

working on a modpack where i'd like to use Geolosys to generate large ore veins, instead of having many smaller veins everywhere. Currently there doesn't seem to be a way to disable any of the default ore gen inside the betweenlands. 

Could we get a config option to adjust how big the ore veins (or how common) they are inside the beweenlands, with the option to disable them alltogether? 

Wouldn't mind doing that myself if you guys are ok accepting pull requests. 

Cheers,
SeriousCreeper

**Comment by TheCyberBrick** [comment]
What do you need this for, and is there no other way to get around it?
The BL config is already getting quite large and imo a bit out of hand, so I'd rather avoid adding more (at least non-compat) config options.
If not, feel free to make a PR (on the 1.12-fixes branch).

**Comment by SeriousCreeper** [comment]
Basically i wanna replace the normal ore gen with large/rare veins, similar to something like TerraFirmaCraft ore gen. I haven't been able to disable the BL ore gen with other mods, not sure if that'd be possible at all, hence why the config option to disable (or change the frequency in general) would be quite useful!
I'll see about making a PR for it then, thanks!
