### ISSUE TITLE
Max id range [Crash]

### ISSUE THREAD

**Issue by zzBuilderzz** [TheCyberBrick/The-Betweenlands#1011]
#### Betweenlands version:
TheBetweenlands-3.5.7-universal.jar

#### Forge version:
Forge 14.23.5.2847

#### Singleplayer or Multiplayer
Not sure if this applies since it happens as minecraft is being started up.

#### Installed mods:

1. Download mod profile McEternal on Twitch launcher
2. Download and add all additional mods found in crash report that are not listed in McEternal's mod folder (writting this late at night so I am not really feeling like listing out all the additional mods I added to the pack for myself)
3. load up the launcher, and hit play
4. attempt to load up minecraft

#### Expected result:
Minecraft loads up normally

#### Actual result:
Crash occurs somewhere in step 3 of 7 in loading up minecraft
says on line 7 of the crash report: java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

**Comment by zzBuilderzz** [comment]
Crash report link (must have been accidendtly deleted while typing this issue) :https://paste.dimdev.org/vezilocase.mccrash

**Comment by zzBuilderzz** [comment]
As mentioned in the issue all additional mods not found in MC Eternal's mod folder (when download from the twitch launcher) will be referenced in the crash report along with their respective mod versions.

**Comment by TheCyberBrick** [comment]
The game has run out of potion effect IDs (there can be at most 255 different potion effects). You'll have to remove some mods that add potions.
