### ISSUE TITLE
1.12.2 Betweenlands causes crash on start up

### ISSUE THREAD

**Issue by domination112** [TheCyberBrick/The-Betweenlands#1016]
#### Betweenlands version:
3.5.10

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Modded vanilla

#### Installed mods:
https://pastebin.com/sf7vKK6T

## Link to full crash log
https://paste.dimdev.org/qelesowewi.mccrash

#### How to reproduce:

1.Startup Minecraft
2. Forge loads mods
3. Crash

#### Expected result:
For Minecraft to start

#### Actual result:
Minecraft crashes

**Comment by TheCyberBrick** [comment]
You have run out of block IDs. Either install some mod like JEID or remove other mods.
