### ISSUE TITLE
Ring of Recruitment Not Working While Some Configurations are Activated on Charm Mod (1.12.2) is installed! 

### ISSUE THREAD

**Issue by Leirday** [TheCyberBrick/The-Betweenlands#1018]
#### Betweenlands version: 
 3.5.10

#### Forge version:
 1.12.2-forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
 Singleplayer

#### Installed mods:

[mods.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/4467265/mods.txt)

#### How to reproduce:

1. Equip the Ring of Recruitment
2. Right Click on a mob (ex: Skeleton, Zombie, Pig, etc.)

#### Expected result:
 Nothing, particles appear and the player gets slowed down as usual, but nothing happens to the mob; it does not get the particles of when it becomes "linked."

#### Actual result:
 See above.

**Comment by TheCyberBrick** [comment]
Make sure you keep holding right-click on the mob for long enough. The more health it has the longer it takes to recruit.

**Comment by Leirday** [comment]
> Make sure you keep holding right-click on the mob for long enough. The more health it has the longer it takes to recruit.

I have tried that as well. I even went into the wiki to see if I was doing something wrong. Also, I checked my controls just in case and it still doesn't seem to work. I removed the Random Things mod to test if the bug persists, I'll provide an update soon.

Update: Removed Random Things Mod, still doesn't work. :(
Update 2: Found the mod that has been causing the bug, Charm Mod. I'll try to download a newer version of the mod to see if the bug gets fixed.
Update3: If the "World" Config. is disabled on Charm Mod the problem seems to go away.

**Comment by mxnmnm** [comment]
Yes I can confirm and it also does not use up any XP. I'm going to do more testing later to see if I can find the specific feature that breaks it.

**Comment by mxnmnm** [comment]
It's the bat bucket feature that lets you capture a bat in a bucket that helps u locate nearby entities

**Comment by TheCyberBrick** [comment]
Hm interesting, thanks for looking into it. I've now found the problem: the bat bucket feature makes the player always swing the hand when right-clicking any mob. The ring of recruitment however cancels the recruitment progress when the player swings a hand. This is so the player can't attack while recruiting a mob.

> Yes I can confirm and it also does not use up any XP. I'm going to do more testing later to see if I can find the specific feature that breaks it.

That's intentional. The ring no longer constantly uses XP but instead only when one of your recruited mobs attacks or is being healed by the ring.

**Comment by Leirday** [comment]
TheCyberBrick, I got a question, is this mod going to be ported to the 1.14.4 version or 1.15.2? (I'm asking this because you guys could be the first modders to make an extremely well-made dimension mod in those versions of the game)

**Comment by mxnmnm** [comment]
"1.14+ versions will happen if/when they happen. No ETAs." -from their discord
