### ISSUE TITLE
Aspectrus improperly displayed in infusion bucket

### ISSUE THREAD

**Issue by Jackiecrazy** [TheCyberBrick/The-Betweenlands#1019]
#### Betweenlands version: 
3.5.10

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
https://pastebin.com/abk3v0u0

## Description of the problem
Aspectrus seeds don't display their aspects properly, and perhaps doesn't handle it properly either. 
#### How to reproduce:
1. load infuser with 3 aspectrus of any aspect and 3 sap spit
2. bring to boil until it changes color drastically, remove with bucket
3. observe the bucket's tooltip
4. load infuser with 6 aspectrus of any aspect
5. bring to boil until it becomes a bright purple, place in alembic
6. extract from alembic with vial

#### Expected result:
At (3), it should display 0.75 of the aspect, since 3 was used
At (6), the alembic should yield 1.5 of the aspect

#### Actual result:
the bucket displays 3x Aspectrus: 0.25, while sap spit has its values multiplied by 3 due to using three pieces as per normal
the alembic yields an aspect vial with 0.42 of the given aspect

**Comment by TheCyberBrick** [comment]
> At (3), it should display 0.75 of the aspect, since 3 was used

Ah, that's a bug. The line that's shown for the Aspectrus Fruit is just the name of the item itself, but it doesn't show the contained total aspect below. 👍 

> At (6), the alembic should yield 1.5 of the aspect

There is a 15% loss of aspect when distilling aspects. 1.5 x 0.85 / 3 = 0.425 per vial

**Comment by Jackiecrazy** [comment]
That makes sense then. However, I only used a single bucket of swamp water when distilling, and it gave me 0.425 from that bucket, when according to the formula I should have gotten a vial with 1.275. Is this intended? I would have imagined that using only a single bucket would have made it "extra concentrated" or something of the sort.

**Comment by TheCyberBrick** [comment]
That is intentional because it gives the evaporation mechanic a purpose. If you don't stir enough one bucket's worth of water evaporates and you lose 1/3rd of the contained aspects.
