### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by AsianGodStick** [TheCyberBrick/The-Betweenlands#1020]
The leaves in your mod ”thebetweenlands“ isn't support the mod ”better foliage“,please change this situation,I realy wan't to play ”thebetweenlands“ with ”better foliage“.
I sincerely ask you to do this.
sorry for my English because I'm not a English speaker.  : )

**Comment by TheCyberBrick** [comment]
That is something that can be done by you. BetterFoliage has a config where you can add our blocks and then it _should_ just work.
Config: https://github.com/octarine-noise/BetterFoliage/blob/kotlin-1.12/src/main/resources/assets/betterfoliage/leaves_blocks_default.cfg
Our blocks: thebetweenlands.common.block.terrain.BlockLeavesBetweenlands, thebetweenlands.common.block.terrain.BlockLogBetweenlands
