### ISSUE TITLE
Incorrect description of portal_dimension_targets configuration key

### ISSUE THREAD

**Issue by dashkal16** [TheCyberBrick/The-Betweenlands#1021]
#### Betweenlands version:
Betweenlands 3.5.10 for MC 1.12.2

The description of the portal_dimension_targets mentions that "if no meta is provided 0 is used.".  This does not appear to be the case.  Omitting meta results in the entry not working.

minecraft:end_stone:0/1 works
minecraft:end_stone/1 does not

**Comment by TheCyberBrick** [comment]
👍
