### ISSUE TITLE
Issues running Between lands, have optifine and other mods

### ISSUE THREAD

**Issue by rokybarua** [TheCyberBrick/The-Betweenlands#1023]
Error: java.lang.VerifyError: get long/double overflows locals

Betweenlands version 1.0.6
Forge version 1.7.10 

can't start the game

**Comment by theishiopian** [comment]
1.7.10 is no longer supported

**Comment by TheCyberBrick** [comment]
Use a different OptiFine version. The solution is described on this repository front page..
