### ISSUE TITLE
Ice and fire hydra crashes when blocking their poison projectile with a vanilla shield

### ISSUE THREAD

**Issue by Time-Green** [TheCyberBrick/The-Betweenlands#1025]
#### Betweenlands version:

3.5.10  

#### Forge version:

forge-14.23.5.2852

#### Singleplayer or Multiplayer:

Happened on a single player lan world (which is multiplayer I guess?). The other person had the exact same mods as I had. 

#### Installed mods:

https://pastebin.com/kjt4RdQ8

## Link to full crash log

https://pastebin.com/LS6DS9t3

#### How to reproduce:

1. Find an Ice and Fire hydra
2. Have a vanilla shield
3. Try and block a hydra

#### Expected result:

I honestly expected it to either break through my shield or block the attack

#### Actual result:

My game crashed. Pretty sure it's clientside, my friend did the exact same thing and only they crashed, not the whole lan world. 

I have no idea why betweenlands even causes this, as it isn't exactly related to these events. Yet the callstack and the guy from Ice and fire (https://github.com/Alex-the-666/Ice_and_Fire/issues/2351) agree that I should report it here.

**Comment by TheCyberBrick** [comment]
Thanks.
The problem is not really on our side, but I can add a workaround so it should hopefully no longer crash.
