### ISSUE TITLE
Sludge Menace can spawn in caves underneath Sludgeon

### ISSUE THREAD

**Issue by z64555** [TheCyberBrick/The-Betweenlands#1027]
## Versions
3.5.10

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Happened to me in Multiplayer, but I suspect its also possible in singleplayer

#### Installed mods:
Minecraft Eternal. 1.3.5.3 
https://www.curseforge.com/minecraft/modpacks/minecraft-eternal/files

## Description of the problem
While going up against the Sludge menace, the first stage went as expected.  Only thing I didn't really finish was killing off the sludge turrets as I didn't realize they were killable until I tried just continously whacking at them with a Tinker's rapier later on.

After wandering around the tower looking for the Menace I basically gave up and went into creative/spectator mode to go looking for him.  He ended up spawning on the top side of a cave that was about 8 or so blocks beneath the bottom of the sludge pit chamber.

This is something of an edge case, as I believe it requires caves to be generated directly underneath the sludge pit,  If it wasn't there then the Menace probably would've spawned as normal.

#### Expected result:
Sludge Menace should ignore any block it can attach to *unless* its one of the blocks inside of the sludge pit chamber.

#### Pictures:
![](https://i.imgur.com/hPGd9vD.png)

**Comment by ghost** [comment]
yes it happens to me too
