### ISSUE TITLE
Rubber balls disappears

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1029]
Betweenlands version:
3.5.10

Forge version:
1.12.2 Latest Version 14.23.5.2847

Singleplayer AND Multiplayer:
In Multiplayer --> Forge Server

Installed mods:
Betweenlands 3.5.10

Description of the problem
When I have all my inventory full, I hold a syrmorite solidified rubber bucket in my hand, and I click to get the rubber ball, if my inventory is full, the rubber ball disappears.

Expected result:
Rubber balls in my inv or on the ground

Actual result:
No rubber balls :'v

**Comment by TheCyberBrick** [comment]
👍
