### ISSUE TITLE
(Suggestion) Betweenlands Enchantments

### ISSUE THREAD

**Issue by TheBlueCheese** [TheCyberBrick/The-Betweenlands#1036]
Basically enchantment books but gotten in the Betweenlands and the only way to enchant Betweenlands items. Normal Enchantment Books don't affect Betweenlands items. 

Other Ideas

- You could control the players power scaling with only having combat enchantments like Sharpness IV, V, etc, Spawning only in endgame dungeons. 

- You could have vendors to sell non combat enchantments maybe found in new biomes like Dark Forest to give them reason to be sought after.

- A possible table that saves Betweenlands enchantment books to be used later, You insert what ever book you bought off a vendor in it and you can then play an experience lottery like normal enchantments.

**Comment by PetasiGit** [comment]
Middle Gems act as a sort of enchantment alternative for the dimension. To my knowledge we will not be adding anything like vanilla enchantments to the mod, so I’m going to close this.
