### ISSUE TITLE
Infinite rowboat lanterns

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1037]
Betweenlands version:
3.5.10-3008-SNAPSHOT

Forge version:
latest 1.12.2 - 14.23.5.2847

Singleplayer

Installed mods:
Betweenlands

Description of the problem
Duplicate infinite rowboat lanterns

How to reproduce:
Click with a rowboat lantern on a rowboat.
Break the rowboat
collect the items
Place the rowboat item on the ground
Break the rowboat
collect the items
Place the rowboat item on the ground ...

Expected result:
No infinite rowboat lanterns

Actual result:
Infinite rowboat lanterns \ :'v /

**Comment by TheCyberBrick** [comment]
Oh.. it saves that :P
