### ISSUE TITLE
Crafting Rubber Tree Planks crashes the game

### ISSUE THREAD

**Issue by TheRealZonko** [TheCyberBrick/The-Betweenlands#1040]
I was playing the new update and when I crafted some Rubber Tree Wood into Rubber Tree Planks, the game crashed.  Please look into it because I tried it two more times and it happened each time.

**Comment by ghost** [comment]
that doesn't happen to me, do you have any more mods installed? CraftTweaker maybe? what is your forge version?

**Comment by TheCyberBrick** [comment]
Can't reproduce either. It's a simple vanilla recipe, I don't see how it would crash. Probably caused by another mod
