### ISSUE TITLE
[BUG] Screen resolution

### ISSUE THREAD

**Issue by Gobi740** [TheCyberBrick/The-Betweenlands#1044]
Hi,

Whenever I enter betweenlands me screen stays in full screen however the visible game goes to only quarter of the screen and stays like than. I had the black screen bug but I fixed it with the GL in config however the resolution thing occured before the black screen. 

I am playing on 1.12.2 Minecraft 
I think the version of betweenlands is 3.4.9 universal, that's what it says in my mod folder.

![2020-05-11_01 05 55](https://user-images.githubusercontent.com/65139647/81513882-9ae41a00-9323-11ea-81c5-4645c294fdd8.png)

**Comment by TheCyberBrick** [comment]
Update the mod, this was fixed a while ago
