### ISSUE TITLE
Algaes can't be placed back onto water

### ISSUE THREAD

**Issue by SeriousCreeper** [TheCyberBrick/The-Betweenlands#1045]
#### Betweenlands version:
TheBetweenlands-3.6.0-universal

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### How to reproduce:
Break algae with shears to get the item. 
Try to place it back onto water. 
Tried placing on water (like a lilypad), against a block, and against another algae. None of those work. 

#### Expected result:
Algae gets placed back onto water.

#### Actual result:
Nothing happens

**Comment by TheSilverplier** [comment]
True, you cannot place alguaes on top of water directly. But you can do it like with the old version of trapdoors which means you need to place them adjacent to a pre-existing block (commonly swamp reeds in BL). I agree it would be nice for building ergonomy (both Survival and creative modes).

**Comment by PetasiGit** [comment]
Was fixed in 3.7.2.
