### ISSUE TITLE
[BUG] - Infinite Double Jump with Chiromaws

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1046]
#### Betweenlands version: 
3.6.0

#### Forge version:
1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands
Phosphor
Optifine

#### How to reproduce:
1. Take a Tamed Chiromaw (Regular or Lightning version) on your head in order to be able to double-jump.
2. Go into the water and press the space-bar repeatedly.
3. Keep pressing while getting out of water.
4. You can now "fly" by pressing the space-bar as much as you want. You can go to any height. You will take full fall damage if you land on earth no matter the height you're trying to compensate for.

HOWEVER this bug seems to be inconsistent. I managed to repeat it quite a few times but it might take a few tries. I have posted a link to a video showcasing the bug in case my explications aren't precise or self-explanatory as needed.

#### Expected result:
The Chiromaws should only be able to grant you one double jump and it shouldn't keep repeating itself in a way that provides a method of flying.

#### Actual result:
Instead, you will keep stacking the double jumps and go as high as you want if you keep pressing "space".

#### Pictures:
https://youtu.be/qBPYqCZ310k

**Comment by ghost** [comment]
I can't reproduce
