### ISSUE TITLE
[BUG] - Furnaces' Light Sources Disappear

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1049]
#### Betweenlands version: 
3.6.0

#### Forge version:
1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands
Phosphor
Optifine

#### How to reproduce:
1. Take a mineral or anything that can be smelted in a furnace and grab some sulfur too.
2. Put everything in and remove the sulfur after it starts to melt.
3. Interact a few times with the furnaces.

This bug sometimes will appear and sometimes it's a bit weird on how it is triggered, hope the picture can help to see what is happening.

#### Expected result:
You should have a light source even when sulfur isn't in the furnace because something is still melting.

#### Actual result:
Instead, the light will sometimes disappear no matter how much time there is for the fuel to run out.

#### Pictures:
![furnaces](https://user-images.githubusercontent.com/64988996/81577549-d7f2ef80-93a9-11ea-89b5-e7b09d67f3e7.gif)

**Comment by ghost** [comment]
this is an Optifine bug, I don't use Optifine and it doesn't happen to me

**Comment by SeriousCreeper** [comment]
Happens to me too, no optifine installed https://streamable.com/zqfi7o
