### ISSUE TITLE
[SUGGESTION] - 90° Block for Dentrothyst Shields

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1052]
While testing the different Shields Betweenlands provides. You might want to use the Dentrothyst Shields for their ability to block incomming splash infusions  (including the vanilla splash potions). However I have come to notice that these shields do not block the splash effects depending on an angle of ~90° like the other Shields do. Which means you can block a splash potion from any angle, like illustrated bellow:

![shieldss](https://user-images.githubusercontent.com/64988996/81826070-aad44780-9537-11ea-8524-ca21466cb541.gif)

Thus, I suggest to adjust the angle which protects from the infusions/potions to match the players default field of view. Which is around 90° if I remember.

**Comment by TheCyberBrick** [comment]
That's intentional. The shield already has such a niche function, so I think it's fair that it gets a greater blocking area for splash potions ;)
