### ISSUE TITLE
[Request] Biome ID manual mapping

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1056]
I updated and was greeted with a crash on trying to load a world. The crash was related to OTG and betweenlands having an id conflict, related to the new biome added. I AM using OTG v8, but the dynamic allocation ONLY works when making a NEW world. People are not going to be expected to throw away their entire world because one mod added one new biome, that's just silly, especially on large servers, people would go play another game.

Needed is either a way to manually specify biome ids for betweenlands to use, or an automatic system is implemented that finds an empty id and uses that (preferably one away from other used ids to prevent being stomped on should another mod expand). Worst case an option to disable the new biomes if nothing else can be done.

**Comment by TheCyberBrick** [comment]
I am sorry that happened to your world, but we're not going to make biome IDs configurable.
> but the dynamic allocation ONLY works when making a NEW world.

~~Source for that claim? Biomes use Forge's registries which can dynamically add new IDs even to existing worlds (unless it completely runs out of IDs).~~ nvm, I thought you were talking about Forge. 
Such biome ID conflicts typically happen _because some mods allow manual ID assignments_. 
Manually asaigning IDs is not how it's supposed to be done, it interferes with Forge's automatic ID assignment. 
Other mods are also breaking because of OTG's unconventional biome registration: https://www.reddit.com/r/biomebundle/comments/ekl3g6/biome_id_issue/?utm_source=amp&utm_medium=&utm_content=comments_view_all

**Comment by ghost** [comment]
java.lang.RuntimeException: Tried to register biome openterraingenerator:overworld_frozen_forest to a id 118 but it is occupied by biome: thebetweenlands:raised_isles. This can happen when using the CustomBiomes setting in the world config or when changing mod/biome configurations for previously created worlds. OTG 1.12.2 v7 and above use dynamic biome id's for new worlds, this avoids the problem completely.
This is then followed by a bunch of lines from forge.

This was the first line in the crash report. I looked at the config I made for biome bundle and it appears that dynamic is indeed working because the aforementioned biome id was not configured within the file. (the lowest I configured was well into the 200s to avoid conflicts, but it's rather annoyingly being ignored).

I'll do some further looking into this to see if I can manually fix this. As for forge doing things automatically, that function unfortunately doesn't work right when a large number of biomes are present because if you spill over into dynamic (above ~250) and try to assign a biome that needs to be under that to something above it just spits out an error (or at least it did a couple years ago when I first set them up).

Edit: removing biomieids.txt from the world folder fixes the issue, and the world still has the biomes mapped correctly and generates new terrain fine, leading me to question the existence of this file. It also appears that after doing such the manually configured biome ids I did in biomebundle that were set to prevent this exact issue are now no longer being ignored.

**Comment by TheCyberBrick** [comment]
> Edit: removing biomieids.txt from the world folder fixes the issue, and the world still has the biomes mapped correctly and generates new terrain fine, leading me to question the existence of this file. It also appears that after doing such the manually configured biome ids I did in biomebundle that were set to prevent this exact issue are now no longer being ignored.

Hm weird, but glad you got it resolved.
Like I said before, if no mod manually assigned biome IDs in the first place we wouldn't have these problems, unless Forge runs out of IDs to assign (but then manual assignments also wouldn't help) ;)
