### ISSUE TITLE
[Suggestion] Greeblings & Common Pastimes.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#1059]
Greeblings (if I'm remembering which mob correctly) ~~occasionally hide in shrubbery~~ (seems they don't hide :( but are still shy) and play a musical instrument. This has to be one of my favorite ambient features in this mod, I always make sure to stay nearby when working and frown a little when I frighten them off...
Taking all this into account I'd like to make a suggest. Greebling flutes (or whatever instrument it may be), you'd probably find broken ones in weedwood bushes and use those to discover how to carve a new one, carving a new one would allow the player to practice playing it.
If the player has heard the Greebling song between 2-3 times? They could gain familiarity with it, and acquire the ability to play the song.

Sitting out waiting for a Greebling to play their music, and slowly joining in with a flute and playing it yourself could cause the Greebling to stop playing (but not scurry off and rustle bushes), and approach you, maybe they continue playing the music with you? Give you a gift? Maybe if you're under threat in the general vicinity of that Greebling in the future (similar to Foxes in Minecraft 1.14) they jump out and attack whatever is threatening you?

Your call, just thought about this while playing.

**Comment by spiderking23** [comment]
This is a cool idea. Minecraft and The Betweenlands music has all been really out of the players hands without a Jukebox, but this would add a fun little thing for players to do every once in a while.

**Comment by TheCyberBrick** [comment]
We have some Greebling things planned, including some form of player interaction

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
