### ISSUE TITLE
[BUG] - Shelves Breaking with Greataxes

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1061]
#### Betweenlands version: 
3.6.0

#### Forge version:
1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands
Phosphor
Optifine

#### How to reproduce:
1. Take a Greataxe in your hand (Valonite or Ancient version).
2. Try and put it on a shelf (it will display the animation and stop it half way through).
3. Retrieve the Greataxe and the animation will end, breaking every wooden object in its way.

NOTE: With the recent patch of the #1047 bug, this might be patched as well. But I don't know yet how this specific situation would play out. After a few tests I also noticed this bug can happen with certainly every utility block which has a UI.

#### Expected result:
You should be able to sort the Greataxes in a shelf without the animation displaying, thus without the secondary ability getting triggered.
#### Actual result:
Instead, half of the ability's animation will play right before being stopped. When you will try to retrieve the Greataxe, the animation will continue and break stuff.
#### Pictures:
![Greataxe Return](https://user-images.githubusercontent.com/64988996/82240484-ccb83a80-993a-11ea-8754-ce66624f91dd.gif)

**Comment by TheCyberBrick** [comment]
This is fixed
