### ISSUE TITLE
[SUGGESTION] - New Underwater Mob: The Drowner

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1063]
## Introduction:
Betweenlands’ most underwhelming biome, although full of life and underwater vegetation, is undoubtedly the Deep Waters biome. Fortunately for all of us, one of the future updates in AngryPixel’s mind should tackle the underwater parts of the Betweenlands dimension, with new creatures and maybe even some new mechanics! And because of that, I thought about creating a concept for an underwater creature you could find in the said biome to spice things up a little bit during your travels. So, without any furtherer do, I present to you The Drowner (_no reference to The Witcher intended, I didn’t know they were even a thing, please don't sue me_).

#### Appearance and Behavior:
Drowners are aggressive mobs that rarely spawns in Deep Waters.
They appear as skinny, scaly, tiny humanoid creatures with flippers and fins with a very distinguishable light blue skin and glowing little white eyes (_**example below is an unfinished model**_). 

![Drowner Concept png](https://user-images.githubusercontent.com/64988996/82468040-a7eecf00-9ac2-11ea-95b2-5b7a5e5c1711.png)

They spawn in water bodies [see _Spawning conditions_] and will generally stay underwater, swimming slowly as long as they aren’t aggressive toward the player. Due to their humanoid nature, Drowners use both gills and lungs to breath. Although they can live entirely underwater without much troubles, you can occasionally see them resting on Cragrock Spires or floating above water. 

Despite being a rare creature to encounter, the Drowner should not be underestimated. To compensate their bad sight, they are able to spot players from a long range because of their sense of smell, and will follow them, positioning directly under their prey's location, waiting for an opportunity to attack. If player sail with a boat (Lurker Skin Shield/Weedwood Rowboats) they will try to catch up and jump out of water to attack them [see the _Jump_ attack]. If the players find themselves directly in water, it will adopt a hit and swim tactic [see the _Contact_ attack] and rotate around their prey, waiting for a safe opportunity to attack. They can occasionally inflict the Heavyweight Draught’s effect with a rare bite [see the _Bite_ attack], preventing players to swim and retrieve oxygen. If their health is depleted enough (under 25%) the Drowners will try to swim away, although slowly enough to let players take the final blow.

#### Strategies available:
Although Drowners can be a very dangerous enemy to encounter, they have a few counters to balance their behavior. First, you can choose to flee from them, this might be possible if you are using the Weedwoos Rowboat at its full speed capacity, or you are using a full Lurker Skin set, making you fast enough to distance them. But if you are using a Lurker Skin Shield, or worse, your frail legs, don’t give up! Like the Peat Mummies are attracted to Shimmerstones, Drowner will also try to catch them you throw some, providing you a quick escape. On the opposite spectrum of survival, if you wish to hunt them down, the Drowners could be fooled by a disguise (the full Lurker Skin armor for example) and could be approached without troubles until you attack them. Calling back to their fish/amphibian nature, the Drowners could also be vulnerable to certain types of weapons, if the said weapons exist.

#### Spawning conditions: 
Because of the Drowner’s “complexity” and its dangerous abilities, there should never be more than two in a single biome at the same time. To spawn, they need a minimum 3x3x2 area of swamp water. 

## Statistics (up to tweaking): 
**Health**: 55HP (22.5x![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png))

**Damage:**
Contact Easy: 3 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Half_Heart](https://user-images.githubusercontent.com/64988996/82455247-057b1f80-9ab3-11ea-9bbf-65de623e9475.png))                        
Contact Normal: 6 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png))       
Contact Hard: 8 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png))

Jump Easy: 4 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png))
Jump Normal: 7 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Half_Heart](https://user-images.githubusercontent.com/64988996/82455247-057b1f80-9ab3-11ea-9bbf-65de623e9475.png))
Jump Hard: 9 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Half_Heart](https://user-images.githubusercontent.com/64988996/82455247-057b1f80-9ab3-11ea-9bbf-65de623e9475.png)) 

Bite Easy: 2 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png) + Heavyweight Effect)
Bite Normal: 3 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Half_Heart](https://user-images.githubusercontent.com/64988996/82455247-057b1f80-9ab3-11ea-9bbf-65de623e9475.png) + Heavyweight Effect)
Bite Hard: 4 (![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png)![Heart](https://user-images.githubusercontent.com/64988996/82455237-02802f00-9ab3-11ea-8474-0cc380fde3f6.png) + Heavyweight Effect)

**Experience:** 15

**Loot:** None atm, feel free to make suggestions! I did not wish to dictate a whole new gallery of crafts for potential loot items.

## Conclusion:
And that’s about it for this “Drowner” concept. I don't expect this concept to get much attention and neither do I think there will be a mob of that sort in the actual mod. I just thought, since we do not have many aquatic dangers at the moment, there could be an actual threat to you and your boat travels. And a tiny evil creature that would try to drown you is something I really enjoyed pitching. 
Feel free to add any suggestion to that little concept if you think there are some things to improve (and of course there must be) I'm definitely taking all the feedbacks available on this one!
And why not talk further more about mob concepts in general in the discord server? (#off-topic channel).

**Comment by Leirday** [comment]
Why has nobody commented on this amazingly well-written and developed idea? I love this idea and I'd love to see it come to life.
