### ISSUE TITLE
[BUG] - Chiromaw not Hanging on Slab Ceiling

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1064]
#### Betweenlands version: 
3.6.1

#### Forge version:
1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands
Phosphor
Optifine

#### How to reproduce:
1. Right-click a Tamed Chiromaw (version doesn't matter) to make it sit on your head.
2. Try and hang it on a ceiling made out of slabs (placed on the top half).
2.5 Place a second layer of full blocks with a one-block tall gap above your first ceiling.
3. Watch the Chiromaw ignoring the ceiling's collision (if followed 2.5)/flying away instead of hanging.

#### Expected result:
You should either be able to hang the Tamed Chiromaw on a ceiling made out of slabs placed on the top half part or being told you can't do it.

#### Actual result:
Instead, the Chiromaw won't connect with the slabs and will find the next layer where it can hang or just dismount from your head, depending on the 2.5 step.

#### Pictures:

![you what again](https://user-images.githubusercontent.com/64988996/82609463-dfda3d00-9bbc-11ea-9c5b-91f1bb8477f1.gif)

**Comment by TheCyberBrick** [comment]
This is intentional. The chiromaw will only hang from blocks that have a full/regular face at the bottom, which top half slabs don't.
