### ISSUE TITLE
[Suggestion] Submerged Forest.

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1065]
Hello Betweenlands Developers.
During this epidemic, me and my family have often gone on hikes, and come across some very swamp-like areas. One of these areas gave me an Idea for a new Biome, or SubBiome: The Submerged Forest. It would be, essentially, an area in the Betweenlands similar to the normal Swamplands... except everything is two or three blocks below water level. Every tree would be partially submerged, making this a perfect place for the new fish mobs to spawn, along with the Lurkers and Anglers. It would make the Biome feel even more "Swampy" as you paddle your boat in-between the trees. The Flora of this area, other than the Trees themselves, would be massive amounts of Swamp Reeds, and Swamp Kelp, as well as some of the water plant Life from the Patchy Islands. The plant life should NOT completely block the players view and path, it should just be common enough that these areas don't look like half-flooded tree farms.
Hope the idea is liked, or sparks some inspiratuion for a cool new idea to this already immersive mod.
spiderking23

**Comment by PetasiGit** [comment]
This biome idea has been mentioned before by the devs in #317, it’s on their mind. :)

**Comment by spiderking23** [comment]
Good to know, hope they implement it cause it's a cool idea.
