### ISSUE TITLE
[SUGGESTION] SYRMORITE WEAPONRY!? WHAT!?!? (Also a begging for spears)

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1067]
Hello Betweenlands Devs.
This is going to sound a bit crazy of me. You have already decided what Octine and Syrmorite should be used for, and you probably won't change your minds. Still I'd appreciate it if you'd here me out. So, in the Betweenlands, there are two metals. Octine, and Syrmorite. Octine is a metal that is constantly hot to the touch (Magic?) and can set things on fire, while Syrmorite is literally just Betweenlands Iron without any special abilities (The shield Charge can be done by Valonite, so I don't consider it a unique ability). And recently, I've been watching a lot of Shadiversity's videos. Along with reigniting my love for spears in combat, it also drew up an interest in making things logical. And in the Betweenlands, OTHER than the lack of spears (Sludge Slicer doesn't count, it acts the same as a weak sword), something that always seemed illogical was these two metals. Magic or no magic, WHY CAN YOU NOT MAKE SYRMORITE WEAPONS? It just doesn't make any sense. While it makes things more interesting, it doesn't add up. 
No reason you can give would make any sense. If it were a soft metal that couldn't hold an edge required for a tool, then you would use OCTINE SHEARS. Seriously, if you can make shears with them, a sword isn't that far away, or too difficult to do. And even without the shears, if it couldn't hold an edge, it would be ineffective as armor, as it would bend and puncture easily, making it worse than Slimy Bone, and considering how many armor points it gives, this ain't the case. I can understand it for Octine, you'd cook alive wearing armor made from that, or at least be very uncomfortable (How does it not set fire to your hands, I don't know, but maybe moving the metal is what causes it to heat up to that temperature). However, Octine armor would still be incredibly useful even if it was uncomfortable because enemies who hit you would set ablaze. It would certainly be deadlier to your opponent than Syrmorite. 
And I still have one more thing to complain about: YOU ALREADY HAVE A SYRMORITE WEAPON IN THE GAME. And this weapon is the Basis for every single point in this suggestion... *Whew*. Now that I've gone through all of the problems of lacking Syrmorite Weaponry, I can calm down now... ANYWAY, the weapon that I'm talking about is quite surprising, and you may have done this on accident, but it an Arrow. The Basilisk Arrows. Don't believe me? Take a close look at the arrowhead, then look at a Syrmorite Ingot. Ahhh, see what I've discovered. Anyway, this shows that Syrmorite might be even MORE effective as a weapon than as armor. Because when it cuts into a creature, or pierces them, or whatever, IT PARALYSES THEM. OP? Not really. It wouldn't last too long, and Octine Weaponry's Fire ability would deal additional damage. Also, aren't the bosses immune to the Basilisk effect? And since you've already added it to the world, I think it would make  sense to add Syrmorite tools. And while you at it, spears? No. Just me? Ok, but still, this is something that would improve the game experience between player very much as in PVP situations, or when fighting the Crypt Crawlers, you'd have to beware the Paralysis and the Fire. Scary thought. A Betweenlands thought.
I hope you actually consider the information and argument I've dumped on you today, but no hard feelings if you don't. With best of luck for the Mod and its creators (YOU), stay safe, stay healthy, and have a nice day.
Sincerely, a big Fan,
spiderking23.
P.S. SPEARS PLEEEEAAASE. *Insert Bambi Eyes Here*

**Comment by spiderking23** [comment]
My brother, when reviewing this, mistook my statement about the shears. My argument is that if you can make SHEARS from Syrmorite, then you should be able to make a sword (Or spear). Just to clear up confusion anyone who was confused by that area.

**Comment by theishiopian** [comment]
Yelling in a suggestion is generally considered poor form, just fyi. Also, the basilisk arrows are not canonically made of syrmorite.

**Comment by PetasiGit** [comment]
Since you had the discussion about this on the discord, you can close this now.

**Comment by TheCyberBrick** [comment]
The weapon and armour tiers will stay as they are... for now.
