### ISSUE TITLE
keeps crashing when i try to place any flans vehicle 

### ISSUE THREAD

**Issue by beetweenlands** [TheCyberBrick/The-Betweenlands#1069]
#### 
v.3.6.1 (betweenlands) 
14.23.5.2847 (forge version)
 Singleplayer

#### Installed mods:
micdoodlecore   
  xaerominimap_core1.12.2-1.0     
| [1.12.2]+SecurityCraft+v1.8.17.jar                     
    | [1.12.2]DamageIndicatorsMod-
jei_1.12.2-4.15.0.291.jar \
 athenaeum-1.12.2-1.18.1.jar                         
CodeChickenLib-1.12.2-3.2.3.358-universal.jar  
      | RedstoneFlux-1.12-2.1.1.1-universal.jar       
  BrandonsCore-1.12.2-2.4.18.210-universal.jar    
car-1.12.2-2.0.1.jar                             
	| cdm-0.4.1-mc1.12.2.jar                             
	 | cfm-6.3.0-mc1.12.2.jar                             
	 | CTM-MC1.12.2-1.0.2.31.jar                          
	| Chisel-MC1.12.2-1.0.2.45.jar                      
	        | CoFHCore-1.12.2-4.6.6.1-universal.jar              
	  | CoFHWorld-1.12.2-1.4.0.1-universal.jar            
	CustomMobSpawner-3.11.4.jar
	| ThermalFoundation-1.12.2-2.6.3.27-universal.jar  
  | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar 
	 | dropt-1.12.2-1.18.0.jar                           
	|       | DrZharks-Mocreatures-Mod-12.0.4.jar                                        
	      | DynamicTrees-1.12.2-0.9.8.jar                      
	       | Flan's Mod-1.12.2-5.5.2.jar                       
        | wumpleutil-1.12.2-2.12.9.jar                       
          | foodfunk-1.12.2-4.9.6.jar                         
	    | industrialcraft-2-2.8.197-ex112.jar              
GalacticraftCore-1.12.2-4.0.2.244.jar                               
    Galacticraft-Planets-1.12.2-4.0.2.244.jar       
ICBM-classic-1.12.2-3.3.0b63.jar                   
	 InfernalMobs-1.12.1.jar                            
	| ironchest-1.12.2-7.0.72.847.jar                   
	|MCA-1.12.2-6.1.0-universal.jar                   
	Mekanism-1.12.2-9.7.1.372.jar                      
	 | MineMenu-1.12.2-1.6.10-universal.jar           
	|   | llibrary-1.7.19-1.12.2.jar                      
	         | mowziesmobs-1.5.4.jar                           
	|      | Pam's+BrewCraft+1.12.2-1.0.1.jar                   
	         | Pam's+HarvestCraft+1.12.2zg.jar                   
	        | pyrotech-1.12.2-1.4.23.jar                         
	| L          | SchopCraft-0.3.1-for-MC-1.12.2.jar                
	          | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     
	     | TravellersBackpack-1.12.2-1.0.23.23.jar            
	      | update+4.jar                                       
     | VariedCommodities_1.12.2(21nov19).jar              
	|    | Xaeros_Minimap_20.5.0_Forge_1.12.jar               
	   | TheBetweenlands-3.6.1-universal.jar     

to full crash log
https://pastebin.com/FMZiF05f

	
	
ok so I'm playing with around 50 mods and i try to place a flans mod plane my screen freezes and my game crashes

**Comment by TheCyberBrick** [comment]
This seems to be unrelated to Betweenlands, and the same crash seemed to happen without Betweenlands installed: https://github.com/FlansMods/FlansMod/issues/1125. Try updating Flan's mods.
