### ISSUE TITLE
Crashes before Title screen can load.

### ISSUE THREAD

**Issue by NightHeartt** [TheCyberBrick/The-Betweenlands#1073]
#Versions
#### Betweenlands version:
Version 3.6.1

#### Forge version:
1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
Meant for singleplayer, could not get that far.

#### Installed mods:
Animania 1.12.2 (1.7.3)
Apple Skin 1.12 (1.0.9)
Aquaculture 1.12.2 (1.6.8)
Baubles 1.12 (1.5.2)
CraftStudioAPI (1.0.1.95)
ExtraAlchemy 1.12 (0.5.4)
A Peculiar Fantasy (0.6.0)
Forestry For Minecraft 1.12.2 (5.8.2.422)
Mr.Crayfish's Furniture Mod 1.12 (6.3.1)
Improved Backpacks 1.12.2 (1.4.00)
jei 1.12.2 (4.15.0.293)
Minerva Library (1.0.13)
Pam's HarvestCraft 1.12.2 (1.12.2zg)
Snad 1.12.2 (1,7,09.16a)
Swing Through Grass 1.12.2 (1.2.3)
Thaumcraft 1.12.2 (6.1BETA26)
The Between Lands (3.6.1)
Trinkets And Baubles (0.30.1)
Twilight Forest 1.12.2 (3.10.1013)

## Link to full crash log
https://gist.github.com/NightHeartt/4d7f2db803e096c76e13c6cbbd51b435

#### How to reproduce:
1. Have listed mods, and forge version installed.
2. Press play button on the minecraft launcher
3.  Wait...

#### Expected result:
For the game to launch normally and allow me to create a world and play.

#### Actual result:
The game crashes before the title screen can load up, specifically on forges "building" screen.

**Comment by TheCyberBrick** [comment]
This is likely either caused by https://www.curseforge.com/minecraft/mc-mods/a-peculiar-fantasy-mod or by missing https://www.curseforge.com/minecraft/mc-mods/potion-core
