### ISSUE TITLE
An idea to fix possible balance issues with other mods installed.

### ISSUE THREAD

**Issue by JasonPra** [TheCyberBrick/The-Betweenlands#1074]
What I propose is adding an item whitelist feature. How this could work is it would scan your inventory for any items that are not whitelisted in the configuration files. If it finds them it should then delete them from your inventory. 

P.S I do understand that an easy fix to the balance issues just not play with other mods however I'm a guy likes to play with a lots of mods. I don't necessarily like them all to mingle though. If I were to take God's a thaumcraft magic into this world it would make it too easy.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
