### ISSUE TITLE
game becoming unplayable...

### ISSUE THREAD

**Issue by JasonPra** [TheCyberBrick/The-Betweenlands#1075]
The game starts a lock up and you can't move much so the game becomes unplayable if you have the Aether II mod installed...

#### Betweenlands version:
Won't matter. I have tryed a few.

#### Forge version:
1.12.2

#### Singleplayer or Multiplayer:
 Happens in both single and multiplayer.

#### How to reproduce:

Just install this mod with any other mod that adds Dimensions like the Aether for example.

**Comment by TheCyberBrick** [comment]
I can't reproduce this. Perhaps your game is running out of memory, see https://cubedhost.com/help/en/articles/1648388-how-do-i-allocate-more-memory-to-my-minecraft-launcher-client-side
