### ISSUE TITLE
Client side crash when weeping blue is placed in vanilla flower pot

### ISSUE THREAD

**Issue by Adrakaris** [TheCyberBrick/The-Betweenlands#1076]
#### Betweenlands version:
3.5.6

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Multiplayer Forge Server

#### Installed mods:
All the Mods 3 Remix 1.5.4
https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix
+Optifine 1.12.2_HD_U_F5

## Link to full crash log
https://pastebin.com/whLGaLrr

## Description of the problem
I put a weeping blue into a vanilla flower pot. This the proceeded to completely freeze my game and eventually crash it. The server does not crash, however, and when i load back in the same thing happens. The flower renders in the flowerpot fine, it seems.

#### How to reproduce:

1. Place a weeping blue into a flower pot

#### Expected result:
Flower goes in pot, carry on as normal.

#### Actual result:
Flower goes in pot, freeze for the next 2 minutes, not responding, crash

**Comment by TheCyberBrick** [comment]
This is caused by the "Plants" mod.
