### ISSUE TITLE
Weird Aspectrus fruit plant behaviour

### ISSUE THREAD

**Issue by Charesque** [TheCyberBrick/The-Betweenlands#1078]
#### Betweenlands version: 

3.6.1.

#### Forge version:

14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Optifine-1.12.2_HD_U_F4

## Description of the problem
Aspectrus Fruits can continually grow up to 3 blocks tall even with censer inactive, but having an aspect in its internal storage. This behaviour does not occur if the censer is completely empty, however.
#### How to reproduce:

1. Fill the censer with a desired aspect and activate it, so it brings the growth of aspectrus plants at least to the 1st stage.
2. Leave that exact aspect in censer, but don't activate it once it runs out of fuel.
3. Observe the growth of aspectrus plants with censer not working.

#### Expected result:

Aspectrus plant should probably not grow with censer inactive.

#### Actual result:

Aspectrus fruit continue to grow even with censer inactive,

**Comment by TheCyberBrick** [comment]
Hm, right. Yeah, it should only grow when the censer is active :P
