### ISSUE TITLE
Crash On start up. Help appreciated 

### ISSUE THREAD

**Issue by EAGBCD** [TheCyberBrick/The-Betweenlands#1079]
#### Betweenlands version:

Latest

#### Forge version:

Latest

#### Singleplayer or Multiplayer:

SP

#### Installed mods:

https://www.curseforge.com/minecraft/modpacks/minecraft-eternal

Also added 

optifine
Redstone Arsenal
Blood Magic
Animus
Genetics reborn
Apotheosis
Serene Seasons
Youngs better caves
Save My Stronghold!
Draconic evolution
MmmMmmMmmMmm
PSI
Super sound muffler revived 
Torch master
Better advancements 
Enivonemntal tech
Ender io energy 
Morph-o-Tool
Pretty beaches
Unlimited Chisel Works
Potion icon remover
immersive railroading
Snow! Real Magic!
(And library mods needed for these mods not on the list)

## Link to full crash log
https://gist.github.com/EAGBCD/38d045127cd16eb2ac45bc658d02480a

#### How to reproduce:

1. Prest start game
2. Wait till the end of step 2 on the forge thing
3. Crash

#### Expected result:

Game open good

#### Actual result:

Game not [open]([url](url))

**Comment by TheCyberBrick** [comment]
You've run out of potion IDs. Adding more mods to large modpacks that already push limits will likely cause such issues. You can try  using https://www.curseforge.com/minecraft/mc-mods/jeid, however be warned that this can potentially corrupt worlds, so make backups.
