### ISSUE TITLE
Dead Trees

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#108]
Made up of rotten weedwood bark. Giant stumps and hollow logs. They should gen in swamplands. Poison Ivy grows on them.
Found these for reference. They are Dave's. http://s1316.photobucket.com/user/Vadis365/media/2014-09-26_225737_zps7f965350.png.html?sort=3&o=2
http://s1316.photobucket.com/user/Vadis365/media/2014-09-26_225940_zps46f70b1a.png.html?sort=3&o=3

Rotten weedwood bark sometimes spawns a termite when broken, though the mobs dont have to be added yet. A silverfish can be used for now.

**Comment by vadis365** [comment]
Do you want hollow Logs like the Erebus - or is there some fancy block planned?

**Comment by MrCompost** [comment]
Just hollow logs would be good. I added the texture for Rotten Bark btw. I'd just use silverfish as a placeholder until the termites are done.

**Comment by TripleHeadedSheep** [comment]
So now that these are added, what's left to do for them? I guess the termite mobs will come in a later stage and we use place holders for now?

**Comment by MrCompost** [comment]
Hmm yeah, we'll just use leeches for now. The Rotten Bark should have a 25% chance of spawning them when broken and otherwise drop nothing.

**Comment by MrCompost** [comment]
Gonna close this one for now.
