### ISSUE TITLE
Betweenlands Dimension not initialize

### ISSUE THREAD

**Issue by skrilax91** [TheCyberBrick/The-Betweenlands#1080]
#### Installed mods:
All SevTech : Ages Mods 

A Block of Charcoal Curseforge
AbyssalCraft Integration Curseforge
AbyssalCraft Curseforge
Actually Additions Curseforge
Actually Baubles Curseforge
Advanced mortars Curseforge
Animalium Curseforge
Antique atlas Curseforge
AppleCore Curseforge
AppleSkin Curseforge
Applied energistics 2 AE Mod Info
Armoreablemobs Curseforge
Astikoor_horse
Astralsorcery Wiki Curseforge
AutoRegLib
Base
Baubles
Bdlib
Better With Addons
BetterAdvancements
BetterBuildersWands
BetterFoliage
BetterFps
BetterWithMods
BiblioCraft
BloodMagic
BNBGamingCore
BNBGamingLib
Bonsaitrees
Bookshelf
Buildcraft Builders
Buildcraft Core
Buildcraft Factory
Buildcraft Robotics
Buildcraft Transport
Caliper
car
CarryOn MC
CD4017BE_lib
Ceramics
Chameleon
Chargers
ChickenASM
Chisel
chiselsandbits
ClientTweaks
Clumps
CodeChickenLib
ColouredTooltips
CommonCapabilities
compactmachines3
ContentTweaker
Controlling
CookingForBlockheads
CraftStudio
CraftTweaker2
CTM
Cucumber
CustomMainMenu
Cyclic
CyclopsCore
DarkUtils
DeathCompass
DefaultOptions
Despawningspawners
DimensionalControl
DimensionStages
Dung Pipe
ElevatorMod
EmberRootZoo
EnchantmentDescriptions
EnderStorage
Enderutilities
Environmentaltech
Extendedcrafting
ExtraPlanets
FancyBlockParticles
FarmingForBlockheads
Farseek
FastWorkbench
FatCat
Ferdinand's Flowers
Foamfix
Forgelin
ForgeMultipart
GalacticraftCore
Galacticraft
GalacticraftTweaker
GameStages
Generators
Geolosys
GobbleCore
Guide
Harvest
HorsePower
HuntingDimension
Hwyla
Immcraft
ImmersiveEngineering
ImmersiveEngineering Core
Immersivepetroleum
Immersivetech
ImprovedBackpacks
Incontrol
InductiveLogistics
Industrialforegoing
InfoAccessories
IntegratedDynamics
InventoryTweaks
IronBackpacks
Ironchest
Ironjetpacks
ItemStages
IvToolkit
Jei_1.12.2
Journeymap
JourneyMapStages
Just A Raft Mod
JustAFewFish
Justthetips
KleeSlabs
LootTableTweaker
MagmaMonsters
Mantle
mcjtylib
Mekanism
Mercurius
MicdoodleCore
MJRLegendsLib
mobends
MobGrindingUtils
MobStages
modtweaker
modularmachinery
modular
Morpheus
MouseTweaks
MoVillages
mpbasic
MPUtils
MTLib
multiblockstages
MundaneRedstone
mysticalagradditions
mysticalagriculture
natura
Neat
NetherEx
noRecipeBook
NotEnoughItems
NoWorldgen5You
Nutrition
OceanFloor
oeintegration
OreExcavation
OreStages
Overloaded
pickletweaks
Placebo
PlayerAPI
playerskin
pneumaticcraft
PowerAdapters
Prestige
PrimalChests
PrimalCore
PrimalTech
ProgressionTweaks
prospectors
QuantumStorage
Quark
QuickLeafDecay
rangedpumps
RealisticItemDrops
RebornCore
RebornStorage
RecipeStages
RecurrentComplex
RedstoneFlux
refinedstorage
refinedstorageaddons
ResourceLoader
rftools
rftoolsctrl
roadrunner
rustic
Scannable
SevTweaksNPC
simpleautorun
simplegenerators
SimpleStorageNetwork
SimplyArrows
SmoothFont
SpartanShields
spatialservermod
StevesCarts
stg
StorageDrawers
Streams
StuffASockInIt
supersoundmuffler
TallGates
TConstruct
tesla
The Beneath
TheBetweenlands
TheBetweenlands
TheBetweenlands
ThirstyBottles
TinkersComplement
TinkerStages
TinkerToolLeveling
TipTheScales
Toast Control
togetherforever
TombManyGraves
Totemic
tothebatpoles
Translocators
Traverse
Triumph
trumpetskeleton
Tumbleweed
twilightforest
Uppers
valkyrielib
ViesCraft
VillagerTrades
Waddles
WailaStages
WanionLib
WaterControlExtreme
WaterStrainer
Wawla
weirdinggadget
WildCrops
Wither Skeleton Tweaks
Wopper
xnet
YNot
yoyos 

## Description of the problem
I currently have an issue with The Betweenlands Mod, specialy with the dimension, it seems like the dimension are like otherworld.
Animals like pig and cow spawn and otherworld trees spawn. Also no one of mob spawn.
You have [here](https://github.com/DarkPacks/SevTech-Ages/issues/4177) the link of the issue on SevTech : Ages GitHub

#### How to reproduce:

1. Go to the BetweenLand

#### Expected result:
A normal dimension generation

#### Actual result:
A Fully bugged dimension generation

#### Pictures:

![2020-06-29_01 49 34](https://user-images.githubusercontent.com/6585219/86002621-e1dfb900-ba10-11ea-854d-c44e6f464d5f.png)
![2020-06-29_01 49 46](https://user-images.githubusercontent.com/6585219/86002625-e310e600-ba10-11ea-8f13-04f96d09bfa3.png)
![2020-06-29_01 50 08](https://user-images.githubusercontent.com/6585219/86002627-e3a97c80-ba10-11ea-84f4-211aa8bfe224.png)

**Comment by TheCyberBrick** [comment]
Looks to me like some sort of biome conflict. This is likely not caused by Betweenlands itself, but some other mod overwriting biomes. Could maybe also be caused by SpongeForge or some of your plugins since BL usually works fine in SevTech ages.
