### ISSUE TITLE
When Player broke vase and attack termite, server crashed

### ISSUE THREAD

**Issue by Caishangqi** [TheCyberBrick/The-Betweenlands#1082]
#### Installed mods:

| State  | ID                              | Version                 | Source                                          | Signature                                |
	|:------ |:------------------------------- |:----------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                       | 1.12.2                  | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                             | 9.42                    | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                             | 8.0.99.99               | CatServer-5ef3d0c-universal.jar                 | None                                     |
	| LCHIJA | forge                           | 14.23.5.2854            | CatServer-5ef3d0c-universal.jar                 | None                                     |
	| LCHIJA | creativecoredummy               | 1.0.0                   | minecraft.jar                                   | None                                     |
	| LCHIJA | ivtoolkit                       | 1.3.3-1.12              | minecraft.jar                                   | None                                     |
	| LCHIJA | foamfixcore                     | 7.7.4                   | minecraft.jar                                   | None                                     |
	| LCHIJA | randompatches                   | 1.12.2-1.21.0.3         | randompatches-1.12.2-1.21.0.3.jar               | None                                     |
	| LCHIJA | tweakersconstruct               | 1.12.2-1.5.3            | tweakersconstruct-1.12.2-1.5.3.jar              | None                                     |
	| LCHIJA | bspkrscore                      | 7.6.0.1                 | [1.12]bspkrsCore-universal-7.6.0.1.jar          | None                                     |
	| LCHIJA | treecapitator                   | 1.43.0                  | [1.12]TreeCapitator-client-1.43.0.jar           | None                                     |
	| LCHIJA | itemfilters                     | 1.0.3.12                |ItemFilters-1.0.3.12.jar            | None                                     |
	| LCHIJA | chameleon                       | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                  | None                                     |
	| LCHIJA | attributefix                    | 1.0.4                   | AttributeFix-1.12.2-1.0.4.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | guideapi                        | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar              | None                                     |
	| LCHIJA | additional_lights               | 1.12.2-1.2.1            | additional_lights-1.12.2-1.2.1.jar              | None                                     |
	| LCHIJA | applecore                       | 3.4.0                   | AppleCore-mc1.12.2-3.4.0.jar                    | None                                     |
	| LCHIJA | charset                         | 0.5.6.4                 | Charset-Lib-0.5.6.4.jar                         | None                                     |
	| LCHIJA | crafttweaker                    | 4.1.20                  | CraftTweaker2-1.12-4.1.20.574.jar               | None                                     |
	| LCHIJA | mtlib                           | 3.0.6                   | MTLib-3.0.6.jar                                 | None                                     |
	| LCHIJA | modtweaker                      | 4.0.18                  | modtweaker-4.0.18.jar                           | None                                     |
	| LCHIJA | jei                             | 4.15.0.293              | jei_1.12.2-4.15.0.293.jar                       | None                                     |
	| LCHIJA | appleskin                       | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LCHIJA | mantle                          | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJA | roots                           | 1.12.2-3.0.29           | Roots-1.12.2-3.0.29.jar                         | None                                     |
	| LCHIJA | mysticalworld                   | 1.12.2-1.8.4            | mysticalworld-1.12.2-1.8.4.jar                  | None                                     |
	| LCHIJA | chisel                          | MC1.12.2-1.0.2.45       | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCHIJA | baubles                         | 1.5.2                   | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | thaumcraft                      | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LCHIJA | twilightforest                  | 3.10.1013               | twilightforest-1.12.2-3.10.1013-universal.jar   | None                                     |
	| LCHIJA | tconstruct                      | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCHIJA | conarm                          | 1.2.5.9                 | conarm-1.12.2-1.2.5.9.jar                       | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | armoryexpansion                 | 1.4.2                   | armoryexpansion-1.4.2.jar                       | None                                     |
	| LCHIJA | armoryexpansion-custommaterials | 1.4.2                   | armoryexpansion-1.4.2.jar                       | None                                     |
	| LCHIJA | armoryexpansion-iceandfire      | 1.4.2                   | armoryexpansion-1.4.2.jar                       | None                                     |
	| LCHIJA | armoryexpansion-matteroverdrive | 1.4.2                   | armoryexpansion-1.4.2.jar                       | None                                     |
	| LCHIJA | athenaeum                       | 1.12.2-1.18.1           | athenaeum-1.12.2-1.18.1.jar                     | None                                     |
	| LCHIJA | artisanworktables               | 1.12.2-1.23.4           | artisanworktables-1.12.2-1.23.4.jar             | None                                     |
	| LCHIJA | artisanautomation               | 1.12.2-1.0.5            | artisanautomation-1.12.2-1.0.5.jar              | None                                     |
	| LCHIJA | astralsorcery                   | 1.10.22                 | astralsorcery-1.12.2-1.10.24.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | atum                            | 2.0.17                  | Atum-1.12.2-2.0.17.jar                          | None                                     |
	| LCHIJA | betternether                    | 0.1.8.6                 | betternether-0.1.8.6.jar                        | None                                     |
	| LCHIJA | bibliocraft                     | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| LCHIJA | bloodmagic                      | 1.12.2-2.4.3-105        | BloodMagic-1.12.2-2.4.3-105.jar                 | None                                     |
	| LCHIJA | carryon                         | 1.12.3                  | CarryOn+MC1.12.2+v1.12.3.jar                    | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | cathedral                       | 1.12.2-1.9.9            | Cathedral-1.12.2-1.9.9.jar                      | None                                     |
	| LCHIJA | chunkpregenerator               | 2.1                     | Chunk+Pregenerator+V1.12-2.3.jar                | None                                     |
	| LCHIJA | cookingforblockheads            | 6.5.0                   | CookingForBlockheads_1.12.2-6.5.0.jar           | None                                     |
	| LCHIJA | craftingex                      | 1.2.0                   | CraftingEX_1.12-v1.2.0.jar                      | None                                     |
	| LCHIJA | crafttweakerjei                 | 2.0.3                   | CraftTweaker2-1.12-4.1.20.574.jar               | None                                     |
	| LCHIJA | crafttweakersync                | 1.0                     | CraftTweakerSync(CT脚本同步)-1.0.jar                | None                                     |
	| LCHIJA | opframe                         | 1.4.0                   | OnlinePicFrame_v1.4.35_mc1.12.2.jar             | None                                     |
	| LCHIJA | creativecore                    | 1.10.0                  | CreativeCore_v1.10.16_mc1.12.2.jar              | None                                     |
	| LCHIJA | customnpcs                      | 1.12                    | CustomNPCs_1.12.2-(01Oct19).jar                 | None                                     |
	| LCHIJA | electrostatic                   | 1.0.1                   | electrostatic-1.12.2-1.0.1.jar                  | None                                     |
	| LCHIJA | embers                          | 1.13-hotfix2            | EmbersRekindled-1.13-hotfix2.jar                | None                                     |
	| LCHIJA | forgelin                        | 1.8.4                   | Forgelin-1.8.4.jar                              | None                                     |
	| LCHIJA | soot                            | 1.6                     | Soot-1.6.jar                                    | None                                     |
	| LCHIJA | thebetweenlands                 | 3.6.1                   | TheBetweenlands-3.6.1-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | pewter                          | 1.4.3                   | Pewter-1.4.3.jar                                | None                                     |
	| LCHIJA | taiga                           | 1.12.2-1.3.3            | taiga-1.12.2-1.3.4.jar                          | None                                     |
	| LCHIJA | embersconstruct                 | 1.2.4                   | embersconstruct-1.12.2-1.2.4-hotfix.jar         | None                                     |
	| LCHIJA | embersified                     | 1.0.3                   | Embersified-1.12.2-1.0.3.jar                    | None                                     |
	| LCHIJA | engineersdecor                  | 1.1.0-b2                | engineersdecor-1.12.2-1.1.0-b2.jar              | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | fasterladderclimbing            | 0.1-146                 | FasterLadderClimbing-1.12-0.1-146.jar           | None                                     |
	| LCHIJA | flatcoloredblocks               | mc1.12-6.8              | flatcoloredblocks-mc1.12-6.8.jar                | None                                     |
	| LCHIJA | foamfix                         | 0.10.5-1.12.2           | foamfix-0.10.5-1.12.2.jar                       | None                                     |
	| LCHIJA | llibrary                        | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil                          | 8.0.4                   | fossilsarcheology-8.0.4.jar                     | None                                     |
	| LCHIJA | ftbbackups                      | 1.1.0.1                 | FTBBackups-1.1.0.1.jar                          | None                                     |
	| LCHIJA | ftblib                          | 5.4.7.2                 | FTBLib-5.4.7.2.jar                              | None                                     |
	| LCHIJA | ftbutilities                    | 5.4.1.128               | FTBUtilities-5.4.1.128.jar                      | None                                     |
	| LCHIJA | ftbquests                       | 1.8.1.1                 | FTBQuests-1.8.1.1.jar                           | None                                     |
	| LCHIJA | cfm                             | 6.3.1                   | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCHIJA | futuremc                        | 0.2.3                   | future-mc-1.12.2-0.2.3.2.jar                    | None                                     |
	| LCHIJA | waila                           | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHIJA | immersiveengineering            | 0.12-98                 | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LCHIJA | immersivepetroleum              | 1.1.9                   | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
	| LCHIJA | immersivetech                   | 1.3.10                  | immersivetech-1.12-1.3.10.jar                   | None                                     |
	| LCHIJA | incontrol                       | 3.9.16                  | incontrol-1.12-3.9.16.jar                       | None                                     |
	| LCHIJA | instantunify                    | 1.1.2                   | instantunify-1.12.2-1.1.2.jar                   | None                                     |
	| LCHIJA | journeymap                      | 1.12.2-5.5.4            | journeymap-1.12.2-5.5.4.jar                     | None                                     |
	| LCHIJA | jarm                            | 1.1.1                   | Just+A+Raft+Mod-1.1.1.jar                       | None                                     |
	| LCHIJA | jeid                            | 1.0.3-55                | JustEnoughIDs-1.0.3-55.jar                      | None                                     |
	| LCHIJA | loottweaker                     | 0.2.0                   | LootTweaker-0.2.0+MC1.12.2.jar                  | None                                     |
	| LCHIJA | materialchanger                 | 1.0                     | materialchanger1.0.3-1.12.2.jar                 | None                                     |
	| LCHIJA | mcwbridges                      | 1.0.4                   | mcw-bridges-1.0.4-mc1.12.2.jar                  | None                                     |
	| LCHIJA | mcwroofs                        | 1.0.1                   | mcw-roofs-1.0.1-mc1.12.2.jar                    | None                                     |
	| LCHIJA | mcwwindows                      | 1.0                     | mcw-windows-1.0.0-mc1.12.2.jar                  | None                                     |
	| LCHIJA | mist                            | 1.2.4.7                 | MistyWorld-1.12.2-1.2.4.7.jar                   | None                                     |
	| LCHIJA | numina                          | 1.12.2-1.0.38           | Numina-1.12.2-1.0.38.jar                        | None                                     |
	| LCHIJA | powersuits                      | 1.12.2-1.0.46           | ModularPowersuits-1.12.2-1.0.46.jar             | None                                     |
	| LCHIJA | netherportalfix                 | 5.3.17                  | NetherPortalFix_1.12.1-5.3.17.jar               | None                                     |
	| LCHIJA | nutrition                       | 4.6.1                   | Nutrition-1.12.2-4.6.1.jar                      | None                                     |
	| LCHIJA | ordinarycoins                   | 1.5                     | ordinarycoins-1.12.2-1.5.jar                    | None                                     |
	| LCHIJA | harvestcraft                    | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zg.jar                 | None                                     |
	| LCHIJA | patchouli                       | 1.0-20                  | Patchouli-1.0-20.jar                            | None                                     |
	| LCHIJA | pvj                             | 1.6.4                   | ProjectVibrantJourneys-1.12.2-1.6.4.jar         | None                                     |
	| LCHIJA | puddles                         | 1.1                     | Puddles-1.1.jar                                 | None                                     |
	| LCHIJA | reborncore                      | 3.19.4.529              | RebornCore-1.12.2-3.19.4.529-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | reccomplex                      | 1.4.8.2                 | RecurrentComplex-1.4.8.2.jar                    | None                                     |
	| LCHIJA | rustic                          | 1.1.4                   | rustic-1.1.4.jar                                | None                                     |
	| LCHIJA | sereneseasons                   | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar       | None                                     |
	| LCHIJA | signpost                        | 1.08.3                  | signpost-1.12.2-1.08.3.jar                      | None                                     |
	| LCHIJA | spiceoflife                     | 1.3.12                  | SpiceOfLife-mc1.12-1.3.12.jar                   | None                                     |
	| LCHIJA | stepup                          | 1.0.2-mc1.10-1.12.2     | StepUp-1.0.2-mc1.10-1.12.jar                    | None                                     |
	| LCHIJA | storagedrawers                  | 5.2.2                   | StorageDrawers-1.12.2-5.4.2.jar                 | None                                     |
	| LCHIJA | teastory                        | 3.3.3-B33.418-1.12.2    | TeaStory-3.3.3-B33.418-1.12.2.jar               | None                                     |
	| LCHIJA | techreborn                      | 2.27.3.1084             | TechReborn-1.12.2-2.27.3.1084-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | thaumicrestoration              | 1.4.0                   | ThaumicRestoration-1.4.0.jar                    | None                                     |
	| LCHIJA | totemic                         | 1.12.2-0.11.6           | Totemic-1.12.2-0.11.6.jar                       | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| LCHIJA | travelersbackpack               | 1.0.29                  | TravelersBackpack-1.12.2-1.0.29.jar             | None                                     |
	| LCHIJA | variedcommodities               | 1.12.2                  | VariedCommodities_1.12.2(21nov19).jar           | None                                     |
	| LCHIJA | worleycaves                     | 1.5.1                   | worleycaves-1.5.1.jar                           | None                                     |
	| LCHIJA | kiwi                            | 0.5.3.32                | Kiwi-1.12.2-0.5.3.32.jar                        | None                                     |
	| LCHIJA | cuisine                         | 0.5.22-build929         | Cuisine-0.5.22-build929.jar                     | None                                     |
	| LCHIJA | structurize                     | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar         | None                                     |
	| LCHIJA | minecolonies                    | 1.12.2-0.11.811-BETA    | minecolonies-1.12.2-0.11.811-BETA-universal.jar | None                                     |
	| LCHIJA | techreborn_compat               | 1.0.0                   | TechReborn-ModCompatibility-1.12.2-1.4.0.76.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | armoryexpansion-conarm          | 1.4.2                   | armoryexpansion-1.4.2.jar                       | None                                     |
	| LCHIJA | mysticallib                     | 1.12.2-1.7.0            | mysticallib-1.12.2-1.7.0.jar                    | None                                     |
	| LCHIJA | tweakersconstructpostload       | 1.12.2-1.5.3            | tweakersconstruct-1.12.2-1.5.3.jar              | None                                     |

## Link to full crash log

https://paste.ubuntu.com/p/dqzjbFMB3y/

#### How to reproduce:

1. When player enter the between land and using tconstruct weapon broke vase and attack termite
2. the server crashed
3. the weapon has the traits(Reviving)

#### Expected result:

the server not crash 

#### Actual result:

server crashed

**Comment by GoryMoon** [comment]
Not an issue with the Betweenlands, it's caused by https://www.curseforge.com/minecraft/mc-mods/taiga-tinkers-alloying-addon calling a client only method.
Looks like it's caused when the player is using an item that has the "reviving" trait.
