### ISSUE TITLE
"Ticking Rotating Particle" crash when getting in and out of rowboat with Weather 2/CoroUtil installed (1.12.2)

### ISSUE THREAD

**Issue by Cypranex** [TheCyberBrick/The-Betweenlands#1083]
#### Betweenlands version:

3.6.1

#### Forge version:

14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

https://pastebin.com/BVXqSWBa

## Link to full crash log

https://pastebin.com/Cy8J1fXG

#### How to reproduce:

1. Create new world.
2. Spawn yourself a rowboat.
3. Attempt to get in and out of rowboat.  It will usually happen on the first time getting in, but sometimes I had to do it a couple times.

#### Expected result:

No crash.

#### Actual result:

I was immediately presented with a "Closing Internal Server" window, a crash window appeared saying that the following mods were at fault: Extended Renderer, Extended Config, CoroUtil.

#### Pictures:

Apologies if this issue is not the fault of the Betweenlands, I honestly wasn't sure.  Thank you for the help.

**Comment by TheCyberBrick** [comment]
Yep, this problem is caused by CoroUtil. You should report it to their issue tracker 👍
