### ISSUE TITLE
Tar Pools

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#109]
Pools of liquid tar generate on the surface and more commonly underground. Liquid tar is very thick, slows you down a lot. If you become submerged you immediately take suffocation damage. Solid Tar forms when liquid tar meets water. Tar Beasts spawn in the pools.

**Comment by MrCompost** [comment]
Closing this for now, doesn't need to be open yet.

**Comment by vadis365** [comment]
Closing this at both types of tar pool now are in game.
Mob AI's etc. are a different issue.
