### ISSUE TITLE
Port the whole mod to 1.15.2/1.16.2

### ISSUE THREAD

**Issue by Emerald-Rocket** [TheCyberBrick/The-Betweenlands#1093]
Please port the whole mod to newer versions than 1.12.2, because I play forge on 1.15.2 and later, and that is the version where I play with my original mods. I want to try my mods with The Betweenlands and its items with my mod. I can't downgrade my mod to older versions.

Please port version 3.6.2 to forge 1.15.2 - 31.0.36 Singleplayer

Here is my main mod that I want to try this mod out without downgrading: Blocks, Tools, Realms and beyond
Download for 1.15.2: https://www.curseforge.com/minecraft/mc-mods/blocks-tools-realms-beyond

**Comment by PetasiGit** [comment]
Not happening anytime soon. There are no plans to port.

**Comment by Kuraiko55** [comment]
When I  downloaded the latest version of the mod I received a file  named "TheBetweenlands-3.6.2-universal.jar".
Does "universal" mean it's compatible with any MC version?

**Comment by pau101** [comment]
No, "universal" means it is for both client and dedicated server as we do also provide a server only jar which excludes client assets to reduce file size.

**Comment by Kuraiko55** [comment]
> No, "universal" means it is for both client and dedicated server as we do also provide a server only jar which excludes client assets to reduce file size.

I see. Thanks for the enlightenment and quick response!
