### ISSUE TITLE
[Suggestion] Bone Crawler

### ISSUE THREAD

**Issue by 000TheEldritchOne000** [TheCyberBrick/The-Betweenlands#1095]
Description: 
The Bone Crawler is a new spider like mob that will rarely spawn naturally in the Betweenlands. It has 3 sizes and 1 mini-boss version. The three sizes determine it's strength, damage, and health. This mob would shoot out a large web like net at you. Rapping you up on contact causing decay for 2 seconds. Only Large bone crawlers, and the Bone Crawler Patriarch mini-boss can. The large and mini-boss wear slimy bone armor to protect them. You must hit these armor pieces knocking them off allowing you to damage them. The Bone Crawler Patriarch has 1 Matriarch Chiromaw wing on it's abdomen which can shoot 5 Chiromaw barbs at you in a small explosion towards it's enemy. Also these spiders can swiftly move up walls and ceilings able to jump at you.

(A side note: Chiromaw's and Bone Crawlers hate eachother)

Stats: 
Bone Crawler Patriarch: 210 health, damage 10 on all difficulties, and decay 2 for 4 seconds 
Large Bone Crawler: 30 health, damage 6 on easy, damage 8 on normal, damage 10 on hard, and decay for 3 seconds.
Medium Bone Crawler: 15 health, damage 3 on easy, damage 5 on normal, damage 7 on hard, and decay for 2 seconds.
Small Bone Crawler: 5 health, damage 1 on easy, damage 2 on normal, damage 4 on hard.

Drops:
The drops from them all will consist of slimy bones, Crawler meat, Crawler fangs, and exp. For the Patriarch Bone Crawler 2-5 Chiromaw barbs can drop.

The Dungeon:
The Bone Crawler Den is the name for the dungeon. New blocks will be added, webbed Pitstone blocks will be found like pillars in it. This dungeon will be some what cramped with cocoons of Chiromaw's, and Swamp Hag's. This dungeon will only generate in the Pitstone Caves. The cocoon Chiromaw's and Swamp Hag's give a hit on what to use to breed them

Spawning:
Bone Crawls can spawn alone in the Caves rarely, or more common in the Pitstone Caves. They also can spawn when a rift is completely closed and the Betweenlands is shrouded in darkness. Crawling their way out of the ground.
 
Crafting:
Crawler fangs will be used to add a special decay effect on non-boss/mini-boss mobs. They effect lasts 2 seconds reducing the mobs health like the player having the decay effect put on them. Crawler meat is something

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
