### ISSUE TITLE
(Almost) no sounds in The Betweenlands dimension have subtitles.

### ISSUE THREAD

**Issue by sjaak31367** [TheCyberBrick/The-Betweenlands#1096]
#### Betweenlands version:

3.5.10

#### Forge version:

1.12.2-14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer (tested). Multiplayer possibly too, unknown.

#### Installed mods:

SevTech: Ages (3.1.5) - ( https://atlauncher.com/pack/SevTechAges )

## Link to full crash log

N/A

#### How to reproduce:

1. Have subtitles enabled
1.1. "Options" -> "Music & Sounds..." -> "Show Subtitles:"
2. Enter or be in The Betweenlands dimension (If there are multiple and I've only so far discovered one, I am referring to the swampy one.)
3. Go about doing stuff, punch mobs, go caving, etc.
4. Notice that the subtitle/caption box in the lower-right corner of your screen does not display the sounds from The Betweenlands things/actions/environments. (Except breaking blocks, eating, walking (or at least those I have discovered so far).)

#### Expected result:

Sounds to show up in the lil' box, like:
"Lurker growls", "Eerie cave sounds", "Boulder rolling"
with an indicated direction if applicable.

#### Actual result:

The only sounds I remember showing up were player sounds such as "Footsteps", "Eating", "Burp", and possibly mining, and player-hurt as well.
Cave-noises, mobs, and other, do now show up. Making tracking them sometimes difficult, as well (possibly) resulting in jump-scares to people hard-of-hearing.
(Example: There's suddenly a boulder in your face, or you were punched off a ledge by a hag, because you did not hear them coming, nor could you see their sounds approach.)

#### Pictures:

Kind regards,
~Sjaak

**Comment by vadis365** [comment]
Hello, we have added a lot of subtitiles now - so closing - Thank you.
