### ISSUE TITLE
Suggestion:Add mechanisms so that players can eat the main world food normally  in the late game

### ISSUE THREAD

**Issue by 363144628** [TheCyberBrick/The-Betweenlands#1098]
I love The food Pam's HarvestCraft serves but they spoil all over in The Betweenlands.I understand why this mechanism was designed.But I still hope that there is a mechanism that can use costly rituals or equipment at a later stage to get other foods back to normal within a certain size.The mechanism should be complex enough to prevent early implementation.

**Comment by PetasiGit** [comment]
I believe the intention of the mod is to have you survive off of what’s in the dimension. There is a config option for food decay if you want to use other foods in the dimension.

**Comment by 363144628** [comment]
@okl1001 I agree with you, but after I killed the BOSS and finished the story, it really bothers me that I still can't eat normally.However, adding the corresponding food directly to the whitelist or turning off the spoilage function undoubtedly loses a lot of fun.Therefore, I hope that there will be certain methods to restore at least part of the food to normal consumption in the later stage, rather than directly modify the configuration.

**Comment by PetasiGit** [comment]
There is no final boss as you seem to imply. Nor is there currently a real storyline. Even the lore is mostly up to the player’s interpretation. I think you’ll have to stick with using the whitelist in the config.

**Comment by 363144628** [comment]
Well, I'll give it a try.Thank you for your response.
