### ISSUE TITLE
[SUGGESTION] Greebling Theatre and Peat Mummy graveyard.

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1101]
Two ideas for possible generated structures that players can happen upon in the Betweenlands.

Greebling Theatre/ Greebling Stage:

Greeblings provide eerie music to enhance the atmosphere when traveling through the thick environment of the Betweenlands.  Finding a sort of small, makeshift stage suspended between two trees with a small ensemble of Greeblings playing in unison would add to that aesthetic.  This is mostly due to how out of place a stage would seem in the wild, yet it fits among the foliage having been erected from natural materials.  This could be entirely cosmetic to the environment, or you could possibly trade with them to obtain Greebling instruments; as these Greeblings are more accustomed to being the center of attention and don't frighten easily.  The Greebling pan flute and Cello could be used to play music with other Greeblings you find in the wild and that would cause them to reward you with a random helpful item.  These items would be slightly better than pot of chance loot considering the lengths required to trade with Greeblings.  The loot would be more in line with things like unanimated tar minions, or maybe even a Greebling specific item/ring.  You can only receive one reward per each befriended Greebling.  Or maybe playing Greebling instruments would cause them to congregate around you or your base for some sort of protection or buff.

Peat Mummy graveyard:

Peat Mummies take up residence within marsh and sludge planes biomes.  However, they simply crawl out of the ground and have no real origin point.  The Peat Mummies are the result of bodies being naturally preserved within the peat found in the ground.  Having these mummies manifest from a graveyard full of peat would make a lot of sense.  This would not replace the already established way Peat Mummies spawn out in the wild, as not all the bodies of wayward explorers are found and buried!  The graveyard would just be a bit more concentrated with the presence of Peat Mummies.  Unlike the previous idea, this area would greatly benefit from being an opportunity to brave a hardship with the promise of loot.  Shimmer Stones could be found here, as well as a few trinkets that can be dug up from some of the graves.  This loot would be consisting of weapons and tools rather than materials, as I would assume the bodies belonged to former explorers (who would have had gear on them upon death) before becoming Peat Mummies.  Alternatively, you could just use the graveyard as a proper arena to spawn the Dreadful Peat Mummy with a sort of feeding alter in the center instead.

Concept images are below.

I hope this sparked some curiosity at the very least.

![image](https://user-images.githubusercontent.com/69959989/90752634-a4c3d480-e2a5-11ea-8b79-b1a969aae633.png)

![image](https://user-images.githubusercontent.com/69959989/90752750-c4f39380-e2a5-11ea-93e0-05d07dc950ac.png)

![image](https://user-images.githubusercontent.com/69959989/90752768-cb820b00-e2a5-11ea-8a12-18d02bf978d8.png)

**Comment by Chiromaw** [comment]
one last idea for the Greebling Theatre: as an alternative, it could maybe be built or crafted rather than found in the wild to attract Greeblings that will stay and play to provide protection or buffs.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
