### ISSUE TITLE
ProjectEX - Collector doesn't EMC 

### ISSUE THREAD

**Issue by serafirim** [TheCyberBrick/The-Betweenlands#1105]
#### Betweenlands version:
3.6.2

#### Forge version:
forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:
Multiplayer and Singleplayer

#### Installed mods:
Aether Legacy 1.4.4
appliedenergistics2-rv6-stable-7_1
Avaritia-1.12.2-3.3.0.33-universal
BaseMetals-1.12-2.5.0-rc2.332
BrandonsCore-1.12.2-2.4.18.210-universal
buildcraft-all-7.99.24.6
ChanceCubes-1.12.2-4.1.0.300
chiselsandbits-14.33
CodeChickenLib-1.12.2-3.2.3.358-universal
CustomNPCs_1.12.2-(01Oct19)
Draconic-Evolution-1.12.2-2.3.25.351-universal
EnderCore-1.12.2-0.5.76
EnderIO-1.12.2-5.2.57
Erebus-1.0.30
extrautils2-1.12-1.9.9
Flat-Colored-Blocks-Mod-1.12.2
ForgeMultipart-1.12.2-2.6.2.83-universal
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
Guide-API-1.12-2.1.8-63
Industrial-Craft-2-Mod-Experimental-1.12.2
InventoryTweaks-1.63
Iron-Chests-Mod-1.12.2
jei_1.12.2-4.15.0.268
Mantle-Mod-1.12.2
Mekanism-1.12.2-9.8.2.389
MicdoodleCore-1.12.2-4.0.2.280
MMDLib-1.12-1.0.0-rc2.36
MrTJPCore-1.12.2
MultithreadedNoise-1.12.2-0.0.2
Neat+1.4-17
NetherPortalFix_1.12.1-5.3.17
NotEnoughItems-1.12.2-2.4.3.245-universal
OpenBlocks-1.12.2-1.8.1
OpenModsLib-1.12.2-0.12.2
outfox-0.1.5-mc1.12.2
performant-1.12.2-1.10
phosphor-1.12.2-0.2.6+build50-universal
ProjectE-1.12.2-PE1.4.1
ProjectEX-1.2.0.40
ProjectRed-Base-1.12.2
ProjectRed-Compat-1.12.2
ProjectRed-Fabrication-1.12.2
ProjectRed-Integration-1.12.2
ProjectRed-Lighting-1.12.2
ProjectRed-Mechanical-1.12.2
ProjectRed-World-1.12.2
railcraft-12.0.0
RedstoneFlux-1.12-2.1.1.1-universal
spongeforge-1.12.2-2838-7.2.1
Surge-1.12.2-2.0.77
TheBetweenlands-3.6.2-universal
thutcore-mc1.12.2-v5.21.0
Tinkers-Construct-Mod-1.12.2
twilightforest-1.12.2-3.10.1013-universal
unloader-1.2.0
VanillaFix-1.0.10-150
Waystones_1.12.2-4.0.72
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (1)
Xaeros_Minimap_1.18.5.3_Forge_1.12

#### How to reproduce:
1. Look in the inventory for Orange Collector
2. See if there is a yellow text that reads: EMC ##### (number)

#### Expected result:
EMC reading is there and you can EMC the collector

#### Actual result:
Nothing there that reads about EMC

**Comment by PetasiGit** [comment]
What does this have to do with The Betweenlands, exactly? I’m a bit confused.

**Comment by vadis365** [comment]
sigh.
