### ISSUE TITLE
When I use Shaders in The Betweenlands, Game seems to be stuck in the Loading Screen, But have no crash.

### ISSUE THREAD

**Issue by AnguineChip** [TheCyberBrick/The-Betweenlands#1106]
## Versions 
**- Forge 1.12.2 (Forge 14.23.5.2854)**
#### Betweenlands version:

**_Newest Version of the mod._**

#### Forge version:

**Forge 14.23.5.2854.**

#### Singleplayer or Multiplayer:
 
Singleplayer

#### Installed mods:
 
Modpack = Dark and Dangerous by Asianhalfsquat (YT)

#### How to reproduce:

1. Playing with any shader
2. Enter the Portal
3. Stuck in loading screen

#### Expected result:
 
Working Shaders

#### Actual result:
 
I am Stuck in the abyss of the loading screen

**Comment by TheSilverplier** [comment]
You can't use shaders in the betweenlands. That's why. Basically, BL uses its own shaders for lighting and various other things. You can always go in Config->Render to disable them. Then it should work normally. Or you can give up on external shaders, the choice is yours.

**Comment by AnguineChip** [comment]
ok, thx for the tip
