### ISSUE TITLE
Jukebox music disks do not stop music once music disk is removed or/and jukebox broken

### ISSUE THREAD

**Issue by Wethead05** [TheCyberBrick/The-Betweenlands#1108]
- Betweenlands version : 3.6.2

- Singleplayer

- Mods : the betweenlands

- How to reproduce:
1 - Play one of Voog2's wonderful disks in a weedwood jukebox
2 - Remove disk from jukebox
3 - Music will continue to play until the track has ended ( getting out of audible area does not impact the playing of the track)
4 - However music restarts once the disk is reinserted.

- Possible reasons - the code for the betweenlands jukebox is not the same as vannila as it is a separate block

**Comment by TheCyberBrick** [comment]
Please update to the latest version, if this is still a problem. I'm unable to reproduce this in the latest version, or maybe you're using another mod that might break this?
