### ISSUE TITLE
Why are giant roots Purple with yellow dots?

### ISSUE THREAD

**Issue by ForsakenAtlas** [TheCyberBrick/The-Betweenlands#1111]
#### Betweenlands version:
The betweenlands 3.6.2 Universal

#### Forge version:
1.12.2

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Only mods installed are Betweenlands, The Midnight, Mo Bends, Optifine

## Description of the problem
1. Messed with setting for some better textures
2. Left game and rejoined
3. Roots Are PURPLE WITH YELLOW DOTS! (Someone please help)

The roots of the giants roots are all of a sudden Purple with yellow dots on them and its annoying to the texture.

#### Actual result:
I left the game and when I joined back.. Purple roots

**Comment by PetasiGit** [comment]
This is due to the Halloween event that’s currently active in the game. To disable this, type `/blevent off thebetweenlands:spook` or go into the mod’s config menu and turn off Online event overrides.

**Comment by ForsakenAtlas** [comment]
Thank you so much.
