### ISSUE TITLE
Remove Gem Circle System

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1112]
Is there any way to remove the Gem Circle crafting?

I don't mind it on betweenlands items, but it's really annoying to see it for every.armor.type and every.weapon.in.the.game.

I can't seem to get MineTweaker to properly remove these recipes; is there any way to remove these recipes from the game?

**Comment by ghost** [comment]
Figured out how to use Mine Tweaker to run the script:

**recipes.removeByRecipeName("thebetweenlands:recipe_circle_gems");**

**Comment by PetasiGit** [comment]
Please close the issue if you’ve found a solution, thanks!

**Comment by TheCyberBrick** [comment]
👍
