### ISSUE TITLE
Mystery Crash!?!

### ISSUE THREAD

**Issue by xombiekilla** [TheCyberBrick/The-Betweenlands#1113]
[crash-2020-10-26_05.47.52-server.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5438050/crash-2020-10-26_05.47.52-server.txt)
Supposedly, this crash was caused by The Betweenlands mod. Something that's never happened to me before.

**Comment by TheCyberBrick** [comment]
Why is this crash supposedly caused by the Betweenlands? I don't think that's the case, I can't see anything pointing towards that. The only way this could happen is if the overworld somehow failed to load.
