### ISSUE TITLE
crashes please help

### ISSUE THREAD

**Issue by artzygal** [TheCyberBrick/The-Betweenlands#1114]
newest version,tried to go into world!
---- Minecraft Crash Report ----

WARNING: coremods are present:
  wings (wings-1.1.6-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.3.0-build.0528.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  FutureMC (future-mc-1.12.2-0.2.4.0.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.3.7.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/26/20 4:49 PM
Description: Exception initializing level

java.lang.NullPointerException: Exception initializing level
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.world.World.getCapability(World.java:4000)
	at thebetweenlands.common.world.storage.WorldStorageImpl.getCapability(WorldStorageImpl.java:81)
	at thebetweenlands.common.handler.WorldEventHandler.onChunkLoad(WorldEventHandler.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1982_WorldEventHandler_onChunkLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:862)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:156)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.world.World.getCapability(World.java:4000)
	at thebetweenlands.common.world.storage.WorldStorageImpl.getCapability(WorldStorageImpl.java:81)
	at thebetweenlands.common.handler.WorldEventHandler.onChunkLoad(WorldEventHandler.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1982_WorldEventHandler_onChunkLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:862)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:156)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 1 Drop: 0
	Level seed: -2580771172055826702
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4463733192 bytes (4256 MB) / 9999220736 bytes (9536 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 20, tcache: 87, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 150 mods loaded, 148 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version              | Source                                             | Signature                                |
	|:------ |:----------------------- |:-------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2               | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                     | 9.42                 | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                     | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy       | 1.0.0                | minecraft.jar                                      | None                                     |
	| LCHIJA | littletilescore         | 1.0.0                | minecraft.jar                                      | None                                     |
	| LCHIJA | xaerominimap_core       | 1.12.2-1.0           | minecraft.jar                                      | None                                     |
	| LCHIJA | atlcraft                | MC1.12-Ver1.9        | ATLCraftCandlesMod(MC1.12-Ver1.9).jar              | None                                     |
	| LCHIJA | baubles                 | 1.5.2                | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | atum                    | 2.0.19               | Atum-1.12.2-2.0.19.jar                             | None                                     |
	| LCHIJA | jei                     | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | quark                   | r1.6-177             | Quark-r1.6-177.jar                                 | None                                     |
	| LCHIJA | autoreglib              | 1.3-32               | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | axolotl_12              | V4 1.12.2            | Axolotls+V4+1.12.2.jar                             | None                                     |
	| LCHIJA | boba_teas               | 1.0.0                | Baking+Life+v.6+-1.12.2.jar                        | None                                     |
	| LCHIJA | bibliocraft             | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | biomesoplenty           | 7.0.1.2441           | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | birdsnests              | 2.1.0                | BirdsNests1.12.2-2.1.0.jar                         | None                                     |
	| LCHIJA | blocklings              | 1.0                  | Blocklings+6.0.1_b+-+1.12.2.jar                    | None                                     |
	| LCHIJA | bloodmoon               | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bonsaitrees             | 1.1.4                | bonsaitrees-1.1.4-b170.jar                         | None                                     |
	| LCHIJA | bookshelf               | 2.3.585              | Bookshelf-1.12.2-2.3.585.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | birdwmod                | 1.12.2-1.6.0         | TheBirdwatchingMod-1.6.0.jar                       | None                                     |
	| LCHIJA | bookworm                | 1.12.2-2.5.2.1       | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
	| LCHIJA | botania                 | r1.10-361            | Botania+r1.10-361.jar                              | None                                     |
	| LCHIJA | forgelin                | 1.8.3                | Forgelin-1.8.3.jar                                 | None                                     |
	| LCHIJA | bountiful               | 2.2.2                | Bountiful-2.2.2.jar                                | None                                     |
	| LCHIJA | butterflies             | 1.12.2-1.0.3         | butterflies-1.12.2-1.0.3.jar                       | None                                     |
	| LCHIJA | cakemod                 | 1.0.0                | CakeMod_1.12.2.jar                                 | None                                     |
	| LCHIJA | carryon                 | 1.12.1               | CarryOn MC1.12.2 v1.12.1.jar                       | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | caves_and_cliffs        | 1.0.6                | CC(FG1.12.2)+v1.0.6.jar                            | None                                     |
	| LCHIJA | ceramics                | 1.12-1.3.7           | Ceramics-1.12-1.3.7.jar                            | None                                     |
	| LCHIJA | chameleon               | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | charm                   | 1.12.2-1.3.7         | Charm-1.12.2-1.3.7.jar                             | None                                     |
	| LCHIJA | chickens                | 6.0.4                | chickens-6.0.4 (2).jar                             | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCHIJA | roots                   | 1.12.2-3.0.31        | Roots-1.12.2-3.0.31.jar                            | None                                     |
	| LCHIJA | mysticalworld           | 1.12.2-1.9.1         | mysticalworld-1.12.2-1.9.1.jar                     | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-1.0.1.44    | Chisel-MC1.12.2-1.0.1.44 (1).jar                   | None                                     |
	| LCHIJA | chiselsandbits          | 14.33                | chiselsandbits-14.33 (1).jar                       | None                                     |
	| LCHIJA | chococraft              | 0.9.8.0              | chococraft_1.12.2-0.9.8.0.jar                      | None                                     |
	| LCHIJA | coffeework              | 1.2.9                | coffeework-1.2.9.jar                               | None                                     |
	| LCHIJA | colored_water           | 1.12.2-b37           | ColoredWater-1.12.2-b37.jar                        | None                                     |
	| LCHIJA | comforts                | 1.4.1.3              | comforts-1.12.2-1.4.1.3.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | comfycozy               | 1.3                  | comfycozy-1.3.jar                                  | None                                     |
	| LCHIJA | cookingforblockheads    | 6.5.0                | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
	| LCHIJA | craftstudioapi          | 1.0.0                | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | opframe                 | 1.4.0                | OnlinePicFrame_v1.4.40_mc1.12.2.jar                | None                                     |
	| LCHIJA | creativecore            | 1.10.0               | CreativeCore_v1.10.16_mc1.12.2.jar                 | None                                     |
	| LCHIJA | creeperconfetti         | 1.4.2                | creeperconfetti-1.4.2.jar                          | None                                     |
	| LCHIJA | cucumber                | 1.1.3                | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCHIJA | customcraftingtables    | 1.0.0                | customcraftingtables-1.0.2-1.12.2.jar              | None                                     |
	| LCHIJA | customspawner           | 3.11.4               | CustomMobSpawner-3.11.4.jar                        | None                                     |
	| LCHIJA | cxlibrary               | 1.6.1                | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
	| LCHIJA | ptrmodellib             | 1.0.4                | PTRLib-1.0.4.jar                                   | None                                     |
	| LCHIJA | props                   | 2.6.3                | Decocraft-2.6.3_1.12.2 (1).jar                     | None                                     |
	| LCHIJA | deliciousdelights       | 1.4.1                | DeliciousDelights-1.4.1.jar                        | None                                     |
	| LCHIJA | doggytalents            | 1.15.1.6             | DoggyTalents-1.12.2-1.15.1.6.jar                   | None                                     |
	| LCHIJA | mocreatures             | 12.0.5               | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
	| LCHIJA | element                 | 1.0.1                | Elementary+Staffs+1.0.4.jar                        | None                                     |
	| LCHIJA | exoticbirds             | 1.0                  | Exotic+Birds+1.12.2-3.2.0.jar                      | None                                     |
	| LCHIJA | golems                  | 7.1.8                | Extra-Golems-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | extrautils2             | 1.0                  | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | fairylights             | 2.1.6                | fairylights-2.1.6-1.12.2.jar                       | None                                     |
	| LCHIJA | familiarfauna           | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
	| LCHIJA | fancylamps              | 1.2.1                | fancylamps-1.2.1.jar                               | None                                     |
	| LCHIJA | farmingforblockheads    | 3.1.28               | FarmingForBlockheads_1.12.2-3.1.28.jar             | None                                     |
	| LCHIJA | ferdinandsflowers       | 1.10.4.1             | Ferdinand's+Flowers-1.12.x-1.10.4.1.jar            | None                                     |
	| LCHIJA | flatcoloredblocks       | mc1.12-6.8           | flatcoloredblocks-mc1.12-6.8.jar                   | None                                     |
	| LCHIJA | flying_things           | 1.5.2                | flying_things-1.5.2-1.12.jar                       | None                                     |
	| LCHIJA | foamflower              | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar                | None                                     |
	| LCHIJA | forgeendertech          | 1.12.2-4.5.3.0       | ForgeEndertech-1.12.2-4.5.3.0-build.0528.jar       | None                                     |
	| LCHIJA | cfm                     | 6.3.1                | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LCHIJA | futuremc                | 0.2.4                | future-mc-1.12.2-0.2.4.0.jar                       | None                                     |
	| LCHIJA | gm                      | 1.0.5                | Gem+Mod-1.0.5.jar                                  | None                                     |
	| LCHIJA | gemsplusplus            | 1.12.2-V7.0.4        | gemsplusplus-1.12.2-7.0.4.jar                      | None                                     |
	| LCHIJA | hatstands               | 1.0.0                | hatstands-1.0.0-1.12.2.jar                         | None                                     |
	| LCHIJA | horse_colors            | 1.12.2-1.0.2         | horse_colors-1.12.2-1.0.4.jar                      | None                                     |
	| LCHIJA | hsbdry                  | 0.2HealthySalad      | HusbandryPies0.2-1.12.2.jar                        | None                                     |
	| LCHIJA | waila                   | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | ichunutil               | 7.2.2                | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mantle                  | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | inspirations            | 1.12.2-0.2.9         | Inspirations-1.12.2-0.2.9.jar                      | None                                     |
	| LCHIJA | inventorypets           | 2.0.6                | inventorypets-1.12-2.0.6.jar                       | None                                     |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | jeid                    | 1.0.3-48             | JustEnoughIDs-1.0.3-48.jar                         | None                                     |
	| LCHIJA | chickendungeons         | 1.0.1                | ldshadowlady-chickendungeons-1.0.1.jar             | None                                     |
	| LCHIJA | dogslie                 | 1.0.2                | LetSleepingDogsLie-1.12.2-1.0.2.jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | littletiles             | 1.5.0                | LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar          | None                                     |
	| LCHIJA | maidensmaterials        | 3.3                  | Maiden's+Marvelous+Materials-3.3.jar               | None                                     |
	| LCHIJA | mcwdoors                | 1.0                  | mcw-doors-1.0.0-mc1.12.2.jar                       | None                                     |
	| LCHIJA | mcwwindows              | 1.0                  | mcw-windows-1.0.0-mc1.12.2.jar                     | None                                     |
	| LCHIJA | moarmors                | 1.0.0                | Mo'Armors+V.1.6+[1.12.2].jar                       | None                                     |
	| LCHIJA | mopickaxes              | 10.0: Final BETA     | Mo-Pickaxes-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | morechickens            | 3.1.0                | morechickens-1.12.2-3.1.0 (1).jar                  | None                                     |
	| LCHIJA | morefurnaces            | 1.10.5               | MoreFurnaces-1.12.2-1.10.6.jar                     | None                                     |
	| LCHIJA | mo_swords               | v5                   | moSwords-1.12.2v5.jar                              | None                                     |
	| LCHIJA | naturaldecormod         | 1.3.6                | NaturalDecorModV1.3.6.jar                          | None                                     |
	| LCHIJA | neverenoughcandy        | 1.2.3                | NeverEnoughCandy-1.12.2-1.2.3.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ruby_mod                | 1.4.4b               | Njarm_v1.4.4b_mc1.12.2.jar                         | None                                     |
	| LCHIJA | notenoughpets           | 2.2.0                | NotEnoughPets-1.12.2-v2.2.0.jar                    | None                                     |
	| LCHIJA | oresabovediamonds       | 3.2                  | OresAboveDiamonds+1.12.2+v4.2.jar                  | None                                     |
	| LCHIJA | outfox                  | 0.1.5                | outfox-0.1.5-mc1.12.2.jar                          | None                                     |
	| LCHIJA | harvestcraft            | 1.12.2zb             | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LCHIJA | patchouli               | 1.0-20               | Patchouli-1.0-20.jar                               | None                                     |
	| LCHIJA | pattysmorestuff         | @VERSION@            | PattysMoreStuff-stable-1.1.8.jar                   | None                                     |
	| LCHIJA | pinklysheep             | 4.0.2                | pinklysheep-mc1.12.2-4.0.2.jar                     | None                                     |
	| LCHIJA | placeableitems          | 3.3                  | placeableitems-3.3.jar                             | None                                     |
	| LCHIJA | placebo                 | 1.6.0                | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCHIJA | quarkoddities           | 1                    | QuarkOddities-1.12.2.jar                           | None                                     |
	| LCHIJA | randomenchantments      | @VERSION@            | randomenchants-0.1.4a.jar                          | None                                     |
	| LCHIJA | redstoneflux            | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | reptilemod              | 3.8.4                | Reptile-Mod-1.12.2.jar                             | None                                     |
	| LCHIJA | rockhounding_core       | 3.22                 | rockhounding_core-1.12.2-3.22.jar                  | None                                     |
	| LCHIJA | gbook                   | 2.9.4                | Guidebook-1.12.2-2.9.4.jar                         | None                                     |
	| LCHIJA | rockhounding_rocks      | 1.12.2-3.20          | rockhounding_rocks-1.12.2-3.20.jar                 | None                                     |
	| LCHIJA | rustic                  | 1.1.6                | rustic-1.1.6.jar                                   | None                                     |
	| LCHIJA | scollectibles           | demo                 | scollectibles-1.1.jar                              | None                                     |
	| LCHIJA | signpost                | 1.08.3               | signpost-1.12.2-1.08.3.jar                         | None                                     |
	| LCHIJA | simplytea               | 1.6                  | simplytea-1.6.jar                                  | None                                     |
	| LCHIJA | skinnedcarts            | 1.0.0                | SkinnedCarts-1.0.jar                               | None                                     |
	| LCHIJA | spartanshields          | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
	| LCHIJA | storagedrawers          | 1.12.2-5.4.0         | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
	| LCHIJA | tropicraft              | 7.1.9.115            | tropicraft-MC1.12.2-7.1.9.115.jar                  | None                                     |
	| LCHIJA | unlimitedchiselworks    | 0.3.4                | UnlimitedChiselWorks-0.3.4.jar                     | None                                     |
	| LCHIJA | thebetweenlands         | 3.6.2                | TheBetweenlands-3.6.2-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | storagedrawersunlimited | 1.12.2-1.3.0         | StorageDrawersUnlimited-1.12.2-1.3.0.jar           | None                                     |
	| LCHIJA | sushimod                | 1.1                  | Sushi-Mod-1.12.2.jar                               | None                                     |
	| LCHIJA | swanboat                | 1.12.2-1.0.1         | swanboat+-+1.0.1+(1.12.2).jar                      | None                                     |
	| LCHIJA | tinymobfarm             | 1.0.5                | TinyMobFarm-1.12.2-1.0.5.jar                       | None                                     |
	| LCHIJA | travellersbackpack      | 1.0.22.22            | TravellersBackpack-1.12.2-1.0.22.22.jar            | None                                     |
	| LCHIJA | treechopper             | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| LCHIJA | ultimate_unicorn_mod    | 1.5.16               | ultimate_unicorn_mod-1.12.2-1.5.16.jar             | None                                     |
	| LCHIJA | useless_sword           | 1.2.2                | UselessSword-1.12.2-V1.2.2.jar                     | None                                     |
	| LCHIJA | vending                 | 1.12.2-3.0.1.2       | vending-1.12.2-3.0.1.2.jar                         | None                                     |
	| LCHIJA | wallpapercraft          | 1.0.1-alpha          | wallpapercraft_1.12.2-1.0.2-beta.jar               | None                                     |
	| LCHIJA | waystones               | 4.1.0                | Waystones_1.12.2-4.1.0.jar                         | None                                     |
	| LCHIJA | llibrary                | 1.7.19               | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | wings                   | 1.1.6                | wings-1.1.6-1.12.2.jar                             | None                                     |
	| LCHIJA | bauble_wings            | 1.0.0                | wings-1.1.6-1.12.2.jar                             | None                                     |
	| LCHIJA | wolfarmor               | 3.4.1.1              | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar      | None                                     |
	| LCHIJA | xaerominimap            | 20.3.0               | Xaeros_Minimap_20.3.0_Forge_1.12.jar               | None                                     |
	| LCHIJA | xercamod                | 1.12.2-1.2           | xercamod-1.12.2-1.2.jar                            | None                                     |
	| LCHIJA | xlfoodmod               | 1.12.2-1.9.2         | XL-Food-Mod-1.12.2-1.9.2.jar                       | None                                     |
	| LCHIJA | ladylib                 | 2.1                  | Ladylib-2.1.jar                                    | None                                     |
	| LCHIJA | lumen                   | 0.4.0                | lumen-Beta+0.4.1.jar                               | None                                     |
	| LCHIJA | proxyslib               | 1.3.0                | proxys-lib-1.12.2-1.3.0.6.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | mysticallib             | 1.12.2-1.9.0         | mysticallib-1.12.2-1.9.0.jar                       | None                                     |
	| UD     | mowzies_wings           | 1.0.0                | wings-1.1.6-1.12.2.jar                             | None                                     |
	| UD     | mobends_wings           | 1.0.0                | wings-1.1.6-1.12.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
CorePlugin (ForgeEndertech-1.12.2-4.5.3.0-build.0528.jar)
  
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
FutureMC (future-mc-1.12.2-0.2.4.0.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
CharmLoadingPlugin (Charm-1.12.2-1.3.7.jar)
  svenhjol.charm.base.CharmClassTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  org.dimdev.jeid.JEIDTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_19_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  
LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.5126
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by TheCyberBrick** [comment]
This is usually caused by other mods that break world capabilities (a Forge feature). There's not much we can do on our side. I recommend you try to find out which mod causes this issue and then report it to them.
