### ISSUE TITLE
(Suggestion!) An anchor ladder for the Draeton to get to ground level better

### ISSUE THREAD

**Issue by booooooooop** [TheCyberBrick/The-Betweenlands#1115]
Well I don't know if it's major enough to warrant implementation but I found when parking my draeton it never really worked well, the whole "drop the anchor and get dragged down" thing (although I loved the animation!). I'm wondering if it's possible to add an attachment/upgrade that allows you to stay in the air when the anchor is dropped and climb down and up along the rope.

**Comment by Chiromaw** [comment]
Although I agree that the anchor is a bit finicky, the problem with the Draeton staying in the air when anchored is the patching.  Not all holes in the ballon can be patched from within the Draeton and so you have to land and dismount to patch up the holes on the top and sides.  Having the Draeton hover in mid air would make it very difficult to do this, possibly requiring survival players to build up to it wherever they land.

**Comment by booooooooop** [comment]
Well of course you could have it on a winch system like the original anchor.

**Comment by PetasiGit** [comment]
I’m opposed to this idea because I don’t see it being used. Hovering mid-air takes fuel, and I don’t think anyone is going to want to use more fuel than is absolutely necessary since it’s rather expensive.

**Comment by booooooooop** [comment]
Darn, totally forgot about the fuel thing.

**Comment by TheCyberBrick** [comment]
While this would be cool, it'd probably take quite an effort to make this work properly and also not provide much benefit, as Okl has pointed out.
