### ISSUE TITLE
Wisp Lantern

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1117]
In vanilla Minecraft, lanterns are a fantastic alternative to torches in the sense that they provide light while adding to both an interior and exterior aesthetic.  It would be fantastic if the betweenlands had some sort of lantern of its own as a building alternative to torches or candles.  Normally these options work great, but I feel lanterns would work especially well with an outdoor setting or hanging from a roof.  It would give off light when placed and maybe even when held in hand for caves and the sludgeon.  It would be crafted with a wisp surrounded by syrmorite nuggets.  Although Wisps are used to scale the risk/reward ratio of Spirit Tree bosses, these lanterns would provide a very simple additional use for them.

**Comment by vadis365** [comment]
Closing as lanterns are in next update.
