### ISSUE TITLE
[SUGGESTION] small Weedwood Chest tweak

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1118]
Would it be possible to tweak Weedwood Chests so that two single chests or two double chests can be placed right next to each other.

**Comment by PetasiGit** [comment]
Copying vanilla code should be possible to my understanding. Good suggestion.

**Comment by Chiromaw** [comment]
Thanks

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
