### ISSUE TITLE
Food!

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#112]
See below.

**Comment by SanAndreasP** [comment]
Alright, a "better" list from me (h = hunger, s = saturation):
* Angler Meat raw/cooked - raw dropped by Anglers | <tt>raw: 4h / 1.8s, cooked: 8h / 18s</tt>
* Frog's Leg raw/cooked - raw dropped by Frogs when we add them | <tt>raw: 2h / 1.2s, cooked: 4h / 4.8s</tt>
* Snail Flesh raw/cooked - raw dropped by Snails | <tt>raw: 3h / 1.6s, cooked: 6h / 13.2s</tt>
* Reed Donut - Crafted using a ring of dried swamp reeds | <tt>6h / 13.2s</tt>
* Jam Donut - crafted using a donut and a middle fruit | <tt>10h / 20s</tt>
* Gert's Donut (easter egg type) - crafted using a donut, slimeball and wight heart | <tt>6h / 13.2s + 8HP</tt>
* Kraken Tentacle (Raw)/Kraken Calamari (raw) - dropped by Kraken boss when we add it | <tt>?</tt>
* Middle Fruit - dropped by Middle Fruit Bush crop when we add it | <tt>6h / 15.6s</tt>
* Mince Pie - dropped sometimes by Presents when we add them | <tt>4h / 4.8s</tt>
* Weeping Blue Petal - acts like a golden apple but for Decay | <tt>like normal golden apple</tt>
* Wight's Heart | <tt>0h / 0s + 8HP</tt>
* Yellow Dotted Fungus - Dropped by the Yellow Dotted Fungus crop when we add it | <tt>10h / 20s</tt>
* [TEXTURE NEEDED] Silt Crab Claw - Dropped by Silt Crabs when we add them | <tt>?</tt>
* [TEXTURE NEEDED] Crab Stick - Crafted using 3 Silt Crab Claws | <tt>?</tt>
* [TEXTURE NEEDED] Nettle Soup - Crafted using a Weedwood Bowl, Weedwood Bucket of Water and a Nettle (flowered or not) | <tt>?</tt>

**Comment by MrCompost** [comment]
Only 3 more =)

**Comment by SanAndreasP** [comment]
Can you add the hunger value for the other 3 foods? I'll choose the fitting saturation level.

**Comment by MrCompost** [comment]
Sure
