### ISSUE TITLE
[[SUGGESTION]] Clean Sludgy Mud Bricks in Purifier

### ISSUE THREAD

**Issue by MalachiteTGC** [TheCyberBrick/The-Betweenlands#1123]
Please add it so you can put sludgy mud bricks found in a sludgeon in a purifier. This also would would work on decayed mud tiles. 

So any sludgy mud brick block found in a sludgeon can be put in a purifier and it would revert it back to undecayed mud bricks. Worm pillars and decayed mud tiles also would work with this, reverting them to the undecayed versions.

**Comment by PetasiGit** [comment]
You could add this in yourself via custom recipes.
https://the-betweenlands.fandom.com/wiki/Configuration

**Comment by TheCyberBrick** [comment]
Yes, this is doable with custom recipes as described on the wiki.
