### ISSUE TITLE
Two small bugs with the latest update

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1127]
While playing through the 3.7.1 new update for the first time I noticed:

1. Offering Table cannot be "pick blocked" in creative mode

2. The Infestation mob does not despawn when in peaceful difficulty.  This may be intensional, but I would assume since it can do damage upon contact; it would be classified as a hostile mob.

Also it would be helpful if there was a description of the "Blessed" effect and the twist it has either in game or on the Wiki.

**Comment by TheCyberBrick** [comment]
👍

**Comment by vadis365** [comment]
2 different things in 1 issue - annoying!

Parts  1& 2 fixed in dev.
