### ISSUE TITLE
[[SUGGESTION]] Syrmorite Rails and Minecarts

### ISSUE THREAD

**Issue by MalachiteTGC** [TheCyberBrick/The-Betweenlands#1128]
I feel like another way to travel in the betweenlands should be by rail, similar to vanilla rails.

These rails should be made of syrmorite or octine and syrmorite can also be made into minecarts. 
- Syrmorite Rails should be made like vanilla rails except replace iron with syrmorite ingots and sticks with weedwood sticks and the recipe should yield 16 rails.
- Octine Rails would function like vanilla powered rails. They would be crafted like syrmorite rails but with octine ingots and would yield 6 rails. 
- Syrmorite Cart would be a functioning minecart for the betweenlands. It would be made like vanilla minecarts but with syrmorite. They could go on any rails like vanilla carts.

This could make a possibility mineshafts for the betweenlands could be found.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
