### ISSUE TITLE
[[SUGGESTION]] Mineshafts

### ISSUE THREAD

**Issue by MalachiteTGC** [TheCyberBrick/The-Betweenlands#1129]
There should be mineshafts found in the betweenlands, as a new underground structure. They would have a main shaft or multiple levels, and sometimes could lead to the surface as a mine entrance. They would be filled with syrmorite rails, carts and more if those are ever added. They could be made of betweenstone or pitstone depending on the level they spawn at. The floors of the main shafts could have smooth or tile versions of the stone, with pillars every few blocks as supports. Different rooms could be in various locations which you have to go through a maze-like system of shafts to find these rooms. Pots of chance should be found throughout the shafts.

Examples: 
- Spawner rooms - These could have a spawner that spawns swamp hags, wights, boulder sprites or other mobs and some loot chests.
- Ore rooms - Rare rooms full of large piles of various ore depending on the location like syrmorite, sulfur, slimy bones, octine, scabyst or valonite which would be where miners would store ores and their rails sometimes can have carts containing metal, swift picks or gems.
- Abandoned outposts - Rooms with weedwood chests (Sometimes empty, sometimes with loot), sulfur furnaces, weedwood crafting tables, etc.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
