### ISSUE TITLE
Tree Roots

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#113]
Using the stalactite/stalagmite code we could make cool looking roots that come out of the water. They should just drop Weedwood Bark. A few could gen together and poke out 1-3 blocks above the water. Definitely belong in Coarse Islands biome, maybe patchy islands too but less common.

**Comment by TheCyberBrick** [comment]
They don't drop weedwood bark yet. I don't think weedwood bark is implemented yet, unless you mean "rotten bark" instead

**Comment by MrCompost** [comment]
Its a block =P

**Comment by TheCyberBrick** [comment]
Still doesn't drop weedwood bark yet :P

**Comment by MrCompost** [comment]
oops sorry

**Comment by MrCompost** [comment]
Actually, it's better if it drops nothing imo. Closing this for good =P
