### ISSUE TITLE
[[Suggestion]] Syrmorite Stonecutter once the mod gets updated to 1.14 or 1.15.

### ISSUE THREAD

**Issue by MalachiteTGC** [TheCyberBrick/The-Betweenlands#1131]
Once the mod is updated to 1.14, syrmorite and betweenstone could be used to make stone cutters which function like vanilla ones, but for betweenlands blocks.

Here are the recipes they might have for cutting these blocks:

Betweenstone
- Raw to bricks, chiseled, raw/brick stairs, slabs and walls
- Bricks to chiseled, brick stairs, slabs and walls (Also applies to mossy/cracked)
- Smooth to pillar, tiles, smooth stairs, slabs and walls
- Mossy smooth to mossy tiles, mossy smooth stairs, slabs and walls.

Limestone
- Raw to bricks, chiseled, raw/brick stairs, slabs and walls
- Bricks to chiseled, brick stairs, slabs and walls
- Polished to pillar, tiles, smooth stairs, slabs and walls

Cragrock
- Raw to bricks, chiseled, raw/brick stairs, slabs and walls
- Bricks to chiseled, brick stairs, slabs and walls
- Smooth to pillar, tiles, smooth stairs, slabs and walls

Pitstone
- Raw to bricks, chiseled, raw/brick stairs, slabs and walls
- Bricks to chiseled, brick stairs, slabs and walls
- Smooth to pillar, tiles, smooth stairs, slabs and walls

Scabyst
- Scabyst bricks to scabyst stairs, slabs and walls, pillars/tiles (If added) and all 3 chiseled variants
- Chiseled scabyst to switch variants

Temple Bricks
- Temple bricks to pillars, stairs, slabs and walls

Mud Bricks
- Mud bricks to tiles, carved mud bricks, carved mud brick edges, worm pillars, stairs, slabs and walls (Also applies to sludgy mud bricks)
- Sludgy mud bricks to decayed mud tiles/worm pillars of same decay stage.

**Comment by Chiromaw** [comment]
Although this feature could theoretically be added anyway, I don't think the devs have any plans to go beyond 1.12.  That could change in the future, but it is unlikley.  Good idea.

**Comment by PetasiGit** [comment]
It’s unlikely that the mod will be updated past 1.12, even within years of now it still might not be. Syrmorite isn’t particularly sharp anyway, lore-wise, with the exception of shears.

**Comment by Chiromaw** [comment]
I would say the existence of shears justifies a stone cutter.  True, syrmorite isn't sharp by nature, but it could possibly be combined with valonite or bone to create an alloy that would hold an edge.  Or simply just take a liberty.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
