### ISSUE TITLE
Incorrect Loot Tables?

### ISSUE THREAD

**Issue by Kirbyarm** [TheCyberBrick/The-Betweenlands#1132]
#### Betweenlands version:
3.5.10

#### Forge version:
14.23.5.2864

#### Singleplayer or Multiplayer:
Multiplayer

#### Installed mods:
SevTech Ages Modpack (3.1.7)

## Link to full crash log
N/A

## Description of the problem
https://i.imgur.com/rzDQtRw.png

As you can see from the screenshot I have three Rings of Ascent in my inventory. I collected these randomly from killing mobs. My friend and I spent two realtime days worth of play sessions looking for just 1 Ring of Ascent which we finally ended up scoring from atop a Cragrock Tower.

I believe the first one was from an Angler Fish and the second was from a Shallowbreath that actually attacked us inside our base.

On the wiki it shows that the Ring is only found in POI chests.

#### Expected result:
On the wiki it shows that the Ring is only found in POI chests. This is what I expect.

#### Actual result:
It's pretty straightforward to understand, reading the above.

#### Pictures:
One image URL included in description section above.

#### Additional Information:
If this is intentional behaviour for the mod, please let me know in this ticket! Thanks everyone for your time, this is one of the best mods I've ever played~

**Comment by TheCyberBrick** [comment]
This is a change made by the SevTech mod pack to facilitate the progression, so it's intentional.
And thanks 😄
