### ISSUE TITLE
Infestation effect through solid walls. [Bug?]

### ISSUE THREAD

**Issue by Ridley11** [TheCyberBrick/The-Betweenlands#1136]
Minecraft 1.12.2
#### Betweenlands version:

3.7.1

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

[modlist.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5659174/modlist.txt)

#### How to reproduce:

1. Place an infestation mob behind a sealed wall of varying thickness
2. Stand on the other side of the wall

#### Expected result:

I am not certain this is the intended result of this creature, but I would suspect they should not be able to have this effect on the player without direct line of sight and/or from behind solid walls. 

#### Actual result:

The new infestation mob can cover the player in insects from behind solid walls. This is a particular problem underground while mining, as you will quite frequently have infestations aggro'ing to the player from behind walls and then coming right up to the wall and sitting there. As the player mines closer and enter the insect aura effect, they will take damage and their screen will be covered. Forcing the player to either have to retreat from that space or dig through to kill the mob. If this is intended then I think this is a bit overpowered, as it also causes problems in dungeons like the sludgeon too, as infestations _outside_ the sludgeon boundaries can still 'infest' the player, and the player cannot do anything about this as they cannot mine through the walls to get to the infestation.

**Comment by vadis365** [comment]
Should be fixed somewhat in dev. Made it so the mob can only attack players it sees, may need changing to allow for certain blocks.
