### ISSUE TITLE
Possible Oversight - Weedwood Barrel recipe does not consume Weedwood Bucket

### ISSUE THREAD

**Issue by ReactivePlatypus** [TheCyberBrick/The-Betweenlands#1139]
#### Betweenlands version: 
3.7.1 Universal

#### Forge version:
14.23.5.2854

#### Singleplayer or Multiplayer:
Both. First seen on Wolfbayne's server and double-checked in singleplayer using only the Betweenlands.

#### Installed mods:
Happens regardless of other installed mods. 

#### How to reproduce:

1. Craft a Weedwood barrel.
2. The Weedwood Bucket is not consumed in the crafting process. You have now made two fluid containers out of one.

#### Expected result:
The bucket is a fluid container, and seems like it would be be consumed to act as the "container" in the barrel.

#### Actual result:
The bucket is not consumed. Seems inconsistent with how it logically "should" work.

**Comment by flamebane** [comment]
can confirm

**Comment by TheCyberBrick** [comment]
Obviously the bucket is only used as a scaffolding for the barrel wall that is later removed, duh. Can we just run with that? ( ͡° ͜ʖ ͡°)

**Comment by flamebane** [comment]
sure

**Comment by PetasiGit** [comment]
Scaffold buckets. :ap_look:
