### ISSUE TITLE
Seemingly Random Crash to Desktop

### ISSUE THREAD

**Issue by unfamoushero** [TheCyberBrick/The-Betweenlands#1147]
## Minecraft version:
1.12.2

#### Betweenlands version:
3.5.10-universal

#### Forge version:
1.12-forge-14.23.5.2854

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Sevtech Ages of the Sky modpack - https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky
with Optifine 1.12.2_HD_U_F5

## Link to full crash log
https://pastebin.com/JZD49nNx

#### How to reproduce:

1. Boot up the game with the aforementioned mods installed/active
2. Play the game normally for roughly 5-10 minutes, within sight of the original portal tree
3. With no consistently perceivable trigger on my end, the game will crash to desktop.

#### Expected result:
Being able to explore the initial area of the Between lands and start getting into the mod for fun and profit.  

#### Actual result:
Game crashes after a short period of play.

#### Pictures:
n/a

**Comment by TheCyberBrick** [comment]
This crash seems to be caused by Astral Sorcery, please report it [there](https://github.com/HellFirePvP/AstralSorcery/issues), thanks!

**Comment by unfamoushero** [comment]
Hmm ok I will ask them as well then.
