### ISSUE TITLE
Suggestions- Creative Inventory maintnence and two small decoration ideas.

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1151]
I really enjoy playing this mod and I would say most of my time is spent building in creative mode to see how everything interacts, and design Cool bases for my survival play through.  I always look forward to the next update and I am getting a lot of use out of the new wind chimes and lanterns.  However I sometimes have trouble navigating the creative menu.  Most of it is haphazardly memorized from repetitive use, but I think it would be beneficial (especially for new players) if the creative inventory was slightly re-organised.  Little things like empty dentrothyst vials being in the middle of various infusions and aspects, or grouping mob spawn eggs in with the vanilla spawn eggs can be a pain to navigate through.  The majority is sorted very well, but a few new tabs say for mobs, consumables, or utility blocks would make it a lot more convenient.  especially since the utility blocks (crafting table, furnace, infuser, etc.), being the most useful to access for learning their functions, are all the way at the bottom of a dense block page.  Additionally, adding functionality to things like the sludgeon doors and door codes from the creative inventory would be fantastic. 

On a separate note; it would be kinda cool if:

1. You could place saplings in mud brick flower pots.

2. Each boss having a decorative trophy drop to hang up in your base, similar to the large spirit tree face mask.  A Dreadful Peat Mummy skull, Primordial Malevolence cloak, Sludge Menace medallion (like the disc on the floor of the pit of decay), Barashee Mask, or Chiromaw Matriarch wings for example.

**Comment by PetasiGit** [comment]
I’m not sure if the creative inventory can be precisely organized due to the way forge works, but I don’t know cody stuff. @TheCyberBrick would know if this is feasible or not. In the mean time, you could use a mod like JEI to have larger pages of the mod’s blocks by filtering with @thebetweenlands. Or you could use the vanilla search tab in the creative inventory.

Multiple things in one issue, *grrrr.* 🙃

1) I agree that this should be added for vanilla consistency.

2) I get what you mean, but I’m not sure we want to add more drops to the bosses. The unique items you get from each boss already kinda act as trophy items, don’t they?

**Comment by Chiromaw** [comment]
Thanks for the recommendation of JEI.  I can't imagine it would be too hard to simply change the position of items in a menu. However, like you, I also don't fully understand the technical side.  It's not too much of an issue, just figured it would be a good quality of life aspect.

Also regarding trophies: true, most bosses have trophy- like drops (rings).  But I meant drops the served solely as decoration for a survival base.  Also mini bosses drop items like a chirobarb eruption and a door key that both eventually get consumed.  The rings also tend to either be equipped or stay in a chest.  It seemed odd how the spirit tree has a trophy drop you can hang on a wall but no other bosses do.  Plus, think how awesome it would be to have a Barashee Face hanging on your wall.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
