### ISSUE TITLE
Draeton refusing to go Down When pressing LCtrl

### ISSUE THREAD

**Issue by Shibva** [TheCyberBrick/The-Betweenlands#1154]
#### Betweenlands version:

TheBetweenlands-3.7.2-universal.jar

#### Forge version:

Lattest for 1.12.2
![image](https://user-images.githubusercontent.com/38770780/103401480-f9f6d900-4b16-11eb-87d1-eba963f9aa26.png)

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

https://gist.github.com/SteamDoge9000/583c25c49b0ebfc97de28247070fbb8f

#### How to reproduce:

1. Install the mods
2. ride the Draeton
3. use the keybind 

#### Expected result:

Desent

#### Actual result:

Dosent do it period

#### Pictures:

![image](https://user-images.githubusercontent.com/38770780/103401637-aafd7380-4b17-11eb-9a0e-c058059e004e.png)

Addional Files:
[optionsof.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5756788/optionsof.txt)
[optionsshaders.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5756789/optionsshaders.txt)
[hc_options.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5756790/hc_options.txt)
[options.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/5756791/options.txt)

**Comment by PetasiGit** [comment]
Have you checked for keybind conflicts?

**Comment by Shibva** [comment]
yes
and when I reconfigured them it was not doing it

but then when I went out and reloaded it, It seems to start working again for some reason

idk if it was a glitch or something but it seems to be working fine now, even after reverting the keybinds I have set

**Comment by PetasiGit** [comment]
Perhaps it was just a once-off thing then, and not a consistent issue?

**Comment by Shibva** [comment]
only logical explination I suppose

thanks and can you check out the other issue Im having with the Rowboat? #1153
