### ISSUE TITLE
2-high plants can delete tap buckets on Rubber Trees when grown from Ground Dried Swamp Reed

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1158]
Using dried ground swamp reed on the ground near a tapped rubber tree will cause a plant (often a 2 block tall plant) to grow directly beneath the bucket and totally delete it without dropping it.  This only happens if the bucket is placed on the tree 2 blocks above the ground.  Not sure if this works with 1 block tall plants too, as I could not get any to spawn underneath the bucket in this way.

Version: 3.7.2

Forge version: 1.12.2, 14.23.5.2854

**Comment by PetasiGit** [comment]
Fixed in 3.8.1.
https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod/files/3540284
