### ISSUE TITLE
Screen freezes when trying to enter Weedwood Rowboat

### ISSUE THREAD

**Issue by Mgooy** [TheCyberBrick/The-Betweenlands#1163]
#### Betweenlands version:

 3.7.2

#### Forge version:

14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Betweenlands
OptiFine 1.12.2 HD U F5 (I have also tested this with versions U F4, U E3 and U E2)

#### How to reproduce:

1. Optifine installed with shaders off, Betweenlands with all options set to default, also happens with shader disabled
2. Right-click on any Weedwood Rowboat to get in it

#### Expected result:

Enter the boat as you do with no other mods installed

#### Actual result:

The screen freezes on the last displayed contents right before right-clicking on the boat to get on it, but with a blurred or smudged effect. Game audio plays as normal and pressing shift to dismount causes the game to run normally again. 
When the screen is frozen I can use the A and D buttons to move the boat (no change to the image on screen) and when I dismount the boat has moved as it should.
This happens in both the Betweenlands dimension and the overworld.

#### Pictures:

![](https://i.imgur.com/vvph6Uq.png)

**Comment by Mgooy** [comment]
This seems to have been caused by incompatibility with a mod I had previously installed and deleted. I don't know which mod this was but I fixed the issue by deleting the contents of my .minecraft folder and reinstalling Betweenlands and optifine

**Comment by DerangedLazyArtist** [comment]
It was probably optifine's anti-aliasing. Turning it off fixed this issue for me.
