### ISSUE TITLE
Suggestion: Draeton Repeller upgrade

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1164]
It would be very interesting if the Draeton had a repeller upgrade that could project a shield around the balloon mid flight as long as it is filled Byariis.  It would drain the same way as a regular repeller with passive drain as well as incoming attacks from greebling riders, chiromaws, ect.  This upgrade would be crafted similarly to the furnace and crafting table upgrades, but with a dentrothyst bottle (or repeller) in place of the utility block, and a shimmerstone instead of an ingot.  This would make the draeton more resiliant during flight.

**Comment by PetasiGit** [comment]
I don’t think this is going to be added simply because it negates all risks while using the draeton. There has to be a balance, you see. But I’ll leave it open for now.

**Comment by Chiromaw** [comment]
The shield itself would have to be balanced.  For instance, it could be similar to the ring of recruitment where holes could be punctured with repetitive attack.  Or it could all together just not be as effective and long lasting as a normal repeller.  I always find that trying to do any crafting, smelting, or inventory management mid air is interrupted by oncoming attacks from mobs.  In essence, the repeller upgrade would simply make the balloon more durable rather than temporarily indestructible; allowing for more use of the Draeton's multifunctional intensions.  The same could be accomplished through a simple upgrade to the balloon endurance.  But I figured having it take the form of a Draeton upgrade would not only be more interesting, but also balance the gain with a loss with it having to take up one of the 4 upgrade slots.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
