### ISSUE TITLE
Suggestion- mud golem functionality

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1170]
I had a thought about this yet to be implemented mob.  As of now (according to the wiki) the mud golem will hurl mud at enemies and perhaps even carry some items for you as hinted by the backpack.  What if the mud golem had alternate uses in addition to just following you around on your adventure.  So far we have a plethora of companion mobs including: tar minions, emberlings, Chiromaws, lightning Chiromaws, harlequin toads, and most hostile mobs that can be effected by the ring of recruitment. All capable of damaging enemies while keeping pace with the player.  Rather than just another damage dealing companion, consider for a moment two separate ideas that lend more of a unique reason to keep mud golems around.

1. You could set them to take care of simple tasks at your base.  Such as filling/emptying composers, re-fueling furnaces, stirring infusers/mortars, emptying alembics, etc.  Nothing too crucial aside from small, helpful favors that could be taken on in your stead.  This could be accomplished by binding a golem to a utility block rather than the player.  Even while away, they could continue their jobs until interrupted.  (If chunk loading is an issue, this functionality would still be helpful even while still at your base with them).  Hurling mud could stay as their basic defense, and emptying blocks like a composter would store the items (compost in this case) in its backpack until the player empties it.  The amount of golems would be limited based on something like a simple cap or maybe an infighting/bickering mechanic should there be too many of them.  This would simply work by making the golems have an arguing animation with each other that would play out preventing them from doing their jobs when too many other golems are around.  This would prevent automated tasks from becoming too OP.  You could easily right click them to assign/de-assign them to a task or to follow you on an adventure in stead.

2. Every generated structure can be fully explored and completed without the help of companion mobs.  The underground temple could be an exception to this.  In order to progress through the temple, you would need the help of a mud golem.  It could be used to open doors that only it can open, or solve puzzles using some additional abilities only it possesses.  It is my assumption that hostile temple guardians will hide among inanimate ones.  assuming this is correct, the mud golem could possibly identify and warn you which is which.  This all requires you to keep the golem alive in order to beat the dungeon.  Temple guardians might even prioritize the golem over the player in combat.  It doesn't seem like mud would be too common that far underground, so it would require the player to have some mud (or pre made mud golems in item form) on hand while negating the ability to just infinitely make more golems while you're there.  This places emphasis on how many "tries" you have at the dungeon before having to return to the surface for more mud without making a golem death too taxing on progression.  The mud slinging would be a simple defense mechanism so that the golem isn't helpless in a fight.

These ideas could exist simultaneously, but that could be too much functionality for one mob in comparison to all the others.  Though there could always be two variants of mud golems as well.  Or maybe you run through the temple with the mud golem as previously mentioned, and gain the ability to acquire temple guardians that can be repurposed to do tasks at your base instead of the mud golems.  I like the initial concept on the wiki, and feel there are so many things it could do differently than the other companion mobs to set it apart.  As it stands right now, my personal opinion is that if I need help with mid adventure storage or lighting, I bring lurker skin pouches and sulfur torches; and if I need help with combat, I'm pretty content with Chiromaws.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
