### ISSUE TITLE
small heads up on wiki

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1174]
the title page still says that the current version of Minecraft is 1.16.4 but it was recently updated to 1.16.5 on Jan 15.  It might not even be worth mentioning, but seeing as I cannot edit it (or can't figure out how to) and it's such a small detail that can easily be forgotten; I figured I'd let you know.

**Comment by PetasiGit** [comment]
Updated, thanks.
