### ISSUE TITLE
Suggestion- Spirit Fruit Or Jello Cake

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1177]
Not necessarily for a specific function, but if say there is a Betweenlands anniversary; it would be pretty neat if you could craft jello cake from any of the 3 types of jello.  Or a special spirit fruit or forbidden fig cake for fun.  Any of which can be placed and have a set portion of servings.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
