### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1179]
Plz may you make an update for 1.16 fabric? Fabric is a cute modloader with good optimization, better graphics and easier coding. Its already more popular than forge (cause sodium mod).

**Comment by Chiromaw** [comment]
I'm not a dev, but I do know for a fact that there are no plans to update past 1.12.2 even in the far future.  Although I am not 100% sure on fabric, I am pretty confidant in saying that I have not heard of any plans to make a fabric version either.  Sorry.

**Comment by PetasiGit** [comment]
We are not updating past 1.12.2 for the foreseeable future, and certainly not completely switching to a different modloader. With the size of the mod, that would be ridiculous.
