### ISSUE TITLE
Suggestion: Middle gems enchantment system

### ISSUE THREAD

**Issue by Nayzore** [TheCyberBrick/The-Betweenlands#1182]
I'm pretty new to The Betweenlands and already in love with this mod. I may be missing something, but I can't find any use for my experience points (besides these teleporting stones). I suggest implementing some variety to gems, thus fixing two "issues" if you can say so: first, somewhat boring gem system that currently has no variability, no RNG, no progression, just six enchantments - three for tools and three for armor. Second, finding a purpose for your well-earned EXP points (and giving you another reason not to die).

(most vanilla enchantments will either be useless or game-breaking in Betweenlands and need changes at least or overhaul at most. Not to mention that adding something so familiar to something as unknown and obscure as Betweenlands can break a unique uncanny atmosphere of the mod)

For example, just an undeveloped quick idea:
Enchanting table or something with two slots - for an item and a gem, each gem can give you one of, for example, 15 enchantments - three tiers (some locked/unlocked depending on your level) with five enchantments each. Enchantments are random, but you can pick tier (if unlocked) and gem: red is offense (for weapons), green is defense (for armor), and blue is utility (for tools), and a new white gem for universal enchantments (unbreaking/mending) or no new gems, just a chance to get something universal in addition to basic enchantment.

**Comment by TheCyberBrick** [comment]
Hey, thanks! Currently the only use for XP points is to fuel the several rings that you can obtain from loot or bosses, and those rings are actually quite significant for combat and travelling (e.g. Ring of Ascent).
Customizability of tools/weapons is something that has been planned for quite a while now (blacksmithing) and is in development (runes), so I'm not sure we're going to add another system besides those.

**Comment by Nayzore** [comment]
Thanks for your response. I don't know how runes will look and work like, but it sounds tempting, can't wait for them to be released!
