### ISSUE TITLE
[Suggestion] Nerf Infestation Spawn Rates

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1185]
On my multiplayer server, when me and my friends are underground, Infestations are by far the most common mob we come across... in fact, they are almost the ONLY mob we come across. They are so common, and although a cool mob to fight, have no benefit for us killing them other than getting rid of an incredible nuisance... As such, I'd suggest decreasing their spawn rate to much lower, with a slight increase from that lower value in certain biomes, specifically Sludge Plains, and other places of Rampant Decay.

**Comment by TheCyberBrick** [comment]
Version?

**Comment by spiderking23** [comment]
3.7.2 was when I meant to do this, I do not know if it has been addressed in the latest 3.7.3, has it been?

**Comment by spiderking23** [comment]
It's still a problem for  3.7.3 but less so.

**Comment by PetasiGit** [comment]
Nerfed in 3.8.0.
