### ISSUE TITLE
[Suggestion] Weedwood and Dentrothyst Armor

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1186]
Since you plan on adding human NPCs to the game with whom the players can interact and trade with, these tribesmen will need weapons and armor, and almost none of them should be as advanced as the player, they don't really need to be. As such, I suggest you should add weedwood armor. This would allow these less advanced tribes to more adequately defend themselves from mobs, as well as give the player a very easy starting Armor Option. What's more, this armor could be upgraded by adding dentrothyst shards to it, giving it a 25% magic damage reduction. This would allow the beginners Weedwood shield and the Dentrothyst Shields to have a "partner in arms," and make the NPCs generally hardier and more defense heavy. Only Guard or Hunter NPCs should wear these armors, and Only Chieftans or some other important role should use dentrothyst.

**Comment by Chiromaw** [comment]
part of this is along the idea of blacksmithing which the devs are planning to add at some point.  However, Weedwood armor would be too useless.  bone armor isn't too hard to come by, and it already doesn't do much.  adding magic damage reduction would give it too much of a benefit over other armors.  Also villagers wouldn't necessarily need armor.  What if their already dead?  plus they could have makeshift weapons to keep enemies at bay.

**Comment by spiderking23** [comment]
Why would villagers need armor? Same reason the player does, to not die. We don't want the guardsmen and hunters getting killed every two seconds. And weedwood armor would actually be a pretty decent start, less durable but same protection as lurker skin. Just none of its mobility benefits. It can then be upgraded with Dentrothyst, which will increase its protection, and reduce magic damage by 25% making it the best armor to fight the Primordial Malevolence with until you get Ancient Armor.

**Comment by PetasiGit** [comment]
These suggestions are redundant, sorry. We have a low-tier armor already: it’s bone armor. Ancient armor is supposed to be unique—adding magic protection to another set devalues it. 

There may possibly be armor upgrades in the future anyway. But they’re not a priority right now.

**Comment by spiderking23** [comment]
I understand the viewpoint, but the Weedwood armor wouldn't be THE "Low Tier," but an alternative Low tier with its own advantages, such as making the player move up faster in water, and being VERY cheap. Along with being able to be upgraded by adding Dentrothyst Crystal Plating and spikes, giving a 25% of magic damage. I thought this to be something the non-nomadic tribes of people to use, the ones who would use their surroundings as their weapons and armor. Since they'd be in swamplands, with few lurkers, dragonflies, and since they most likely don't mine, this would allow them to have an actually decent armor source. Also, Slimy bone is actually surprisingly hard to get since it isn't easy to spit underground. And as far as redundancy goes, technically that means Slimy Bone armor is redundant, as it can easily be bypassed straight up for syrmorite. I understand the points you came up with, they crossed my mind, but I think the pros Outweigh the cons here. Actually, there Aren't any cons. It probably wouldn't be too difficult to implement, and modeling shouldn't be too much of a hassle.
