### ISSUE TITLE
[Suggestion] Shamblers Spawning Nerf

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1188]
Shamblers are supposed to be fairly rare. A sludge on mob. I have almost a stack of their drops and am no where near a sludgeon level. Make their spawning outside of Sludgeons Much Much rarer please.

**Comment by Chiromaw** [comment]
Yes please, I agree. they are too common in the swamplands.

**Comment by PetasiGit** [comment]
They could be less common, I agree.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
