### ISSUE TITLE
[SUGGESTION] Spirit tree Armor

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1189]
Spirit Tree Armor set that gives slightly more armor than Valonite Armor, and has little spirit tree faces that shift around your body that shoot enemies when you get hit, kinda like thorns.  It has no durability, but if you die with the armor equipped in your armor slots, it will revert to rotten wood armor that gives less defense than slime bone armor and no additional perks.  This happens even if keep inventory is on, but not if the armor is in the inventory and not equipped.  It also decays even if the blessed status resurrects you.

Two ideas on how to obtain this armor:

1. (craftable), using spirit tree wood, and small animated spirit tree face masks.  This may seem cheap and overpowered, but with the rarity of spirit tree wood, and the fact that the masks have to each be animated; it makes the armor pretty pricey.

2. (uncraftable), add it to the item scroll rotation.  An item scroll will have a chance to yield one of the 4 armor pieces at a time.  This option makes it more rare, but it is a powerful armor.  Plus, it would be cool to have a chance to get armor from item scrolls.

The method of obtaining the armor would depend on how rare you want it to be.  Yes it is powerful, but has a considerable drawback.

**Comment by spiderking23** [comment]
This sounds interesting, but kind of broken for something you get from an Item Scroll. Especially if you are one of the crazy people playing Betweenlands in Hardcore. Perhaps instead, it would have the ability to send the root shockwave out that will damage hostile mobs... or I would much prefer (no friendly fire) if it grabbed hostile mobs like the spirit tree instead.

**Comment by spiderking23** [comment]
Also, rotting when you die? I understand it's spirit tree, but I don't think that's a great idea to add to an item. It makes it feel more valuable than a player's life.

**Comment by Chiromaw** [comment]
I like your idea of the root ability holding a mob in place.  That could be an alternate use.  Also, the decay idea was meant to balance the strength of the set.  There could be a way to restore it, say putting it in the purifier for an extended period of time.  Or maybe sticking the decayed armor back into the animator to reanimate it.

**Comment by TheCyberBrick** [comment]
Hm that sounds kinda cool actually. Not sure about the rotting mechanic and it being as strong as valonite though. Instead of rotting on death it could be in an inactive state except when you're wearing a bark amulet? The armour could even be unbreakable because it'd only be effective when wearing a bark amulet, and so you'd trade damage on hit with damage per time.

**Comment by Chiromaw** [comment]
ok, I guess I should have made this more clear: when I said the armor rots, I didn't mean that it would disappear, it would become minimally active (or completely inactive) until you somehow return it to its previous (active) state.  Also thecyberbrick, I like your idea the best with the bark amulet.  The armor could "rot" as the bark amulet drains durability until the armor reaches an inactive state.  Plus it works well with balancing use and power, and gives the bark amulet more significance.  The fact that bark amulets can't be repaired also grants the armor a more unique method of use country to all other armors in the mod.  Since you would have to go and kill a spirit tree pretty much every time you want to use the armor, unless you have a spare lying around.

**Comment by spiderking23** [comment]
I like that this idea is evolving. It would also go very well as like a chieftain armor for the future tribes, so I am all for evolving and improving this idea further.

**Comment by Chiromaw** [comment]
yeah, the tribe settlements could worship spirit trees and maybe even have some sort of interaction with them.

**Comment by spiderking23** [comment]
Probably only little friendly ones though. Not the full mini boss.

**Comment by Chiromaw** [comment]
agreed.  They could maybe even cultivate spirit fruit, and trade with the player.

**Comment by spiderking23** [comment]
Maybe, but that might make spirit fruits too easy to get. So maybe it would be a temporary trade that can only happen a few times, Rarely.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
