### ISSUE TITLE
The base of beacon

### ISSUE THREAD

**Issue by GoldenTotem** [TheCyberBrick/The-Betweenlands#1197]
#### Betweenlands version:

3.7.3

#### Forge version:

14.23.5.2855

#### Singleplayer or Multiplayer:

Single

#### How to reproduce:

1.The blocks such as valonite blocks, octine blocks and other blocks can not be the base of beacon.

#### Expected result:

Valonite blocks, octine blocks and other blocks of mineral can make beacons active  just like vanilla.

**Comment by Chiromaw** [comment]
I think this would me more of a request than a bug report.  To my knowledge, none of the Betweenlands blocks can power a beacon.  It's a good thought though.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
