### ISSUE TITLE
[Suggestion] Armor. Dentrothyst Armor. (And Weedwood too)

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1198]
Magic Damage sucks, as it ignores armor, and the only gear that even protects you from it is endgame Ancient Armor. We need protection from Wights, especially Wight turrets, because even the skull mask cannot protect you from that. So here is my Proposal: Weedwood and Dentrothyst armor. Weedwood Armor would be cheap, and offer about as much protection as Lurker Skin, but it isn't something you plan on keeping this way. No, it's main use is to have Dentrothyst added to it covering vital areas (without effectively creating glass armor) that will give 25 to 50 percent magic damage reduction (depending on the color of Dentrothyst used) so players trying to survive the Hardcore game will not be slaughtered by Wight Turrets. The Weedwood Armor would also be great armor for certain tribes, as it's even easier to get them the camouflaged bone. Their guards could wear Dentrothyst armor, and the shaman or leader could wear Orange Dentrothyst armor. It's a win win for beginner players.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
