### ISSUE TITLE
[Suggestion] The Transcendence of Gold

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1199]
So Gold appears in both the Overworld and the Nether, even in the Betweenlands' older versions of Minecraft. It's definitely magical, as it's easy to enchant, and is used in the creation of Golden Apples, and more importantly totems if undying. As such, I believe the magical metal of life should possibly have... more of a use. My suggestion is to make gold something that appears in the Betweenlands. And it's not useless either. Gold obviously has some form of life magic, and along with its tools being immune to both the Betweenlands decay and corrosion due to their purity and magical essence, it would make sense for it to have magical uses. Specifically in Runes. Since they have natural healing abilities, the runes made with gold could have to do with regeneration, the creation and preservation of life, and perhaps, even be a requirement for access to the Prime Wight or Temple. Along with all of this, it would give Betweenlands Players an interesting strategy, as Gold tools would be the only tools from the over world that would work in the Betweenlands, meaning these tools would be decent set to bring for those traveling to this dimension. And it would make gold less useless. I'd suggest it be fairly rare, as to not make the Betweenlands a great place to get this now incredibly useful material.

**Comment by spiderking23** [comment]
This would not have to be something huge, it could just be a neat little connection to base MC psuedo-lore, and wouldn't justify players having massive amounts of it until later game, with Runeweaving. And even then, it would still be only somewhat useful. The biggest thing this would add I think would be potential building materials like gilded bricks or something like what appears in the current temple concept on the wiki.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
