### ISSUE TITLE
Druid circle needs a little tweaking 

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#12]
Not really necessary, but I think it would be better if the pillars looked a little more randomised and natural. Perhaps varying heights. Vines growing on them would look great too. Thanks!

**Comment by vadis365** [comment]
No worries - the pic I took was very much WIP. ;P

**Comment by MrCompost** [comment]
How do I add labels such as enhancements, as well as milestones?

**Comment by vadis365** [comment]
magic - look at the right hand side and the little gear symbol next to assignee or milestone.

**Comment by MrCompost** [comment]
Ah yes, thanks.

**Comment by vadis365** [comment]
Do you want some magic like particles coming off the druid stone?
Or would that just be overkill?

**Comment by MrCompost** [comment]
Sure!
