### ISSUE TITLE
[Suggestion] Avaritia 1.1x 's infinity tools and armor should not be affected by the betweenlands decay mechanic and can be used normally in the dimension

### ISSUE THREAD

**Issue by Ghidhor** [TheCyberBrick/The-Betweenlands#1202]
title says it all

Avaritia's Infinity tools and armor are extremely op and endgame,and even if their not betweenland related,they should not be affected by the mechanics of the dimension

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
