### ISSUE TITLE
[Suggestion] Allow configuring which boots negate mud effect

### ISSUE THREAD

**Issue by MrRedstoneA1** [TheCyberBrick/The-Betweenlands#1204]
Like the title says, it would be great to be able to decide which armor negates mud just like the rubber boots. Being able to combine rubber boots with other boots could also work, but it would then have to work on any boots from any other mods as well. I would prefer the config option if that's possible.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
