### ISSUE TITLE
Unexpected Error occurred inside the Sludgeon

### ISSUE THREAD

**Issue by MrRedstoneA1** [TheCyberBrick/The-Betweenlands#1207]
Versions

3.7.3-SNAPSHOT

Forge version:

Forge 14.23.5.2855

Singleplayer or Multiplayer:

Singleplayer

Installed mods:

https://gist.github.com/MrRedstoneA1/2a8c73b0134c1cf14d2fa305f49758aa

Link to full crash log

https://gist.github.com/MrRedstoneA1/4e02e554a4ff395ba5b1a896e7109a9a

Description of the problem

I was just playing normally in the sludgeon when VanillaFix caught an error. The game did not crash but VanillaFix provides a crash report.

I found the steps to reproduce.
Go into the sludgeon and use syrmorite shears to collect puffshroom tendrils. There seems to be some sort of issue when the game tries to convert the block back into regular mud bricks, according to the report.

**Comment by TheCyberBrick** [comment]
Thanks 👍

**Comment by MrRedstoneA1** [comment]
No problem.
