### ISSUE TITLE
[SUGGESTION] Songstones

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1208]
Songstones would be the BL equivalent of Noteblocks. They would be crafted from a type of stone (Betweenstone, Pitstone, Cragrock, Limestone, and any future types of stone.) The recipe would be 1 Amulet Socket, 6 Stone(Whichever type), and 2 Scabyst. Songstones can also have Middle Gems applied to them to allow for different instruments. Tuning Songstones is more challenging than in Vanilla. When right clicking on a Songstone a random note will be selected instead of in ascending order. But, if you right click with a Gem Singer, they will tune like Vanilla. Activating them is the same as normal, either via left click or redstone. 
    Some of the instruments I think should be on Songstones are: Harpsicord, Viola, Pan Flute, Piano, Orchestral Drum, Harp, Lute, and Choir.

**Comment by Chiromaw** [comment]
This just seems overly complicated.  First off, the betweenlands doesn't really need note blocks, nor is there any betweenlands equivalent to redstone.  So how would they trigger.  Plus, the the random note tuning would be more of a nuance than a fun challenge.  That right there would personally stop me from using them in survival.

**Comment by spiderking23** [comment]
Well, Inlike the concept, but executed as is, it might be a bit too much. I would love to make some form of music in BL though.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
