### ISSUE TITLE
[SUGGESTION] Chiromaws On Dreatons (damage)

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1209]
As of right now, when more than one regular or electric Chiromaw is pulling a draeton, and they attack a mob; they can hit each other with their barbs.  This can be very frustrating when trying to use 6 of them to pull for you.  Please make it so that Tamed Chiromaws are immune to other Tamed Chiromaws attacks.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
