### ISSUE TITLE
[SUGGESTION] Animator Slow Sulfur Drainage

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1210]
When using an Animator and you run out of Sulfur, the bar immediately runs out and you wasted alot of fuel. I suggest that when an Animator runs out of Sulfur the bar slowly drains, similar to a furnace. This way you wont lose all of your progress if you cant refill it in time.

**Comment by Chiromaw** [comment]
I second this request.

**Comment by CrazyAceking** [comment]
Third

**Comment by spiderking23** [comment]
I'll Fourth and Fifth this!

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
