### ISSUE TITLE
Cragrock tower leaves inviseble blocks when collapsing

### ISSUE THREAD

**Issue by rnatcole** [TheCyberBrick/The-Betweenlands#1212]
When a cragrock tower is collapsing it leaves invisible blocks on the stairs and floors which makes the player stuck, making it impossible to get out alive.

#### Betweenlands version:
3.7.3 

#### Forge version:
14.23.5.2854 

#### Singleplayer or Multiplayer:
This bug occurs in Singleplayer and Multiplayer

#### Installed mods:
The only mod instaled is the Betweenlands 

#### How to reproduce:
Clear a cragrock tower and wait for it to start crumbling 

#### Expected result:
In others versions you would run to the exit trying to avoid the falling blocks 

#### Actual result:
The floor is gone and I can't move

**Comment by FirestarPlayz** [comment]
Ive been having this problem too! A good way to avoid it until its patched is to get down on the outside of the tower either with a Volarkite or Grappling Hook.

**Comment by rnatcole** [comment]
For people that already know this bug exist it easy to avoid. But I'm think more on a new player perspective, can you imagine, it's his first time clearing a tower and then just die and loses his stuff because of this.

**Comment by Chiromaw** [comment]
this is a well known problem.  It has to do with mc not being able to keep up with that many moving entities.  So although the block dropping animation plays out, the collision gets all funky and often stays in place.  The best way to avoid this is a volarkite like the people above said.  I agree, it needs to be patched.

**Comment by SeriousCreeper** [comment]
fixed in latest update
