### ISSUE TITLE
[SUGGESTION] Small Sludgeon Upgrades

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1213]
Yea yea another list but I think this format works well.

  Usable Beams and Beam Origin
After a Sludgeon is completed, the Beam Origin at the top deactivates. When broken, it will drop an Inactive Beam Origin. When crafted with a full Life Crystal, the crystal will drain and it will give you an Active Beam Origin. This works just like the normal one after the Braziers have been lit and shoot out a Sludgeon Beam from the bottom. Beam Lenses and passages can also be crafted from Green Dentrothyst and Pitstone Bricks. 

  Treasure Room
The Sludgeon has a very surprising lack of general loot in it. To solve this I propose a treasure room below the Pit of Decay. After the Sludge Menace is defeated, a small hole in the center of the pit should open up. Inside is a room with a pool of Stagnant Water and some loot. Chests and blocks of Ancient Remnant (when that is implemented), Scabyst and Valonite should be found. There would also be Glowing Betweenstone lighting the room up. This would be guarded by Giant Sludge Worm spawners.

  Split Track
The music in the Pit of Decay should be split into two parts to separate the fights; the first during the Pit of Decay pre-fight, and the second during the Sludge Menace battle. Either Owltkins could make another track for the Sludge Menace, or the current song could be split in half. At the midpoint of the song (about 1:23) is where it should be split. The first part for the Pit of Decay, the second for the Sludge Menace.

  Brazier Mob Attracter 
Braziers should be able to be crafted from 3 Octine Ingots, 4 Weedwood Sticks, and 1 Ancient Remnant. When lit, they should increase the mob spawn rate in maybe a 30 block radius. Braziers wont have any affect on Sludgeon Beams, nor will they spawn Emberlings.

  Smart Moving Walls
Moving Walls are easily the dumbest thing in BL. They can’t move past a bunch of random things causing players to get stuck and possibly die. They should be able to kill/break: Living Roots, Lampreys, Armor Stands, Item Frames, Spirit Masks, and possibly other things I didnt test.

**Comment by Chiromaw** [comment]
The sludge already has a treasure room underneath the pit of decay.  You reach it by going through the crypts.  It is where you find the ancient great sword and the ancient armor set, along with pots of chance.  That combined with the shelves and chests in the main labyrinth, and the barashee lair; I feel the sludge has a lot more loot compared to every other structure.  I agree that braziers should be cartable, I love their model and wish I could get them without having to beat a sludge every time.  I wouldn't like them to attract mobs though, that negates any decorative use it could have.  And it has a lot of uses in that respect.

**Comment by spiderking23** [comment]
I agree with your Brazier but, should be mainly decorative. Maybe some practical use that makes sense, such as Healing Emberlings, or decreasing spawns around it. Also, maybe it could act as a Waypoint on maps, because currently, the only way that works is to build your base at a structure.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
