### ISSUE TITLE
[SUGGESTION] Swamp Catacombs

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1214]
Swamp Catacombs would be an uncommon structure that spawn in Swamplands that are intended to be done relatively early game. They would be made from Betweenstone Bricks and Mud Brick Shingles. They would be a cemetery with a building in the center. There are various graves with Swamp Hag spawners and loot chests inside them (The graves do not have block protection like the rest of the build). The building in the center would have a small spiral staircase leading down into the catacombs. The catacombs are a long hall extending in two directions that contain Pitstone Brick caskets lining the walls and Pots of Chance. The caskets would have more loot chests and spawners (The caskets also do not have block protection). At each end of the corridor would be a Peat Mummy spawner that is up in the air and Octine, Syrmorite, and Scabyst Blocks, which are block protected. To reach the spawner you have to do the parkour on platforms around the it. Once both spawners are broken, the structure is no long protected and the loot blocks can be picked up. When you return to the surface 10-20 Swamp Hags will be awaiting you.

**Comment by Chiromaw** [comment]
This is very similar to an idea I posted about a peat mummy graveyard.  Although there were noticeable differences, the sentiment is the same.  It seems like a no brainer for the bl to have some sort of graveyard structure, and I feel the devs could have a field day with it.  Glad to see someone else has an interest in it.  Quite honestly though, I don't think any of the ideas on this GitHub will be used unless the devs run out of ideas.  Which will never happen.

**Comment by FirestarPlayz** [comment]
The point is less that its a graveyard and more that its a low level dungeon. Right now there is a major lack of structures to do early game and hopefully the devs will fix that.

**Comment by Chiromaw** [comment]
I agree.  Bl takes a while to really get going.  Tried to get some pals into it with mixed success. Just too slow a start.  I'd love to see more early game content than could really hook you.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
