### ISSUE TITLE
[SUGGESTION] Diseases

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1215]
Diseases would be somewhat similar to Infusions but more dangerous and powerful. First, catching them would not be like Infusions. Each Disease is caught in different circumstances depending on which it is, and when they are contracted a vague message will appear above your hotbar telling you which you got. They are divided into 3 types: Senses, Physique, and Health. They cannot be bottled or used like Infusions so they cannot be weaponized. You can see what Diseases you have by looking at the top of your screen in the inventory. Similar to effects, they last for a certain amount of time before dissipating. But, they count down days (20 minute periods) instead of minutes, and cannot be removed via milk or whatever the BL equivalent is. Diseases would last from about one day to five, depending on the type. The only way to heal a Disease without waiting is through Tonics. Tonics would be made in a similar way to Infusions. To make them you must put a Spirit Fruit, Weeping Blue Petals, and 1 Aspect (Dayuniis for Senses, Yihinren for Physique, and Yeowynn for Health) into an Infuser and combine them like you would Infusions. Tonics are also divided into three types: Tonic of Senses, Tonic of Physique, and Tonic of Health. Each would remedy their corresponding Disease. Whenever a Tonic is used, instead of removing the Disease, it will shorten the time of it. When you use a Tonic, 5 minutes will be taken off of the remaining time for the Disease of that type, only if you only have one of said type. If you have multiple only 2 minutes will be taken off from them. Tonics of other types have no affect on a Disease. There isnt a way to prevent yourself from getting Diseases, the only way to stop it is to have high health as the lower your health bar is the higher a chance of you catching a Disease.

Here are some ideas for Diseases that I came up with:
Name
Type
Contraction message
Cure message
Contraction conditions
Effects

  Sludgebreath
  Health
  ‘You begin coughing up brown mucus’
  ‘Your lungs feel empty and you can breathe deeply again”
  Can be caught in the Sludgeon, or inflicted by the SM. Can also be caught from Sludge Tendrils(Future suggestion)
  When sprinting you lose hunger much faster. When under water your air drains faster.

  Nettletongue 
  Health
  ‘Your tongue begins prickling before going numb’
  ‘You begin feeling your tongue again’
  If you eat too many plant based foods you can get it. Walking through too much Nettle or Poison Ivy can also cause it.
  Food becomes less effective and Chiromaw Wings dont work.

  Bog Bones
  Physique
  ‘Your arms start feeling heavier than they should’
  ‘Your whole body is filled with energy’
  Swimming an excessive amount will cause this. It can also be caught when attacked by Leeches and Lampreys.
  Slows down your attacks and mining speed. It also slows your reaction time in Draetons and Weedwood Rowboats.

  Snail Stomach
  Physique
  ‘Your stomach rumbles and you feel nauseous’
  ‘Your stomach feels like a weight has just been lifted off of it.’
  Can be caught by eating raw meats or food that has maxed sickness. Blood Snails can also infect you.
  The effects of Food Sickness are greatly increased. You will also randomly be affected with hunger and nausea. Chiromaw 
  Wings are made inedible.
  
  Bat's Eye
  Sense
  ‘Your vision suddenly goes cloudy’
  ‘The world become clear again’
  Can be caught by spending too much time in the Lake Caverns. Also caught by being submerged in Stagnant Water.
  Your vision is cloudy and it is difficult to make thing out more than 5 blocks away.

  Mummy's Curse
  Sense
  ‘Your ears begin ringing and sounds become distant’
  ‘You feel your ears pop before noise becomes normal’
  This can be caught while fighting Peat Mummies, the DPM, the Barishee, or by being submerged in Tar.
  All sound becomes very quite and sometimes you will hear a ringing sound. Subtitles are also messed up.

**Comment by TripleHeadedSheep** [comment]
Sounds very similar to the ailments and apothecary idea from issue #1077

**Comment by FirestarPlayz** [comment]
Well it looks like you guys have it covered then! Pretend this suggestion never happened I guess

**Comment by spiderking23** [comment]
Well, actually, Ailments look more like Wound infections, they aren't diseases per se. I'd love to see these used in tandem, as it would mean management of your health would also be a factor in survival. I feel like diseases seems too much like a simple effect though. So I will make a suggestion regarding this one sometime later.

**Comment by Chiromaw** [comment]
I think this in tandem with the ailments issue would be a welcome addition.  I believe the ailments suggestion also got a "new feature" tag (and a low priority tag).  Good idea.  This would lend more use to the apothecary in that other issue as well.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
