### ISSUE TITLE
[SUGGESTION] Wisp in a Bottle

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1216]
The Wisp in a Bottle would be an accessory that allows you to gather Wisps not during Auroras. When equipped, you will be able to approach Wisps and pick them up. This would also allow pickup for Wisps outside of the Betweenlands. Every Wisp that is affected by this would take durability off of the bottle. It has a low durability so it will not take long to break. When broken, the Wisp in a Bottle will spawn a Wisp wherever you are standing. There are two ways you can obtain it. Either you craft it with 1 Wisp and 1 Green Dentrothyst Bottle or you get it from Item Scrolls, your pick.

**Comment by Chiromaw** [comment]
I do think that there needs to be more specialized accessory items other than just the item magnet, bark amulet, and lurker pouch (rings and middle amulets aside).  However once you get a wisp simulacra, it is pretty easy to farm wisps.  And they are not needed in early game.  I don't really see a use for this item.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
