### ISSUE TITLE
[SUGGESTION] New lore scraps (infestation) and lore booklet

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1217]
The infestation mob would be a perfect candidate for a lore scrap page.  The paper itself can have little holes in it like a ton of bugs chewed it out.  The content of the page would be how unrelenting and nightmarish they are.  How they will swarm you and slowly eat away your flesh.  I would like to see more lore pages, there haven't been any new ones in a while.  It would also be nice to be able to combine them into a little booklet.  And you can keep adding new pages as you find them.

**Comment by FirestarPlayz** [comment]
Good idea, and a Lore Catalog would also really help with storing them.

**Comment by Chiromaw** [comment]
that's what I mean by the little booklet.  You could combine 2 or more lore pages in a crafting table to make a lore scrapbook.  You could also combine the scrapbook with other lore pages you find to add them to the collection.  It seems to me like it would be a fairly simple addition.  Something the devs could just stick in.  No new materials or anything like that, just a new crafting result and a simple UI like the herblore book.  There aren't many lore scraps so it wouldn't take too long to compile them either.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
