### ISSUE TITLE
[SUGGESTION] Better Braziers (Inspired by the comments on my Sludgeon Suggestion)

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1218]
Crafting Recipe
Braziers should be craftable with 3 Octine Ingots, 4 Weedwood Sticks, and 1 Ancient Remnant. These could be lit with Moss and Octine. The crafted Braziers would not affect Sludgeon Beams nor summon Emberling Shamans. 

  Map Waypoint (Idea from Spiderking)
If a crafted and lit Brazier that is not a Mob Beacon is right clicked with a Bone Wayfinder, it should turn into a Waypoint. This would destroy the Wayfinder. Waypoint Braziers would be similar to normal Braziers but it will have teal fire and Reed Rope wrapped around it with small teal baubles hanging from that. Waypoints would appear on the Amate Map making them very helpful if you arent near any structures. If a Waypoint is unlit, it will be breakable and drop a normal Brazier. This will not return your Wayfinder.

  Mob Beacon
If a lit and crafted Brazier that is not a Waypoint is right clicked with a Life Crystal, it will become a Mob Beacon. The fire on top will turn to a light green and a Life Crystal will float above it. Mob spawning in a 30 block radius from this will be increased greatly, but the effect does not stack. As the Mob Beacon burns, the Life Crystal will slowly drain power. When it is at 0% the Beacon will no longer work. Shift-right clicking will remove the Life Crystal allowing you to recharge it. If a Mob Beacon is broken, it will drop the Life Crystal and the Brazier.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
