### ISSUE TITLE
[Suggestion] Firefly Jar... on a STICK!

### ISSUE THREAD

**Issue by CrazyAceking** [TheCyberBrick/The-Betweenlands#1219]
Idea: An accessory that is effectively a firefly in a jar, hanging from a pole that's strapped to your back. 
When equipped: Illuminates the area around you. (Potentially keeps away enemies that don't like bright lights, though that's a side thing at best). While in use, its durability slowly goes down, as the firefly inside begins to die. When the durability runs out, the item is not destroyed, but the light goes out, and to turn it back on you have to put it in a crafting table with another firefly.
Crafting Recipe: 5 weedwood sticks, 1 reed rope, 1 dentrothyst vial (possibly), 1 firefly.

**Comment by FirestarPlayz** [comment]
I like the idea but maybe it would make more sense instead of being an accessory it would be something hand held

**Comment by CrazyAceking** [comment]
So something to be held in the off hand? Hmm

**Comment by spiderking23** [comment]
... I feel like a simple dynamic lights mod covers this pretty well already as a handheld light source... so I have a bit of a counteruse with my Knapsacks and Backpacks suggestion: https://github.com/Angry-Pixel/The-Betweenlands/issues/1220

**Comment by CrazyAceking** [comment]
I mean, just cause one mod does it, doesn't mean another mod can't. You know how many tech mods have a way of turning ore into powder? Quite a lot. Plus, this is a (somewhat) aesthetically matching addition. A lantern on a stick with a firefly in it, can't get more swamp hermit-ish than that!

**Comment by spiderking23** [comment]
Fair point, but outside of appearance, what does this add function wise that's different than any dynamic lights mod... nothing. Which is why I think that having it as a equipped item is unique, it leaves your hands free.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
