### ISSUE TITLE
Animator

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#122]
Uses Len's model. 

Animating Idols - 
You put an Idol (Bronze/Silver/Gold) into each the middle slot of the GUI, a Life Crystal in the left slot and a whole 64 stack of Sulfur in the right. The model of the Idol will then be  rendered floating around slowly on top, without it's legs. The sulfur and life crystal will also be rendered beneath. The sulfur will give off lots of small yellow swirly particles like the torches, and the particles given off by the life crystal will rise up through the hole and surround the Idol. See this for reference. https://twitter.com/Angry_MrCompost/status/585865246784512001

When the process is complete, the Idol will appear floating above the table with its legs, and will rotate so it always faces the player like the old one did. When right clicked, the Animated Idol mob will follow you around.
This video of the old Animator may be helpful. Skip to 3:25 - https://www.youtube.com/watch?v=dc3_rUQtEhs

Animating Item Scrolls - 
The same as Idols, expect you put in an item scroll. It then appears rotating above the table. When it is done, a random item will appear floating above the Animator instead of the item scroll. It can be obtained by right clicking. 

Only certain items can be obtained from a scroll. Some loot items cant be obtained. Until more items are added, do this for now -

Sulfur 40%
Octine Ingot 30%
Valonite Shard 20%
Life Crystal 10%

**Comment by sor1n** [comment]
I claim to have finished it, if you think I have not, let me know.

**Comment by MrCompost** [comment]
Nope, there are a couple more things.
The bar for the life gem doesn't seem to work correctly. It either doesn't appear or doesn't seem to go down. The sulfur bar works, however you cant see it go down unless you exit the GUI and go back into it.

**Comment by MrCompost** [comment]
Oh, and also when you break it, any items in it aren't dropped, which could cause issues.

**Comment by MrCompost** [comment]
When I took out the Item Scroll before exiting the GUI my game crashed. Also I just realised, the Animator appears to be missing it's sound if that was ever added.

**Comment by vadis365** [comment]
re-assigned to Sam :P - he knows how to do it ;)

**Comment by TheCyberBrick** [comment]
mkay

**Comment by MrCompost** [comment]
This is still open? Not any more!
