### ISSUE TITLE
[Suggestion] Knapsacks and Backpacks!!

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1220]
Lurker Skin Pouches are GREAT. They give us so much extra space to store things while we Mine and Adventure. There are two issues I have with em though. First, The little item doesn't really do the amount of space justice. Second... they are basically just non-placeable Shulker Boxes. There is nothing particularly unique or interesting about their use... or their depiction on the player. So, I propose an... upgrade. Instead of there being small, medium, and large Pouches, there should instead be a small pouch, a large pouch, a Knapsack, and finally, a Backpack! Along with generally looking better, the uniqueness of these two items versus the pouches is you could Place them as a block, but this is not all. The knapsack would have the same storage as the current large pouch, but would have two advantages. First, it can be placed down, like the backpack. But secondly, and more importantly, it can be attached to The sides of Boats (Draeton included), the Toads, AND tied to Fenceposts. Basically, it acts as a more versatile storage. Backpacks, however, are a little different. An upgrade to the knapsack, with one extra row, they can also be placed down. But their real advantage, is the ability to attach up to Two POUCHES to the side of the backpack as additional storage! Alongside your normal pouch! Using the backpack or knapsack could be fairly simple as well. It would have the same key binding as accessing a pouch, and you'd just use that key again while inside the pouch... or it could open a radial menu like when equipping things... but instead, you choose which to open. The final benefit of having a backpack would be tied to the radial menu and its inventory. It would have special equipment spots for certain adventuring gear. Two for a tools, one for Caving rope, one for a grappling hook, and one for a dynamic light source, IE a lantern of some kind. (No torches, no need to set your backpack on fire). And, yeah. It'd be even more useful then a lot of backpack mods, and I think would be super useful for Adventuring, Caving, and simple travel. I'll upload some concept art of the Knapsack and Backpack model later, and perhaps an actual rendering, if the modeler I know is up to it. Suggestions, and Tweak ideas welcome.

**Comment by FirestarPlayz** [comment]
I really like this! Right now Pouches are very dry but this would be great. The only issue is the extra Backpack slots. I think that its too OP and should instead have craftable upgrades like the Draeton or Rowboat so you still have to work for the extra functionality.

**Comment by spiderking23** [comment]
... I did. That's what I mean, you need to craft Two desperate pouches for the additional slots the backpack provides over a Knapsack. (Outside of the slight increase from it just being a bigger storage container). And, to craft it, you'll need to have gotten Syrmorite for a buckle.

**Comment by spiderking23** [comment]
Or that's my idea on it's crafting.

**Comment by spiderking23** [comment]
(Knapsack is literally replaces the third upgraded pouch with some extra abilities)

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
