### ISSUE TITLE
[SUGGESTION] Chiromaw Patriarch (to be considered in conjunction with Spiderking23's mountain idea)

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1222]
NOTE: please read Spiderking23's "varied terrain" suggestion before reading this.

The Chiromaw Matriarch is a formidable opponent.  However, who does she mate with to birth so many offspring.  What if there was also a Chiromaw Patriarch living within the dens of tall mountains.  The Patriarch would be much larger, and have a more regal appearance.  Boasting an intricate crown of barbs as well as a more muscular body and wider wing span.  The Patriarch could be protecting a stash of ores, gems, and other treasures due to a fixation on shiny objects.  It collects these objects to impress Matriarchs with their shimmer in hopes of finding a mate.  Furthermore, the Matriarchs and Patriarchs of the betweenlands would be given an AI behavior that occurs during a mating season.  The chiromaw mating season would rotate similarly to a weather event (though not having to do with weather).  During a mating season, the patriarch will leave its den to fly to a nearby matriarch nest for mating.  This temporarily leaves its collection of loot unprotected.  However, the patriarch takes some of the better loot with it to impress the matriarch.  The player could loot the stash while the patriarch is away or take on the patriarch for the full reward.  This is similar to how you can scale the difficulty of a spirit tree with wisps, however being more of an "either/ or" scenario rather than a scaling of difficulty.  Also, when looting an empty den, there is always the fear of the patriarch returning.  This window of it being away is pretty short.  Plenty of time to loot the den, but not enough to laze about.  Mating seasons could be predicted by either crafting a device, having a special flower that lives on the mountains and turns color when a mating season is active, or just simply seeing the patriarch away from its den.  Another alternative would be to make regular chiromaws more visually aggressive to signify the season is taking place; they are common enough.  The patriarch would normally stay in its den guarding its hoard, but will attack intruders near it, or possibly scaling the mountains it lives in.  It would be a much harder fight than the matriarch to preserve that fear factor, and could serve to make the mountain biome a late game challenge for players.  Not every mountain biome would have a patriarch den.  These mountains would also be "soft" gated off early game sorta like how the sludge planes are kinda gated off until you get rubber boots.  The mountains would require a grappling hook, or some sort of new climbing gear to effectively traverse.

**Comment by spiderking23** [comment]
Or Building.

**Comment by Chiromaw** [comment]
building what?

**Comment by spiderking23** [comment]
I love this idea, as a "soft" gateway, I would instead suggest instead of just steepness, there should also be some other hazard, like Rockslides, falling debris, and the total inability for traversing UP water. Such as rapids! (Would be great for large rivers as well)

**Comment by Chiromaw** [comment]
I love all 3 of those ideas.

**Comment by spiderking23** [comment]
Thanks.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
