### ISSUE TITLE
[Suggestion] putting plant tonic in barrels

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1223]
it would be very helpful with farming if you could place and take plant tonic from weedwood or syrmorite barrels near your farm with a bucket.

**Comment by FirestarPlayz** [comment]
I second this

**Comment by spiderking23** [comment]
I third, Fourth, Fifth, Sixth, and 7th this.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
