### ISSUE TITLE
[Suggestion] Cake, Pie, or other Wholesome Goodie

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1224]
I just want a placeable food that allows me to do something like this to newbies on my BL server: ![image](https://user-images.githubusercontent.com/65906726/120419174-ece14e80-c32f-11eb-8c96-536a76ff4c4b.png)

**Comment by FirestarPlayz** [comment]
I remember awhile back someone suggested a Spirit Cake or something

**Comment by Chiromaw** [comment]
that was me.  A spirit fruit cake, or jello cake for all 3 of the jello types.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
