### ISSUE TITLE
[SUGGESTION] Musical Instruments

### ISSUE THREAD

**Issue by avale1648** [TheCyberBrick/The-Betweenlands#1225]
Greeblings Riders can drop some musical instruments (for example, banjo, violin or flute), when they're falling from chiromaws. Player can play on instruments and dueling with Greeblings Musicians, and if player win, greeblings does not run from player anymore.

**Comment by Chiromaw** [comment]
I had an idea a while back for crafting instruments and playing with greeblings for some bonus.  The issue I have with flying greeblings dropping them is that you would have to exit the Draeton, or fly off a raised island to get the drop.

**Comment by avale1648** [comment]
Maybe, but I still think it would be more interesting if the instruments will be a rare drop from greeblings riders or from dead greeblings in nests, because then it would be a valuable items. And I think it's not very big problem to land your draeton to take a drop.

**Comment by Chiromaw** [comment]
if it were to be taken from nest corpses, that is fine bc you just pick up the drop.  True you can just land the Draeton, but it can sometimes be hard to find a good spot to land away from mobs.  Plus, the item could drop in an undesirable spot that is hard to get to.  I would love to see musical instruments added to bl though.  Maybe give them some functionality with a ritual.  I'll think on it and maybe post another issue to take this idea further.

**Comment by avale1648** [comment]
Yes, I think you right about a drop, cause if it falls to deep waters it will be a real problem

**Comment by spiderking23** [comment]
Screw Functionality, I want to learn to play the Menu Tracks!!! (There should be sheet music to help players do so)

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
