### ISSUE TITLE
[SUGGESTION] Taring Creatures

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1227]
Tar buckets should be able to be used as weapons. Similar to throwing Infusions, if you hold right click with a Tar Bucket, it will throw the Tar in a flurry of particles and damage whatever it hits. You can also get the effect by staying submerged in Tar for 15 seconds. After dealing contact damage, the Tar will cover the victim slowly dealing damage and slowing down movement and attack speed, it will also obstruct your vision (If Apothecary is added it may also give a Burn.) The only way to remove Tar is to take a bath in Swamp Water; or for a much faster clean up, Stagnant Water. In Swamp Water it would take about 2 minutes of being submersed, and for Stagnant only 30 seconds. The effect will also dissipate after 20 minutes without water. If a Tared mob is killed it also has a chance to drop Tar Drips. This would not affect bosses or minibosses.

**Comment by spiderking23** [comment]
This is a cool idea, but not quite streamlined. After all, placing a bucket of tar in front of yourself will slow any and all ground based enemies on their way to you almost as badly as sludge does. Instead, maybe a new Tar Projectile for the slingshot by mixing two sludge, tar drip, and a pebble. Slows and blinds enemies, and not super super expensive.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
