### ISSUE TITLE
[SUGGESTION] Dead life crystal fragment use

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1228]
Once the life crystal fragments use up their charge, they are useless.  Why not make it so you can combine 9 dead fragments into a full life crystal that can be recharged.

**Comment by FirestarPlayz** [comment]
Sounds good to me

**Comment by spiderking23** [comment]
I would love this feature. However, I think t he amount required to make a full crystal should be based on the percentage of power it has compared to an actual crystal, and then have something else added to fuse the two together, like say a Valonite Crystal, Wight Heart, and, maybe ancient remnants or some other crystal. ¯\_(ツ)_/¯

**Comment by Chiromaw** [comment]
I thought of that at first, but each fragment has 50% charge.  That would mean only 2 are needed for a full crystal, which would be op.  That's why you would only combine them after they are used up.

**Comment by spiderking23** [comment]
That's why they need more material to fuse. Otherwise, this would be fairly OP, without the other materials to convert and help store the energy, maybe in the 9 together method, you only get like 0.22 (2/9ths) or so of all of the combined energy back.

**Comment by spiderking23** [comment]
Meaning you need nine full shards to get the equivalent of a single Full Crystal.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
