### ISSUE TITLE
Purifier

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#123]
Middle Gem Ores are put into the bottom slot and Middle Gems pop out the top. The machine is right clicked with a Weedwood Bucket of Water to fill it up. It needs 3 buckets for a full bar. This drains as the machine 'purifies' the ores. One bucket = one ore. Water is rendered inside the barrel-like part. It is still normally but running when the process is taking place. It will also glow and the furnace part at the bottom will give off the sulfur particles too.

**Comment by MrCompost** [comment]
Closing this for now, doesn't need to be open yet.

**Comment by vadis365** [comment]
I think this is done.
