### ISSUE TITLE
[SUGGESTION] Slingshot Addition

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1231]
The slingshot is not a supper effective weapon.  Even early game, a weedwood bow is just as easy to get.  The benefit of a slingshot is so that if you run low on arrows, you can just mine some betweenstone and make quick projectiles.  However, I personally never find a need for this, and arrows (although scarce due to angler teeth being annoying to get in large quantities) are pretty plentiful from pots of chance.  I suggest that launching pebbles from a slingshot should be able to distract enemies.  Hitting an enemy dead on would aggravate them, but hitting a block nearby would temporarily distract them and cause them to investigate the noise.  This would also shrink their agro range for the duration that they investigate, making it possible to slip by or even sneak up on them.  You would not be able to distract a mob already aware of your presence, boss mobs would be immune to the distractions; stronger mobs like tar beasts and wights would either have a chance to not be distracted or would have a shorter period of being distracted.

**Comment by spiderking23** [comment]
This along with a Vision Cone mod would be super immersive and fun. They shouldn't be fooled too many times though, especially smarter creatures, and if say an emberling finds a pebble, it will start searching for you and although it might look towards the next pebble, it won't go over to it. And Wights should ignore pebbles entirely, they don't care about the noise.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
