### ISSUE TITLE
[SUGGESTION] - Ground/Tree/Cave Basilisk

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1234]
## Mob Concept: The Basilisk Family
The Betweenlands are a realm of many dangers, filled to the brim with monstrosities ready to strike at any time. From the inoffensive looking snail to the horrific beasts who lurks in the dark, your journey promises to be a painful discovery of the reality of this corrupted swamp. But today is a time of reflection, food for thoughts if you prefer.
 
Today, we will ask ourselves what threat could roam around the corner, what foul creature born from our imagination might come visit you in the Betweenlands. Say welcome to the Basilisk.

## The Ground Basilisk:
![Ground Basilisk Showcase](https://user-images.githubusercontent.com/64988996/121814183-f93ea300-cc6f-11eb-9104-ddfd83fb3213.png)
Let us start with the most common and least aggressive of them all, matter of speaking, the Ground Basilisk. This hunter enjoys chasing Geckos around as well as Anglers, should it meet one,  lying both in the grass and in the waters of the Swamplands. Its venom is a potent one, almost instantly petrifying its victim’s motor functions. Should it be frightened, it will rear up, raise and vibrate its crest to persuade an opponent to give up on attacking. Should the threat stay, it will spray them with of mixture of bile and venom, poisoning and paralysing them before taking off. Three individuals have been spotted on the surface, one the same colour as swamp grass to blend in the flora, one brown of the mud, blending in the plains. The last one of them is the rarest, and most aggressive of them all, a female of dark red colour. Attacking any threat to protect her eggs, settled in mud nests. Should you encounter one, her babies are near, but death follows her path should you be ill-intended.

## The Tree Basilisk:
![Tree Basilisk Showcase](https://user-images.githubusercontent.com/64988996/121814225-2c813200-cc70-11eb-978c-aca39b8ad240.png)
Our next subject is a snake that has adapted to live in heights and catch its prey on the fly, namely, the Tree Basilisk. This mighty snake lives in about every normal trees of the Betweenlands, much more dangerous than its ground based kin. His most distinctive behaviour traits is his ability to snag Chiromaws and Fireflies out of the air. They hunt by hanging down for the trees like vines, still like stone, relying on the spot located on their head to attract critters looking for food. They also smell nice to Chiromaws despite what you could think of these dirty bats. When a creature gets close enough, the Basilisk will bite and hold tight, making the prey totally immobile and carrying it off somewhere high up to rip apart. Additionally and although not a large snake, this specie has evolved to defend itself against larger foes. They will attack Humans, Harlequin Toads and even Lurkers, should they get too close. It’s venom isn’t as long lasting as its Ground cousin’s, but the Tree Basilisk largely makes up for it by being the most aggressive snake of them all. As mentioned, this predator lives in all trees that are high enough to defend a nest. It is believed there is a different individual for each specie of tree. The notable difference between male and female are their frills, which are of a light purple like a fig for the female, and white like a pear for the male.

## The Cave Basilisk:
![Cave Basilisk Showcase](https://user-images.githubusercontent.com/64988996/121814239-3efb6b80-cc70-11eb-8eaf-a2ee34a3ca81.png)
The shyest snake that exist are the Cave Basilisks, rarest of them all. They are found swimming in the lakes and rivers deep down the underground. Adapted to live deep down, their scales act as a camouflage, mimicking the look of Pitstone. Almost totally silent, these aquatic serpents are fast skittish and stealthy. They have to be. Stalkers and Infestations prey on them. As such, they only surface in order to breath and rest. Should they face an attack, they can leap out of the water to try and grab their hunter, effectively dragging them in to drown them. Stalkers have perfected the art of hunting Basilisks, waiting on a roof overhanging the water in a still silence, waiting for its prey to come out. Once the serpent has surfaced, they will grab it before finish it off in a quick and brutal bite on the head, dragging the corps off to eat it. However one should not underestimate the danger of the Cave Basilisk, as their venom it the strongest lasting out of all the snakes, believed to last as long as a Draught which carries their name. When it comes to Humans, they often drown their hunter more than the hunter manages to harm them. Even Stalkers are not immune to this fate, and can be brought to a watery grave. Female are almost identical to their male counterpart, with the sole difference being their fins and crest, pink like precious Valonite.

## The Spirit Basilisk?
![Spirit Basilisk Showcase](https://user-images.githubusercontent.com/64988996/121814272-618d8480-cc70-11eb-838a-08670d131250.png)
This unique individual, kin to the Ground Basilisk, appears in the vicinity of a player’s moss bed, should the Human be kind to nests or even try to tame a baby. If the conditions are met, the Spirit will be found on a bed, and grant Luck and Resistance for a couple of minutes. However there is another occurrence of this individual, rarely spotted in the wilderness. If a nesting Basilisk dies, most specifically by Human hands, the Spirit will appear, should there be no other mother to protect the children. It will curl around the nest, making it untouchable until the eggs hatch.

## Conclusion:
With those final words ends our showcase of the Basilisk Mob concept. This wouldn't have been possible without @spiderking23 who imagined those graceful creatures (though nasty snakes I'll tell you), helped designing their appearance and helped me out on many aspects of their creation. It was a great creative exercise, and I cannot encourage anyone enough to try it out yourself, whether it is a suggestion for this mod, or for a mod of your own. Thanks again to the developers of The Betweenlands for their hard work, your accomplishments are a gold mine for imagination!

### Additional Notes:
If there are any brave souls who are willing to make this idea come to life, like making an add-on for example, you can ask me (@TheSilverplier) about the models. I made them under Blockbench and also created the textures along with spiderking. We currently have every variations mentioned in this suggestion (male/female/tree variants) and would be pleased to help you out if you wish to use them.

**Comment by spiderking23** [comment]
And I have to thank @TheSilverplier for his dedicated work and skill, and his patience in creating these beautiful little serpents. Watching them come to life thanks to his skilled modeling has been a joy during some of the worlds hardest days, and it has cemented a friendship that I hope lasts a Lifetime. Stay safe everyone, maybe I'll come back with another cool idea. So, for those who liked this, and want to join in on the ride... stay tuned.

**Comment by Chiromaw** [comment]
are you guys making an add-on mod

**Comment by TheSilverplier** [comment]
> are you guys making an add-on mod

I think I can confidently say that both of us would like to see it become an add-on for The Betweenlands. Unfortunately, I don't have any knowledge when it comes to Java, and I don't think spiderking can do it either (but I don't know if he intends to learn it). Not to say that it's something that will never happen though!

**Comment by Chiromaw** [comment]
well more power to you if you do.  It looks great.

**Comment by spiderking23** [comment]
Thank you @Chiromaw. Means a lot. I was a kinda hoping the Devs would adopt the idea, but I would certainly not be against an addon... maybe even an official addon, like a dlc to many games (but free, because mod, and because I'm not Bethesda)

**Comment by spiderking23** [comment]
If you know anyone who would like to work on it, let us know I guess. I do plan on learning some more Java, but right now I simply lack time.

**Comment by Chiromaw** [comment]
sadly I don't know anyone who would be able to work on it.  I feel like snakes are such a missed opportunity in bl.  They would fit the aesthetic so well.  Plus they could add an edge to survival.  Having to look up in the trees for possible ambushes.  Plus having basilisk arrows in the game seemed odd without a basilisk.  this would hopefully make those arrows cartable (I forget if you mentioned that).

**Comment by spiderking23** [comment]
It's Ok.

**Comment by spiderking23** [comment]
@TheSilverplier In case someone wishes to make this a thing and has the skills to do it, we should probably mention that we have models/textures for every single Variation of snake. So that's what this comment is for, but you can add it to the original issue if you think we should.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
