### ISSUE TITLE
[Suggestion] The Humble Brush Pile

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1235]
So, in the betweenlands, there are like... 3 main fuel sources. Sulfur, Wood, and Tarred Hearthgrove. Not a lot. And although Wood is plentiful, it's not very efficient. So, the solution? A new, renewable, efficient, and convenient fuel source. The Brush Pile. It's simple, you put in plants, sticks, leaves, bushes, etc. You get Dry Twigs, and Dry Brush. 

![image](https://user-images.githubusercontent.com/65906726/122304954-0e1b7080-ced4-11eb-8932-7f771412653c.jpeg)

Twigs burn 3 items each, brush cooks 2. Not bad, but very good. But brush and Twigs, along with some rope, can be made into bundles, which burn for thrice as long. The other benefit: Dry Brush can be placed and makes a good alternative to thatch as a roof... but more importantly, is SUPER FLAMMABLE. As flammable as moss. You can use it as a way to get a convenient fire source without waiting for moss to grow. The brush pile has one other function: Although slow, it dries reeds for free. Mosses and fungus are the only plants you cannot convert. Other benefits: it can store all those extra sticks and plants and turn them into a better fuel, and it gives you a reason to craft sticks as fuel instead of slabs.

**Comment by spiderking23** [comment]
If there ever is a campfire added, I would like to see a mechanic to add fuel in Three forms: tinder, to start it out, kindling, as buildup to a small, usable fire, and the Big stuff. If it ever is added, brush would be tinder, while dry twigs would be kindling, but both would last longer than moss and normal sticks.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
