### ISSUE TITLE
[Suggestion] Treefisher Felid

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1236]
Well... there are only three mammals in all of Betweenlands. Chiromaws, Stalkers, and Crypt Crawlers. Where is their common ancestry? Well, here's a start. The Treefisher is a 6 limbed cat like creature related to the stalker, but much less dangerous. It hunts small critters and rodents (see my future Rodents suggestion) and has poisoned spines like a Chiromaw. However, it will run instead of fight a human, it's too small and fragile to be a real threat, while we are much larger. They have 4 eyes, and would act as a sort of pest, eating your farm animals and stealing fish, but could be tamed, as they have the utility of being the only known predator to the deadly Tree Basilisk.

![image](https://user-images.githubusercontent.com/65906726/122424900-166bbe00-cf5d-11eb-9d4b-6050e53c7445.jpeg)

**Comment by spiderking23** [comment]
Please more mammals. It's concerning that Humans only close relations are hostile mole people, a six armed cave cyclops, and a giant spines bat.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
