### ISSUE TITLE
[Suggestion] Tiger in the Bushes

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1237]
Infestations suck. They are a good mob, but very annoying, by design. So let's balance this out with their cousin. The Tiger Beetle is an ambush predator that eats basically all invertebrates (Snails, Leeches, Dragonflies, Small and Medium Sludge Worms, etc) which can attack from bushes, fly short distances (like across bodies of water) run very fast, and deal decent damage. They also cannot be harmed by Infestations like it's other predators (the frogs). They also like shiny things, and though normally neutral, they will attack any player with middle gem amulets (or armor) and chase shimmerstones. They drop various colored shells used in dyes and Herblore, and are edible. They are hunted by Chiromaws, Lurkers, Harlequin Toads, and some Players who like the taste of beetle. They hide in bushes and attack and chase for about 150 blocks before getting bored and tired, and retreating to bushes again. Most of their prey flees from them, so they require cover. They can also be seen by keen eyes individuals inside bushes due to their colorations (Sulfur Yellow, Octine Orange, Scabyst Teal, and the most common, Bright Bush Green). They are NOT Tamable.

**Comment by spiderking23** [comment]
They would rarely chase geckos, but only if the more nutritious food sources had disappeared. And they would probably attack frogs, but not the Black or Purple ones, (The Poisonous one, and the One that's kinda close (not really, but eh))

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
