### ISSUE TITLE
[SUGGESTION] Spice

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1238]
A very simple and temporary solution to food sickness.  Spice would be to food sickness as Scabyst is to tool corrosion.  Spice could be obtained by aspects distilling in the alembic leaving behind some dregs.  These dregs would pop out of the alembic when all aspects are removed from it.  Dregs aren't a guarantee, but are randomly produced around 50% of the time when distilling.  These dregs could be placed in a mud brick spice jar (placed like a Dentrothyst Vial) to ferment into a fine spice.  After some time has passed, you can right click the spice jar with a stack of any sort of consumable item, and the spice effect will be applied to that stack.  You will know when the spice is done fermenting when the particle effect around the jar goes away.  If you have more food in your hand than you have spice in your jar, the spice will only apply to the same amount of food items and leave the rest unaffected.  This does not separate the single stack into two different stacks.  When a food item has had spice applied to it, it will essentially prolong the food sickness effect.  Hovering over a stack of say 64 reed doughnuts may indicate that 26 spiced reed doughnuts remain.  This means the next 26 doughnuts you eat will be exempt from the food sickness count.  After the 26th has been eaten though, the remaining food resumes the food sickness count.  One spice jar can hold 64 spice.  This would be very helpful for tackling large dungeons and long treks; and quite honestly, it is a gateway into a fantasized bl cooking system that I would love to see added.  I have a few ideas as to how a more in depth cooking system could work, so maybe I'll post more in the future if people are interested.

**Comment by spiderking23** [comment]
Mmmm... Spicy Angler Fish fillet with a side of mushroom, and a sprinkle of nettle.

**Comment by Chiromaw** [comment]
you're speaking my language pal! :)

**Comment by spiderking23** [comment]
Well, or there's just me, who subsists on the blood of my enemies alone. Being a vampire has its perks, but man I miss some good food tastes.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
