### ISSUE TITLE
[Suggestion] Better Banners

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1239]
Banners in Minecraft are great. They are a cool, unique way to express oneself and ones allies. But... they're pretty plain. Banners are all only a backdrop of a single shade, and are all the same shape. Not only that, but the number symbols we can use is tiny. There are like 4 or 5 symbols in all of Minecraft. So, let's change all that, with Betweenlands' Better banners. First, the shape. Banners should have a few size options, and shape options. Shapes: A split bottom, pointed bottom, the classic flat bottom, and to diagonal bottoms. Fairly simple, don't need to much there. Then, size options. Well, for one, banners that are just generally bigger is cool, but within each Catagory, there should be thin, thick, long, super long, and short variations. (The smallest banners and flags would only have 2 to 3 color options and no patterns, cause they are tiny) and then, for just about everything in the Betweenlands, there would be a pattern to represent it. 

![image](https://user-images.githubusercontent.com/65906726/122686756-efbdb980-d1e0-11eb-8993-7e7ac4ed42f6.jpeg)

Want a stalker pattern, we got that. Want a Basilisk pattern, for that too. Frog pattern, swamp hag pattern, heck, even a Swamp Reed Pattern! But the thing BFF or the Devs, each would have their own custom banner. I have a few examples cooked up already, but they could do others as well, giving us the awesome banners to play around with. And finally, colors. There should be like 3 or 4 different shades of each color. As well as a default green color (cause they're reed cloth banners). The last thing: Wear and Tear. Banners should ruin and tear in the rain, be burned by your enemies and then rescued by you. They should be able to be interacted with more. As for putting them on shields... We'll, the default shield ain't in BL... so how about instead, a new kind of shield that can be made from every material partially, but also be made of wood. Still customizable, but better than what vanilla gives us. Maybe a bit weaker than the default Valonite shield, but also mor fashionable. Sounds nice don't it.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
