### ISSUE TITLE
[Suggestion, Bug?] Short Offensive Infusions

### ISSUE THREAD

**Issue by spiderking23** [TheCyberBrick/The-Betweenlands#1243]
Welp... Let's see, Basilisk Draught last for how long, at Max Duration? Mere Seconds. 10 Seconds exactly. It doesn't immobilize anyone or anything you wouldn't just use the arrow for for long enough to actually be helpful. Either your too close and splash yourself with it for even longer than the target, OR your too far away to be able to use it. Even an Op draught like the Basilisk Draught shouldn't be so short. The MINIMUM duration should be at least 30 seconds. At least. And Basilisk Draught isn't the only mal-effected offensive infusion, most of the others are super short as well. Please buff the offensive infusions, as currently... they are basically Useless.

**Comment by spiderking23** [comment]
Sorry for the textual yelling, but I had to make the point clear.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
