### ISSUE TITLE
Crash with Traveler's Backpacks

### ISSUE THREAD

**Issue by MrRedstoneA1** [TheCyberBrick/The-Betweenlands#1245]
Betweenlands version:
3.7.3-SNAPSHOT

Forge version:
14.23.5.2855

Singleplayer or Multiplayer:

Singleplayer

Installed mods:

Over 60 mods

Link to full crash log

https://gist.github.com/MrRedstoneA1/b4a40be1e750ab379bd4b07973a4ee08

Description of the problem

When trying to transfer liquid from the backpack's tank to external container like the barrels, it works fine when there's liquid in the tank. When the tank is empty however, the game crashes.

How to reproduce:

1.Equip the backpack. (you'll have to put it on your back. Right click the backpack and click the equip button.)
2.Equip the hose and attach it to the backpack by right clicking. You can now select a tank and change modes.
3.Put the hose in "spill" mode (transfer liquid from tank to ground/liquid container)
4.Attempt to transfer liquid from tank to barrel, but tank is empty. (Shift and right click liquid container to transfer liquid)

#### Expected result:

Nothing should happen. The tank is empty and can't transfer liquid. Transferring liquids does work when there's actually liquid in the tank.

#### Actual result:

The game instantly crashes.

**Comment by TheCyberBrick** [comment]
That's an error on Traveler's Backpack's side. More specifically, it seems to try filling the barrel with a null FluidStack, which isn't allowed. It should instead use FluidUtil#tryFluidTransfer.

**Comment by MrRedstoneA1** [comment]
Alright, I made a ticket on their issue tracker.
