### ISSUE TITLE
[Suggestion] Scavenging Chiromaw

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1248]
To counter the overabundance of food, I came up with the idea of scavenging Chiromaw. They are not a new mob, but a new set of features for the current Chiromaw. When left unattended, chests will be sorted through by Chiromaw for loot. This will be mostly food, but they also have a chance to take Middle Gems, Dentrothyst Shards, and nuggets/splinters. When stealing food, Chiromaw will take 5-10 pieces and carry it in their claws. They will drop the stolen items upon death. Chiromaw will take any kind of food items excluding: Wight Hearts, Spirit Fruit, Nettle Soup, Weeping Blue Salad, and Chiromaw Wings. Chiromaw also would have the ability to pick up dropped food from the ground. They will begin by circling for a few seconds before diving down to pick some up. This will be especially problematic when you die with food outside your pouches. Chriomaw's final ability is to grab food from your hand. This would be an especially rare occurrence but will still be annoying. If you are holding food in your hand and are at more than half hunger, theres a small chance that a nearby Chiromaw will swoop down and take the stack of food from your hand before flying off.

**Comment by WorldSpinAround** [comment]
I LOVE that idea so much.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
