### ISSUE TITLE
[SUGGESTION] Dyeing lurker skin pouch strings

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1251]
I often carry (or store) several lurker skin pouches.  Although they can each be named something different, it would be very nice to be able to tell them apart at a glance.  Seeing as the next update will most likely add dyes and dyed items; it would be very helpful if you could combine a lurker skin pouch in a crafting table with a chosen dye.  This would change the color of the string tying the pouch closed on the item icon to the color of the dye.  The other alternative is that the dye colors the pouch itself, but I feel the strings would look better.  Either way, it would be a fantastic little addition that just makes item management much easier and quicker.

**Comment by FirestarPlayz** [comment]
This is fun and functional! Good suggestion I support

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
