### ISSUE TITLE
[SUGGESTION] Bad Weather

### ISSUE THREAD

**Issue by oggook** [TheCyberBrick/The-Betweenlands#1252]
About environment,I think you can add three bad new weather, the first is called a tornado, it can be formed after heavy rain, he can roll up blocks of creatures, farmland, after the tornado can generate something new, can bring treasure to adventurers. The second, called a thunderstorm, is a variant of heavy rain, unlike thunderstorms in the main world, which are more violent in The Between Lands and occasionally accompanied by "small tornadoes" that can also be added as creatures to blow players into the air
Thunderbolts will be more frequent and easier to hit players. A rare variant, acid rain, can also be added, which can corrode blocks and farmland, and the corrosion values can drop rapidly and extremely harshly. All three will make the otherwise un bright sky darker. Players will be affected by the wind, blown away by the wind, walking will become difficult, screen, under the tree, water will appear particle effect (not that kind of terrible particle effect). The player's corrosion values are consumed faster. You can add a brand new potion - feng shui.
to walk in the wind. You can also build a "wind shelter and acid shelter" (which can be added as a multiparty block) to protect the crop, blocks have different corrosion values (the workload may be a bit large, I believe you:))

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
