### ISSUE TITLE
[SUGGESTION] Draeton pet mob support

### ISSUE THREAD

**Issue by Chiromaw** [TheCyberBrick/The-Betweenlands#1254]
If the 2nd seat is not taken by a player, it would be awesome if you could stick a tamed emberling back there.  You can put one in if you have carry on installed.  But you can only take them out by breaking the dragon.  no new upgrade to be crafted is needed.  Just a small tweak so that emberlings or tarminions can be put in the back seat to ride with you.  If tarminions die while seated in the dreaton, the inanimate tar minion items dropped can just be immediately be picked up into your inventory, or if that's full, funnel into an attached lurker skin pouch.  Or maybe a separate compartment entirely.  Or just make it so tar minions life timer stops when in a draeton and so they will never die while seated until they are taken out and their timer resumes.  You would also be able to seat several tarminions in the back as opposed to just one like the emberling.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
