### ISSUE TITLE
[SUGGESTION] Amate Item Frame

### ISSUE THREAD

**Issue by Raghav0107** [TheCyberBrick/The-Betweenlands#1255]
I think it would be a good idea to have a Betweenlands version of the item frame, for decorating purposes... The draeton has one, so why not?
It would function in the exact same way as a normal item frame, as well as being able to display amate maps.
For a crafting recipe, i think weedwood sticks surrounding a piece of amate paper is a good choice.

**Comment by Chiromaw** [comment]
this has been mentioned several times along with a weedwood armor stand.  So the devs are aware of it and may add it in the future.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
