### ISSUE TITLE
[SUGGESTION] Sea Caverns, Suction Cups, and Leviathans

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1257]
Yea this is a long one

The Sea Cavern would be a dark subiome/structure (I dont know how youd code it) found in the Lake Cavern Layer. It would be a large cave about the size of 2-3 raises Isles full of water. Much of the current and future sea life would be found here, such as: Anglers, Urchins, Jellyfish, and various plants, although most of the life wont give off much light. The Sea Caverns would also have stalactites and Life Crystal Ore, but slightly more to make it rewarding. Various other new plants and creatures would be found here. A new pink coral called Lake Coral would be found here. It would be the same as Deep Water and Mire corals but a different color and it gives off much less light. There would also be a new kind of underwater plant called Pitflower. They would grow on stalks and have a pink and blue flower ontop. Both parts would be used for Herblore. In addition to the current marine life there would also be Rock Fish. They are large passive fish that has one large eye and skin like Pitstone. They would drop Rock Fish Fins which can be used to make Caveman's Soup or ground for Herblore. 

Also in the depths would be the Sanguid. A rare squid like monster that would latch onto the players face and drain their hunger and decay. It would be like a more powerful underwater leach. The Sanguid would drop Sanguid Suckers. These could be used to craft Suction Cups, an accessory. When equipped, you can latch onto walls by holding shift. You can also climb them by holding shift and W. If you are damaged or run out of hunger while holding onto/climbing a wall you will fall. When holding onto or climbing a wall your Suction Cups will lose durability, which goes faster when climbing. 

The final addition related to this subiome/structure is the Lurker Leviathan, or just Leviathan for short. The Leviathan would look very similar to the normal Lurker but its gargantuan and has bluish skin rather than green. The Leviathan would be about 9 blocks long and 3-4 blocks wide. It will hungerly snap its jaws at most fish, the only exception being Sanguids. It would have 150 health and deal 4 damage if youre hit with its fins(?) or tail. If you were to be caught in its jaws it would shake you and deal 9 damage. (Both these numbers are excluding armor) If you managed to kill this beast it would drop 4-8 Lurker Leviathan Skin and 6-9 Lurker Leviathan Teeth. Leviathan Teeth can be used to make Leviathan Tooth Arrows, which are like Angler Tooth Arrows, just stronger. They can also be used in Herblore, or in place of Angler Teeth on Grappling Hooks. Leviathan Skin would used to make a few things. First, it can be used to craft the Leviathan Diving Armor. It would be a more effective Lurker Skin Armor, and have the same effects with a greater buff. It would also have the armor stats of Bone Armor. There is no Leviathan Skin Shield. The second use for Leviathan Skin would be Leviathan Balloon Draeton Upgrade. This would be made from 6 Leviathan Skin, 3 Reed Rope, and 1 Tar Trip. The Leviathan Balloon would be applied by simply right-clicking the Draeton Balloon with the item. It would have a similar design with the picture of a Leviathan on the side. Tt would be the same color as the Leviathan rather than green. It does not use any upgrade slots like the other Draeton Upgrades. The Leviathan Balloon would be much less susceptible to punctures, but it is still repaired with normal patches. The upgrade drops if the Draeton is broken. The third use for this would be the Leviathan Skin Quiver. It would be crafted from 3 Leviathan Skin and 2 Reed Rope. It would open like a Lurker Skin Pouch, but it only has 9 slots. It cannot be upgraded. Arrows can be put in it, and when a bow is used the arrows will be taken from it rather than the inventory. The fourth and final use for Leviathan Skin would be Leviathan Minion Plating. This would be made from 2 Reed Rope, 4 Leviathan Skin, 2 Ancient Remnant, and 1 Syrmorite Shield (Yes really) This would create an armor item that can be applied to: Giant Toads, Emberlings and Tamed Chiromaw. It would give similar states to Bone Armor. There would also be a similar item, Leviathan Tar Minion Plating. It would be crafted in a similar way, but rather with a Bone Shield and makes 5 sets. These, as expected, can be applied only to Tar Minions. This would give stats like those of Lurker Skin Armor.

(Btw if youre too lazy to code 3d biomes you can alternatively just make it so Sea Caverns generate in Deep Waters biomes instead of normal Lake Caverns)

**Comment by FirestarPlayz** [comment]
I just realized theres more about the Leviathan than there is everything else

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
