### ISSUE TITLE
[SUGGESTION] Better Termites

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1258]
Currently, Termites suck. Theyre boring and serve no real purpose other than being annoying, which other mobs do much better. To fix this issue I have a list of ideas that could help improve these bugs. First, Termites should cliomb walls. Like cmon why dont they? Second, Termites should be able to infest wood blocks. This includes both planks and log and that Weedwood stuff. They cannot infest blocks inside a Repeller just incase that wasn’t obvious. In this state they can either pass through them, or change the wood to rotten wood if they are in a log block. Note this does not work with Sap, Rubber, or Spirit Trees. While hiding in a wood block, they also have the ability to birth more Termites. This would cause a bunch of small Termites to infest the block, and when broken all of them will release starting an infestation of Termites. (Different than Infestations, the cave-dwelling bitches) These smaller Termites would then be able to grow slowly into a normal sized one. Third, Termite swarms should be able to spawn. Groups of 7-12 Termites will rarely spawn in Swamplands and either attack a player or infest a nearby tree. This would allow for Termite infestations to spread quickly, which will present a problem. To combat this I suggest a new item called Insecticide. If you combine a Crushed Rottbulb, a hunk of Compost, and a Bottle of Shallowbreath, you will get a bottle of Insecticide. This can be thrown like normal Infusions and will cause any termites in a 15 block radius to either die or leave the area, depending on RNG. Termites will not return to this area for a long time after. Finally, you should be able to capture Termites with a net. These Termite items can then be crafted with a jar, which is being added in the new update, to make a Termite Jar. These can hold up to 8 Termites and will list what sized they are in the description. This jar can then be thrown like an Infusion to summon a swarm of Termites wherever you like.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
