### ISSUE TITLE
[SUGGESTION] Get out of my swamp!!! Advancement

### ISSUE THREAD

**Issue by Raghav0107** [TheCyberBrick/The-Betweenlands#1259]
This Advancement would be obtained by killing a wight inside a repeller's shield.
There's already one Shrek Joke in the mod... so why not another?

**Comment by FirestarPlayz** [comment]
I support this movement

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
