### ISSUE TITLE
An observation

### ISSUE THREAD

**Issue by PCAwesomeness** [TheCyberBrick/The-Betweenlands#126]
I just observed that Wights are just as weak as Anglerfish in terms of attack strength. 

As well as this, Swamp Hags only have more health than a zombie, and not more attack strength or speed.

Will these stats be changed?

**Comment by TheCyberBrick** [comment]
I'll just quote what Oli said: "They aren't finished yet. Just because we commit them doesn't mean they we've done with them."
All of the mobs are very WIP, most of the current stats and AI are just placeholders.

**Comment by PCAwesomeness** [comment]
What!? Come on. If they're still WIP, then why are their personal issues closed?

**Comment by vadis365** [comment]
Please stop posting issues with things that you have been told are WIP - it is getting annoying.

ALL THE MOBS ARE WIP! THE VERSION YOU TEST IS JUST WHAT I HAVE COMMITED FOR THE NIGHT! THERE ARE ONLY SO MANY HOURS AVAILABLE TO CODE AND THEN I COMMIT!

So, please only post bugs and crashes and not progressive reports on stuff that is being worked on.

**Comment by PCAwesomeness** [comment]
OK, I'm sorry for getting on your nerves. :(

Next time, I'll just post something else.

**Comment by TripleHeadedSheep** [comment]
David's patience is also still WIP :3

**Comment by vadis365** [comment]
No worries - we just have a plan with things that non-team members don't know about... so you end users only see things as we progress - not the eventual finished thing....
