### ISSUE TITLE
[SUGGESTION] Shallowbreath Fluid Traps

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1261]
(Inspired by Syren_DM’s idea)
If youve played Skyrim before you may be familiar with this idea. Shallowbreath Fluid Traps would be trap blocks that hang from ceilings and ropes. If a player were to walk below the trap, a bottle will fall and make a fiery explosion, damaged and burning nearby players and mobs. They can also be set off by pebbles and arrows. Obviously they would be found in various structures guarding loot. If they were to be craftable, theyd be made from 1 Reed Rope, 1 Undying Ember, and 1 Shallowbreath Fluid.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
