### ISSUE TITLE
[SUGGESTION] Pm Attacks and Changes

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1262]
Currently, the PM (Primordial Malevolence) has only 4 attacks, if you include the Wight summon. So, last night I came up with a few ideas for attacks and changes to make the fight more engaging. First, slam attack. During his second phase, the PM will rise up and quickly slam down into the ground, creating a shockwave that is similar to the Shockwave Sword. This, aside from being another attack, also forms a connection with the Wights Fortress' main loot item. Second, Player Possession. During either phase, the PM will summon a ring of 6 projectile heads to circle around you. One of which will have a slightly green tint. If you hit this one with a sword the ring will disappear and you will have a green projectile to launch at the PM. The possession will work similar to how it does with Wights. You take damage periodically. The only difference is if you hit one of the normal heads, you will take more damage. Finally, the Shield Dome. This is less an attack and more of a QoL change, I guess. When the PM is alive a sphere of the PM's shields will surround the top of the tower, preventing mobs from getting in, and you from getting out. Touching them would have the same effect as touching the PM's shields. There would also be holes to allow reentrance into the teleporter room.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
