### ISSUE TITLE
[SUGGESTION] Rubble and Cave-ins

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1263]
Im gonna get straight to the point, BL should have cave ins. This would work using rubble blocks. Rubble is a falling block, and has a varient for every type of stone. Betweenstone, Pitstone, Cragrock and Limestone. Rubble can be made/found in a few ways. First, it just spawns in big deposits underground, and will fall if the blocks are updated. Second, it can appear when an explosion happens. When something explodes, a second radius is made. In this radius all stone blocks are turned to rubble, and will fall if floating. Finally, rubble blocks have a chance to appear if stone blocks are above falling rubble, this will cause cave-ins to travel upwards for longer than would normally happen. This also means it can stop by random chance. Rubble can also made from right-clicking a stone block with a pickaxe.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
