### ISSUE TITLE
[SUGGESTION] Lots of new Advancements 

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1266]
Oh boy

Name
'Description'
(Requirements)

Doh! [Hidden]
‘Try to play Gert’s Donut in a jukebox’
(Put Gert’s Donut in a jukebox) 

Escape The Betweenlands 
‘Create a new Swamp Talisman for your grand escape’
(Craft a new Swamp Talisman from Betweenlands materials)

Harlequin Toady
‘Tame a Harlequin Toad’
(Tame a Harlequin Toad)

Which Came First?
‘Hatch a Baby Chiromaw’
(Hatch a tame Chiromaw )

And Along Came Zeus
‘Have your Chiromaw Egg struck by lightning, you monster’
(Obtain a Lightning Chiromaw Egg)

Hitokage
‘Capture a wild Emberling’
(Tame a wild Emberling)

Tar Soldier 
‘Where did the Prime Wight keep his Tarmies?’
(Craft a Tar Minion)

Tar Legion [Hidden]
‘Up his Sleevies! Or Tsleevies I guess’
(Make a stack of Tarminions)

Avid Fan [Hidden]
‘Get jumped by your Stalker. Or one of many’
(Get stalked and attacked by a Stalker)

Supporting the Community
‘You can add to the gallery on our Discord server!’
(Craft and place a Gallery Frame)

Let There Be Light!
‘Attack a lantern to your Weedwood Rowboat’
(Use a Weedwood Rowboat Lantern Upgrade)

run. [Hidden]
‘Seriously get the hell out of there’
(Stumble across a Hag Turret)

Drunkard’s Strength 
‘Drink an Infusion to give you the upper-hand’
(Drink an Infusion)

Ill Tell You When Ive Had Enough! [Hidden]
‘Have 5 different Infusions active simultaneously’
(Have 5 Infusion effects at once)

Overzealous [Hidden]
‘Try to eat a Chiromaw Wing before you need to’
(Eat a Chiromaw Wing before it works)

Echolocator
‘Locate a Middle Gem or Life Crystal with a Gem Singer’
(Use a Gem Singer to find a gem)

Shambler-man!
‘Craft a Grappling Hook’
(Craft a Grappling Hook)

Dazzling [Hidden]
‘Wear every accessory item at once’
(Have every accessory equipped at the same time. All three Amulets are required)

Light The Way Rudolf! [Hidden]
‘Attach a Firefly to your Draeton’
(Attack a Firefly to a Draeton)

By Druids, For Wayfinders
‘Find a Bone Wayfinder and link it to a Menhir’
(Link a Bone Wayfinder to a Menhir)

Proud Parent [Hidden]
‘Animate Spores to make a Sporeling’
(Animate Spores)

Amber Slippers
‘Craft and wear Rubber Boots’
(Put on Rubber Boots)

The Kings Curse [Hidden]
‘What part of Forbidden dont you understand?’
(Eat a Forbidden Fig)

Chemical Farmer
‘Grow and harvest an Aspectus Fruit’
(Harvest an Aspectus Fruit)

Meteorologist [Hidden]
‘Have a Windchime predict every event’
(Experience every type of event predicted by a Windchime)

Louisiana Jones
‘Don the very stylish Explorers Hat’
(Wear an Explorers Hat)

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
