### ISSUE TITLE
[SUGGESTION] Shield Spikes

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1268]
Chirobarbs are kinda useless. I came up with an idea to give them a use that can be used late game. Shield spikes would be crafted from 4 Chirobarbs surrounding a Sludge Ball. They would be applied to all shields, except Living Weedwood, like Middle Gems. When applied, anything that hits the shield will take some thorns damage, this also worked with charge attacks. A shield with Shield Spikes would have a number bar, similar to Food Sickness. It would have a scale of 0-50, max being highest Sharpness, 0 being lowest. Everytime a shield with spikes is hit, this number will have a chance to go down by 1. If the shied is disabled with an axe, it will go down by 5. The lower the Sharpness level the less damage it deals on each block. When it reaches 0 the spikes will disappear and you can reapply spikes. Spikes cannot be repaired in an Animator.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.

**Comment by Chiromaw** [comment]
I like this idea.  I had thought of something similar except it would function something like the spring razor from dishonored.  You could craft a chirobarb mine with sludge and chirobarbs and place them on a surface (ground/ wall/ roof).  When a hostile mob walks near it, it triggers and erupts a small barrage of barbs.
