### ISSUE TITLE
[SUGGESTION] Super Cave Update: Part one, Root Layer

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1270]
Part one: Root layer

Before I describe what the Root Layer would be let me explain what the layers in this cave update would look like. There would be 5 different cave layers, each with their own foliage, blocks, and mobs. Here is a visual representation of what it would look like: [Apparently I cant paste images here so just see image below] This also shows changed ore distribution, the wider the bar the more there is. Anywho let me get to the main topic.

The Root Layer would be the first layer in this new cave system. It would extend from y120 - y95. The caves in this would be round and wide, with little height variation. They would also rarely connect to one another. In these caves would be a wide variety of plants. They would include some of the biome specific plants, depending on what biome is above them. They would also have roots hanging from the ceiling. The ground of these caves would also have patches of another block, Grassy Betweenstone. This would look like it sounds, Betweenstone with grass on it. It would have physics like Mossy Cragrock Top, just a different texture that doesnt require a bottom. You could also find Hanging Roots hanging from the ceiling. There would also be other various unique plants down here that im too lazy to think of and describe. In these caves would also spawn Lurkers, Harlequin Toads, Mire Snails, Swamp Hags, and other creatures depending on the biome above. There would also be a handful of unique mobs in these caves. The first of which is the Snatcher. It is a green and brown plant-like creature with 4 large eyes. It would hang from ceilings waiting for the player to walk below it. Once in reach, the Snatcher will drop down and grab the player in its jaws. Once snatched, the Snatcher will rise back up, pulling the player with it. The player will receive the poison effect and will continue being effected until they are released, by hitting the beast. It is very susceptible to Slingshots. Next up is the Root Crawler. The Root Crawler is a small, almost dog like creature made from roots. It has a big head with even bigger jaws. If they bite you they will stop you in your tracks as they pull on you. They will let go if they are hit twice, at which point they will run off to regain health. They are also very hostile towards eachother. They will also eat frogs if given the chance. Finally, the Moss Baby. The Moss Baby would be a small and friendly creature in the form of a moss ball. It would slide around doing not much of anything. If the player were to feed it Sap Balls or Weeping Blue Petals, it would then spit out an item from a list of plant and plant related things. For example, seeds, herblore items, normal plants, and occasionally Sap Spit. Every time you feed it, it will get bigger. Once it gets close to its max, it will start making gross noises and look sick. When more food after this, it will expand before popping into a flurry of particles. If you were a heartless monster and killed it it would drop the Moss herblore item.

![image](https://user-images.githubusercontent.com/84095964/132137824-217a0ae2-7354-4420-bc4b-5b605d0c3115.png)

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
