### ISSUE TITLE
[Suggestion] Each biome should have their own ambiance.

### ISSUE THREAD

**Issue by MagmaSlime123** [TheCyberBrick/The-Betweenlands#1271]
Title.

Each biome should have their own ambiance. Most of the lush biomes having their usual current soundtacks, whilst the dead and gross type biomes having other sounds.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.

**Comment by MagmaSlime123** [comment]
There's quite a few other suggestions on here as well.
