### ISSUE TITLE
[SUGGESTION] Super cave update: Part two, Normal Layer

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1272]
Part two: Normal Layer

Before I describe what the Normal Layer would be let me explain what the layers in this cave update would look like. There would be 5 different cave layers, each with their own foliage, blocks, and mobs. Here is a visual representation of what it would look like: [Apparently I cant paste images here so just see image below] This also shows changed ore distribution, the wider the bar the more there is. Anywho let me get to the main topic.

The Normal Layer would be pretty much the same to the current Cavern Layer, and would extend from y95 to y50 The foliage and blocks would be essentially the same; actually entirely the same, the experience is good as it is. The only change I could think of is the Grapplopod. It would be an octopus like creature that latches onto walls and changes its texture to match them. They move by reaching their tentacles towards the ceiling and swing around as if they had a Grappling Hook. Do note they move little. If they feel threatened by the player they will swing up and attack the player by latching onto their face for a few seconds before retreating. If they are losing the fight they will squirt ink at the player and make their escape. They would drop Grapplopod Tentacles which can then be cooked into Grapplopod Calamari, as a reference to the ever elusive Swamp Kraken. The next one will have more depth I swear.

![image](https://user-images.githubusercontent.com/84095964/132138046-1e00ea49-e4ad-4c7f-b0a7-d7b30c20aae8.png)

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
