### ISSUE TITLE
Help finding "rope" texture in .jar file?

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#1277]
Hi all,

I'm messing with some textures, particularly for the Cave Rope. Is there any way someone could tell me what the texture is for the cave rope "rope", so I can make it look brown and "ropey" instead of "green and plant-like"? I can't find any texture options for the "rope" of the betweenlands mod.

**Comment by PetasiGit** [comment]
I don't think you can change the caving rope texture. Climbing rope, you can. But the caving rope is an entity, pretty sure the rope color is hard-coded for that,
