### ISSUE TITLE
Fix shader FloatBuffer/Out of memory crash

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/The-Betweenlands#128]

**Comment by quantumdude836** [comment]
Any hints as to how this can be reproduced?

**Comment by MrCompost** [comment]
I honestly don't really know. Thing is, as lovely as they look, the shaders cause much more trouble than they are really worth if I'm honest. I'd just leave them to Sam, I'm not sure what he wants to do with them.

**Comment by TheCyberBrick** [comment]
Wasn't able to reproduce this at all, and I'm not sure what would cause it. I'll probably rewrite the shader system anyways, the vanilla implementation sucks.

**Comment by TheCyberBrick** [comment]
I'll close this for now. I have not gotten any more reports of this bug and haven't ever had it myself
