### ISSUE TITLE
Missingitems making server unable to start on new update

### ISSUE THREAD

**Issue by TwinkGenji** [TheCyberBrick/The-Betweenlands#1285]
#### Forge version:
14.23.5.2855

#### Singleplayer or Multiplayer: 
Multiplayer (Forge Server, hosted with Apex Hosting)

#### Installed mods:
[Link to mod list used (excluding the betweenlands 3.7.3, ver. 3.8.0 was the one used )](https://drive.google.com/drive/u/0/folders/1UtQ1YrSOI8MkFaRaPou9KlrtkcUiUluP)

## Link to full crash log
[Link](https://gist.github.com/TwinkGenji/57059e3d93c4c797b068d762f7907c3e)

## Description of the problem
updated from ver. 3.7.3 to 3.8.0 on my minecraft server, and when booting up the server there were suddenly missing items (mainly from the anglers) that would leave the server unable to load fully without the items being present, resetting the betweenlands dimension did not help the issue eithier. server only went back to working the way it was before after going back to ver. 3.7.3., but unsure as to what could be causing the missing items since i assume they havent been entirely removed in the new update? help would be appreciated, ty! :)

#### How to reproduce:

1. remove ver. 3.7.3 from server
2. upload ver. 3.8.0 to server
3. start server

#### Expected result:
server to start as expected but with the new additions for the betweenlands

#### Actual result:
server unable to fully start, stuck infinitely "starting" due to missing items from the betweenlands- but does not crash

**Comment by SeriousCreeper** [comment]
That's normal with minecraft, you have to enter `/fml confirm` on your console to let the server accept the missing items.
Or do what the last line in your log says.

**Comment by TwinkGenji** [comment]
> That's normal with minecraft, you have to enter `/fml confirm` on your console to let the server accept the missing items. Or do what the last line in your log says.

is it normal for all the blocks to be missing :(
![2021-10-28_18 34 06](https://user-images.githubusercontent.com/93308496/139345433-b2b60999-b5f8-4180-bc5a-1e2a9ce4881c.png)

![2021-10-28_18 34 00](https://user-images.githubusercontent.com/93308496/139345426-e5fa42d3-478d-408d-b8cd-b9aca299f1de.png)

![2021-10-28_18 33 50](https://user-images.githubusercontent.com/93308496/139345415-98b79347-effd-4d1f-8164-11f483a83fba.png)

**Comment by SeriousCreeper** [comment]
Um no that looks bad. Could you send your server log? And you did confirm, not cancel, right? 
(Also side question, what resource pack is that for the UI? Looks nice lol)

**Comment by TwinkGenji** [comment]
> Um no that looks bad. Could you send your server log? And you did confirm, not cancel, right? (Also side question, what resource pack is that for the UI? Looks nice lol)

https://gist.github.com/TwinkGenji/5c1e0ff85c729bf15bdef0a8728cc04a
here's the full server log from that session, also the resource pack is vividity!

**Comment by TwinkGenji** [comment]
> > Um no that looks bad. Could you send your server log? And you did confirm, not cancel, right? (Also side question, what resource pack is that for the UI? Looks nice lol)
> 
> https://gist.github.com/TwinkGenji/5c1e0ff85c729bf15bdef0a8728cc04a here's the full server log from that session, also the resource pack is vividity!

additionally, things seem to work in singleplayer
![2021-10-28_19 24 45](https://user-images.githubusercontent.com/93308496/139350179-437eb231-f1da-4fc0-9d6e-250ea14ec810.png)

**Comment by SeriousCreeper** [comment]
Thanks! It seems like the server is missing the mod, which is weird if it lets you get on with it installed locally though... Could you double check it's on it, and the right version? Perhaps re-install it, just in case.

**Comment by TwinkGenji** [comment]
> Thanks! It seems like the server is missing the mod, which is weird if it lets you get on with it installed locally though... Could you double check it's on it, and the right version? Perhaps re-install it, just in case.

omg turns out that the betweenlands was in my main server folder and not the mods one when i thought it uploaded it there,moving it fixed the problem tysm for the help btw :D

**Comment by SeriousCreeper** [comment]
Glad it helped :)
