### ISSUE TITLE
Shadow Walker and Mist Blocks placed in gmc cant be broken

### ISSUE THREAD

**Issue by FirestarPlayz** [TheCyberBrick/The-Betweenlands#1286]
Betweenlands 3.8

14.23.5.2854

Singleplayer

The Betweenlands

1. Go into creative mode
2. Get and place Shadow Walker/Mist Bridge
3. Try and fail to break it

You cant break them

Still cant break them

**Comment by SeriousCreeper** [comment]
They work differently and aren't meant to be cheated in and placed.
