### ISSUE TITLE
Texture bug/oversight - Weedwood logs no longer place directionally

### ISSUE THREAD

**Issue by ReactivePlatypus** [TheCyberBrick/The-Betweenlands#1288]
#### Betweenlands version: 
3.8.0

#### Forge version:
14.23.5.2855

#### Singleplayer or Multiplayer:
Singleplayer, but likely both

#### Installed mods:
Only Betweenlands 3.8.0

#### How to reproduce:

Place weedwood logs on the side of another block.

#### Expected result:

Weedwood logs place directionally depending on what block face they were placed against.

#### Actual result:

Logs are aligned vertically, regardless of placement position.

Other log types seem to be unaffected. It only applies to weedwood.

#### Pictures:

https://i.imgur.com/tLfsCsq.png

**Comment by PetasiGit** [comment]
:sob:
