### ISSUE TITLE
[Suggestion] Add configs for custom smoking, fish cleaning, and filtering.

### ISSUE THREAD

**Issue by Ashen-sysadmin** [TheCyberBrick/The-Betweenlands#1291]
It would be nice for modpacks to be able to add meat smoking recipes. Currently I am working on something that centers around this mod.

**Comment by SeriousCreeper** [comment]
Smoking and crab pot recipes already exists, they can be added to the recipes.json inside the config folder.
For Smoking, the format is:
```
  "smoking_rack": [
    {
      "input": {
        "item": {
          "id": "modid:itemid"
        },
        "smoking_time": 1
      },
      "output": {
        "item": {
          "id": "modid:itemid"
        }
      }
    }
  ]
```

for crab pot it's
```
  "crab_pot_filter_silt": [
    {
      "input": {
        "item": {
          "id": "modid:itemid"
        }
      },
      "output": {
        "item": {
          "id": "modid:itemid"
        }
      }
    }
  ]
```

and just replace the "silt" part with "bubbler" for the other one. 

While the new ones aren't listed here yet, this might help in general for custom recipes: https://the-betweenlands.fandom.com/wiki/Configuration 

As for Fish Cleaning, it's not possible to add custom fish to it currently, but you can modify the loot tables for existing fish to determine the items.

**Comment by Ashen-sysadmin** [comment]
Thanks!
