### ISSUE TITLE
[Suggestion] Compatability with SimpleDifficulty?

### ISSUE THREAD

**Issue by Carvercarver1** [TheCyberBrick/The-Betweenlands#1297]
Compatibility of HUD elements of SD with TBL. It is basically similar to Tough as Nails, but more of a remake or remaster of it. Hud element of decay bar and thirst seem to overlap, I wonder if it is able to be fixed or adjusted as compatibility? >_>

**Comment by SeriousCreeper** [comment]
You can already move the decay bar yourself by modifying the config.

**Comment by Carvercarver1** [comment]
Oh. I'm dum.
