### ISSUE TITLE
Weedwood logs not showing as directional

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [TheCyberBrick/The-Betweenlands#1299]
Betweenlands version:
Betweenlands Universal 3.8.0

Forge version:
forge-1.12.2-14.23.5.2855

Singleplayer or Multiplayer:
Singleplayer

Installed mods:
JEI (jei_1.12.2-4.16.1.301.jar)
Betweenlands release 3.8.0 (universal)

Description of the problem:
When placing weedwood logs to make them face a different direction (like any other log), it doesnt show as being placed in the intended direction, always facing upward. When looking at it with F3, however, it still shows it as facing in the intended axis.

**Comment by vadis365** [comment]
Duplicate of #1288
