### ISSUE TITLE
Fishing Minigame consuming hunger before saturation

### ISSUE THREAD

**Issue by Umber0010** [TheCyberBrick/The-Betweenlands#1304]
Betweenlands version:
3.8.0

Forge version:
14.23.5.2855

Singleplayer or Multiplayer: Single Player Vanilla/Forge

#### Installed mods:
The Betweenlands
AppleSkin
AutoRegLib
Betweenlands Storage
Blood Magic
Clumps
Controlling
CraftTweaker
CraftTweaker Integration
Dynamic Trees
Dynamic Trees - The Betweenlands
Guide-API
Inventory Tweaks
JEI
Mouse Tweaks
Quark
Simple Storage Netwokr
Tomb Many Graves
Tomb Many Plugins - The Betweenlands
Veinminer

Description of the problem:

When catching a fish, the fishing minigame will drain the player's hunger regardless of current saturation. As a reminder, Saturation is a hidden stat that specifically staves off hunger drain.

How to reproduce:

1. Install Appleskin for easier visualization
2. Find a fish with a high stamina bar
3. Eat foods with high gains (Pear Jello or Mire Scramble are reccomended)
4. Perform the fishing minigame and watch as hunger drains without touching Saturation

Expected result:
Saturation drains as result of using hunger

Actual result:
Hunger drains despite saturation bar remaining full

Pictures:
(Yellow Overlay for the hunger bar represents saturation)
![2021-11-26_11 18 31](https://user-images.githubusercontent.com/25757398/143619086-118c285f-bb2a-40f1-b911-b81b92049acd.png)

![2021-11-26_11 19 06](https://user-images.githubusercontent.com/25757398/143619108-437ea873-e636-4830-b617-164aeea0cc08.png)

(Note, Slight saturation loss is on account of swimming in and of itself. The hunger bar below it should not have drained at all until the yellow bar was empty)

**Comment by PetasiGit** [comment]
Fixed/changed in 3.8.1.
https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod/files/3540284
