### ISSUE TITLE
Rotten Logs need finishing

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#131]
Their gen needs finishing and the rendering bug needs fixing.

**Comment by TheCyberBrick** [comment]
The rendering bug is due to a vanilla mechanic for transparent blocks. Could be fixed by making the block non transparent so that that vanilla mechanic is not used. Should be fixed in 1.8 anyways.

**Comment by MrCompost** [comment]
Still has the weird bug where its like it it isnt sure what part to render first.
