### ISSUE TITLE
Unneeded buckets being shown in JEI and the Creative inventory.

### ISSUE THREAD

**Issue by MagmaSlime123** [TheCyberBrick/The-Betweenlands#1311]
See https://github.com/CyclopsMC/CyclopsCore/issues/166. Issue between these mods.

**Comment by Ashen-sysadmin** [comment]
Betweenlands has a config to disable extra buckets in jei, Have you tried turning it on?

**Comment by MagmaSlime123** [comment]
I did not see any option for this.

**Comment by Ashen-sysadmin** [comment]
In the config under compatibility. There should be something like this:

    B:show_non_bl_fluids=true

**Comment by MagmaSlime123** [comment]
Oh, my bad.
