### ISSUE TITLE
[Bug/Unintended game mechanic] Rocksnot pods stealing mobs from each other

### ISSUE THREAD

**Issue by CTsquared** [TheCyberBrick/The-Betweenlands#1317]
#### Betweenlands version:
Most recent: 3.8.1

#### Forge version:
1.12.2-forge-14.23.5.2855

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands (removed all mods to see if it still occurs, it does)

#### How to reproduce:

1. Spawn two or more Rocksnot pods within close proximity to each other (~5 blocks)
2. Spawn a mob that they can eat
3. Observe.

#### Expected result:
Rocksnots would ignore mobs already being eaten by another Rocksnot.

#### Actual result:
They detect that there is a mob that it can eat, regardless of whether it's already being eaten by another Rocksnot, so it will attempt to steal the mob from the other Rocksnot. This results in the mob taking a very long to die.

Unsure if this is a bug or just an unintended game mechanic.

#### Video:
[LINK](https://youtu.be/ZfCmq7au3TE)

**Comment by SeriousCreeper** [comment]
This is an intended mechanic, yes
