### ISSUE TITLE
Redo biome decoration

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/The-Betweenlands#132]
Redo most decoration so that the chunks are decorated when the chunk is being provided. This should improve performance greatly because there are no chunk & storage lookups needed anymore. The trees are fine as they are, they just need to ignore small plants when generating so that they can be generated last.

**Comment by MrCompost** [comment]
I've just enabled it again and for whatever reason everything is running very smoothly now, so I'll close this unless something comes up.
