### ISSUE TITLE
Server Crash with java.lang.StackOverflowError: Ticking entity

### ISSUE THREAD

**Issue by m719030572** [TheCyberBrick/The-Betweenlands#1323]
#### Betweenlands version:
v3.8.1-release 

#### Forge version:
forge 14.23.5.2860

#### Singleplayer or Multiplayer:
catserver with Bukkit: 1.12.2-R0.1-SpigotAPI

#### Installed mods:
https://play.mcmod.cn/sv20186176.html

## Link to full crash log
https://github.com/m719030572/documents/blob/5e1666bce73471768f16ed7c488e2e1372739b18/crashlog

#### How to reproduce:
No method of reproduction has been found yet.

#### Expected result:
Fix it or provides a way to avoid this crash.

**Comment by JoshieGemFinder** [comment]
Looking at the code, this was caused by two urchins attacking each other: when they do, they attack back (this is the thorns-like damage they have), this could theoretically happen an infinite amount of times per frame, using up all the resources on your computer, so instead, java steps in and crashes the game

**Comment by JoshieGemFinder** [comment]
You might think one of the urchins should've died, but it looks like they don't actually take damage before dealing damage to the attacker, which is another urchin, which deals damage to it, but the damage never actually is dealt, because they're too busy dealing thorns damage

**Comment by darthvader45** [comment]
Yeah, and this happened on my world, basically corrupting it because I can't go in and deal with em.  We need a fix asap.

**Comment by vadis365** [comment]
fixed a while ago

**Comment by darthvader45** [comment]
Thank you, really annoyed me for a while.
