### ISSUE TITLE
Minecraft failed to start!

### ISSUE THREAD

**Issue by GruiaYT** [TheCyberBrick/The-Betweenlands#1325]
## Description of the problem
Minecraft Failed to start!An error during the startup prevented Minecraft from starting.The following mod(s) have been indentified as potential causes:Unknown

#### Pictures:
![9cb717ba-8494-4d8f-b686-20a0f82d4e50](https://user-images.githubusercontent.com/68369902/165030673-c495c05d-4de4-46cf-b99d-dacb36b6fcc3.png)

**Comment by SvenParoth** [comment]
This doesn't even specify The Betweenlands as the mod causing the crash... also we need the crash logs to help out at all

**Comment by GruiaYT** [comment]
> This doesn't even specify The Betweenlands as the mod causing the crash... also we need the crash logs to help out at all

But this mod is in my modpack and this error say to contact the pack dev.

**Comment by SeriousCreeper** [comment]
But you have also other mods in your pack... the error doesnt say that it crashed because of the betweenlands. And without being able to look at the crash report (literally mentioned on the screen), no one will be able to help you with this error.

**Comment by GruiaYT** [comment]
ok.but nobody helps me on the official curseforge discord server and idk what to do

**Comment by SeriousCreeper** [comment]
Post the actual crash report file
