### ISSUE TITLE
"Premium Produce" Advancement mistake in US_lang file

### ISSUE THREAD

**Issue by TheSilverplier** [TheCyberBrick/The-Betweenlands#1329]
## Issue:
The current text in the US_land file displays the "Premium Produce" Advancement and its decription as being part of the "survivalist" tree branch, despite it pertaining to the "farmer" category in-game.

#### Pictures:
![image](https://user-images.githubusercontent.com/64988996/171666110-ce5c1cae-4080-465d-8de1-54abdace08e4.png)

**Comment by link5669** [comment]
Just submitted a pull request for this, will update you when it's accepted

**Comment by PetasiGit** [comment]
Fixed in dev.
