### ISSUE TITLE
Shaders are broken

### ISSUE THREAD

**Issue by PCAwesomeness** [TheCyberBrick/The-Betweenlands#133]
Seriously. When I log onto a world, the shaders derp out and this happens...

http://imgur.com/FFKtPxu

**Comment by TheCyberBrick** [comment]
They're working fine. It's just that shaders are sometimes not working the same way on every GPU (especially on integrated ones, e.g. Intel HD Graphics). No part of the code should cause such a result and in the picture it looks more like a typical driver issue. Have you tried updating your graphics driver?
If you want me to have a look at this issue I'll need to know exactly which graphics card and driver version you have.

**Comment by PCAwesomeness** [comment]
My driver version is 8.901.3.0.

**Comment by TheCyberBrick** [comment]
I also have to know which graphics card you have

**Comment by PCAwesomeness** [comment]
AMD Radeon HD 6520G.

Is that it?

**Comment by TheCyberBrick** [comment]
Yes, thanks. Looks like your driver is already 3-4 years old, have you tried updating the driver?

**Comment by PCAwesomeness** [comment]
3, yeah.

And no.

**Comment by TheCyberBrick** [comment]
I'm not sure whether Windows Update updates your graphics driver. I have an nvidia card and I have to do it seperately through the nvidia control panel.

**Comment by PCAwesomeness** [comment]
Hm. I was just seeing this:
https://www.google.com/search?q=how+to+update+your+driver&oq=how+to+update+your+driver&aqs=chrome..69i57.7979j0j1&sourceid=chrome&es_sm=93&ie=UTF-8

**Comment by TheCyberBrick** [comment]
You're probably better off downloading the driver from the official website: http://support.amd.com/en-us/download
It should automatically detect the driver you need. And it's probably best if you create a restore point before updating your driver like this: http://windows.microsoft.com/en-us/windows7/create-a-restore-point

**Comment by PCAwesomeness** [comment]
After days of waiting, I'm just going to say that I first got the shader issue when I got build 38 (the one with the Silt Crab). Were the shaders updated or tampered with?

**Comment by TheCyberBrick** [comment]
That's weird, I have not changed anything related to the shaders or rendering in general since then. I'll look through the commits of the other devs, but I doubt they changed anything related to the shaders. I might just rewrite the shader system and not use the vanilla MC implementation anymore, hopefully that will fix those bugs.

**Comment by PCAwesomeness** [comment]
Figured out you can fix this just by pressing "Super Secret Settings". Let's see if it's a permanent fix.

**Comment by PCAwesomeness** [comment]
Yup, it is.

**Comment by TripleHeadedSheep** [comment]
That's not a fix, that's a temporary solution...

**Comment by PCAwesomeness** [comment]
OK.

**Comment by TheCyberBrick** [comment]
By pressing F4 or changing the super secret setting you just disable the shaders :P

**Comment by PCAwesomeness** [comment]
I see.

**Comment by TheCyberBrick** [comment]
Just a quick question: If you click on the super secret setting a couple of times, does it enable any special effects? And if so, do they work properly?

**Comment by PCAwesomeness** [comment]
I'll see.

**Comment by PCAwesomeness** [comment]
Not sure. All Super Secret Settings does now is play sounds.

**Comment by sor1n** [comment]
Shaders are indeed broken, I get a rainbow vision with it. I have an NVIDIA GeForce GT 525M

**Comment by Yelteen** [comment]
I've got the same issue.
I made some screenshots in my test world.
![2015-06-15_17 15 10](https://cloud.githubusercontent.com/assets/10757570/8163990/9b14a96c-1386-11e5-9393-dbc5360a52b7.png)
![2015-06-15_17 15 17](https://cloud.githubusercontent.com/assets/10757570/8163994/9d7197e2-1386-11e5-9cb7-1467077e7bf6.png)

**Comment by Yelteen** [comment]
EDIT: I ise a NVIDIA Geforce 540M Driver version 347.88 on Windows 7 HP 64bit

**Comment by TripleHeadedSheep** [comment]
Say no to drugs!

**Comment by PCAwesomeness** [comment]
@TripleHeadedSheep 

XD

**Comment by TheCyberBrick** [comment]
I'll test the mod on my old laptop and see if I can reproduce this bug. I just need to find a way to reproduce it to be able to fix it

**Comment by TheCyberBrick** [comment]
This seems to be fixed now, could anybody else also test this and confirm?

**Comment by PCAwesomeness** [comment]
I will tomorrow!

**Comment by PCAwesomeness** [comment]
It's fixed!

**Comment by TheCyberBrick** [comment]
Great! Thanks for confirming this :)
