### ISSUE TITLE
Need fix for 1.7.10

### ISSUE THREAD

**Issue by Gargule** [TheCyberBrick/The-Betweenlands#1332]
Hi. I know, 1.7.10 dead and everything, but i want to play ONLY on this MC version, so…
Can i have fix, please?

#### Betweenlands version:
Not necessary, but for 1.7.10, ofc

#### Forge version:
Not necessary

#### Singleplayer or Multiplayer:
Both

#### Installed mods:
It's VERY long and also unnecessary

## Link to full crash log
No crushes

#### How to reproduce:
Use any mod that can increase max health and go to Betweenlands

#### Expected result:
Your max health stays same as long as Decay bar is full

#### Actual result:
Your max health capped at 20 while you are in Betweenlands

#### Pictures:
Not necessary

**Comment by PetasiGit** [comment]
We do not support the 1.7.10 version of the mod anymore, sorry.
