### ISSUE TITLE
Shulker boxes can be placed in Lurker Skin Pouches/Fishing Tackle Boxes and vice-versa

### ISSUE THREAD

**Issue by thebotz** [TheCyberBrick/The-Betweenlands#1334]
#### Betweenlands version:

3.8.1

#### Forge version:

14.23.5.2860

#### Singleplayer or Multiplayer:

Singleplayer

## Description of the problem
Lurker Skin Pouches and Fishing Tackle Boxes can be put inside of vanilla Shulker Boxes, and Shulker Boxes can be put inside of them. This can be looped for infinite storage.

#### How to reproduce:

1. Obtain shulker boxes and some lurker skin pouches or fishing tackle boxes.
2. Place a shulker box inside a lurker skin pouch or fishing tackle box.
3. Place the shulker box containing the skin pouch or fishing box inside another lurker skin pouch or fishing tackle box.
4. Place that skin pouch/tackle box inside a second shulker box.
5. Infinite storage! (Until you cause a chunk saving error or "bookban" yourself)

#### Expected result:

Lurker Skin Pouches and Fishing Tackle Boxes should not be able to contain shulker boxes, or be placed in them.

**Comment by TheCyberBrick** [comment]
Good catch, thanks!
Fixed in dev.

**Comment by TheCyberBrick** [comment]
Btw, there's a config option called "Lurker Skin Pouch Blacklist" where items can be added to prevent them from being used in lurker skin pouches (and also fishing tackle boxes). Can be useful when other mods add inventory items.
