### ISSUE TITLE
Finish the portal!!!

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#134]
C'mon guys, it's been about 4 months. The portal block itself needs it's custom particles firstly. It also needs the custom sounds adding and well as the swaying screen effect when you enter. Instead of the mossy cobblestone portal that we have atm, it should be created by right clicking any kind of sapling with the Swamp Talisman (including BL ones so the player has a way of getting back if the portal gets broken). It would have to be done in such a way so that the player doesn't get stuck in the blocks when it gens. When a block is broken, the whole thing will quickly 'decay' as leaves would, breaking the portal. When you enter the dimension, another portal is generated on the surface in a Swamplands biome. 

EDIT - 
Woohoo! It's looking fantastic =)
We just have a few more things to do - 
*Replace the druid stone with something else. Maybe just a block identical to Weedwood with the same name, and have it drop Weedwood.
*Add a delay and swaying effect when entering the portal.
*Add the portal trigger and travel sounds.
*Make the current particles green. No need to use the fancy custom ones atm, we can do that later.
 *Seems like if you go back to the overworld and then into the BL again, another portal is created.

**Comment by vadis365** [comment]
I started making this thing and was told someone else was doing it.
FFS LEX!
I pretty much made the whole bloody thing it only need for the finishing touches!

**Comment by imdutch21** [comment]
portal now mostly fixed. We only need to make it so you don't insta teleport and that the sound plays while in the portal

**Comment by imdutch21** [comment]
need someone to help me with the teleporting to the other dimention because I am very stuck.

**Comment by MrCompost** [comment]
Woohoo! It's looking fantastic =)
We just have a few more things to do - 
*Have the portal gen at height 85
*Replace the druid stone with something else. Maybe just a block identical to Weedwood with the same name, and have it drop Weedwood.
*Have it so that the player is always moved inside the portal tree.
*Add a delay and swaying effect when entering the portal.
*Add the portal trigger and travel sounds.
*The portal looks awesome and doesn't really need any more aesthetic changes or additions, so the fancy custom particles can be put to one side for now. Perhaps just make the smoke particles we use green instead and we can call it done.

**Comment by MrCompost** [comment]
Er... ok, it was working and now I seem to be spawning in the ground again in the BL. Not sure what's up with that.

**Comment by MrCompost** [comment]
Ok, seems like if you go back to the overworld and then into the BL again, another portal is created.

**Comment by TripleHeadedSheep** [comment]
What's left to do? Or can we close this?

**Comment by MrCompost** [comment]
*Replace the druid stone with something else. Maybe just a block identical to Weedwood with the same name, and have it drop Weedwood.
*Add a delay and swaying effect when entering the portal.

aaaaand the backup portal I think

**Comment by TripleHeadedSheep** [comment]
Ah, ok... So who's gonna do this?

**Comment by MrCompost** [comment]
Whoever. Whenever. The usual.

**Comment by TripleHeadedSheep** [comment]
Done

**Comment by TheCyberBrick** [comment]
*Replace the druid stone with something else. Maybe just a block identical to Weedwood with the same name, and have it drop Weedwood.

*The backup portal

Oops, forgot about those two
