### ISSUE TITLE
Crash using Latest Version while Loading.

### ISSUE THREAD

**Issue by fullskele** [TheCyberBrick/The-Betweenlands#1343]
#### Betweenlands version:
Tested with versions 3.9.0 and 3.9.1

#### Forge version:
Tested with 14.23.5.2859 and 14.23.5.2860

#### Singleplayer or Multiplayer:
Singleplayer instance, no testing done for multiplayer.

#### Installed mods:
Included in crash log System Details. 

## Link to full crash log
https://gist.github.com/fullskele/7a03fdc733e5e9a3c1a2b0c3b1abfa42

#### How to reproduce:

1. Start the modded instance, and wait for loading to nearly conclude.
2. The game will crash.

**Comment by SeriousCreeper** [comment]
Not seeing anything in the logs that would point towards Betweenlands (or any mod really). 
Try without optifine and see if that works. 
Does it work when you disable just the Betweenlands?

If so, please upload your latest.log after having launched the pack and the crash occurred, there might be more in there that could point towards the issue.

**Comment by ALJ323** [comment]
I'm also experiencing this same issue and I have been able to start the game without Betweenlands since updating to 3.9.0 and 3.9.1. Reverting to 3.8.1 also allows me to launch the game successfully

**Comment by fullskele** [comment]
I uninstalled Optifine and tried to load with version 3.9.1, and was successful. The game started.

I then tried to load 3.9.1 with Optifine again to try and produce a crash, but the game was again able to load correctly. 

I tried a third time after disabling an unrelated mod, and was met with a crash. Latest.log: https://gist.github.com/fullskele/4fbfc1db08e930a661c33cd7e9a11c0e

@ALJ323, could you try to load the game once on 3.9.1 without Optifine, and then again with Optifine?

**Comment by magcicada** [comment]
I have the same crash report without optifine but there is anthoer render mod.

**Comment by OzarkBungler** [comment]
I've managed to narrow this down, the crash occurs with Betweenlands 3.9 and up alongside the Had Enough Items fork of JEI. Crashlog showing just these two failing to launch:
https://gist.github.com/OzarkBungler/683b23d1a25b0c620f2548a9e81f70f7

**Comment by magcicada** [comment]
> I've managed to narrow this down, the crash occurs with Betweenlands 3.9 and up alongside the Had Enough Items fork of JEI. Crashlog showing just these two failing to launch: https://gist.github.com/OzarkBungler/683b23d1a25b0c620f2548a9e81f70f7
![image](https://user-images.githubusercontent.com/45464670/210370640-ecc8d746-5e8b-4cd4-ad68-1026b61920fb.png)

**Comment by magcicada** [comment]
And HEI works for me, I am sure it is Fluidlogged or other mod that change fluid tpye will cause this crash.
Just list here that I found: [Fluidlogged API](https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api), [Clear Water](https://www.curseforge.com/minecraft/mc-mods/clear-water), [GregTech CE: Unofficial](https://www.curseforge.com/minecraft/mc-mods/gregtech-ce-unofficial), [SmoothWater](https://www.curseforge.com/minecraft/mc-mods/smoothwater), etc.
