### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by agabeluga** [TheCyberBrick/The-Betweenlands#1346]
#### Betweenlands version:

3.9.0

#### Forge version:

14.23.5.2860

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | mixinbooter         | 7.0               | minecraft.jar                                 | None                                     |
	| LCH   | jei                 | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | abyssalcraft        | 1.10.4            | AbyssalCraft-1.12.2-1.10.4.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | aether_legacy       | 1.5.3.2           | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LCH   | aether_legacy_addon | 1.12.2-v1.3.0     | Aether Continuation v1.3.0.jar                | None                                     |
	| LCH   | orbis-lib           | 0.2.0             | orbis-lib-1.12.2-0.2.0+build411.jar           | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether              | 0.3.0             | aether_ii-1.12.2-0.3.0+build411-universal.jar | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aoa3                | 3.3.6             | AoA3-3.3.6.jar                                | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCH   | appleskin           | 1.0.14            | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | atum                | 2.0.20            | Atum-1.12.2-2.0.20.jar                        | None                                     |
	| LCH   | base                | 3.14.0            | base-1.12.2-3.14.0.jar                        | None                                     |
	| LCH   | betteradvancements  | 0.1.0.77          | BetterAdvancements-1.12.2-0.1.0.77.jar        | None                                     |
	| LCH   | betternether        | 0.1.8.6           | betternether-0.1.8.6.jar                      | None                                     |
	| LCH   | betterquesting      | 3.5.329           | BetterQuesting-3.5.329.jar                    | None                                     |
	| LCH   | bibliocraft         | 2.4.6             | BiblioCraft[v2.4.6][MC1.12.2].jar             | None                                     |
	| LCH   | blue_skies          | 1.1.3             | blue_skies-1.12.2-v1.1.3.jar                  | None                                     |
	| LCH   | bookshelf           | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | cavern              | 2.3.1             | Cavern_1.12.2-v2.3.1.jar                      | None                                     |
	| LCH   | clumps              | 3.1.2             | Clumps-3.1.2.jar                              | None                                     |
	| LCH   | controlling         | 3.0.10            | Controlling-3.0.10.jar                        | None                                     |
	| LCH   | ctm                 | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCH   | divinerpg           | 1.7.1             | DivineRPG-1.7.1.jar                           | None                                     |
	| LCH   | endreborn           | 0.3.8             | EndReborn [0.3.9].jar                         | None                                     |
	| LCH   | erebus              | 1.0.32            | Erebus-1.0.32.jar                             | None                                     |
	| LCH   | huntingdim          | 1.0.42            | HuntingDimension-1.12.2-1.0.42.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | journey             | 1.0.6.11          | Journey-Into-The-Light-1.12.2-1.0.6.11.jar    | None                                     |
	| LCH   | journeymap          | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCH   | landsoficaria       | beta-1.12.2-1.0.3 | landsoficaria-beta-1.12.2-1.0.3.jar           | None                                     |
	| LCH   | libraryex           | 1.2.2             | LibraryEx-1.12.2-1.2.2.jar                    | None                                     |
	| LCH   | lost_aether         | 1.0.2             | lost-aether-content-1.12.2-1.0.2.jar          | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | twilightforest      | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCH   | moartinkers         | 0.6.0             | moartinkers-0.6.0.jar                         | None                                     |
	| LCH   | mousetweaks         | 2.10              | MouseTweaks-2.10-mc1.12.2.jar                 | None                                     |
	| LCH   | neat                | 1.4-17            | Neat 1.4-17.jar                               | None                                     |
	| LCH   | netherex            | 2.2.5             | NetherEx-1.12.2-2.2.5.jar                     | None                                     |
	| LCH   | neid                | 1.5.4.4           | NotEnoughIDs-1.5.4.4.jar                      | None                                     |
	| LCH   | patchouli           | 1.0-23.6          | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCH   | midnight            | 0.3.5             | themidnight-0.3.5.jar                         | None                                     |
	| LCH   | rifting             | 1.0.0             | Rifting.jar                                   | None                                     |
	| LCH   | bq_standard         | 3.4.173           | StandardExpansion-3.4.173.jar                 | None                                     |
	| LCH   | beneath             | 1.7.1             | The Beneath-1.12.2-1.7.1.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | tinkersaddons       | 1.0.7             | Tinkers' Addons-1.12.1-1.0.7.jar              | None                                     |
	| LCH   | tinkersaether       | 1.4.1             | tinkersaether-1.4.1.jar                       | None                                     |
	| LCH   | tcomplement         | 1.12.2-0.4.3      | TinkersComplement-1.12.2-0.4.3.jar            | None                                     |
	| LCH   | tinkersjei          | 1.2               | tinkersjei-1.2.jar                            | None                                     |
	| LCH   | tinkersoredictcache | 1.0               | TinkersOreDictCache-1.0.jar                   | None                                     |
	| LCH   | traverse            | 1.6.0             | Traverse-1.12.2-1.6.0-69.jar                  | None                                     |
	| LCH   | phosphor-lighting   | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50.jar             | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCH   | jade                | 0.1.0             | Jade-0.1.0.jar                                | None                                     |
	| LCE   | thebetweenlands     | 3.9.0             | TheBetweenlands-3.9.0-universal.jar    

## Link to full crash log

https://gist.github.com/agabeluga/97dde21238044c27448dc18784c5123d

#### How to reproduce:

1.Open the game
2.
3. etc...

#### Expected result:

The game doesn't crash

#### Actual result:

The game crashes

**Comment by SeriousCreeper** [comment]
`Failed to register dimension for id 20, One is already registered`

As it says, you already have a dimension with ID 20 in use, which is what the betweenlands uses by default. You can change that in the config.

**Comment by agabeluga** [comment]
How to change it
