### ISSUE TITLE
Finish off the arrows

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#135]

**Comment by vadis365** [comment]
How... I'm warning you - issues with no info will be closed....

**Comment by TripleHeadedSheep** [comment]
Angler Tooth Arrow: Basic arrows for the Weedwood Bow.
Octine Arrow: arrows for the Weedwood Bow that can set enemies on fire.
Poison Angler Tooth Arrow: Arrows for the Weedwood Bow that can poison enemies.

Those are the three basic arrows for now.
Two other ideas are:
Basilisk Arrow: A loot only arrow. It petrifies mobs for a few seconds upon impact.
Balloon/flare Arrow: Crafted with rubber. Upon impact (also with water) these arrows release a small balloon that floats up and acts as light source. Very useful on lakes.

**Comment by MrCompost** [comment]
I can add crafting recipes and names once they are done.
