### ISSUE TITLE
Incompatibility between version 3.9.1 and Had Enough Items 

### ISSUE THREAD

**Issue by SiliconAshes** [TheCyberBrick/The-Betweenlands#1350]
Thank you for the time and effort you've put into this fantastic mod!  I absolutely love it and always look forward to an update!

With the latest update (TheBetweenlands-3.9.1-universal), there seems to be an incompatibility with Had Enough Items (HadEnoughItems_1.12.2-4.24.2).  For me, the game will crash just before the main menu would come up.

Steps to reproduce (using MultMC):

    Create a new 1.12.2 Minecraft instance

    Install forge 14.23.5.2860 (latest via MultMC)

    Install TheBetweenlands-3.9.1-universal (latest on curseforge)

    Install HadEnoughItems_1.12.2-4.24.2 (latest on curseforge)

    Attempt to start the instance

For me, the the game crashes late in the load process, near when the main menu would otherwise come up.  I don't know if this is on your side or on HEI's side.

   This issue does not arise if Just Enough Items (jei_1.12.2-4.16.1.302) is used instead of Had Enough Items.  It also does not arise with the previous version of The Betweenlands (TheBetweenlands-3.8.1-universal).

Here is a pastebin of my latest.log, and crash-report:

latest.log: https://pastebin.com/iXD2qbjy
crash-report: https://pastebin.com/bdBDhMX3

I did not see this issue reported on your issue tracker, and if I did miss it, I apologize.

Again, thank you very much for this mod!  

---

#### Betweenlands version:

TheBetweenlands-3.9.1-universal

#### Forge version:

forge 14.23.5.2860

#### Singleplayer or Multiplayer:

Crash before main menu

#### Installed mods:

HadEnoughItems_1.12.2-4.24.2
TheBetweenlands-3.9.1-universal

## Link to full crash log

latest.log: https://pastebin.com/iXD2qbjy
crash-report: https://pastebin.com/bdBDhMX3

#### How to reproduce:

This is using MultiMC on Windows 10:

1. Create a new 1.12.2 Minecraft instance
2. Install forge 14.23.5.2860 (latest via MultMC)
3. Install TheBetweenlands-3.9.1-universal (latest on curseforge)
4. Install HadEnoughItems_1.12.2-4.24.2 (latest on curseforge)
5. Attempt to start the instance

#### Expected result:

Game starts up/main menu comes up

#### Actual result:

Game crash before main menu comes up

**Comment by sddsd2332** [comment]
I discussed it with the developers of HEI on Discord, and he thought the problem might be on an asynchronous build of HEI

You need to turn off asynchronous builds in the HEI configuration file to enter the game normally
`B:asyncSearchTreeBuilding=false`

**Comment by SiliconAshes** [comment]
That does indeed allow the game to load.  Thank you very much for the workaround!

**Comment by vadis365** [comment]
this looks to be solved
