### ISSUE TITLE
Balance mob spawning 

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#136]

**Comment by vadis365** [comment]
How - just adding a title provides no info - and I'll close the issues that are like this....

**Comment by TripleHeadedSheep** [comment]
We should make a proper list about where the mobs should spawn and under what conditions.

**Comment by MrCompost** [comment]
Right er... one thing I would like is for light levels to affect the spawning of hostile mobs, so the player can place down torches and it's all good. As for spawn rates and such...
Anglers - fine as they are
Blood Snails - just need to be more common
Dragonflies - just need to be more common
Fireflies - need to be A LOT more common. They should also sometimes gen in huge swarms for want of a better word. That looks really pretty.
Mire Snails - just need to be more common
Blood Snails - just need to be more common
Silt Crabs - spawn quite often on Silt.
Sludges - less common. Also see the Sludge issue.
Sporelings - spawn on Shelf Fungus in groups
Swamp Hags - turn these bastards down a bit, they are everywhere
Tar Beasts - They are only supposed to spawn in Tar Pools, which we don't have yet. As I said in the Tar Beast issue, we may as well just remove them for now. 
Wights - they shouldn't spawn in groups, and they should be more common.

**Comment by MrCompost** [comment]
Meh, I'll close this for now.
