### ISSUE TITLE
The Betweenlands and PVJ cause maximum id range exceeded during client launch on large modpacks (FIXED)

### ISSUE THREAD

**Issue by daydream-adrift** [TheCyberBrick/The-Betweenlands#1379]
Forge ver. 14.23.5.2859. Betweenlands ver. 3.9.6. Singleplayer game version 1.12.2. My modpack is custom made, the list of mods are included in the crash report which I will include in the gist link below:

https://gist.github.com/daydream-adrift/66722ae9bbc9a8fcd8a69744e1646e1e

Description of the problem:
The game crashes whenever both The Betweenlands and Project Vibrant Journeys are installed. This crash occurs during the mod loading process and is reported by Vanilla Fix. I've tried looking into blacklisting Betweenlands in Project Vibrant Journeys' config file but on it's CurseForge page, in the comments I found the developer report that the blacklist code was written badly and they won't be fixing it because they've stopped development for that version (1.12.2).

I hope you can discover what the conflict is and if there's a potential fix on your end. thank you for your time,

~daydream-adrift.

EDIT: A side note I forgot to mention is that in some instances (I've done this multiple times) Vanilla Fix will root out Galacticraft first and then, after disabling Galacticraft, it will blame OMlib and Open Modular Turrets but will always come back to PVJ when disabling them. The only thing that will stop the crash from there is disabling either Betweenlands or PVJ. Just so there's no confusion I am currently able to run those other mods with either Betweenlands or PVJ installed.

Another thing I forgot is that these two mods will work with each other only up to a certain point, that being when I install a certain amount of mods, which is when these other mods (Galacticraft, OMlib and OMT) are mentioned by Vanilla Fix but will stop mentioning them when either of the two mods in question (PVJ or Betweenlands) are removed.

I believe that's all I needed to add, if I remember something else I'll add it here.

**Comment by Bendoo123** [comment]
Invalid id range exceeded means your game is trying to register more items than it can. Install JustEnoughIDs to remove the limit and fix the crash

**Comment by daydream-adrift** [comment]
> Invalid id range exceeded means your game is trying to register more items than it can. Install JustEnoughIDs to remove the limit and fix the crash

Hey Bendoo, I tried what you said and it worked! Thank you for extending the help~

–daydream-adrift
