### ISSUE TITLE
The leaves should drop saplings

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#138]
Atm they just drop the leaf block.

**Comment by TripleHeadedSheep** [comment]
And shouldn't decay when place by a player or placed by generation at all

**Comment by vadis365** [comment]
They have to decay on generation or you will have lots of crappy leaves floating around once the wood is gone....
Saplings is a different thing - but I'll look in to it later.

**Comment by TripleHeadedSheep** [comment]
Alright, makes sense. But still, when placed by the player...
