### ISSUE TITLE
death animation lag

### ISSUE THREAD

**Issue by ralseilii** [TheCyberBrick/The-Betweenlands#1381]
In the latest version of Betweenlands, playing this mod alone poses no issues. However, when other mods are installed (any mod—I've tried in several modpacks, and the issue only arises when Betweenlands is added), killing multiple creatures at once causes a delay in the death animation. Specifically, the creatures die one by one instead of all at once. When I remove Betweenlands, the death animations return to normal. It's worth mentioning that triggering creature death using redstone (for example, using redstone to trigger TNT and kill a zombie) doesn't result in this delay. But when player-induced actions lead to creature death (for example, igniting TNT to kill a zombie using flint and steel, or killing a zombie with a sword), the delay occurs. Is this a bug in Betweenlands? It would be greatly appreciated if this could be fixed for modpack creators. If it isn't a bug, I apologize for any inconvenience.

**Comment by Rimusp** [comment]
Im pretty sure im having the same issue.
Every time i kill any mob the tps spikes up and the world stops for like 2 seconds after and then resumes.

**Comment by JoshieGemFinder** [comment]
@ralseilii, could you provide your forge version and some mods that this occurs with? Currently there's not enough information to properly debug and test this issue.

@Rimusp you might be allocating too much memory which is causing the garbage collector to freeze up, try allocating less minimum/maximum memory, if the problem persists, create a new issue of your own.

**Comment by ralseilii** [comment]
@JoshieGemFinder This issue is not caused by a specific mod but rather, once the modpack becomes substantial in size (for example, a modpack with 200-300 mods), as long as the "Betweenlands" mod is included, there will be a delay in death animations. This problem does not occur when adding the "Betweenlands" mod to the original game or a small-scale modpack (with just a few dozen mods). This phenomenon is not very friendly to creators of large modpacks.

**Comment by ralseilii** [comment]
and i used CensoredASM but I think that is not main reason, because when delete the betweenlands in any large modpack the death animation becomes normal.

**Comment by JoshieGemFinder** [comment]
Could you provide a modpack that this occurs with? Collecting 200-300 mods that don't interact with betweenlands in a way that causes other issues is not a trivial task, and having an example would really make debugging this easier. This may also be an issue that only occurs on certain forge versions, so providing that would also be useful to the process.

**Comment by ralseilii** [comment]
i think i will post modpack sometime later

**Comment by ralseilii** [comment]
some issues happened when reproducing the issue but still haven't solved.I will do it later

**Comment by ralseilii** [comment]
i think i find it ,it is caused by Quark and i changed some Quark config settings. Using 1.12.2-Forge_14.23.5.2860

**Comment by Rimusp** [comment]
Would be Nice if you could tell us which config option it is that you changed

**Comment by ralseilii** [comment]
I can't accurately say which one i changed because using the default config causes lag. I just copied the RLCraft Quark config, and the lag disappeared.

**Comment by Rimusp** [comment]
For anyone else having this issue: Use the ROTN edition atleast for me it fixes the issue https://www.curseforge.com/minecraft/mc-mods/quark-rotn-edition
