### ISSUE TITLE
Game crashes with Alfheim Lighting Engine

### ISSUE THREAD

**Issue by victorguima** [TheCyberBrick/The-Betweenlands#1390]
Game immediately crashes when loading up minecraft 1.12.2, on forge v14.23.5.2859, this is the mod list:

TheBetweenlands-3.9.6-universal.jar
Alfheim-1.0.2.jar
!Red-Core-MC-1.7-1.12-0.5-Dev-3.jar

Specification:
OS: Windows 10
CPU: Ryzen 5 5500
GPU: Radeon RX 5500 XT
RAM Allocated: 8GB
No crash report is generated by the game.

**Comment by victorguima** [comment]
Crash also happens with Hesperus, but not with the original [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge)

**Comment by JoshieGemFinder** [comment]
This is almost certainly due to The Betweenlands's shaders, try disabling them (if necessary, through its config file directly) and try again. I'll look into this a bit more when I have time and will report here if I find anything.

**Comment by victorguima** [comment]
Apparently I was missing a dependency for that mod, MixinBooter, and enabling it fixed the issue.
