### ISSUE TITLE
Exit boat bug

### ISSUE THREAD

**Issue by alvaromagu** [TheCyberBrick/The-Betweenlands#1395]
#### Minecraft version:
1.12.2

#### Betweenlands version:
3.9.6

#### Forge version:
8.0.99.99

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
voxelmap
jei
thebetweenlands

## Link to full crash log
[Link](https://gist.github.com/aIv4ro/8ba41660ab867e5468919372bd3ee6ab)

#### How to reproduce:
1. Get on the boat
2. Get out the boat

**Comment by SeriousCreeper** [comment]
That's a crash with voxelmap, probably should report it to them first

**Comment by alvaromagu** [comment]
Oh!, thanks for help, i will install another
