### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by hl2jeep** [TheCyberBrick/The-Betweenlands#1400]
very little activity for a year or more, the last update was 10 months ago with no commits being made on the main branch since, the only other commit i could find is 7 months old on the 1.12-bushes branch. Is the project abandoned or shelved?

**Comment by JoshieGemFinder** [comment]
Not abandoned, it's just that most of the team have things going on in real life or are working on other projects. Development will start up again sooner or later.

There's still a somewhat active community on the discord, if you want more information you can go there and probably ask the devs more directly.
