### ISSUE TITLE
Silt Crab tweaks

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#142]
I added a little snip sound effect for when they attack. Also sometimes they will go up to the player and not hit them, or hit them twice. Silt also slows them down, which is a problem since that's where they spawn. They also cant climb up mud blocks, so they tend to get stuck in the water.

**Comment by PCAwesomeness** [comment]
1: Yeah.

2: Why not make them able to walk freely on silt?

3: You could give them the mud walking capabilities that you did to the 1st 5 mobs.

**Comment by MrCompost** [comment]
Right, well now they seem to like swimming rapidly  through solid blocks, spinning around on the spot and floating in the middle of the water. Works a bit better now though :P

**Comment by MrCompost** [comment]
I'll just close this
