### ISSUE TITLE
Rain?

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#143]
It started raining but... it didn't. I dunno, see here - http://imgur.com/SFRzaTu
Weird, it shouldn't rain at all.

**Comment by quantumdude836** [comment]
Looks like it happens when "level.dat" has "raining" set to 1 when the world is loaded.

**Comment by MrCompost** [comment]
Ah, I see. I created a new world.

**Comment by quantumdude836** [comment]
Now fixed
