### ISSUE TITLE
Lurkers =)

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#147]
These big fellas swim around slowly in water, minding their own business, until you attack them. At that point they are like pigmen, all of them will become hostile. They also swim faster when attacking. They will crawl onto land to attack, but aren't as fast. They hunt anglers. Being big and strong, they have a strong hit and a very strong knockback, but they only have as much health as, say, a Zombie. Maybe a bit more. They drop Lurker skin. They spawn in groups in Deep Waters and Patchy Islands.

**Comment by TripleHeadedSheep** [comment]
I know the spawning isn't done yet, but just to throw it out there. They should be way less common than they currently are ;)
I'm not sure if they should spawn in Deep Waters. Since they live an amphibian life, it would be weird for them to live in an area where they can't easily crawl onto land

**Comment by MrCompost** [comment]
The Lurker is almost done now, it just needs to be neutral like pigmen and it needs an animation for walking on land. Also there is a slight issue where it's head flips around weirdly.

**Comment by MrCompost** [comment]
Sorry, I think I gotta reopen this one; their AI is a bit wonky. They seem to have problems with their pathfinding (I guess... er... some technical term), especially when attacking enemies. When I attacked one they didn't even come towards me, though I think it looked like they were attempting to. They do attack dragonflies and anglers, though again the way they try to attack is a bit off.

**Comment by pau101** [comment]
Were you in creative when you tried to get a lurker to attack you?

**Comment by MrCompost** [comment]
Nope, survival.

**Comment by PCAwesomeness** [comment]
How functional is it now?

**Comment by TheCyberBrick** [comment]
Seems pretty functional to me, but I'm not sure if the bugs Oli mentioned are already fixed

**Comment by MrCompost** [comment]
I think it's done now, it seems to work great for me.
