### ISSUE TITLE
Giant Bulb Capped Mushroom

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#148]
These things! https://pbs.twimg.com/media/CEKBe_hWAAIzj0o.png
Made up of Bulb Capped Mushroom Stalk, Bulb Capped Mushroom Cap and the small Bulb Capped Mushrooms which gen around it. The two new blocks act like vanilla mushroom blocks, and drop Bulb Capped Mushrooms. They also glow, giving off as much light as glowstone. They gen in the patchy islands biome. That's it I think.

**Comment by imdutch21** [comment]
do we already have the textures for these blocks?

**Comment by TheCyberBrick** [comment]
Yes, they are already on github:
https://github.com/TheCyberBrick/The-Betweenlands/blob/master/resources/assets/thebetweenlands/textures/blocks/bulbCappedShroomStalk1.png
https://github.com/TheCyberBrick/The-Betweenlands/blob/master/resources/assets/thebetweenlands/textures/blocks/bulbCappedShroomStalk2.png
https://github.com/TheCyberBrick/The-Betweenlands/blob/master/resources/assets/thebetweenlands/textures/blocks/bulbCappedShroomCap.png
