### ISSUE TITLE
Redo Rotten Logs

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#149]
Ok, so the model didn't work out. Instead it will be made up of multiple regular blocks. The textures are all done. Drops Rotten Bark as always.

**Comment by TripleHeadedSheep** [comment]
Well this takes longer then necessary :P

**Comment by MrCompost** [comment]
Yup, it should be really easy as well XD

**Comment by TripleHeadedSheep** [comment]
Done, they gen in the Marshes.
