### ISSUE TITLE
Purple Rain Trees

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#150]
I think it should look roughly like this http://data2.whicdn.com/images/60253650/original.jpg
Just google purple rain tree for more. 
It should be pretty tall, like the giant Weedwood trees, but the trunk should be thinner, perhaps 4x4 at the base of the tree and then thinner as it gets higher, with many branches fanning out. It is, of course, made mainly of Purple Rain Logs. At the top there are small clumps of Purple Rain Leaves. Not too many, it should only have a thin but broad canopy like in the picture. Dave's Sap tree does that well, but on a much smaller scale. It would also be cool if some bits hung down, kinda like in this picture I found - http://static.planetminecraft.com/files/resource_media/screenshot/1144/2011-11-06_180727_781303.jpg
It's crappy, I know, but you get the idea. The leaf blocks give off purple leaf particles which fall downwards to the ground, and also drop Purple Rain Saplings. Dangling down from the leaves are Purple Hangers, which act just like the Hangers we already have. The hangers that are nearest to the top of the canopy have flowers growing on them, and when broken drop Purple Rain Flowers. Lastly, Purple Rain Leaves cover the ground beneath the tree, just like trees in the swamplands biome. 
I think that's it. Just ask if you need anything else.

This is a good picture too - http://hdwallpapers.cat/wallpaper/purple_rain_wisteria_tree_blossoms_japan_hd-wallpaper-1770540.jpg

**Comment by MrCompost** [comment]
Nearly done! Now we just need to do the following - 
Have them gen in the world
Fallen purple leaves on the ground beneath the tree
Have the leaves drop purple leaf particles and LOTS OF THEM
Have the flowering hangers drop the seeds
Have the sapling grow into the tree if that's not already done

**Comment by TripleHeadedSheep** [comment]
Got the mimplemented, Sam, Dave and I agreed they look terrible, so we removed them until we come up with a good replacement.
Closing this for now
