### ISSUE TITLE
Mossy Cragrock

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#153]
Cragrock should have moss on it, just like grass blocks work, except this moss goes two blocks 'deep' instead of one.

Example with the textures:
http://puu.sh/i7x3C/8993a326fe.png

So you have a normal cragrock, a somewhat mossy cragrock and a very mossy cragrock on top.
The textures are already commited.

**Comment by MrCompost** [comment]
Happy Len? :)

**Comment by TripleHeadedSheep** [comment]
So happy, my butthole even smiles

**Comment by TheCyberBrick** [comment]
Your butthole smile is contagious, it made my butthole smile as well ( ͡° ͜ʖ ͡°)

**Comment by MrCompost** [comment]
What the hell?
