### ISSUE TITLE
Druid Altar changes/additions

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#16]
So, me and Sam have discussed some things, and we think this is a good idea.
When you put all of the different talisman pieces in the GUI, it closes itself after a second or two so that the player can see the Altar clearly.
There is then an animation where the different pieces all come together to form the whole swamp talisman, and the light beams used when the enderdragon dies shine out. You can also add some other fancy particles if you want, you guys can do what you want really. 
'Altar.ogg' plays when this happens too, and the animation should last about 13 seconds or so. 
After that, when you right click on the GUI again, the talisman pieces will all be gone and the swamp talisman will be in the centre. 
Whilst the animation is happening, you cannot right click on the Altar.

Sam can handle most rendering and such, and Dave will have to help out with the packet stuff.

**Comment by SanAndreasP** [comment]
Question: Why need a GUI at all? Couldn't you just throw the pieces towards the altar like in Botania?

**Comment by vadis365** [comment]
Some of the coding for this is a bit wonky - The packet isn't really necessary - it could all be done from the container class and sent to the tile. I'll play with it later on tonight and fix this as the altar itself is kind of broken now. It will give you an infinite dupe on the talisman item.
We could remove the GUI I guess - but Oli wanted it originally.
It is a bit confusing if there are no issues to follow/they contradict each other.
Anything that has changed should be updated or closed and a new issue posted please. :)

**Comment by TheCyberBrick** [comment]
The dupe is fixed and I haven't had any issues so far. I don't see how you would want to do it without a packet though. What the packets currently do:

**Comment by vadis365** [comment]
Sam has pretty much finished all this (and lots more besides).
Closing and making a new issue for the runestone stuffs. :)
