### ISSUE TITLE
Rubber Stuffs

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#161]
Len needs to make the model for the bucket hanging on the tree.
Right clicking a Weedwood Bucket onto a Rubber Tree Log places it. If you come back after 15 minutes, it is filled with liquid rubber. Place the bucket in a furnace and you get a Ball Of Rubber and the empty bucket back. The balls of rubber can be crafted into rubber boots, which prevents the player from sinking into mud, and also makes blocks like silt have no slowness effect. Rubber Blocks can be crafted too, and they act basically just like slime blocks do.

**Comment by TripleHeadedSheep** [comment]
Model is has been made weeks ago, you slowpoke ;)

**Comment by MrCompost** [comment]
*was

**Comment by TheCyberBrick** [comment]
Rubber tap is finished

**Comment by TheCyberBrick** [comment]
This is pretty much done, only the rubber block is left
