### ISSUE TITLE
Ambient particles (insects)

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#162]
The idea is to add a few particle effects that could enhance the overall ambience greatly.
We have two types of moths, a fly, a mosquito and a water beetle. They have different frames to mimic animation.

Moths: spawn basically anywhere near trees or plants

Flies: spawn near certain plants (carniverous) or decayed/dead stuff. And maybe just to annoy you, occasionally around your head ;)

Mosquitos: spawn mostly above water, preferable more above shallow water than deep water. Very common in marhes.

Water beetles: well yeah... in the water.

Note that these particles dont need to be very common (especially to not ruïn performance too much)
The textures are already comitted if I'm correct. Otherwise just lemme know and I'll send them
_____________________________________________________________________________
EDIT: Need to fix that water stuff, waterbeetles dont fly, moths dont swim and all

**Comment by TheCyberBrick** [comment]
"especially to not ruïn performance too much"
Performance with particles is not really a concern if done right, you could have hundreds and not drop more than 2 frames

**Comment by MrCompost** [comment]
They aren't committed yet, and I should also add that they are animated.

**Comment by PCAwesomeness** [comment]
Why would they be particles?

**Comment by TripleHeadedSheep** [comment]
Already stated that Oli, but yeah ^^

PCAwesomeness, due to their size and the fact that they're 100% aesthetic, it would be better to have them as small particles. They aren't really worth making a mob.

**Comment by PCAwesomeness** [comment]
I see.

**Comment by TheCyberBrick** [comment]
I've added all the particles but the spawn rates need some testing and tweaking

**Comment by MrCompost** [comment]
I think we can close this now, they look great to me and we can easily add more if we want.

**Comment by TripleHeadedSheep** [comment]
Opened it, just because of the water glitchy bug. That needs to be fixed

**Comment by MrCompost** [comment]
Seems fixed to me.
