### ISSUE TITLE
Dragonflies have invisible wings

### ISSUE THREAD

**Issue by PCAwesomeness** [TheCyberBrick/The-Betweenlands#164]
When viewed on Damage Indicators, their wings can still be seen, but otherwise, you can't see them.

**Comment by pau101** [comment]
Do you have any other mods installed? I can't reproduce the issue.

**Comment by PCAwesomeness** [comment]
On one instance, I have ThaumCraft, Mowzie's Mobs, Aqua Creepers, and Twilight Forest installed alongside the Betweenlands. On another, I have the Aether and the Betweenlands.

In both instances, the dragonflies have invisible wings that could only be seen in their Damage Indicators portrait.

**Comment by pau101** [comment]
So even just having the Betweenlands installed you can't see their wings? What version of Forge are you using?
