### ISSUE TITLE
Textures for herblore type stuff

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#171]
These are largely just ideas that will be worked on.
EDIT - A LOT of work.

Cattail - Cattail Head - Cattail Head Torch or something, couldn't find any genuine medicinal uses
Cardinal Flower - Cardinal Flower Petals - Cardinal Flower Tea (cures sickness, perhaps some kinds of foods have a chance of making you sick)
Sundew - Sundew Gland - Some sort of medicine, apparently it treats things like  asthma, coughs, lung infections, and stomach ulcers.
Pitcher Plant - Pitcher Plant Leaf - A medicine that cures digestive issues, could allow the player to eat certain types of food again after becoming fed up of eating them when we add that.
Bog Bean - Bog Bean Fruit - This is another one that deals with digestive issues. Not sure what to do with all of these.
Golden Club - Golden Club Flower - Couldn't find a use, we'll probably have to make something up
Marsh Marigold - Marsh Marigold Flower - Used to treat a lot of things namely sores and general pains.
Coral - No idea, but apparently it helps to cure cancer so hurray.
Water Flower - Er...
Venus Fly Trap - Cancer again?!
Arrow Arum - This shit messes you up if you eat it so I don't know.
Buttonbush - Another supposed "cure-all".
Marsh Hibiscus - Well, apparently it encourages menstrual flow but er... Anyway, its another "cure-all".
Pickerel Weed - Only use I could find is for food.
Marsh Mallow - Among other things, it is actually used to cure insect bites so that could be useful.
Milkweed - Traditionally used to cure warts, but this one is another "cure-all".
Iris - Cures "dropsy", whatever the hell that is.
Blue Eyed Grass - Indigestion and stomach pain again.
Boneset - Well it cures fever but it also makes you piss a lot, sweat a lot, shit a lot and vomit a lot. Worth it?
Bottle brush grass - Couldn't find anything.

Uuuuuughh.....

**Comment by MrCompost** [comment]
When looking stuff up, I noticed that a lot of these plants are actually used for fuel, so we could actually have use them instead of sulphur. It would probably be more interesting actually.

**Comment by TripleHeadedSheep** [comment]
Oli, your issues are unclear and a mess... Since when are textures equal to properties?
And besides, the list is unclear, the properties can just be made up and dont need to corrolate with RL properties.
Lastly, it is mostly unclear because you put too much opinion in it. Adding things like 'uuuuuughh....' and 'Cancer again?!' dont add anything

**Comment by TripleHeadedSheep** [comment]
Closing it, it is useless. Will make a new list soon
