### ISSUE TITLE
New (additional) textures for rune stones

### ISSUE THREAD

**Issue by vadis365** [TheCyberBrick/The-Betweenlands#18]
Whilst the altar is crafting, we have made it so the rune stone textures change to an animated texture - see pngs called druidStone1Active - druidStone5Active.
The bitmaps are 16 x 128.
The idea was to make them change colour whilst the altar is crafting and give an even more epic effect.
Sort of like a smooth transition from in-active to active and back again - like normal -> red glow and back. I haven't touched the textures as I thought Oli would revel in making them exactly as he wants :).
All the code is done and ready for some MrCompost texture magic.

**Comment by MrCompost** [comment]
This was done, but I'm not sure what to do with it. We may remove it.
