### ISSUE TITLE
Ore blocks/items

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#19]
Sulfur Ore - basically just the BL version of coal. Drops 1 Sulfur item.
Octine Ore - BL version of iron. The ore has flame particles and gives off a small amount of light. Can be smelted into Octine Ingots.
Valonite - BL version of diamond, thought it isn't quite as rare. Drops Valonite Shards.

**Comment by vadis365** [comment]
Ok, I have added all the ore blocks including the gems.
I will add particles and smelting recipes later on:
What I would like is a list for each block's:

hardness - this will effect mining time
blast resistance - explosion proofing
pickaxe mining level (like stone, iron,  diamond etc.)
if the ore gives xp when mined (like coal)

If working it out is a bit tricky - just tell me vanilla equivalents (like iron, coal, diamond etc.)

Cheers
Me. ;P

**Comment by vadis365** [comment]
Done.
