### ISSUE TITLE
Dark Druid Mob

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#2]
Needs model/texture/sounds
Has glowing texture
Attacks by lifting the player into the air whilst raising their arms slowly, as if by magic, and then throwing them backwards. They also give off black particles whilst doing this.
Drops a random Swamp Talisman Piece.
They spawn around the Druid Circles and dont stray far from them (Altar can act as the spawn point?)
They can teleport short distances, like enderman. When they do so, hey create a puff of smoke particles.

**Comment by vadis365** [comment]
Got most of this working by fixing the old code :)
The Entity class is a bit of a mess (sorry previous coder)
and will need to be changed to add teleporting.
The particle handling is also a bit derpy - I'll fix it all tonight probably.

**Comment by vadis365** [comment]
*particles are sorted
teleporting will be added soon.

**Comment by vadis365** [comment]
Druid now Teleports to player etc..
Closing so a new issue can be opened if tweaks are needed.
