### ISSUE TITLE
Betweenstone Furnace

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#20]
Acts like a regular furnace, but gives off yellow particles (the particles are the same as redstone's)

**Comment by vadis365** [comment]
Made this to be like a vanilla furnace that also burns sulfur....... YAWN!
Needs to be made more 'special' - Maybe smelt 2 things at once like a double furnace?

**Comment by vadis365** [comment]
OK - just had a better idea - will need a couple of new textures...
Take a BL furnace (they can stay as they are) and craft with another one to get a dual furnace.
Still only takes up one block but is a dual furnace.
Maybe add something BL to the recipe so it isn't just plonking 2 furnaces in a crafting grid tho'....

**Comment by MrCompost** [comment]
Hmmm, I'm not sure. Its supposed to just be for aesthetics. I can't really think of a  good special use, since things are supposed to be harder.

**Comment by MrCompost** [comment]
That does sound interesting though. Why not have two furnaces though?

**Comment by vadis365** [comment]
means it is more compact and not just another thing that is already in vanilla

**Comment by MrCompost** [comment]
True. I'll have to think about it though tbh.

**Comment by vadis365** [comment]
I'll make it and remove it if you don't like it :P

**Comment by MrCompost** [comment]
Well if you make it, I probably wont ask you to remove it unless its really awful :P
Which it wont be. Do you what you want man!

**Comment by vadis365** [comment]
Made a dual furnace - I think the gui needs a little re-positioning on the slots - but works.
Please try it.

**Comment by MrCompost** [comment]
Yeah I did, works well!
