### ISSUE TITLE
Weedwood Crafting Table

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#21]
Acts like a regular crafting table. 
If I remember correctly, Sam added a feature in the original version where it renders what you are crafting on the grid, but I'm not sure exactly how this worked. He can add it if he wants though.

**Comment by SanAndreasP** [comment]
I may be able to do that

**Comment by SanAndreasP** [comment]
It would act like a Crafting Station from Tinkers Construct where the content of it would stay in there when left.
I dunno if the content can be viewed by other players then, though (like the TiC CS) or act like an ender chest...

**Comment by vadis365** [comment]
Awesome.
ganymedes01 does it for gany's surface mod as well

**Comment by MrCompost** [comment]
Just found this old screenshot. http://pbs.twimg.com/media/BAlX9MpCEAAnp5v.png
