### ISSUE TITLE
Weedwood/Bark/Logs

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#23]
The huge trees' trunks are made of up two blocks - Weedwood and Weedwood Bark. 
Weedwood Bark is tough and takes a while to break. It has no use other that for aesthetics. 
The Weedwood is softer and breaks faster. 
Weedwood logs are from small weedwood trees. They act like regular logs. 

Unlike the old weedwood block which required a bunch of textures, these only require 3.

**Comment by vadis365** [comment]
Done
