### ISSUE TITLE
Tools/Armour 

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#26]
~~Weedwood Tools - like regular wood tools.
Octine Tools - Has the same stats as gold tools. Octine Swords have a 1/4 chance of lighting mobs of fire when hit.
Valonite Tools - Same stats as diamond.~~

Octine Armour - Same stats as iron armour. Fire does not harm the player when worn.
Valonite Armor - Same stats as diamond armour.

**Comment by vadis365** [comment]
sigh, crossed out done stuff (eventually)

**Comment by vadis365** [comment]
Done. The event handler on the octine armour is a bit derpy tho' - will need to be changed...
