### ISSUE TITLE
Hangers 

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#27]

**Comment by vadis365** [comment]
What do these do and how do they do it?

**Comment by MrCompost** [comment]
They hang off of the leaves on the giant weedwood trees. There is a type that has seeds on them, but that's for a future update. You can see them in this old video a fan made. https://www.youtube.com/watch?v=gAMAbfZDLWg

**Comment by vadis365** [comment]
Yeah, I get what they look like - but what do they do?
Do they grow? Do they turn in to seeded ones after a time? etc....

**Comment by vadis365** [comment]
Well, They should be different to this....
https://www.youtube.com/watch?v=QlIS7wQ2rHU
