### ISSUE TITLE
Giant Weedwood Tree

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#28]
Generate in any of the 4 basic biomes we have added.
Some can be found quite close together, forming a big (mostly) closed canopy, and others further apart.

I'd like them to look roughly like the old BL trees. This time though, Weedwood Bark generates on the outside and Weedwood on the inside.

**Comment by vadis365** [comment]
kay... started to work on this - will take a while to get it 'just right'.

**Comment by vadis365** [comment]
Progress - update.
Got the bulk of this done. Need to add a bit more randomness and the shelf fungus/hangars.
Try with the test item on a super flat world - it takes a short while to gen - but in game it would be ok.

**Comment by MrCompost** [comment]
Looks fantastic! Do you think you could have more size variation if that's possible, so sometimes they can be almost stupid big?

**Comment by MrCompost** [comment]
Nearly done
