### ISSUE TITLE
Weedwood Tree

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#29]
These trees use Weedwood logs instead of the Weedwood/Weedwood Bark. 
They are much smaller than Giant weedwood trees, as you would expect, being around the same size as a regular tree.
You can do whatever you want with these for their generation, though it should be quite simple.

**Comment by vadis365** [comment]
Worked out a basic plan for the shape/size.
Will add random variations based on my design - will make tonight (after work).
All the wood and leaves/saplings are added so, should be easy enough to make something that looks good now :)

**Comment by vadis365** [comment]
Done - all bar tweaks.
