### ISSUE TITLE
Altar

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#3]
Needs model/texture (use code from Erebus)
Has animation - rocks in middle float slowly up and down
Cyan particles given off in the middle
Has a glowing texture
Cannot be broken - like bedrock
Generates in the middle of druid circles
When right clicked, alter GUI is displayed.
Swamp Talisman is crafted by putting every different Swamp Talisman piece into the GUI.

NOTE - 'Altar.ogg' is not for this.

**Comment by vadis365** [comment]
Outdated issue this is all done.
