### ISSUE TITLE
Naturally generating blocks for terrain gen

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#312]
**GENERAL TERRAIN**
- [x] Betweenlands Bedrock
- [x] Betweenstone
- [x] Dead Grass
- [x] Limestone
- [x] Cragrock (plus 2 mossy types)
- [x] Mud
- [x] Pistone
- [x] Silt
- [x] Sludgy Dirt
- [x] Swamp Dirt
- [x] Swamp Grass

**ORES**
- [x] Life Crystal Ore
- [x] Octine Ore
- [x] Middle Gem Ore (three types)
- [x] Scabyst Ore
- [x] Slimy Bone Ore
- [x] Sulfur Ore 
- [x] Syrmorite Ore
- [x] Valonite Ore

**LIQUIDS**
- [x] Stagnant Water
- [x] Swamp Water
- [x] Tar

**NATURAL PLANKS AND FUNGI**
- [x] Algae
- [x] Arrow Arum
- [x] Black Hat Mushroom:
- [x] Bladderwort
- [x] Blue Eyed Grass
- [x] Blue Iris
- [x] Bog Bean
- [x] Boneset
- [x] Bottle Brush Grass
- [x] Broomsedge
- [x] Bulb-Capped Mushroom
- [x] Bulb-Capped Mushroom Stalk
- [x] Bulb-Capped Mushroom Top
- [x] Buttonbush
- [x] Cardinal Flower
- [x] Cattail
- [x] Cave Grass
- [x] Cave Moss
- [x] Copper Iris
- [x] Dead Weedwood Bush
- [x] Deep Water Coral
- [x] Double Swamp Tallgrass
- [x] Fallen Leaves
- [x] Flathead Mushroom
- [x] Golden Club
- [x] Hanger
- [x] Hollow Log
- [x] Lichen
- [x] Marsh Hibiscus
- [x] Marsh Mallow
- [x] Marsh Marigolds
- [x] Milkweed
- [x] Mire Coral
- [x] Moss
- [x] Nettle
- [x] Peat
- [x] Pickerel Weed
- [x] Phragmites
- [x] Pitcher Plant
- [x] Poison Ivy
- [x] Root
- [x] Rotten Weedwood Bark
- [x] Rubber Tree Leaves
- [x] Rubber Tree Log
- [x] Rubber Tree Sapling
- [x] Sap Tree Leaves
- [x] Sap Tree Sapling
- [x] Shelf Fungus
- [x] Shoots
- [x] Sludgecreep
- [x] Soft Rush
- [x] Sundew
- [x] Swamp Kelp
- [x] Swamp Plant
- [x] Swamp Reed
- [x] Swamp Tallgrass
- [x] Tall Cattail
- [x] Thorns
- [x] Venus Fly Trap
- [x] Volarpad
- [x] Water Weeds
- [x] Weedwood
- [x] Weedwood Bark
- [x] Weedwood Bush
- [x] Weedwood Leaves
- [x] Weedwood Sapling
- [x] Weeping Blue

**STUFF FOUND IN STRUCTURES**
- [x] Angry Betweenstone
- [x] Betweenstone Bricks
- [x] Betweenstone Bricks Mirage
- [x] Betweenstone Pillar
- [x] Betweenstone Tiles
- [x] Betweenlands Spawner
- [x] Chiselled Betweenstone 
- [x] Chiselled Cragrock
- [x] Chiselled Limestone
- [x] Chiselled Pitstone
- [x] Cracked Betweenstone Brick
- [x] Cracked Betweenstone Tiles
- [x] Cragrock Bricks
- [x] Cragrock Pillar
- [x] Cragrock Tiles
- [x] Energy Barrier
- [x] Gecko Cage
- [x] Glowing Betweenstone Tile
- [x] Glowing Smooth Cragrock
- [x] Item Cage
- [x] Possessed Block
- [x] Pot of Chance
- [x] Spike Trap
- [x] Limestone Bricks
- [x] Limestone Pillar
- [x] Limestone Tiles
- [x] Mossy Betweenstone Bricks
- [x] Mossy Betweenstone Tiles
- [x] Mossy Smooth Betweenstone
- [x] Mud Bricks
- [x] Mud Flower Pot
- [x] Octine Block
- [x] Pitstone Bricks
- [x] Pitstone Pillar
- [x] Pitstone Tiles
- [x] Polished Limestone
- [x] Betweenstone Brick Slab
- [x] Cragrock Brick Slab
- [x] Mud Brick Slab
- [x] Pitstone Brick Slab
- [x] Smooth Cragrock Slab
- [x] Weedwood Plank Slab
- [x] Smooth Betweenstone
- [x] Smooth Cragrock
- [x] Betweenstone Brick Stairs
- [x] Cracked Betweenstone Brick Stairs
- [x] Mossy Betweenstone Brick Stairs
- [x] Mossy Smooth Betweenstone Stairs
- [x] Cragrock Brick Stairs
- [x] Mud Brick Stairs
- [x] Smooth Cragrock Stairs
- [x] Pitstone Cragrock Stairs
- [x] Syrmorite Block
- [x] Valonite Block
- [x] Betweenstone Brick Wall
- [x] Cracked Betweenstone Brick Wall
- [x] Mossy Betweenstone Brick Wall
- [x] Cragrock Brick Wall
- [x] Pot Of Chance
- [x] Pitstone Brick Wall
- [x] Smooth Betweenstone Wall
- [x] Smooth Cragrock Wall
- [x] Weak Betweenstone Tiles
- [x] Weak Mossy Betweenstone Tiles
- [x] Weak Polished Limestone
- [x] Weedwood Chest
- [x] Weedwood Sign

**OTHER GEN STUFF**
- [x] Green/Orange Dentrothyst
- [x] Solid Tar
- [x] Stalactite
- [x] Will o' the Wisp

**Comment by TheCyberBrick** [comment]
All done :D
