### ISSUE TITLE
Day/Night Cycle

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#314]
Since we have decided to add some sort of day/night cycle Sam and I discussed a bit about the mechanics. Here is what we've got:

**Nighttime:**
- Will have the duration of 2 Overworld nights
- Could have a rare occasion where it has the duration of 3 Overworld nights
- Duration cannot be affected by the player

**Daytime:**
- Duration will vary between 0.125 and 1 Overworld day
- Duration can be extended to 1.5 of an Overworld day by the player
- Will never be as bright as Overworld days, more like a twilight zone

Maybe we could add some extra features to the daytime, like decay being slowed down or crops growing faster. I have no idea if that is realisable.
Furthermore, we could look at mob behaviour during day or night.

**Extending:**
- Extending the daytime can be done with a block that requires the (very rare) Pyrad Staff
- Players can extend the day up to 1.5 of an Overworld Day
- Extending requires a certain fuel (uncertain what that could be right now)
- The 'extending block' will give some visual feedback about the current duration of the day and by how much units it can still be extended
  _______________________________________________________________________________
  There was also something being mentioned about a moon and moon cycle. I think Oli knows more about that.

**Comment by imdutch21** [comment]
as a fuel maybe use some of the herblore stuff? Something like the repeller does

**Comment by TheCyberBrick** [comment]
@imdutch21 yup, that was the initial idea

**Comment by TripleHeadedSheep** [comment]
@imdutch21 @TheCyberBrick 
Yeah, although I'm not really convinced something from herblore should affect the day/night cycle... Doesn't seem connected to it somehow

**Comment by vadis365** [comment]
This is a thing in another form atm in 1.12.2
