### ISSUE TITLE
Balkons Weapon Mod and Between Lands crash

### ISSUE THREAD

**Issue by godemperoroftheworld** [TheCyberBrick/The-Betweenlands#321]
Heya, upon loading a world with the two aformentioned mods I get this crash:
http://pastebin.com/N5ePw18v

Seems to be due to entity ID conflict, but neither your mod nor Balkons seems to have a config option for changing Entity IDs.

Thanks!

**Comment by TheCyberBrick** [comment]
~~It seems that you have the Betweenlands debug mode enabled. Please disable it in the config and then try again.~~ Never mind that.
Either way, Balkons Weapon Mod adds a datawatcher to the player entity which is not advisable and leads to issues sooner or later. We can't really fix this on our side.

Edit: Oh and please provide the full crash log and not only the stack trace. The rest also contains important data.

**Comment by godemperoroftheworld** [comment]
Allright, here it is:
http://pastebin.com/Jz9Na32z

**Comment by TheCyberBrick** [comment]
As mentioned before, this is most likely an issue of Balkons Weapon mod
