### ISSUE TITLE
Spirit Trees

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#323]
Spirit Trees are rare trees that act as mobs in the sense that they attack and can be killed. They do however, not move.
Their base trunk would occupy a 4*4 square minus the corners.

The trees exist out of the following blocks:
- [x] Spirit Leaves: 
  _Hanging leaves that act as wall blocks. They might drop Spirit Fruits, just like oak trees drop apples. Spirit Fruits would be a BL equivalent of the Golden Apples._
- [x] Spirit Logs: 
  _Just like any other logs, but maybe these could have fancy animated variations with glowing parts. Spirit Logs can be crafted in Spirit Planks, which are quite stronger than regular planks. Maybe they will also have a special use later on._
- [x] Face(s):
  _The faces are the mob part of the tree. There is atleast one main face (2x2x1 blocks, at eye level in the trunk) and up to 3 additional 1x1x1 faces, which can spawn anywhere. The faces spit Sap, which are projectiles affected by gravity. They do an AoE damage upon impact. The main face should do more damage, and maybe once the main face is killed, the additional ones die as well._
- [ ] Cocoons #313:
  _Cocoons grow (slowly) in the canopy. They have 3 stages. After that, they hatch a Pyrad. They can be obtained in a way (which needs specifiying) and replanted somewhere else to hatch a tame baby Pyrad for the player._
- [x] Roots:
  _Spirit Roots, that look like regular roots, surround the area around the tree, making the area a bit more difficult for the player to manouver. The closer they are to the tree, the taller they grow._

---

If a player kills 3 or more faces, here is a chance of a weather event occuring, which spawns an Elder Pyrad mini-boss as well. The event ends when the Elder Pyrad is killed.

**Comment by theishiopian** [comment]
when you say 4x4 minus the corners, do you mean 6x6, but with a rounded base?

**Comment by TheCyberBrick** [comment]
- [x] Destroying wisps weakens tree
- [x] The more wisps the more XP when the tree dies
- [x] Axes deal more damage to tree
- [x] Shockwave attack between the two wisp circles
- [x] Spitting Sap attack
- [x] Roots holding player down attack

**Comment by SamuraiShogun1102** [comment]
How about a Giant spirit tree boss that drops a large spirit tree sapling?
