### ISSUE TITLE
Vanilla minecraft music in the main menu title screen, left by betweenland main menu=false

### ISSUE THREAD

**Issue by lightning02** [TheCyberBrick/The-Betweenlands#324]
With betweenland installed, if you also use liteloader with custom music menù you have to disable betweenland main menu in the config file, but.... then the minecraft vanilla music start to plays in the main menu... and it ruins the res_voxelmenumusic ogg sounds that plays over :(

**Comment by TheCyberBrick** [comment]
Can you verify this is only happening with the Betweenlands installed? The BL only replaces the music ticker when you are actually in the dimension, not in the main menu. I'm not quite sure why this would be happening.

**Comment by lightning02** [comment]
I've already reproduced with only forge 1614 installed + betweenlands and liteloader (+ lib_voxellib_2.3.1_mc1.7.10, mod_voxelmenu_4.1.4_mc1.7.10, res_voxelmenumusic_v_mc1.7.10 litemods)  and it's definetly that, if I remove the_betweenlands 1.0.6  the vanilla musics don't play in the main menu

**Comment by lightning02** [comment]
any news? :/

**Comment by TheCyberBrick** [comment]
We don't plan on supporting the 1.7.10 version anymore because we're currently updating to 1.10. This bug is only a minor issue anyway if it's just the music in the main menu.
