### ISSUE TITLE
Utility Blocks

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#326]
First off we ought to start with the basics - 
- [x]  Weedwood Crafting Table - has special render properties
- [x] Sulfur Furnace - has an extra slot for the Limestone Flux, so that item will need adding in addition to make it fully functional
- [x]  Dual Sulfur Furnace - Double the furnace, double the GUI slots
- [x] Weedwood Chest
- [x] Moss Beds - Not actually for sleeping since the BL has no day/night cycle (unless we decide on adding that in at a later date) but they do set the spawn point and display a message.
- [x] Weedwood and Syrmorite Rubber Tap
- [x] Purifier
- [x] Infuser
- [x] Mortar (and pestle)
- [x] Alembic
- [x] Animator
- [x] Item shelf
- [x] Gecko cage

The following are all BL equivalents of existing vanilla blocks, so they shouldn't take long either - 
- [x] Buttons - Betweenstone and Weedwood
- [x] Doors - Weedwood, Rubber Tree Plank and Syrmorite (which acts like Iron)
- [x] Weedwood Fence Gates
- [x] Rubber Tree Plank Fence Gates
- [x] Pressure Plates - The Weedwood Pressure Plate will activate when any form of entity hits it, including players, mobs, drops and arrows. The Betweenstone Pressure Plate will only activate through players and mobs, and the Syrmorite Pressure Plate only activates through players.
- [x] Sulfur Torch
- [x] Syrmorite Hopper
- [x] Trapdoors - Weedwood, Rubber Tree Plank and Syrmorite (acts like Iron)
- [x] Weedwood Jukebox
- [x] Weedwood ladder
- [x] Weedwood Lever
- [x] Weedwood Sign

**Comment by MrCompost** [comment]
Some of these may be already done, in which case please just tick em off.

**Comment by imdutch21** [comment]
why does ticking something off make me remove @dmf444 everytime
