### ISSUE TITLE
Items to update and add

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#329]
**# Materials**
- [x] Amate Paper: Used to make helpful books for the dimension.
- [x] Amulet Socket: Used in the creation of wearable amulets.
- [x] Angler Tooth: A drop from Anglers.
- [x] Aspect Vials: Vials of a specific aspect usable in infusing.
- [x] Aspectrus Fruit: Fruit from a unique crop that is infused with an aspect.
- [x] Bucket of Liquid Rubber: Harvested from Rubber Taps.
- [x] Cave Moss Clump: Harvested from Cave Moss found in caverns.
- [x] Crimson Snail Shell: A drop from Blood Snails.
- [x] Deep Water Coral: Harvested from Deep Water Coral found in deep waters.
- [x] Dentrothyst Vial: Containers for Infusions.
- [x] Dragonfly Wing: A drop from Dragonflies.
- [x] Dried Swamp Reed: Made by drying Swamp Reed.
- [x] Dry Bark: Dropped by Hollow Logs.
- [x] Ground Items: Various materials ground in the Mortar, used in infusions.
- [x] Ground Weedwood Bark: Used to make Woodchip Paths.
- [x] Life Crystal: Mined from Life Crystal Ore.
- [x] Lurker Skin: A drop from Lurkers.
- [x] Middle Gem: Mined from Middle Gem Ores.
- [x] Mire Coral: Harvested from Mire Coral found underwater in the Betweenlands.
- [x] Moss: A drop from Moss blocks.
- [x] Mud Brick: Used to make Mud Brick blocks.
- [x] Ochre Snail Shell: A drop from Mire Snails.
- [x] Octine Ingot: Obtained by smelting Octine Ore.
- [x] Plant Items: Various parts of different plants that can be ground.
- [x] Poison Gland: A drop from Blood Snails.
- [x] Reed Rope: Crafted with Swamp Reed.
- [x] Scabyst: Can be coated on tools to stop corrosion.
- [x] Slimy Bone: A drop from the Swamp Hag.
- [x] Sludge Ball: A drop from Sludges.
- [x] Solid Rubber: Made by heating Buckets of Liquid Rubber.
- [x] Sulfur: An item that is very similar to coal, mined from Sulfur Ore.
- [x] Swamp Kelp: Harvested from Swamp Kelp growing underwater.
- [x] Swamp Reed: Harvested from Swamp Reed found growing in the Betweenlands.
- [x] Syrmorite Ingot: Mined from Syrmorite Ore.
- [x] Tar Beast Heart: A drop from Tar Beasts.
- [x] Tar Drip: A drop from Tar Beasts.
- [x] Valonite Shard: Mined from Valonite Ore.
- [x] Volarpad Leaf: Harvested from Volarpads found growing in lush biomes.
- [x] Weedwood Bowl: Used for making Nettle Soup.
- [x] Weedwood Infusion Bucket: A bucket containing any infusion concocted at the Infuser.
- [x] Weedwood Stick: An item crafted from Weedwood Planks.

**# Consumables**
- [x] Angler Meat Steak: Obtained by cooking Raw Angler Meat.
- [x] Ball of Sap: An edible item obtained from trees that replenishes the decay bar.
- [x] Black Hat Mushroom: An edible, although not very sustaining, mushroom.
- [x] Bulb-Capped Mushrooms: An edible and very 'flashy' mushroom.
- [x] Chiromaw Wing: The wing of a strange beast that can counter food sickness.
- [x] Crabstick: Crafted with 3 Silt Crab Claws.
- [x] Flathead Mushroom: An edible, although not very sustaining, mushroom.
- [x] Forbidden Fig: A tempting looking, although deceiving, fig.
- [x] Fried Frog's Leg: Obtained by cooking Raw Frog's Legs.
- [x] Fried Swamp Kelp: Obtained by cooking Swamp Kelp.
- [x] Gert's Donut: Crafted with a Reed Donut, a Wight's Heart, and a Slimeball.
- [x] Green Marshmallow: Increases movement speed when eaten.
- [x] Infusions: The Betweenlands equivalent of potions, with varying special effects.
- [x] Jam Donut: Crafted with a Reed Donut and a Middle Fruit.
- [x] Nettle Soup: Crafted with a Weedwood Bowl, various mushrooms, and a Nettle.
- [x] Pink Marshmallow: Increases jump height when eaten.
- [x] Purple Pear: Collected from Purple Pear bushes.
- [x] Purple Pear Jello: Crafted with Purple Pears and Sludge Jello.
- [x] Raw Angler Meat: A drop from Anglers.
- [x] Raw Frog's Leg: A drop from Frogs.
- [x] Raw Snail Flesh: A drop from Mire Snails and Blood Snails.
- [x] Reed Donut: Crafted with Dried Swamp Reed.
- [x] Rotten Food: What happens to outside food you bring into the Betweenlands.
- [x] Sap Jello: Crafted with Balls of Sap and Sludge Jello.
- [x] Seared Snail Flesh: Obtained by cooking Raw Snail Meat.
- [x] Silt Crab Claw: A drop from Silt Crabs.
- [x] Sludge Jello: Obtained by cooking Sludge Balls.
- [x] Tainted Potion: What happens to outside potions you bring into the Betweenlands.
- [x] Tangled Root: Harvested from Root blocks.
- [x] Weeping Blue Petal: Obtained from Weeping Blue flowers.
- [x] Wight's Heart: A drop from the Wight.
- [x] Yellow Dotted Fungus: Collected from Yellow Dotted Fungus crops.

**# Equipment**
- [x] Angler Tooth Arrow: Basic arrows for the Weedwood Bow.
- [x] Basilisk Arrow: Arrows for the Weedwood Bow that can 'petrify' enemies.
- [x] Bone Armor: Basic armor crafted using Slimy Bones.
- [x] Bone Tools: Basic stone-level tools crafted using Slimy Bones.
- [x] Critter Cruncher: A rare mace capable of great damage to 'critters'.
- [x] Explorer's Hat: A cool looking hat, pretty much.
- [x] Hag Slayer: A rare battle axe capable of great damage to Swamp Hags.
- [x] Lurker Skin Armor: Leather-like armor crafted using Lurker Skin.
- [x] Lurker Skin Pouch: A portable and upgradeable storage unit.
- [x] Middle Gem Amulet: Unique accessories that provides different gem-based bonuses.
- [x] Net: A tool capable of capturing Geckos and Fire Flies in the inventory.
- [x] Octine Arrow: arrows for the Weedwood Bow that can set enemies on fire.
- [x] Octine Tools: Iron-level orange tools crafted using Octine Ingots.
- [x] Pestle: Can be combined with a Mortar to grind certain items.
- [x] Poison Angler Tooth Arrow: Arrows for the Weedwood Bow that can poison enemies.
- [x] Ring of Ascent: A special equippable ring that provides nature-boosted levitation.
- [x] Ring of Power: A special equippable ring that boosts defense and attack.
- [x] Ring of Recruitment: A special equippable ring that allows one to 'recruit' mobs.
- [x] Ring of Summoning: A special equippable ring that summons allies from the depths.
- [x] Rubber Boots: Boots crafted with Rubber that provide highly sought improvements.
- [x] Shockwave Sword: A powerful sword found atop the dreaded Wight Tower.
- [x] Sickle: A tool capable of harvesting plant items from various Betweenlands plants.
- [x] Skull Mask: A special mask that makes Wights not aggressive towards the wearer.
- [x] Sludge Lance: A rare lance capable of great damage to Sludges.
- [x] Swift Pickaxe: A rare pickaxe with very fast speed.
- [x] Syrmorite Armor: Iron-level blue armor crafted using Syrmorite Ingots.
- [x] Syrmorite Shears: A tool capable of collecting many Betweenlands plants in block form.
- [x] Valonite Armor: Diamond-level pink armor crafted using Valonite Shards.
- [x] Valonite Tools: Diamond-level pink tools crafted using Valonite Shards.
- [ ] Volarkite: An item that allows one to drift down from high places.
- [x] Voodoo Doll: A powerful item that can deal a lot of damage to mobs in a radius around the user.
- [x] Weedwood Bow: A ranged weapon that can shoot a variety of new ammunition.
- [x] Weedwood Tools: Very basic tools crafted using Weedwood Bark.
- [x] Wight's Bane: A rare dagger capable of great damage to Wights.

**# Other Items**
- [x] Amulet Slot: Capable of granting additional amulet equip slots to the player.
- [x] Angry Pebble: An explosive drop from Boulder Sprites.
- [x] Aspectrus Seeds: Used to grow Aspectrus.
- [x] Caving Rope: An item useful for finding your path in the dark Betweenlands caverns.
- [x] Compost: A item essential to the Betweenland's agriculture system.
- [x] Firefly (item): A Firefly caught with the Net.
- [x] Gecko (item): A Gecko caught with the Net.
- [x] Ground Dried Swamp Reed: Used to speed or initiate growth of plants.
- [x] Herblore Book: A book that details Aspect effects and recipes based on observations.
- [x] Inanimate Tarminion: Items left behind by Tar Minions.
- [x] Item Scroll: Shows an item and can be animated to get the item.
- [x] Limestone Flux: A material that can increase ore smelting output.
- [x] Lore Scrap: Pieces of various writing left behind by previous observers.
- [x] Mummy Bait: A tasty treat that could attract some...unwelcome attention.
- [x] Music Discs: Special items that play unique music tracks.
- [x] Plant Tonic: Used to 'purify' Betweenlands crops.
- [x] Purple Pear Bush Seeds: Used to grow Purple Pear Bushes.
- [x] Shimmerstone: A throwable item that can distract Peat Mummies.
- [x] Spores: A drop from Sporelings.
- [x] Swamp Talisman: An item obtained in Druid circles that allows access to the Betweenlands.
- [x] Tar Minion (item): Entities that can be thrown to attack enemies.
- [x] Weedwood Bucket: A basic bucket that can collect Betweenlands liquids.
- [x] Weedwood Rowboat: Used to swim the waters of the Betweenlands more efficiently.
- [x] Candy: Food items obtainable during the Halloween season.
- [ ] Guide Book: An ingame guide to the content of the mod, currently unfinished.
- [x] Mince Pie: An item found in presents.
- [x] Bone Shield: A basic shield made from Slimy Bones.
- [x] Dentrothyst Shield: Special shields that can negate potion effects.
- [x] Lurker Skin Shield: A special shield that can be used as an emergency raft.
- [x] Octine Shield: A special shield that can reflect projectiles.
- [ ] Rubber Shield: A special shield that entities bounce off of.
- [ ] Solid Tar Shield: A special shield that can block Tar Beast attacks.
- [x] Syrmorite Bucket: A bucket that does not burn when used to collect rubber.
- [x] Syrmorite Shield: A basic shield crafted with Syrmorite Ingots that allows its user to charge.
- [x] Valonite Shield: A basic but powerful shield made from Valonite Shards.
- [x] Weedwood Shield: A basic shield made from Weedwood Planks that can catch fire.

_**Special thanks to Ethan the Incredible and his amazing wiki!**_

**Comment by TheCyberBrick** [comment]
Please only tick off the items that are completely implemented :P

**Comment by imdutch21** [comment]
woops, screwed up...

**Comment by WightofShadows** [comment]
I think this can be closed at this point
