### ISSUE TITLE
Bizarre graphics glitches when tech mods installed.

### ISSUE THREAD

**Issue by themechman** [TheCyberBrick/The-Betweenlands#331]
So running into a problem with things like Galacticraft and some other mods installed along side this one.

Every time I look at my friend, my screen goes ballistic. See attached images

![2016-10-01_13 36 14](https://cloud.githubusercontent.com/assets/2990361/19023975/972b809c-88c8-11e6-8bc0-e5e2ce9497b0.png)
![2016-10-02_17 30 23](https://cloud.githubusercontent.com/assets/2990361/19023973/972b0e5a-88c8-11e6-90a2-917203616cb4.png)
![2016-10-02_17 32 01](https://cloud.githubusercontent.com/assets/2990361/19023972/972a989e-88c8-11e6-8feb-cec094dac126.png)
![2016-10-02_17 35 32](https://cloud.githubusercontent.com/assets/2990361/19023974/972b4a46-88c8-11e6-8aa9-b2108c318878.png)

We tried and tried to find the trigger. It happened less when I went through the portal tree with absolutely nothing on me. Let me know if you need the list of mods.

Now if I go there and he's not there, no glitches. We cannot even have the name in the field of view.

**Comment by MrCompost** [comment]
I actually had similar glitches on one occasion whilst playing on a test server with the others, though no mods were installed apart from the BL. Could you try with just the BL on its own please? Or on a server (or singleplayer if you already are) if possible?

**Comment by themechman** [comment]
I'll see what I can do. Again, results are random. Going to start stripping out mods til it stops.

**Comment by themechman** [comment]
So it seems that when I or my friend look at each other, this happens. He has decay (sometimes a lot) and it does it. When/if he dies, the glitch goes away. I think it has something to do with his skin having a "mask". Perhaps a z-buffer issue?

**Comment by themechman** [comment]
Also, when looking at someone, and opening inventory, it shows nothing at all. Even removes NEI

**Comment by themechman** [comment]
After extensive checking, it seems that it has something to do with the decay overlay. Even with nothing in inventory it occurs.

**Comment by TheCyberBrick** [comment]
Ah yeah, that's probably the case. The decay overlay renderer is pretty hacky. It's a lot better in the 1.10 version though, I assume it won't be a problem there anymore.

**Comment by themechman** [comment]
While I am all for bug fixes I'm not fork-lifting a modpack to 1.10 when I'll loose the majority of the mods I actually want to play.

Is there a way to turn it off?

**Comment by TheCyberBrick** [comment]
No, not currently. The decay can be disabled as a whole by setting the gamerule "blDecay" to false, but it's not possible to disable the renderer only.

**Comment by themechman** [comment]
That is at least a viable short-term option at this point.

**Comment by TheCyberBrick** [comment]
If you do that though make sure your decay bar is filled up all the way. All it does is disabling the decay progress, if your player already has decay it'll still render.

**Comment by themechman** [comment]
Got, it. Thank you.
