### ISSUE TITLE
Biomes not respecting config'd IDs

### ISSUE THREAD

**Issue by Shahelion** [TheCyberBrick/The-Betweenlands#333]
The first thing I noticed was the Eerie biome (Thaumcraft) near my house is now a marsh2 biome according to F3 (also noticeably greener) despite the Marsh 2 biome being set to 66 in the config, and Eerie being set to 194. I get that the 128+ thing might be happening, but it's with a biome that is clearly set otherwise in the config, not a mutation, unless the mutation biome shares the same name (which is silly).

**Comment by TheCyberBrick** [comment]
They do respect the config IDs, the reason for this is due to the biome mutations and that's just how it works unfortunately. We removed the mutation biomes in the 1.10 version, so it shouldn't be a problem there anymore.

**Comment by Shahelion** [comment]
Also minor thing, the biome names aren't capitalized (in F3, at least).

**Comment by TheCyberBrick** [comment]
That's because I planned on localizing the biome names in the lang file for the location titles and for that reason they're not capitalized.
