### ISSUE TITLE
[Request] Portal Tree dimension whitelist

### ISSUE THREAD

**Issue by Shahelion** [TheCyberBrick/The-Betweenlands#334]
I get why the Nether or the End should be off-limits, but what about the Twilight Forest, or the Erebus, or pocket dimensions that are big enough? As it is, they just lead back to the overworld, and now I have this massive tree floating above my rainbow forest.

Perhaps a whitelist for dimensions that it would work in, hard-blacklisting the Nether & the End, and only dims above 0?

**Comment by TheCyberBrick** [comment]
I guess we can do that. The portal gen will be rewritten in future versions anyways

**Comment by Shahelion** [comment]
Are you keeping the tree? Because it looks really good.

**Comment by TheCyberBrick** [comment]
Yeah, the tree will stay :)
We want to make the portals only spawn in certain biomes and also fix a couple of bugs it currently has.

**Comment by TheCyberBrick** [comment]
@Zsashas it has been quite a while, but the next release will allow the player to link portals together with the Swamp Talisman and there will also be a dimension whitelist
