### ISSUE TITLE
Issue with starminer.

### ISSUE THREAD

**Issue by sabfrompc** [TheCyberBrick/The-Betweenlands#338]
You may or may not be familiar with a cool little mod called starminer (http://forum.minecraftuser.jp/viewtopic.php?f=13&t=17975&start=260 for its thread) which allows for all sorts of interesting gravity manipulation in minecraft. For whatever reason, betweenlands stops the player's view from rotating when the player attempts to stand on a star. The model of the player, along with the hitbox both appear to be rotating as expected, it is only the camera that seems to be having issues, leading me to believe it is related to the betweenlands shaders. I have attempted to disable the shaders in the config file as I suspect that's what it's related to, but that does not seem to help. I am on the latest version of both mods, and am not sure if there is something I can do. Optifine had a similar issue back in 1.6.4 with starminer. Code was created (I can provide this if it would help at all) to fix this incompatability, but sadly it was for 1.6.4, not 1.7.10. If anyone knows of a fix for this, or even which portions of the code (I have worked with java in the past, but have not done a much work with graphics, let alone 3d rendering, but I would be willing to give it a shot) in betweenlands cause this I would be thrilled to know about it.

**Comment by TheCyberBrick** [comment]
This is probably related to the weedwood boat perspective. That's the only thing that changes the view perspective iirc.

**Comment by sabfrompc** [comment]
Thanks for the quick reply! I tried disabling the weedwood boat perspective in the config file, but that didn't help. Interestingly, I've also found out that even though the camera doesn't rotate when entering a gravity field from starminer, the hitboxes of the blocks do, meaning it's just the camera that's being funky in first person view. The controls and all the hitboxes appear to be working as starminer intended, which makes this even stranger. For reference sake, here are some screenshots:
How it's supposed to look: http://i.imgur.com/3mwypIs.png
How it looks with betweenlands: http://i.imgur.com/8Pa598P.png
Without betweenlands and f5 view: http://i.imgur.com/TjrJJ0y.png
With betweenlands and f5 view: http://i.imgur.com/GJjZLWN.png

**Comment by TheCyberBrick** [comment]
The perspective renderer is overwritten regardless of whether the weedwood boat perspective is enabled in the config file.
If you're interested in the code that does it:
https://github.com/Angry-Pixel/The-Betweenlands/blob/1.7.10/java/thebetweenlands/core/TheBetweenlandsClassTransformer.java#L362
 https://github.com/Angry-Pixel/The-Betweenlands/blob/1.7.10/java/thebetweenlands/client/perspective/Perspective.java

My guess is that the Starminer mod does the same thing when standing on a star to rotate the camera properly.

**Comment by sabfrompc** [comment]
Thanks so much! I'll download the source and see if I can get things to co-operate a little better.
