### ISSUE TITLE
Portal tree animation

### ISSUE THREAD

**Issue by theishiopian** [TheCyberBrick/The-Betweenlands#344]
So, the portal tree. Its a unique idea, and I like it a lot. However, the fact that the tree just pops into existence upon the use of a talisman on a sapling is kind of annoying. Sure this is Minecraft, but this is also the Betweenlands, a place where normal Minecraft things are 10x prettier. So, I propose an idea for a tree animation.

The way I imagine it working is that each 'frame' of the animation is a smaller version of the tree that gets progressively larger over the course of a few seconds. The animation works by removing the blocks that make up the  previous 'frame' and then placing the blocks that make up the next 'frame', with each 'frame' being a progressively larger tree, with the portal opening once the tree grows to full size. The idea is similar to how animation is often done in vanilla maps, with schematics being pasted on top of each other in rapid succession. 

Here is an example of what I mean: [https://youtu.be/rHQUGaNN7zk?t=10m31s](url)

There could also be fancy particle effects for the animation, like nature energy coming together to power the tree's growth, but that could come later.

**Comment by vadis365** [comment]
It'll do for now.
