### ISSUE TITLE
Query: Number of Block IDs?

### ISSUE THREAD

**Issue by Divineaspect** [TheCyberBrick/The-Betweenlands#346]
I'm attempting build a pack and adding this very shiny looking mod I've been waiting for causes an out of blocks style error on startup, how many block IDs does this mod use?

**Comment by TheCyberBrick** [comment]
There are about 300 blocks IIRC. Forge handles all the block ID distribution, and I doubt you're actually running out of block IDs. Could you post your log?

**Comment by Divineaspect** [comment]
https://gist.github.com/Divineaspect/89e4a6be3fbcd3c7f61f944fc5271716
sure, here ya go.

**Comment by Divineaspect** [comment]
I've also done a tellme dump of all modded blocks
https://gist.github.com/Divineaspect/b092c3e4e3fa82504e6634c776a9728e
If  that means anything to you. It'll be a few hours or days until I can get it in a format where I can do any detailed analysis.

**Comment by Divineaspect** [comment]
![image](https://cloud.githubusercontent.com/assets/8753002/23488899/0c3f5ee6-feb5-11e6-98d8-b4c175b9fcdc.png) for a snapshot of the heaviest other mods by block ids.

**Comment by TheCyberBrick** [comment]
Looks like you were right, I didn't think the block ID limit would be this low.

**Comment by theishiopian** [comment]
Wow, its been a long while since I've seen this kind of error! I thought these died a long time ago.

**Comment by TheCyberBrick** [comment]
Currently there are exactly 279 (or ~~180~~ 280 in the dev version) blocks

**Comment by Divineaspect** [comment]
That's 180 block IDs? That I could work around. Thanks for the update.

**Comment by TheCyberBrick** [comment]
Oh oops that should've been 280

**Comment by Divineaspect** [comment]
oh, that's just painful then.

**Comment by TheCyberBrick** [comment]
There's nothing we can do about that
