### ISSUE TITLE
I found two fairly large mods that do not work with this.

### ISSUE THREAD

**Issue by Zekken01** [TheCyberBrick/The-Betweenlands#350]
The two mods that have issues are [Pams Harvestcraft](https://minecraft.curseforge.com/projects/pams-harvestcraft) and [Random Things](https://minecraft.curseforge.com/projects/random-things).

[Random Things crash log](https://paste.ee/p/EoidV)
[Pams Harvestcraft crash log](https://paste.ee/p/yKEzY)

**Comment by theishiopian** [comment]
This error is virtually identical to the one in issue #349.

**Comment by brodycas3** [comment]
¯\_(ツ)_/¯

**Comment by Zekken01** [comment]
Looks like im one step ahead of that one.

**Comment by theishiopian** [comment]
Interestingly, neither pam's harvestcraft nor randomthings are involved in #349.

**Comment by Zekken01** [comment]
Ive tested with only these two mods too. Neither of them work with it.

**Comment by TheCyberBrick** [comment]
Yeah I'm working on this right now, thanks for giving me two mods to try it out. My guess is that the BL model loader accepts models from other mods which it shouldn't

**Comment by TheCyberBrick** [comment]
Ok I've found the cause, trying to fix it now.

**Comment by TheCyberBrick** [comment]
The problem was caused by a change in a newer version of Forge. The next update will fix this
