### ISSUE TITLE
[1.10.2] Extreme tick lag Clientside (MODDED).

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#353]
When using this mod in my modpack, thebetweenlands dimension literally breaks the game.

Chunks wont spawn, unable to hit animals, changing from survival mode to creative takes 5-15 seconds.

None of this happens else where just in this dimension.

My modpack has 120 mods and im a very avid modpack developer.

Let me know what information you will need to look into this, Great mod but seems to not play fair in a modpack.

**Comment by TheBritishBrotherhood** [comment]
Is there any known mods that can cause this kind of issue?

**Comment by TheCyberBrick** [comment]
Are you using the latest 2.0.1 version? Which version of Forge are you using? Does this always happen or under certain circumstances? Does the mod work fine without those other mods?
If you press and hold F3 + C for ~10 seconds it will crash the game (doesnn't have to be in the BL dimension) and create a crash log, can you send me that log?

**Comment by TheBritishBrotherhood** [comment]
Using 2.0.1.

It happens every time.

It works fine without other mods (Still can lag for split seconds thou)

I am unable to crash it as it is lagging that hard. here is the pack and some images, just import to curse.

FX-8350 CPU - 10GB ram dedicated to the pack.

Modpack: https://drive.google.com/file/d/0Bwx-9ytUP_NveEVlS09yS09faDg/view?usp=sharing

![2017-03-06_15 03 51](https://cloud.githubusercontent.com/assets/21251496/23615487/7b84aba4-027e-11e7-85ad-3032b4df7d41.png)
![2017-03-06_15 03 58](https://cloud.githubusercontent.com/assets/21251496/23615488/7b86e22a-027e-11e7-9fa5-5f3828bc17ba.png)

**Comment by TheCyberBrick** [comment]
You don't have to be in the dimension to do the F3 + C thing

**Comment by TheBritishBrotherhood** [comment]
But it only happens in this dimension no were else. But okay here: http://pastebin.com/x2xZJKQ4

**Comment by TheCyberBrick** [comment]
The point of that crash log is mainly to get a list of mods, their versions, hardware, drivers etc. ;)
I downloaded your pack and I can reproduce the issue which should help a lot.
Btw: Waila was causing a JVM crash for me when loading the pack

**Comment by TheCyberBrick** [comment]
My first guess is that some mod tries to generate things in the Betweenlands and causes chunks to generate recursively.

**Comment by TheBritishBrotherhood** [comment]
Ahh okay :) 

And right okay, We dont have any ores generating so i cant see ores being an issue.

Most and all types of generation have been removed via config, Villages, Ores, Structers etc, I really do hope you find a fix for this xD

**Comment by TheCyberBrick** [comment]
Well, I don't have time right now to do much testing. You can help me by trying to pinpoint which mod(s) cause it though (should be rather simple thanks to the launcher)

**Comment by TheBritishBrotherhood** [comment]
I will try my best, But im also a very busy person :P

**Comment by TheCyberBrick** [comment]
Ok. I managed to narrow it down to the Epic Siege Mod. Works fine with that mod disabled

**Comment by TheBritishBrotherhood** [comment]
Ohh really? I will test it on my side now thank you!

**Comment by TheCyberBrick** [comment]
You may also want to report this on Epic Siege Mod's GitHub

**Comment by TheBritishBrotherhood** [comment]
I will do that not a problem, I also still have some lag but for sure not as bad as before.

Removing more mods will get back to you :)

**Comment by TheBritishBrotherhood** [comment]
Seems to not like vanilla tweaking mods, I have removed all vanilla tweak mods and seems to be running much better :)

I think this issue can be closed for now but i will reopen if issues persist

**Comment by TheCyberBrick** [comment]
Nice, I'm glad you were able to solve it. Could you tell me which mods caused problems?

**Comment by vadis365** [comment]
Gonna kick Funway's butt about this :P

**Comment by TheBritishBrotherhood** [comment]
I cant say what caused it, But removing mods such as (Mo'Bends, Mob Dismemberment, Epic Siege, Knob Control... Or any type of vanilla tweaking mod seems to fix the issue :)
