### ISSUE TITLE
custom mob spawner (CMS) crash

### ISSUE THREAD

**Issue by TitusArmillius** [TheCyberBrick/The-Betweenlands#354]
http://pastebin.com/3LPX3Jir

The crash occurs in the spawnland biome in the overworld, not in The Betweenlands dimension. it also occurs near an altar. My guess is that CMS doesn't like the way the druid spawns.

**Comment by TheCyberBrick** [comment]
This doesn't seem to be caused by the Betweenlands directly. I can't really help with this because CMS' source isn't public.
