### ISSUE TITLE
[1.10.2] OreDict Config? (Suggestion)

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#356]
So i have noticed all blocks in the Between land isnt compatible with vanilla/modded recipes are lets say Logs are not oreDicted.

Is it possible to get a config option for this? 

The reason i ask this is that im using the betweenlands as a default world and no recipes will work unless i get vanilla wood etc

**Comment by TheCyberBrick** [comment]
Sure, please give me a list of blocks and the string they should be oredicted as

**Comment by TheCyberBrick** [comment]
Moved to #357
