### ISSUE TITLE
[1.10.2] Suggestions

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#357]
- [x] Vanilla saplings on swamp dirt/grass
- [x] Lower sulfur xp drop
- [x] Oredict (please post a list)
- ~~[ ] Possible Options to remove Ring Of Flight (too easy)~~

**Comment by TheBritishBrotherhood** [comment]
OreDict:
thebetweenlands:log_weedwood > ore:logWood (beleive this is allready a thing, My testers are noobs)
thebetweenlands:betweenstone > ore:cobblestone
thebetweenlands:swamp_dirt > ore:dirt
thebetweenlands:weedwood_planks > ore:plankWood
thebetweenlands:weedwood_plank_slab > ore:slabWood
thebetweenlands:swamp_reed_item > ore:sugarcane

I will add to this every time i find something unless told otherwise :)

Also Thank you for being such a great group of mod devs, Any other developer would have probably just ignored my suggestions <3

**Comment by TheCyberBrick** [comment]
> Possible Options to remove Ring Of Flight (too easy)

What do you mean by "too easy"?
Compared to other mods' flight items it seems to be underpowered if anything as it only lets you fly 4 blocks above ground and costs XP to use. I don't really want to add config options to remove items. If you really want to get rid of it you can edit/override the loot tables as it is only obtainable through loot.

**Comment by TheBritishBrotherhood** [comment]
Didnt know it used XP, So thats fine then :D

**Comment by TheCyberBrick** [comment]
All the rings do :P

**Comment by TheBritishBrotherhood** [comment]
I should really read more of the Wiki hahaha xD
