### ISSUE TITLE
[1.10.2] Ring Of Flight Fall Damage Issue.

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#361]
This bug has been seen in previous mods when using a ring of flight as you go to land/touch the ground you die instantly.

**Comment by TheCyberBrick** [comment]
That doesn't happen with the BL only, must be some other mod doing something.
~~I can try adding some additional code, but not sure if that'll help.~~
Nvm, that code is already there.
