### ISSUE TITLE
[1.10.2] Ring Of Flight Not Using XP

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#362]
Not sure if its the same for other rings, but no XP is being used

**Comment by TheBritishBrotherhood** [comment]
Watch here if you want to keep upto date with us were all testing :) http://kadgar.net/live/stuntmaker_/fate78/doctorblockhead

**Comment by TheCyberBrick** [comment]
It does use XP, I even saw it in the stream, lol
