### ISSUE TITLE
Blood Snail Poison Jet

### ISSUE THREAD

**Issue by Sean-Amor** [TheCyberBrick/The-Betweenlands#363]
Just seeing if you had plans to work on the poison projectile shortly, I tried figuring it out myself, but failed. Thanks! I'd love to see how you get it working.

**Comment by TheCyberBrick** [comment]
huh? what?

**Comment by Sean-Amor** [comment]
/*TODO add effect when SNAIL_POISON effect is added
    @SideOnly(Side.CLIENT)
    public void trailParticles(World world, double x, double y, double z, Random rand) {
        for (int count = 0; count < 5; ++count)
            BLParticle.SNAIL_POSION.spawn(worldObj, x, y, z, 0.0D, 0.0D, 0.0D, 0, 0);
    }*/

**Comment by TheCyberBrick** [comment]
Uhm, what. That's already implemented
