### ISSUE TITLE
[1.10.2] Flint & Steel not working in TheBetweenlands.

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#364]
Not sure if this is a bug, but when i right click with flint&steel i get a message in chat saying

chat.flintandsteel

Is this on purpose?

![cd73daf80314c7ba118c2df9231c594c](https://cloud.githubusercontent.com/assets/21251496/23674059/76da70e0-036c-11e7-9e2d-9554448975ac.png)

Using this mod as the main dimension in my pack, So need vanilla things to work in most cases, Is there anywere i can speak to you guys other then here?

Regards, Curtis

**Comment by TheCyberBrick** [comment]
Works as intended (almost, the lang is missing, oops).
In the Betweenlands you use an Octine Ingot and right click on tinder (e.g. Moss, Thorns etc.) to create a fire.
This still won't work though because the Nether Portal doesn't work in other dimensions with an ID > 0.
