### ISSUE TITLE
Multiplayer: Screen Stuck On Logging In

### ISSUE THREAD

**Issue by 8BrickDMG** [TheCyberBrick/The-Betweenlands#369]
Hello Angry-Pixel Team,

I recently installed the latest 1.10.2 version of the mod onto a multiplayer server and had the following issue:

The client hangs on the logging in screen when logging into a server but I am able to hear myself walking around & breaking stuff etc, when trying out the controls.

In game sounds seems to works but not the visuals.

I am not sure if this is to do with the mods I'm using in combination but I'm linking the pack list below:
http://pastebin.com/TH9tQaf8

Kind regards,
Jason

**Comment by TheCyberBrick** [comment]
I have two suggestions:
- In the OptiFine settings set "Fast Render" to OFF
- If that doesn't work, open the Betweenlands config and disable the shaders

One of those will most likely solve your problem :)

**Comment by 8BrickDMG** [comment]
Thanks @TheCyberBrick,

I shall give those a try and report back with the results :)

**Comment by 8BrickDMG** [comment]
I checked my Optifine settings and "Fast Render" was already off by default.

Disabling the shaders in the config fixed the issue.

Many thanks! :)
