### ISSUE TITLE
[1.10.2][Suggestion] Config option to change stone block used in druid circles.

### ISSUE THREAD

**Issue by TitusArmillius** [TheCyberBrick/The-Betweenlands#370]
Currently I know of know way to do this without changing the texture of all stone blocks to the desired texture, which is typically counterintuitive aesthetically speaking.

**Comment by TheCyberBrick** [comment]
Hmm I don't want to add a config option for that, but instead I'll replace the normal stone with a Druid Stone without any runes on it so that you can change that texture if necessary.

**Comment by TitusArmillius** [comment]
Thankyou for the quick and polite responses @TheCyberBrick, keep up the great work :)
