### ISSUE TITLE
black screen while playing on a world

### ISSUE THREAD

**Issue by 0Navis0** [TheCyberBrick/The-Betweenlands#372]
I tried to integrate The Betweelands in my modpack ULTRA, but when I create or load any world, I just get a black sreen. Strangely everything seemed to work fine behind, the sounds work well, I can interact, move, break and place blocks, all the buttons work, I can return to the menu if I remember the position of the button. But there is just nothing which display, only a black screen.

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/issues/369#issuecomment-285191799
