### ISSUE TITLE
No atmospheric music or light effects when aproaching/entering cragrock tower.

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#374]
Hi, I've installed the Betweenlands 2.0.2 and have watched the previews and noticed that on the first video there is atmospheric sounds, while on the second video there is not.

Considering that I have encountered no such sounds, can I assume that the atmospheric music was cut for some reason?

**Comment by TheCyberBrick** [comment]
The Cragrock Tower doesn't have music or ambience, the music in the first video just happened to play randomly at that moment. What do you mean by light effects? The wisps?

**Comment by ghost** [comment]
By 'light effects' I meant the wisps that spawn in sequence up the tower; also, what conditions are necessary for that music to play?

**Comment by TheCyberBrick** [comment]
None, it plays randomly. The wisps only appear when you enter the tower in survival, make sure you're not in some different game mode.

If you still have the world, would you mind sending me the world and the position so I can check it out?

**Comment by TheCyberBrick** [comment]
@Titus-Armillius any update on this?

**Comment by ghost** [comment]
@TheCyberBrick Sorry about the absence; and well, I think you answered my question, I have no reason to think otherwise, I was in creative. Also, as a suggestion, I think you should add the music that played in the video as an event for the cragrock tower as it makes it much more interesting, and perhaps do the same for all other special locations.

**Comment by TheCyberBrick** [comment]
Ah ok :P
We do plan on making music play during certain conditions, but we haven't implemented that yet.
