### ISSUE TITLE
[1.10.2] Still cant use other plants on betweenlands dirt etc

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [TheCyberBrick/The-Betweenlands#375]
as the title says

**Comment by TheCyberBrick** [comment]
Well it should be working, at least the vanilla plants do.

**Comment by TheBritishBrotherhood** [comment]
Vanilla seeds not working either :) Nothing working at all apart from betweenlands plants :)

**Comment by TheCyberBrick** [comment]
Seeds, huh? You can't plant vanilla seeds on dirt.

**Comment by TheBritishBrotherhood** [comment]
on hoed dirt IE your composted dirt

**Comment by TheCyberBrick** [comment]
Well, how am I supposed to know you meant composted dirt? :P
I can't really implement this properly since the composted dirt requires additional mechanics.

**Comment by TheCyberBrick** [comment]
3aebae6756821b310d58fa8e0d307f582449c2af
They should be able to grow now, but I can't add mod integration for decay and such

**Comment by TheBritishBrotherhood** [comment]
Appreciate it cyber :D <3
