### ISSUE TITLE
(suggestion) syrmorite tools

### ISSUE THREAD

**Issue by 0Navis0** [TheCyberBrick/The-Betweenlands#376]
I just wanted to suggest to add syrmorite tools because syrmorite can be used for crafting anything except tools, and I don't really understand why this feature misses to the mod. Reversely octine can be used for crafting tools but not armor, and I don't understand neither why this feature misses.

**Comment by WightofShadows** [comment]
It's just that way because syrmorite and Octine are the equivalent tier, and it wouldn't make sense to wear something that burns you.

**Comment by 0Navis0** [comment]
Oh okay, but what about syromrite tools, syrmorite doesn't burn.

**Comment by theishiopian** [comment]
I always assumed that Symorite can't be sharpened, but that doesn't make sense with the shears.

**Comment by 0Navis0** [comment]
Neither with the syrmonite buckets.
