### ISSUE TITLE
Enchanting Octine Sword via Anvil

### ISSUE THREAD

**Issue by greenking13** [TheCyberBrick/The-Betweenlands#380]
Since the betweenlands armor/swords are not enchantable through the enchanting table, I wanted to test if I could enchant using an enchanted book and the Octine Sword. I placed in the Octine Sword and then tried placing the book, and I crashed immediately. I tested enchanting Valonite armor and was able to put the book in the anvil, no crash. I tested enchanting the Octine Sword with a different enchanted book and I got the same result of a crash. Both crashlogs attached.
[crash-2017-03-19_00.13.12-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/853030/crash-2017-03-19_00.13.12-client.txt)
[crash-2017-03-19_00.20.29-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/853031/crash-2017-03-19_00.20.29-client.txt)

**Comment by TheCyberBrick** [comment]
Can't reproduce this, Could you try without the other mods?
