### ISSUE TITLE
[1.10.2] [2.0.2 alpha] Failed splitting texture animation

### ISSUE THREAD

**Issue by Alaberti** [TheCyberBrick/The-Betweenlands#381]
Crashed on loading the game. Crash report: http://pastebin.com/raw/S957fYG5

Looks like there's a particle texture name in another mod (Matter Overdrive) that's similar to yours? @shadowfacts, I assume you might be interested in this as well.

**Comment by TheCyberBrick** [comment]
Ah I see, Matter Overdrive creates new TextureMaps which the BL doesn't expect

**Comment by Alaberti** [comment]
Thanks!

**Comment by TheCyberBrick** [comment]
No problem, thanks for reporting it!
