### ISSUE TITLE
JEI: Broken Recipe For The Animator

### ISSUE THREAD

**Issue by 8BrickDMG** [TheCyberBrick/The-Betweenlands#382]
Hello! I was going through my logs this morning to troubleshoot an inventory glitch that's occurring in my mod pack and found this. 

**Forge:** 12.18.3.2254
**Betweenlands:** 2.0.1
**SP or MP?:** MP

> [00:54:00] [Client thread/ERROR]: Found a broken recipe: thebetweenlands.compat.jei.recipes.animator.AnimatorRecipeJEI@7dff744f
> Failed to get ingredients from recipe wrapper
> 
> java.lang.NullPointerException
> 	at thebetweenlands.common.registries.LootTableRegistry.getItemsFromTable(LootTableRegistry.java:86) ~[LootTableRegistry.class:?]
> 	at thebetweenlands.compat.jei.recipes.animator.AnimatorRecipeJEI.getIngredients(AnimatorRecipeJEI.java:60) ~[AnimatorRecipeJEI.class:?]
> 	at mezz.jei.RecipeRegistry.getIngredients(RecipeRegistry.java:288) ~[RecipeRegistry.class:?]
> 	at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) ~[RecipeRegistry.class:?]
> 	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:242) [RecipeRegistry.class:?]
> 	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:201) [RecipeRegistry.class:?]
> 	at thebetweenlands.compat.jei.DynamicJEIRecipeHandler.onWorldLoad(DynamicJEIRecipeHandler.java:25) [DynamicJEIRecipeHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1019_DynamicJEIRecipeHandler_onWorldLoad_Load.invoke(.dynamic) [?:?]
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
> 	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:75) [bln.class:?]
> 	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:1014) [bll.class:?]
> 	at net.minecraft.network.play.server.SPacketRespawn.func_148833_a(SourceFile:31) [hj.class:?]
> 	at net.minecraft.network.play.server.SPacketRespawn.func_148833_a(SourceFile:12) [hj.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
> 	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by thebrightspark** [comment]
(I play on 8BrickDMG's private server with this version)

I've noticed in the logs that this error only occurs when exiting a world (Single and Multi-player)

**Comment by 8BrickDMG** [comment]
Updated the title as it was another mod causing our inventory glitch :)

**Comment by TheCyberBrick** [comment]
Hm I was aware of the JEI recipe bug, but that's not what causes this bug, right? Could you try without JEI once and then check if it's gone (just temporarily)? I'll probably remove the animator JEI recipe anyways since it won't work like this.

**Comment by 8BrickDMG** [comment]
That's correct. I checked and found out it was the 'Up, Down &I All Around'
mod which caused that specific issue.

I changed the title of this thread when I found out.
