### ISSUE TITLE
Weedwood Boat Causing Crash

### ISSUE THREAD

**Issue by baluka44** [TheCyberBrick/The-Betweenlands#387]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  bouncybeds (bouncybeds-1.10.2-1.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  DummyPlugin (ForgeEndertech-1.10.2-1.2.0.0-build.0015.jar)
  CreativePatchingLoader (CreativeCore v1.6.25 mc1.10.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.2.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  AstralCore (astralsorcery-1.2.3-beta.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 3/30/17 3:46 AM
Description: Unexpected error

java.lang.ClassCastException: thebetweenlands.client.event.handler.WeedwoodRowboatHandler$RowboatCam cannot be cast to net.minecraft.entity.EntityLivingBase
	at am2.particles.ParticleRenderer.render(ParticleRenderer.java:156)
	at am2.particles.ParticleRenderer.onRenderWorldLast(ParticleRenderer.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_ParticleRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at am2.particles.ParticleRenderer.render(ParticleRenderer.java:156)
	at am2.particles.ParticleRenderer.onRenderWorldLast(ParticleRenderer.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_ParticleRenderer_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['baluka44'/532, l='MpServer', x=-100.44, y=120.65, z=468.81]]
	Chunk stats: MultiplayerChunkCache: 587, 587
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1825 game time, 1825 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 51 total; [EntityItem['item.item.thebetweenlands.anglerMeatRaw'/13824, l='MpServer', x=-55.59, y=120.00, z=477.37], EntitySwampHag['Swamp Hag'/13835, l='MpServer', x=-117.50, y=18.00, z=479.50], EntityChiromaw['Chiromaw'/12044, l='MpServer', x=-67.62, y=45.81, z=502.25], EntityWight['Wight'/13837, l='MpServer', x=-99.50, y=34.00, z=463.50], EntitySwampHag['Swamp Hag'/12046, l='MpServer', x=-79.50, y=83.00, z=511.50], EntitySwampHag['Swamp Hag'/12048, l='MpServer', x=-74.50, y=83.00, z=506.87], EntitySwampHag['Swamp Hag'/12050, l='MpServer', x=-75.50, y=41.00, z=504.50], EntityAngler['Angler'/11923, l='MpServer', x=-113.83, y=5.00, z=448.35], EntitySwampHag['Swamp Hag'/12052, l='MpServer', x=-77.50, y=41.00, z=499.50], EntityAngler['Angler'/11925, l='MpServer', x=-119.77, y=4.00, z=450.09], EntityChiromaw['Chiromaw'/12182, l='MpServer', x=-52.63, y=69.63, z=531.75], EntityChiromaw['Chiromaw'/12184, l='MpServer', x=-39.49, y=70.00, z=528.64], EntityLeech['Leech'/11933, l='MpServer', x=-72.50, y=123.00, z=478.50], EntityChiromaw['Chiromaw'/12190, l='MpServer', x=-44.33, y=64.74, z=514.58], EntitySwampHag['Swamp Hag'/12192, l='MpServer', x=-37.50, y=35.00, z=518.50], EntityAngler['Angler'/12194, l='MpServer', x=-41.79, y=120.01, z=517.59], EntityChiromaw['Chiromaw'/12069, l='MpServer', x=-53.50, y=48.44, z=489.13], EntityAngler['Angler'/12198, l='MpServer', x=-48.46, y=119.00, z=514.01], EntityChiromaw['Chiromaw'/12071, l='MpServer', x=-43.83, y=49.59, z=493.23], EntityWeedwoodRowboat['Weedwood Rowboat'/13095, l='MpServer', x=-100.73, y=120.67, z=468.74], EntityChiromaw['Chiromaw'/11944, l='MpServer', x=-82.40, y=75.16, z=510.12], EntitySwampHag['Swamp Hag'/12073, l='MpServer', x=-40.50, y=121.00, z=484.50], EntityAngler['Angler'/11948, l='MpServer', x=-75.34, y=118.00, z=510.32], EntityLurker['Lurker'/12204, l='MpServer', x=-40.24, y=120.09, z=518.96], EntityChiromaw['Chiromaw'/11950, l='MpServer', x=-90.17, y=25.03, z=500.26], EntityChiromaw['Chiromaw'/12206, l='MpServer', x=-39.95, y=71.26, z=526.84], EntitySwampHag['Swamp Hag'/12079, l='MpServer', x=-44.50, y=83.00, z=476.50], EntityChiromaw['Chiromaw'/11952, l='MpServer', x=-97.78, y=24.80, z=510.95], EntitySwampHag['Swamp Hag'/12081, l='MpServer', x=-45.50, y=20.00, z=473.50], EntityLurker['Lurker'/12099, l='MpServer', x=-122.50, y=118.00, z=529.50], EntitySwampHag['Swamp Hag'/12102, l='MpServer', x=-58.50, y=88.00, z=524.50], EntityChiromaw['Chiromaw'/12104, l='MpServer', x=-63.50, y=97.10, z=517.50], EntityAngler['Angler'/12106, l='MpServer', x=-57.50, y=119.00, z=521.50], EntityAngler['Angler'/12110, l='MpServer', x=-57.61, y=119.00, z=509.28], EntitySwampHag['Swamp Hag'/11986, l='MpServer', x=-112.54, y=63.00, z=430.87], EntitySwampHag['Swamp Hag'/11988, l='MpServer', x=-110.84, y=61.00, z=436.41], EntityChiromaw['Chiromaw'/11990, l='MpServer', x=-48.92, y=58.97, z=482.67], EntityLurker['Lurker'/11992, l='MpServer', x=-53.99, y=120.21, z=476.80], EntityWight['Wight'/13147, l='MpServer', x=-101.50, y=74.00, z=516.50], EntityAngler['Angler'/11996, l='MpServer', x=-56.50, y=119.00, z=482.50], EntityAngler['Angler'/11998, l='MpServer', x=-54.43, y=119.00, z=493.55], EntityChiromaw['Chiromaw'/12000, l='MpServer', x=-61.97, y=96.00, z=474.81], EntityBloodSnail['Blood Snail'/12128, l='MpServer', x=-40.50, y=121.00, z=500.50], EntityChiromaw['Chiromaw'/12130, l='MpServer', x=-68.60, y=51.71, z=498.92], EntityAngler['Angler'/12006, l='MpServer', x=-60.34, y=9.00, z=473.60], EntityAngler['Angler'/12008, l='MpServer', x=-61.50, y=9.00, z=473.50], EntitySwampHag['Swamp Hag'/12139, l='MpServer', x=-162.48, y=120.72, z=527.77], EntityItem['item.tile.arsmagica2:tarma_root'/12524, l='MpServer', x=-97.13, y=54.00, z=530.30], EntityItem['item.tile.arsmagica2:tarma_root'/12525, l='MpServer', x=-99.11, y=54.00, z=529.92], EntityLeech['Leech'/12141, l='MpServer', x=-163.00, y=118.00, z=527.58], EntityPlayerSP['baluka44'/532, l='MpServer', x=-100.44, y=120.65, z=468.81]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1502389392 bytes (1432 MB) / 4216266752 bytes (4020 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 18
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 100 mods loaded, 100 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.3.2.1-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	bouncybeds{1.1} [Bouncy Beds] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	roxaendercloud{1.10.2v1.3.0} [Roxa's Ender Cloud Mod] (1.10.2v1.3.0_RoxaEnderCloudMod.jar) 
	UCHIJAAAA	roxaxpgem{1.10.2v1.5.0} [Roxa's Experience Gem Mod] (1.10.2v1.5.0_RoxaXpGemMod.jar) 
	UCHIJAAAA	forgeendertech{1.10.2-1.2.0.0} [Forge Endertech] (ForgeEndertech-1.10.2-1.2.0.0-build.0015.jar) 
	UCHIJAAAA	adhooks{1.10.2-1.1.0.0} [Advanced Hook Launchers] (AdHooks-1.10.2-1.1.0.0-build.0015.jar) 
	UCHIJAAAA	advancedcapes{5.0} [Advanced Capes] (advancedcapes-5.0.jar) 
	UCHIJAAAA	ambientsounds{1.2.0} [AmbientSounds] (AmbientSounds v1.2.1 mc1.10.2.zip) 
	UCHIJAAAA	appletrees{V2} [Apple Trees] (AppleTrees-1.10.2-V2.jar) 
	UCHIJAAAA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJAAAA	arsmagica2{1.5.017} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	astralsorcery{1.2.3-beta} [Astral Sorcery] (astralsorcery-1.2.3-beta.jar) 
	UCHIJAAAA	base{1.10.2-1.2.4} [B.A.S.E] (base-1.10.2-1.2.4.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	BaublesHud{3.2.0} [Baubles-Hud] (BaublesHud-1.10.2-3.2.0.jar) 
	UCHIJAAAA	bearwithme{1.0.0.0} [Bear With Me] (bearwithme-1.10.2-1.3.jar) 
	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJAAAA	betteragriculture{1.0.1} [Better Agriculture] (BetterAgriculture-[1.10.2]-1.0.1.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.7-76.jar) 
	UCHIJAAAA	BloodArsenal{1.10.2-2.0.1-17} [Blood Arsenal] (BloodArsenal-1.10.2-2.0.1-17.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	BuildersGuides{1.10.2-1.0.2} [Builder's Guides] (buildersguides-1.10.2-1.0.2.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	clumps{1.0.5} [Clumps] (Clumps-1.0.5.jar) 
	UCHIJAAAA	coralreef{1.0} [Coral Reef] (CoralReef-1.2.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHIJAAAA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.6.25 mc1.10.2.jar) 
	UCHIJAAAA	creeperconfetti{1.3} [Creeper Confetti] (creeperconfetti-1.2.1.jar) 
	UCHIJAAAA	cxlibrary{1.2.3} [CXLibrary] (cxlibrary-1.10.2-1.2.3.jar) 
	UCHIJAAAA	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.9.4-0.10.0.jar) 
	UCHIJAAAA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	darkutils{1.1.7.111} [Dark Utilities] (DarkUtilities-1.10.2-1.1.7.111.jar) 
	UCHIJAAAA	movingworld{1.10.2-0007} [Moving World] (movingworld-1.10.2-0007-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0006-full.jar) 
	UCHIJAAAA	dsurround{3.3.2.1} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.3.2.1.jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	everlastingabilities{1.2.4} [EverlastingAbilities] (EverlastingAbilities-1.9.4-1.2.4.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.4.4.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.4.3.jar) 
	UCHIJAAAA	geneticsreborn{0.01} [Genetics Reborn] (geneticsreborn-mc1.10.2-v1.0.jar) 
	UCHIJAAAA	gravestone{1.4.9} [Gravestone] (GraveStone Mod 1.4.9.jar) 
	UCHIJAAAA	grimoireofgaia{1.5.3} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.10.2-1.5.3.jar) 
	UCHIJAAAA	gud_clear_jukebox{1.0} [Clear Jukebox] (gud_clear_jukebox-1.0.0.1.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.10.2.jar) 
	UCHIJAAAA	jurassicraft{2.0.5} [JurassiCraft] (JurassiCraft-2.0.5.jar) 
	UCHIJAAAA	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.6.3228} [MineColonies] (minecolonies-universal-1.10.2-0.6.3228.jar) 
	UCHIJAAAA	morefood{1.17} [More Foods] (more-foods-1.10.2-2011-1.17.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.6} [More Furnaces] (MoreFurnaces-1.10.2-1.8.6.jar) 
	UCHIJAAAA	shetiphiancore{3.3.8} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.8.jar) 
	UCHIJAAAA	multibeds{1.2.4} [Multi-Beds] (multibeds-1.10.0-1.2.4.jar) 
	UCHIJAAAA	opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.3.3 mc1.10.2.zip) 
	UCHIJAAAA	packingtape{0.6.0} [Packing Tape] (PackingTape-1.10.2-0.6.0.jar) 
	UCHIJAAAA	simplerecipes{1.9.4-1.10.2a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.9.4-1.10.2a.jar) 
	UCHIJAAAA	petbat{1.4.6} [Pet Bat] (PetBat-1.10.2.jar) 
	UCHIJAAAA	placeableitems{3.0.4} [Placeable Items Mod] (placeableitems-3.0.4.jar) 
	UCHIJAAAA	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCHIJAAAA	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCHIJAAAA	reccomplex{1.2.10-1.10} [Recurrent Complex] (RecurrentComplex-1.2.10-1.10.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.639} [Reliquary] (Reliquary-1.10.2-1.3.3.639.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	rustic{0.1.2.1} [Rustic] (rustic-0.1.2.1.jar) 
	UCHIJAAAA	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.4.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCHIJAAAA	thebetweenlands{2.0.2-alpha} [The Betweenlands] (TheBetweenlands-2.0.2-alpha-universal.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UCHIJAAAA	ultimate_unicorn_mod{1.5.11} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.10.2-1.5.11.jar) 
	UCHIJAAAA	vampirism{1.0.3} [Vampirism] (Vampirism-1.10.2-1.0.3.jar) 
	UCHIJAAAA	teamlapen-lib{1.0.3} [TeamLapen Library] (Vampirism-1.10.2-1.0.3.jar) 
	UCHIJAAAA	vanillamagic{1.10.2-0.21.0.2} [Vanilla Magic] (vanillamagic-1.10.2-0.21.0.2.jar) 
	UCHIJAAAA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	waddles{0.5.0} [Waddles] (Waddles-1.10.2-0.5.0.jar) 
	UCHIJAAAA	wailafeatures{0.3.1.13} [WAILA Features] (WAILA-features-1.10.2-0.3.1.13.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	weaponcaseloot{4.0.2} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.2.jar) 
	UCHIJAAAA	wearablebackpacks{1.6.0} [Wearable Backpacks] (WearableBackpacks-1.10.2-1.6.0.jar) 
	UCHIJAAAA	witherskelefix{1.6.2} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.10.2-1.6.2.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.4.1.0.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  
bouncybeds (bouncybeds-1.10.2-1.1.jar)
  bouncy.beds.BouncyBedsTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
DummyPlugin (ForgeEndertech-1.10.2-1.2.0.0-build.0015.jar)
  
CreativePatchingLoader (CreativeCore v1.6.25 mc1.10.2.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.2.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  am2.asm.Transformer
CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  cubex2.cxlibrary.CoreModTransformer
llibrary (llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.2.3-beta.jar)
  
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13456 Compatibility Profile Context 21.19.164.257' Renderer: 'Radeon(TM) RX 460 Graphics '
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2239
	LWJGL: 2.9.4
	OpenGL: Radeon(TM) RX 460 Graphics  GL version 4.5.13456 Compatibility Profile Context 21.19.164.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: creeperyay (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by pau101** [comment]
Report to [Ars Magica 2](https://github.com/Mithion/ArsMagica2/issues).

**Comment by TheIcyOne** [comment]
Just to confirm, the Weedwood boat appears to use a custom entity for the camera position, yes?

**Comment by pau101** [comment]
That is correct, @TheIcyOne.
