### ISSUE TITLE
Change the Druid AI a bit

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#39]
I managed to beat them with no armour or food and only an iron sword, so I think a few tweaks are needed. 
Make the druid's throw much stronger again, as it first was (sorry, at first I thought it was too strong).
The teleport is freakin' terrifying, although could do with a few adjustments, since atm it appears to just fly towards the player very quickly.
When a druid teleports, there is a delay before it throws you. I think this needs to be removed, because it gives the player a chance to just whack it with a sword a couple of times, which could kill it easily.

**Comment by MrCompost** [comment]
Actually, instead you could change it so that they actual move slower, and appear to rush towards the player in a big cloud of smoke particles. That would probably work a lot better.

**Comment by vadis365** [comment]
Yeah vanilla teleporting is a bit poo (Endermen do the same).
I think I may be able to make a little 'hack' and stop the model from rendering while teleporting.
This will give the illusion, albeit for a split second, of the druid disappearing.

**Comment by MrCompost** [comment]
Don't worry about this one Sorin, Dave said he will look over it. Thanks.

**Comment by MrCompost** [comment]
Just pointing out that the issue still persists, and that you may want to tweak the effect they do when they teleport a bit.

**Comment by vadis365** [comment]
done - closing this.

**Comment by SanAndreasP** [comment]
You can auto-close this when committing something by having "closes #ISSUENUMBER" or "fixes #ISSUENUMBER" ;)

**Comment by vadis365** [comment]
I know that San, but Oli leaves comments and messages - so I like to manually close things sometimes just to check....
