### ISSUE TITLE
[BUG] Entity Pyrad Causing Crash

### ISSUE THREAD

**Issue by TartaricAcid** [TheCyberBrick/The-Betweenlands#390]
Minecraft Version: `1.10.2`;
Forge Version: `12.18.3.2239`;
The Betweenlands Version: `2.0.2-alpha`;
Use Optifine Version: `1.10.2_HD_U_D6`;
Here Is Crash Report: [Click](http://paste.ubuntu.com/24313938/);
How To Cause Crash: When I Hit The Pyrad, The Game Crash.

**Comment by TartaricAcid** [comment]
Thank you a lot. :+1:

**Comment by TheCyberBrick** [comment]
You're welcome, thanks for reporting!
