### ISSUE TITLE
The Betweenlands breaks Minecraft with Shaders

### ISSUE THREAD

**Issue by TomberWolf** [TheCyberBrick/The-Betweenlands#391]
We were using Shaders in our mod pack as long as I can remember without any problems.
Our new mod pack - based on MC 1.10.2 - contains severals shaderpacks, too.

As soon as The Betweenlands was added to the mod pack, Minecraft did not work anymore as it should.
Players aren't able to connect to servers anymore and stuck at the "Logging in" screen with game sounds playing in background.
In single player, the game stucks at world generating process at 0%.
If you want to load an existing world the loading process stucks at 0%, too.

We've tried everything to make sure which mod causes this issue and sadly it is The Betweenlands.

TheBetweenlands-2.0.2-alpha-universal
OptiFine_1.10.2_HD_U_D7
Forge 1.10.2 - 12.18.3.2281

We've tried these shaders:

- Sildurs Vibrant Shaders (Lite / Medium / HIgh)
- Conquest of the Sun
- KUDA

The only one that works is SEUS v11 but just with it's default settings.
As soon as you want to customize it, it doesn't work anymore.

**Comment by TheCyberBrick** [comment]
The Betweenlands has built-in shaders. If you want to use other shader mods you'll have to disable the Betweenlands shaders in the config file.
