### ISSUE TITLE
[1.10.2] BL Biome generation in Created Dimensions

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#392]
There might be a conflict with the mod Simple Dimensions and Biomes O Plenty which lets you create dimensions with commands.  When I create a dimension that uses normal BoP world generation I will get areas of Coarse Islands that generate at the 255 map height limit.

Not sure how to fix this.

https://www.dropbox.com/s/yw5x16vi5w9yy9y/2017-04-16_14.44.22.png?dl=0

https://www.dropbox.com/s/e8ogp9c5f5zctfy/2017-04-16_14.44.29.png?dl=0

**Comment by TheCyberBrick** [comment]
That's either a biome ID conflict or Simple Dimensions generates Betweenlands biomes. The Betweenlands biomes aren't programmed to work with the normal world generator, they should only be generated in the BL dimension.
