### ISSUE TITLE
Feature for Modpacks

### ISSUE THREAD

**Issue by Shazuli** [TheCyberBrick/The-Betweenlands#394]
***Hi!***

I'm creating a private pack for me and my friends use. We are currently not using that many mods as *1.10* version of *Minecraft* never got a stable modding ground, but more and more mods are currently being ported or created for this version.

Anyways, for the suggestion: **The Betweenlands** adds a extra bar above the health bar. But some other mods does the same, as the hunger bar is usually occupied by the armor points bar. One of the mods I have in my pack that adds a extra bar is [Tough as Nails](https://mods.curse.com/mc-mods/minecraft/246391-tough-as-nails), it adds a thirst bar similar to the hunger bar.
My suggestion is a config file where you can change the value for the X and Y location of the Decay bar and maybe a scale value similar to how [Custom main Menu](https://mods.curse.com/mc-mods/minecraft/226406-custom-main-menu) does. This change could benefit other modpack creators who wants to customize as much as possible in their preferred style.

This is absolutely nothing I demand, I am just a fan of the TB mod who also enjoys a good challenge.
Good work all of you in the **Angry Pixels** team!

**Comment by TheCyberBrick** [comment]
This is configurable, just forgot to close this.
