### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by 0Navis0** [TheCyberBrick/The-Betweenlands#398]
I started to get recently a crash at the startup of Minecraft, I don't really know what causes it. https://pastebin.com/MexvU5Lw

**Comment by theishiopian** [comment]
You should do some more testing and then report back if the issue persists. Try removing any coremods, including optifine, and post the crash if it still happens. If it doesn't, add the mods back until it does.

**Comment by TheCyberBrick** [comment]
This really shouldn't happen on a client. Either the mod file is corrupted or another (probably core-) mod messes it up. Please (re)download the latest version of the mod and try again.

**Comment by 0Navis0** [comment]
I redownload it and don't get more the crash. It was a really strange crash, I hadn't any ideas what caused it. Anyway thanks for the help guys.

**Comment by TheCyberBrick** [comment]
No problem. I guess the file somehow got currupted.
