### ISSUE TITLE
[1.10.2] Render Crash

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#399]
Got a weird crash when using the MCA Crystal ball...not sure when the crash log is calling BL...

https://pastebin.com/K0GY5eLG

**Comment by theishiopian** [comment]
Try disabling the betweenlands shaders and see if the issue persists.

**Comment by TheCyberBrick** [comment]
This should now be fixed. Please try again with the new version 2.0.3

**Comment by TheCyberBrick** [comment]
@MokahTGS have you tried again with the latest version?
