### ISSUE TITLE
The Betweenlands and Matter Overdrive Error

### ISSUE THREAD

**Issue by LuxerIThink** [TheCyberBrick/The-Betweenlands#400]
I have a problem with modpack, between two mods: The Betweenlands and Matter Overdrive. Can you see on this pastebin and help me with solve this error.
https://pastebin.com/FdTXiuBD

**Comment by theishiopian** [comment]
What makes you think it's matter overdrive causing the issue? Not saying its not, just curious.

**Comment by LuxerIThink** [comment]
I created modpack, which on start have The Betweenlands. When I add Matter Overdrive and Matter Overdrive core mods (Tesla and ShadowMC), modpack won't work. After that event I tested modpack which have only The Betweenlands, Mater Overdrive, Tesla, ShadowMC and crash is the same. At the end I tested The Betweenlands with Tesla and ShadowMC without Matter Overdrive and It's working. From logic, that is a crash between The Betweenlands and Matter Overdrive.

**Comment by theishiopian** [comment]
Ah, good to know. Make sure you also post this on the matter overdrive bug tracker.

-----Original Message-----

**Comment by TheCyberBrick** [comment]
~~This is the same as https://github.com/Angry-Pixel/The-Betweenlands/issues/399. This should already be fixed in the dev version and~~ I'll upload a new version today
Never mind, I looked at the wrong crash report. Either way, this is also fixed already in the dev version

**Comment by TheCyberBrick** [comment]
Update 2.0.3 is uploaded, please try again with the new version
