### ISSUE TITLE
1.7.10 Multiplayer Problem

### ISSUE THREAD

**Issue by TheCutter** [TheCyberBrick/The-Betweenlands#403]
Connecting to a SMP Server running the latest 1.7.10-server version on a vanilla forge-1.7.10-10.13.4.1614 server does not work with some clients.
The following errors are logged:
`	Line 10069: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Limestone Slab
	Line 10120: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Mossy Smooth Betweenstone Slab
	Line 10136: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Weedwood Planks Slab
	Line 10225: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Mud Brick Slab
	Line 10234: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Smooth Betweenstone Slab
	Line 10330: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Solid Tar Slab
	Line 10441: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Smooth Pitstone Slab
	Line 10447: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Smooth Cragrock Slab
	Line 10503: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Rubber Tree Planks Slab
	Line 10805: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Cracked Betweenstone Brick Slab
	Line 10848: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Cragrock Brick Slab
	Line 10872: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Temple Brick Slab
	Line 10884: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Pitstone Brick Slab
	Line 11691: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Mossy Betweenstone Brick Slab
	Line 11795: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Limestone Brick Slab
	Line 11873: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Betweenstone Brick Slab
	Line 11986: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Thatch Slab
	Line 12041: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Weedwood Planks Slab
	Line 12672: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Limestone Brick Slab
	Line 12927: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Smooth Cragrock Slab
	Line 13409: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Solid Tar Slab
	Line 13644: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Limestone Slab
	Line 14301: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Smooth Betweenstone Slab
	Line 14453: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Temple Brick Slab
	Line 14738: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Cracked Betweenstone Brick Slab
	Line 15246: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Mossy Betweenstone Brick Slab
	Line 15550: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Cragrock Brick Slab
	Line 15572: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Pitstone Brick Slab
	Line 15947: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Rubber Tree Planks Slab
	Line 15978: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Mossy Smooth Betweenstone Slab
	Line 16291: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Mud Brick Slab
	Line 16453: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Thatch Slab
	Line 16708: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Betweenstone Brick Slab
	Line 16736: [19:36:31] [Netty Client IO #1/INFO] [FML/]: Found a missing id from the world thebetweenlands:Smooth Pitstone Slab`

The same version of the Betweenlands mod works on another client.
Any ideas how to fix this?

**Comment by TheCyberBrick** [comment]
Please read "Creating Issues" (on [https://github.com/Angry-Pixel/The-Betweenlands](https://github.com/Angry-Pixel/The-Betweenlands)) on how to properly write an issue the next time.
Since you didn't specify, I'll assume you're running a non-vanilla (vanilla as in the forge installed on the vanilla server jar) server which could be the cause of this.

**Comment by TheCutter** [comment]
Oh sorry, didn't and still can't find the "Creating Issues" Topic...

Yes I'm running forge-1.7.10-10.13.4.1614 on my server on top of vanilla server jar.
What I don't understand is that one client works perfectly and the same modpack on another client doesn't work with the errors above.

**Comment by TheCyberBrick** [comment]
It's on the front page I linked, it's hard to miss.
If you have other mods installed, try removing some of them until the problem is gone

**Comment by TheCutter** [comment]
Oh man, sorry. found it :)
Did you make any changes to the Slab Registration? As it seems that all the slabs are missing in the one client!?

**Comment by TheCutter** [comment]
wrong button , sorry xD

**Comment by TheCutter** [comment]
Yesterday evening the client was able to connect to the server without any problem. Today the same problem again. Could you please give me any hint where to look or what to do? :/

**Comment by TheCyberBrick** [comment]
> If you have other mods installed, try removing some of them until the problem is gone

It's difficult to tell what's wrong because you're using a modpack and I can't reproduce this.

**Comment by TheCutter** [comment]
I can't remove any mods from the modpack... :(
But I can give you the link to the modpack: https://www.technicpack.net/modpack/survivorspack.926205 and the server IP via private message.

**Comment by TheCyberBrick** [comment]
I'm sure you can remove mods. The point is to just temporarily remove them to figure out if another mod causes this problem with the BL

**Comment by TheCutter** [comment]
Ok nevermind, I removed the Betweenlands mod, as it seems to be a little bit buggy in the 1.7.10 version.
