### ISSUE TITLE
Cursed Earth Mob Farm Memory Leaks Server When Betweenlands Installed

### ISSUE THREAD

**Issue by theaardvarker** [TheCyberBrick/The-Betweenlands#406]
Not sure if you care about cross mod issues.  The mobs used were eu2, mob grinding utilities, ender io, and enderchests.  A lot more mods were installed on the server but the conflict arose with this type of farm.

Here's a crash log.
https://pastebin.com/MvQkSS5u

Don't know if that helps but when I removed betweenlands the mob farm works without lagging and crashing the server.

The mob farm is placed in the overworld.

Edit:

Okay, I solved the problem by changing the mob spawning numbers in the config from whatever they were by default to 100000.

It's not like this was a giant cursed earth farm spawning thousands of mobs though so not sure why that helped.

http://imgur.com/a/IuN1e

Anyway, I'll leave this up since it seems a little buggy.  Glad the mod works well after this change.

**Comment by vadis365** [comment]
Seems old and resolved.
