### ISSUE TITLE
Ocean world

### ISSUE THREAD

**Issue by LuxerIThink** [TheCyberBrick/The-Betweenlands#407]
I have a problem bettwen Geographicraft (old Climate Control) with Realistic Terrain Generation and The Betweenlands. The Betweenlands World is a large ocean from bedrock to 120 block height, with dirt clusters or slime islands from tinker. Thanks for help :)

**Comment by TheCyberBrick** [comment]
That's a problem on Geographicraft's side, see #388.
If you want to use the BL and have similar features to Geographicraft you can use Biometweaker instead.
