### ISSUE TITLE
Rowboats Wandering

### ISSUE THREAD

**Issue by Zorlockthewarlock** [TheCyberBrick/The-Betweenlands#410]
the Rowboats seem to wander when placed, floating around in random directions, this is kind of nice because it looks like they are being moved around by the currents, but not very useful if you intend on coming back to your boat after you left it somewhere, perhaps a solution could be letting you tie boats to fenceposts using reed rope, similar to leads and animals using the reed rope.

**Comment by TheCyberBrick** [comment]
You can right-click on the Weedwood Rowboat with a [Tar Drip](http://the-betweenlands.wikia.com/wiki/Tar_Drip) which will create a Tarred Weedwood Rowboat that isn't affected by waves anymore
