### ISSUE TITLE
Betweenlands shader issue

### ISSUE THREAD

**Issue by Nyanico** [TheCyberBrick/The-Betweenlands#415]
Is there a way to have the Betweenlands original shaders on when I get into the Betweenlands and when I get back to the over-world for it to have my own shaders on (I use SEUS shader and minecraft 1.10.2). 

Help would be appreciated!

**Comment by Los2tale** [comment]
if you want to use shader only in overworld but not appear in other dimention jusr create a folder name "world0" in shader folder then move everything in shader to this folder except a shaders.properties file

ps.sorry for my bad english
ps2. still disable BL shader
ps3. this work for me i have a shader in overworld and keep mood of BL

**Comment by MrRedstoneA1** [comment]
Sorry to comment on closed issue, but I figured out a fix for Sildur's shaders. Like Los2tale said above, you need to open the zip file, go to shaders and create a folder named world0. **Do not move every file** inside world0 folder! leave **world1** **and world-1** in their places, leave all of the **properties** files in place. Move every other file inside the **world0** folder. This fixes the water shader not working in the overworld and doesn't result in screen freeze when entering the betweenlands.
