### ISSUE TITLE
Dimension ID conflict

### ISSUE THREAD

**Issue by Havoc1001** [TheCyberBrick/The-Betweenlands#416]
Just recently added The betweenlands to my mod pack, and when used the portal i arrived in the new lands and it said on the screen "No oxygen" and i started dying. Now i have Advanced rocketry mod installed also, but i have checked the dimentions id's and there are no conflicts in the numbers. All of The Betweenlands are in the 20's and 50's, AR is all in the 90's on id's.....Anyone having this problem?

**Comment by vadis365** [comment]
Add BL dimension ID to whatever black list that mod has - though this was nearly a year back so closing, as I doubt it's still needed.
