### ISSUE TITLE
Unable to make this mod work on 1.7.10

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#417]
I cannot make this mod work with or without Optifine  on the latest forge 

- It has a lot of rendering issues
- ticking entity issues whenever the Druid circle spawns
- the way the played is rendered is broken i can see myself outside myself
- cannot work with optifine
- cannot work with shaders
- random crashes
- instant crashes
- index out of bounds errors  java.lang.ArrayIndexOutOfBoundsException: 126430 (numbers keep changing but happens soon after world load)
- without limit biome ids  set to false biomes are ID crash saying biome id is 269  regardless of what id i choose in config and it crashes even tho 269 id is perfectly safe id to use for biome . 

sounds like a great mod but is really broken on 1.7.10
maybe it works better on 1.10+

As far as I can tell there is more work put in 1.10 version than in 1.7.10 version or 1.7.10 is tougher to get working properly. Seems like no matter what I do I can never make this mod work. I haven't been able to go to the dimension cannot find portals, keeps crashing when circles spawn, crashes at world load. is impossible

**Comment by TheCyberBrick** [comment]
We don't plan on updating the 1.7.10 version anymore. If you want to use this mod the 1.10 version is your best bet, it runs much better and is also more stable.

Anyways, maybe I can help you with some of the problems, but I need more information:

> It has a lot of rendering issues

Like what? This is too vague. Any pictures? Maybe disable the Betweenlands' shaders in the config, some systems (especially with integrated graphics cards) can't handle those well.

> ticking entity issues whenever the Druid circle spawns

What do you mean by "ticking entity issues"?

> cannot work with shaders

Yes it can. You need to disable Betweenlands' shaders in the config

> random crashes, instant crashes

I can't help without crash log

> even tho 269 id is perfectly safe id to use for biome

No it's not. The maximum ID you can use is 255 (unless you use some mod that increases the limit). The biomes in the BL also have a mutation with id + 128, thus the maximum ID you can use for a BL biome is 127 (this is no longer the case in the 1.10 version though)

**Comment by ghost** [comment]
Is pretty vague because it won't make a difference since 1.7.10 is somewhat less important right now as everyone is trying to move towards 1.12 

I had this big discussion about the issue with modding for minecraft and got kicked out of that discord server for suggesting to freeze and backport all mods to one MC version. Anyway I won't go there. Just so you know this mod is severely broken for 1.7.10 is pointless even having a download as is not useable in any shape for form. That 1.7.10 mod file is useless as it stands. Great mod just can't be played.

I'll get to try it out when I will get to 1.10

**Comment by TheCyberBrick** [comment]
Sure, but then don't expect any help because I can't help without the information.
83560 people have downloaded the 1.7.10 version and nobody reported it as _that_ broken. Surely most of those people were able to run it.

**Comment by TheCyberBrick** [comment]
Just tried it myself. OptiFine works fine:
![](http://i.imgur.com/BM5AtBX.png)
