### ISSUE TITLE
1.10.2 -2.0.4 Ticking Entity

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [TheCyberBrick/The-Betweenlands#418]
https://pastebin.com/JRh6dvsf

I dont actually know how this happened, i may have spawned it in but I dont think so.

**Comment by TheCyberBrick** [comment]
That's pretty weird. Please remove all other mods temporarily (except Forge of course) and then spawn the "Primordial Malevolence" in a new world and see if the same thing still happens.

**Comment by EPIICTHUNDERCAT** [comment]
will do as soon as i get the chance :)

**Comment by EPIICTHUNDERCAT** [comment]
tested with the mod alone, nothing happened. I spawned in the fortress boss. any ideas what It can be? I may just have to remove the mod.

**Comment by TheCyberBrick** [comment]
Okay thanks for testing it out. It's probably caused by another mod messing with the datawatcher then (which it shouldn't), there's not much we can do about that. The only thing we can do is figuring out which mod causes the problem and then reporting it to the author.

**Comment by EPIICTHUNDERCAT** [comment]
thought so! I can try to troubleshoot :P but who knows how far itll go

**Comment by TheCyberBrick** [comment]
Heh, that'd be awesome if you could do that! Is that modpack you're using available for download somewhere so I could try it out myself?

**Comment by EPIICTHUNDERCAT** [comment]
https://discord.gg/CUAYj4P join this, its my teams discord. This is where we make our packs :P (easier for me to send too!)

**Comment by EPIICTHUNDERCAT** [comment]
(still troubleshooting) No luck yet but ive lowered the amount of mods im working with, crash still happening.

**Comment by EPIICTHUNDERCAT** [comment]
ive lowered it to about 10 mods, im thinking its slashblade but letssss seee!

**Comment by EPIICTHUNDERCAT** [comment]
RIP it like stopped crashing now >.> went down to the point it stopped crashing and now testing every mod it stopped.. must be a combo of mods that creates the issues. but i have no idea which it could be.. welp this was a waste of time..

**Comment by EPIICTHUNDERCAT** [comment]
yea its odd, it was crashing with certain mods (had about 25 loaded) once i started removing it stopped, i readded the 25 that where still crashing and it wouldnt crash anymore.. i dont even know.
