### ISSUE TITLE
Cant play the game, it crashes

### ISSUE THREAD

**Issue by Initrox2** [TheCyberBrick/The-Betweenlands#419]
> The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
> Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)
> 

I play on forge 1.11.2

**Comment by TheCyberBrick** [comment]
Well there's your problem, there's no Betweenlands version for 1.11.2 :P
