### ISSUE TITLE
Materials list for general materials class

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#42]
Middle Gems (there are currently 3 - Aqua, Crimson and Green - but this is probably subject to change)
Blood Snail Shell
Mire Snail Shell
Idols (Bronze, Silver and Gold)
Lurker Skin (file name says crocodile)
Compost
Dragonfly Wing
Swamp Reed
Dried Swamp Reed
Swamp Reed Rope
Swamp Reed Powder (I cant even remember what this is for, add it anyway =P )
Life Crystal
Middle Fruit Seeds (file name says middle fruit)
Mire Coral
Moss
Mud Brick (item, I mean)
Octine Ingot
Rotten Bark
Sap Ball
Slimy Bone
Slimy Bonemeal
Sludge Ball
Snapper Root
Spores
Stalker Eye
Sulfur
Valonite Shard
Weedwood Stick
Wick (don't think we need this any more but add it just in case)
Wight Heart

**Comment by vadis365** [comment]
Slimy Bonemeal is missing as it had no texture :P
