### ISSUE TITLE
1.10.2 Being in the Betweenlands dimension causes major ping increase.

### ISSUE THREAD

**Issue by LeFrenjmun** [TheCyberBrick/The-Betweenlands#425]
A friend of mine hosted a server with Betweenlands, and when ever I enter the Betweenlands my ping goes through the roof and stays at around 1000ms. As soon as I go back to the overworld the lag stops. These issues don't affect my friend and I've tried changing forge versions to no avail. We are using ATLauncher and a tested a clean minecraft 1.10.2 instance w/ just Betweenlands. Instead of port forwarding we use Hamachi, I wouldn't know if that could cause any problems and it hasn't acted up for as long as we used it.

Using forge-1.10.2-12.18.3.2511-universal  and Betweenlands v2.0.4

As for the client log, I can get it if you need.

**Comment by vadis365** [comment]
Probably not needed anymore. We have all aged since this and moved on to new versions.
