### ISSUE TITLE
1.12.2 Crash and other errors when coating tools.

### ISSUE THREAD

**Issue by 63502** [TheCyberBrick/The-Betweenlands#431]
The game crashes when crafting tools with scabyst in order to coat them. More specifically, it seems that the game is trying to coat air blocks, which are an invalid object to be coated instead of just recognizing that no valid corrodible tool is present.

Also on a possibly unrelated note, the GUI of a weedwood workbench that has been used to successfully(no crash + coated item) or unsuccessfully(crash + deleted item) coat something can not be accessed until it has been broken and replaced.

[Crash Report](https://gist.github.com/63502/874dc34d461d0c5c1614c172b4381947)

**Comment by TheCyberBrick** [comment]
Will be fixed in the next version, thanks!

**Comment by 63502** [comment]
Ok, cool. I'll keep an eye out for any more weirdness while I'm playing in my survival world.
