### ISSUE TITLE
Optifine Invisible/No render [1.10] [SOLVED]

### ISSUE THREAD

**Issue by Agalyon** [TheCyberBrick/The-Betweenlands#432]
[1.10], Betweenlands alpha 2.0.4
Optifine is causing the betweenlands to have no rendering, essentially making everything 'invisible' if you will. The UI, inventory, WAILA, and sky are all fine but I can't actually see anything else. I'm free to walk around and leave, but otherwise can't do much besides place blocks. I've read about having a black screen because of having fast render turned ON but I have mine off and this issue still occurs. I understand optifine isn't really supported, but I couldn't find anything about this specific issue on google and I'm almost certain I remember using optifine just fine a few months back, around 2.0.2. I've tested with the betweenlands shader turned off with the config which seems to work fine, but its such a shame to turn it off and everything I've read says turning off fast render fixes it, so I'm making an issue in case this is a new problem.

**Comment by TheCyberBrick** [comment]
Make sure that no other shaders are active in Optifine. If I remember correctly Optifine has some sort of internal shader which might be the cause of this.

**Comment by Agalyon** [comment]
Ahhh alright, ill look into that. Usually if I click anything in the shader menu it just straight freezes but, here we go.

**Comment by Agalyon** [comment]
Awesome tip, that fixed it. For anyone else trying to fix this, you can turn off the optifine shader without opening minecraft by going to the main directory in optionsshaders.txt and changing the second line to
shaderPack=OFF

Thanks again for the help.

**Comment by TheCyberBrick** [comment]
Ah nice! Good to know, thanks.
