### ISSUE TITLE
Things to be worked on for 1.12 release

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/The-Betweenlands#434]
* [x] Lurker AI in water still seems borked (bobs around in place rather than moving) - similar issues apply to Blind Cave Fish
* [x] Druid Chant sound in Altar only plays for the first Talisman construction
* [x] Somehow you can get aspectless Aspect Vials through the Infuser (happened to guy on stream)
* [ ] ~Modded armour render bugged in boat~  
  No longer breaks the textures, but animations aren't applied to armour. Not sure if can be fixed?
* [x] Dual furnace top flux slot needs looking at, apparently broken
* [x] Sometimes Fireflies don't fly at all (see Darko stream) or swim underwater and drown.
* [x] Make Explorer's Hat repairable in animator (should probably use lurker skin equivalent values)
* [x] Add oredict values

Suggestions/Areas of Improvement:
* [ ] Volarkite (maybe for the update after since it needed reworking)
* [x] Add Coarse Swamp Dirt recipe
* [x] New texture for Coarse Swamp Dirt
* [x] It'd be cool if you could make the old Weedwood Bark block (the one with bark on all sides) with a 2x2 square of Weedwood Logs, kinda like how vanilla will be doing it
* [x] There's a "Carved Cragrock" block that looks identical to the Chiseled Cragrock and generates in Cragrock Towers, maybe remove that and just make the tower generate chiseled cragrock?
* [x] The Gecko Cage doesn't currently drop the Gecko when mined, it could either leave behind the entity itself or just the caught item
* [x] Patchy Islands used to have Weedwood trees that would gen in the water. If possible we could  
  maybe bring those back. Decoration is pretty good overall, but perhaps reduce the amount of giant  
  shrooms a fair bit.
* [ ] TEs that require shift, right-click to use should have a bit of text pop up telling you that  
   when you place them down.
* [x] Weedwood tree leaves should have biome colours like grass.  
* [ ] I realised that we really ought to have maps. We have amate paper, so why not amate
  paper maps that work in the BL? Needs marker textures if locations should show up
* [x] Add (optional) keybinds to disconnect from Caving Rope or to connect to the closest end point
* [x] Placing moss on an octine block should also light it on fire
* [x] Octine blocks should give off light, just like the ore does
* [x] Plants should be able to be placed on mudbrick blocks
* [x] Shields need some tooltip info on their extra abilities
* [x] ~Mire Snails should be able to be picked up with a net for easier transportation~  
  Player should be able to pick up and move snail eggs

**Comment by 63502** [comment]
(I will update this as I find things.)
### Small bugs/problems I noticed while playing:

- ~~Fences attempt to connect to non-full blocks like slabs, snow, and the incomplete faces of stairs(haven't tested walls yet, will do later).~~ This was fixed recently in the dev version

- ~~Snow collects on the top of non-full blocks like twisted roots, bottom slabs, stairs, and other various objects it probably shouldn't be on.~~ Was the same problem as above ^

- ~~Sludges, frogs, and dragonflies don't drop xp.~~

- ~~Nettles are WAAAY too brutal on armor durability. They deal one point of durability for each time they deal damage. even  full valonite, which can last for ages without mending and/or unbreaking gets ripped to shreds by even light exploration of swamplands and marshes.~~ Nettles will be far less common, but not less damaging.

### Suggestion:

- ~~I'm not sure if this has been suggested or discussed before, but would it be possible to make some way to repair existing tools/armor without leaving the betweenlands? Washing off decay and applying coating is fine and all, but it's a real headache to have to waste time getting resources and middle gems to re-craft armor every other day, especially with full gem upgraded valonite being my current set. Having to go back to the overworld to trade with villagers for mending books just doesn't cut it, especially for a Betweenlands only survival.~~ Animator now repairs tools.

**Comment by TheCyberBrick** [comment]
@63502 
> Nettles are WAAAY too brutal on armor durability. They deal one point of durability for each time they deal damage. even full valonite, which can last for ages without mending and/or unbreaking gets ripped to shreds by even light exploration of swamplands and marshes.

Nettles will be less common in the next version.

> I'm not sure if this has been suggested or discussed before, but would it be possible to make some way to repair existing tools/armor without leaving the betweenlands? Washing off decay and applying coating is fine and all, but it's a real headache to have to waste time getting resources and middle gems to re-craft armor every other day, especially with full gem upgraded valonite being my current set. Having to go back to the overworld to trade with villagers for mending books just doesn't cut it, especially for a Betweenlands only survival.

It's funny that you mentioned this, just a few days ago we came to the same conclusion and made the Animator be able to repair BL tools/armour :P

**Comment by 63502** [comment]
@TheCyberBrick 
> It's funny that you mentioned this, just a few days ago we came to the same conclusion and made the Animator be able to repair BL tools/armour :P

Hmmm... interesting idea. I take it the animator will fully repair an item with one operation? With the thing chewing through sulfur like it does, it seems(to me) like a reasonable thing to do.

**Comment by TheCyberBrick** [comment]
@63502 yes it does fully repair the tool. Depending on the rarity of the material and how much needs to be repaired it costs more Sulfur and Life Crystal

**Comment by TripleHeadedSheep** [comment]
Regarding maps and amate paper. We should really do more with amate paper. Some stuff has already been suggested, but never worked on. 
I think making a unique map would take a bit too long for the 1.12 update.
