### ISSUE TITLE
[1.12.2] Issues with using Syrmorite Shears on crops

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#435]
Using Syrmorite Shears on planted Yellow Dotted Fungus, White Pears and Aspectrus Plants (any stage of growth as far as I can tell) causes them to drop their seed, but under the ID of the crop block itself with no proper lang and separate from the actual seed item. In the case of Aspectrus Plants, the Rubber Tree Plank Fence it was growing on disappears in the process.

**Comment by TheCyberBrick** [comment]
wat, lol
