### ISSUE TITLE
Spawn checking to be sure you are on the surface.

### ISSUE THREAD

**Issue by Tedyhere** [TheCyberBrick/The-Betweenlands#439]
Hello, I am using Betweenlands as a starting dimension and I'd say roughly about 70% of the time I spawn in the caverns.  Would it be possible to add a check when just doing a normal spawn into the world without a portal that you spawn at surface levels?

I am using Just Enough Dimensions to set my spawn dimension so no portal tree is used. 

If this is too big of an issue I will find a workaround.

**Comment by TheCyberBrick** [comment]
How Just Enough Dimensions spawns the player is not under our control. The water level is much higher in the Betweenlands and I'm assuming that's what causes this problem. If you want you could report that to Just Enough Dimensions' author and ask if he could add a check for the surface height.
