### ISSUE TITLE
Texture for Life Crystal Ore is broken.

### ISSUE THREAD

**Issue by 63502** [TheCyberBrick/The-Betweenlands#441]
Screenshots of invisible or glitched life crystal stalagmites.
![2017-12-17_17 43 48](https://user-images.githubusercontent.com/15267053/34084737-731dc642-e353-11e7-8ea9-4305abfaf104.png)
![2017-12-17_17 46 29](https://user-images.githubusercontent.com/15267053/34084738-75b2adb4-e353-11e7-97f1-c91013fc1f33.png)

**Comment by TheCyberBrick** [comment]
Please update your issue with the required infos

**Comment by TheCyberBrick** [comment]
Probably 1.12 right? Any other mods installed?

**Comment by 63502** [comment]
I forgot the info, sorry. -_-

I'll have it up in a sec.

**Comment by 63502** [comment]
I forgot the info, sorry. -_-

[Mod List](https://gist.github.com/63502/18dffa35d89d51375093932e8773b2c6)

**Comment by 63502** [comment]
It just seems to me that the actual life crystal ore block's texture doesn't want to connect properly with the rest of the stalactite/stalagmite/column.

**Comment by TheCyberBrick** [comment]
Hm ok, thanks. I'll look into it when I have time.

**Comment by TheCyberBrick** [comment]
I'm not sure what exactly causes this for you, but I added a config entry to disable the glow of the ore (that should fix your problem) which will be in the next release.
