### ISSUE TITLE
chunk bug

### ISSUE THREAD

**Issue by coldblacksnow** [TheCyberBrick/The-Betweenlands#442]
1.12.2-forge1.12.2-14.23.1.2555
TheBetweenlands-3.2.1-alpha-snapshot-universal
singleplayer

I accidentally broke portal in the Betweenlands so i create new one(far away from first) to get back and after tp to overworld i got this
![2017-12-18_22 41 19](https://user-images.githubusercontent.com/34198111/34127618-78513cb8-e446-11e7-8e78-f4e46273d2e4.png)
![2017-12-18_22 41 53](https://user-images.githubusercontent.com/34198111/34127636-8a387720-e446-11e7-80d1-011cf364d7d5.png)
![2017-12-18_22 44 15](https://user-images.githubusercontent.com/34198111/34127658-9a45fb7e-e446-11e7-9c8c-736d212d785a.png)

**Comment by 63502** [comment]
Uhhh.... Build a base in it? Maybe? It's obviously not supposed to be there, but it's quite spectacular.

**Comment by coldblacksnow** [comment]
made some tests today, probably it's my fault
how to reproduce it
1 in creative gamemode create a new portal far away from the first and go in
2 hold "w" to run forward while loading(as you are in creative mode you will immediately tp) so after appiring in overworld, befor all chunks normaly loaded, you will tp back to Betweenlands(continue holding "w") after tp back to overworld this happening
![2017-12-19_15 58 08](https://user-images.githubusercontent.com/34198111/34160479-cd974ab6-e4d5-11e7-8b81-f6a174df3727.png)
![2017-12-19_16 09 37](https://user-images.githubusercontent.com/34198111/34161222-9cacd5c6-e4d8-11e7-877d-c62459d294f1.png)

maybe need to make a bit more tests, but you should turn on delay between tp in creative mode

ps few time after tp to overworld, i appeared without "portal tree"
once in ocean and second in forest(probably because"the space is not large enough")

**Comment by TheCyberBrick** [comment]
That is *very* bizarre and I'm unable to reproduce this. I don't see how this can happen... By the looks of it, even the biomes are generated, but that's not possible because the only place where those are generated is in the dimensions generator. Do a fresh install of everything and make sure only Forge and the Betweenlands is installed.
