### ISSUE TITLE
Spawning Primordial_Malevolence crashes Minecraft (Multiplayer)

### ISSUE THREAD

**Issue by DeadPigman17** [TheCyberBrick/The-Betweenlands#443]
My server crashes whenever Primordial_Malevolence is spawned.

I'm using Forge 1.12.2-forge1.12.2-14.23.1.2566 and the Betweenlands 3.1.0-alpha-snapshot-universal

Here's the crashlog: https://ptpb.pw/zEL0

**Comment by TheCyberBrick** [comment]
Please try with the latest version

**Comment by DeadPigman17** [comment]
It still crashes the game, here's the new crashlog (even though it's the same error, i think): https://ptpb.pw/w3Us

**Comment by TheCyberBrick** [comment]
Please send the whole log. And it looks like that's a server log so you also need to send me the client log.

**Comment by DeadPigman17** [comment]
Ok, I found out it's an incompatibility with Mo'Creatures (which I was previously using). Here are the logs: 
Server: https://ptpb.pw/MgWA
Client: https://ptpb.pw/GfJY

**Comment by TheCyberBrick** [comment]
Ok, thanks for figuring out what it was. Mo'Creatures' source unfortunately isn't public and whatever happened here shouldn't be possible unless another mod breaks something of the entity. I recommend you report this issue on Mo'Creatures issue tracker instead: https://github.com/DrZhark/mocreatures/issues

**Comment by TheCyberBrick** [comment]
Can confirm, only happens when Mo'Creatures is installed

Edit: Seems like it only happens when both Mo'Creatures and CustomMobSpawner is installed

**Comment by TheCyberBrick** [comment]
I'll keep this open for a little longer, but I'm pretty sure the problem is not on our side
