### ISSUE TITLE
[Suggestion] Some rewritten Herblore Book entries

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#446]
Just rewrote Infusion entries for the Herblore Book so they flow better (no offense to Bart he's a cool dude)

- The Brew of the Cat's Eye makes the eyes extremely sensitive to light, allowing those afflicted to see very well in the dark. A combination of Freiwynn, Dayuniis, Ordaniis, and Geoliirgaz aspects is required to make this brew. The more Freiwynn is used, the stronger are the brew's effects. The more Dayuniis is used, the longer the brew lasts. Adding Byariis will corrupt the nature of the brew, turning it into the Blindman's Brew, which blinds those afflicted.
- The Draught of Sagittarius contains the power of Sagittarius, allowing those afflicted to see exactly what path their arrow will take when fired from a bow. A combination of Freiwynn, Dayuniis, Byariis, Ordaniis, and Armaniis aspects is required to make this draught. The more Freiwynn is used, the stronger are the draught's effects. The more Dayuniis is used, the longer the draught lasts. Leaving out Byariis will reveal the true nature of the draught, turning it into the Weakbow Draught, which reduces the bow shooting range of those afflicted.
- The Draught of the Unclouded clears a foggy mind, allowing those afflicted to see through dense fog as if it evaporated in front of their eyes. A combination of Dayuniis, Freiwynn, Geoliirgaz, Ordaniis, and Yunugaz aspects is required to make this draught. The more Geoliirgaz is used, the stronger are the draught's effects. The more Dayuniis is used, the longer the draught lasts. Adding Byariis will corrupt the nature of the draught, turning it into the Draught of the Fogged Mind, which causes those afflicted to hallucinate a very dense fog around them.
- The Elixir of Feasting gives the stomach something tough to feed on, satisfying the hunger of those afflicted over time. A combination of Yeowynn, Ordaniis, and Celawynn aspects is required to make this elixir. The more Celawynn is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Adding Byariis will corrupt the nature of the elixir, turning it into the Elixir of Starvation, which causes those afflicted to go hungry more quickly.
- The Elixir of Healing accelerates natural regeneration, healing the wounds of those afflicted over time. A combination of Yeowynn and Ordaniis aspects is required to make this elixir. The more Yeowynn is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Adding Byariis will corrupt the nature of the elixir, turning it into the Elixir of Draining, which drains the health of those afflicted over time.
- The Elixir of Ripening reverses the effects of the decaying aura of the Betweenlands, restoring the physical and psychological health of those afflicted over time. A combination of Yeowynn, Ordaniis, and Dayuniis aspects is required to make this elixir. The more Dayuniis is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Adding Byariis will corrupt the nature of the elixir, turning it into the Elixir of Decay, which accelerates the decaying aura’s effects on those afflicted.
- The Elixir of Strength increases raw physical strength, causing those afflicted to deal more damage when they attack. A combination of Azuwynn and Ordaniis aspects is required to make this elixir. The more Azuwynn is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Adding Byariis will corrupt the nature of the elixir, turning it into the Elixir of Weakness, which reduces the damage dealt by those afflicted.
- The Hunter’s Sense Brew enhances the senses, allowing those afflicted to see and smell the scent trails of creatures in order to track them down. A combination of Freiwynn, Dayuniis, Ordaniis, and Firnalaz aspects is required to make this brew. The more Freiwynn is used, the stronger are the brew’s effects. The more Dayuniis is used, the longer the brew lasts. Adding Byariis will corrupt the nature of the brew, turning it into the Drunkard’s Brew, which causes those afflicted to experience heavy nausea. 
- The Lightweight Draught causes a strange sensation of weightlessness, allowing those afflicted to walk slowly over water as if it were solid ground. A combination of Azuwynn, Byrginaz, Yunugaz, Yihinren, and Geoliirgaz aspects is required to make this draught. The more Yunugaz is used, the stronger are the draught’s effects. The more Yihinren is used, the longer the draught lasts. Adding Byariis will corrupt the nature of the draught, turning it into the Heavyweight Draught, which makes those afflicted unable to swim and causes them to sink in mud no matter what they are wearing to counteract it.
- The Masking Brew masks natural odors like a perfume, making it harder for those afflicted to be detected by predators. A combination of Dayuniis, Armaniis, and Byariis aspects is required to make this brew. The more Armaniis is used, the stronger are the brew’s effects. The more Dayuniis is used, the longer the brew lasts. Leaving out Byariis will reveal the true nature of the brew, turning it into the Stenching Brew, which makes it easier for those afflicted to be detected by predators.
- The Nimblefeet Elixir enhances muscle swiftness and nimbleness, increasing the movement speed of those afflicted. A combination of Azuwynn, Ordaniis, and Yunugaz aspects is required to make this elixir. The more Yunugaz is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Adding Byariis will corrupt the nature of the elixir, turning it into the Lumbering Elixir, which slows the movement of those afflicted.
- The Spiderbreed Draught changes the workings of the skin and muscle, allowing those afflicted to climb up and down any obstacle as if they were an insect. A combination of Azuwynn, Fergalaz, Dayuniis, Yihinren, and Yunugaz aspects is required to make this draught. The more Azuwynn is used, the stronger are the draught’s effects. The more Yihinren is used, the longer the draught lasts. Adding Byariis will corrupt the nature of the draught, turning it into the Basilisk Draught, which paralyzes those afflicted.
- The Swiftarm Brew enables arm muscles to work to their fullest, increasing the arm swinging speed of those afflicted and thus allowing them to mine faster, pull back bows more rapidly, and strike foes more easily. A combination of Azuwynn, Dayuniis, Yunugaz, and Ordaniis aspects is required to make this brew. The more Azuwynn is used, the stronger are the brew’s effects. The more Ordaniis is used, the longer the brew lasts. Adding Byariis will corrupt the nature of the brew, turning it into the Slugarm Brew, which decreases the arm swinging speed of those afflicted.
- The Toughskin Elixir increases skin toughness, protecting those afflicted from harmful plants found throughout the Betweenlands. A combination of Azuwynn, Yeowynn, and Celawynn aspects is required to make this elixir. The more Yeowynn is used, the stronger are the elixir’s effects. The more Celawynn is used, the longer the elixir lasts. Adding Byariis will corrupt the nature of the elixir, turning it into the Poisonsting Elixir, which instantly poisons those afflicted.
- The Basilisk Draught petrifies the motor cortex of the brain, causing those afflicted to be frozen in place. A combination of Azuwynn, Fergalaz, Dayuniis, Yihinren, Yunugaz, and Byariis aspects is required to make this draught. The more Azuwynn is used, the stronger are the draught’s effects. The more Yihinren is used, the longer the draught lasts. Leaving out Byariis will reveal the true nature of the draught, turning it into the Spiderbreed Draught, which allows those afflicted to climb on obstacles.
- The Blindman’s Brew severely limits the functions of the eye, causing those afflicted to only be able to see a small distance in front of them and be unable to sprint. A combination of Freiwynn, Dayuniis, Ordaniis, Geoliirgaz, and Byariis aspects is required to make this brew. The more Freiwynn is used, the stronger are the brew's effects. The more Dayuniis is used, the longer the brew lasts. Leaving out Byariis will reveal the true nature of the brew, turning it into the Brew of the Cat’s Eye, which allows those afflicted to see in the dark.
- The Draught of the Fogged Mind clouds the mind with worrisome thoughts, causing those afflicted to see the illusion of a thick fog surrounding them. A combination of Dayuniis, Freiwynn, Geoliirgaz, Ordaniis, Yunugaz, and Byariis aspects is required to make this draught. The more Geoliirgaz is used, the stronger are the draught's effects. The more Dayuniis is used, the longer the draught lasts. Leaving out Byariis will reveal the true nature of the draught, turning it into the Draught of the Unclouded, which causes any fog to be cleared from the vision of those afflicted.
- The Drunkard’s Brew is highly intoxicating, causing those afflicted to experience a heavy bout of nausea. A combination of Freiwynn, Dayuniis, Ordaniis, Firnalaz, and Byariis aspects is required to make this brew. The more Freiwynn is used, the stronger are the brew’s effects. The more Dayuniis is used, the longer the brew lasts. Leaving out Byariis will reveal the true nature of the brew, turning it into the Hunter’s Sense Brew, which allows those afflicted to detect the scent trails of creatures.
- The Elixir of Decay increases vulnerability to the decaying aura of the Betweenlands, causing those afflicted to experience a quicker decline in physical and psychological health. A combination of Yeowynn, Ordaniis, Dayuniis, and Byariis aspects is required to make this elixir. The more Dayuniis is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Leaving out Byariis will reveal the true nature of the elixir, turning it into the Elixir of Ripening, which reverses the decaying aura’s effects on those afflicted.
- The Elixir of Draining eats away at the body, draining the health of those afflicted over time. A combination of Yeowynn, Ordaniis, and Byariis aspects is required to make this elixir. The more Yeowynn is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Leaving out Byariis will reveal the true nature of the elixir, turning it into the Elixir of Healing, which restores the health of those afflicted over time.
- The Elixir of Starvation makes the stomach digest food faster and less efficiently, causing those afflicted to go hungry more quickly. A combination of Yeowynn, Ordaniis, Celawynn, and Byariis aspects is required to make this elixir. The more Celawynn is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Leaving out Byariis will reveal the true nature of the elixir, turning it into the Elixir of Feasting, which fills the stomach of those afflicted.
- The Elixir of Weakness weakens the muscles, reducing the damage dealt by those afflicted when they attack. A combination of Azuwynn, Ordaniis, and Byariis aspects is required to make this elixir. The more Azuwynn is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Leaving out Byariis will reveal the true nature of the elixir, turning it into the Elixir of Strength, which increases the damage dealt by those afflicted.
- The Heavyweight Draught gives a strange sense of heaviness, causing those afflicted to be unable to swim and causing them to sink in mud despite whatever they may be wearing to protect them from it. A combination of Azuwynn, Byrginaz, Yunugaz, Yihinren, Geoliirgaz, and Byariis aspects is required to make this draught. The more Yunugaz is used, the stronger are the draught’s effects. The more Yihinren is used, the longer the draught lasts. Leaving out Byariis will reveal the true nature of the draught, turning it into the Lightweight Draught, which allows those afflicted to walk over water.
- The Lumbering Elixir makes the muscles lethargic, reducing the movement speed of those afflicted. A combination of Azuwynn, Ordaniis, Yunugaz, and Byariis aspects is required to make this elixir. The more Yunugaz is used, the stronger are the elixir’s effects. The more Ordaniis is used, the longer the elixir lasts. Leaving out Byariis will reveal the true nature of the elixir, turning it into the Nimblefeet Elixir, which speeds the movement of those afflicted.
- The Poisonsting Elixir contains the wrath of the sinister plants found in the Betweenlands, poisoning those affected instantly. A combination of Azuwynn, Yeowynn, Celawynn, and Byariis aspects is required to make this elixir. The more Yeowynn is used, the stronger are the elixir’s effects. The more Celawynn is used, the longer the elixir lasts. Leaving out Byariis will reveal the true nature of the elixir, turning it into the Toughskin Elixir, which protects those afflicted from harmful plants.
- The Slugarm Brew makes the arms feel numb, decreasing the arm swinging speed of those afflicted and thus causing them to mine slower and strike foes less easily. A combination of Azuwynn, Dayuniis, Yunugaz, Ordaniis, and Byariis aspects is required to make this brew. The more Azuwynn is used, the stronger are the brew’s effects. The more Ordaniis is used, the longer the brew lasts. Leaving out Byariis will reveal the true nature of the brew, turning it into the Swiftarm Brew, which increases the arm swinging speed of those afflicted.
- The Stenching Brew has a very potent odor that is desired by monsters, making it easier for those afflicted to be detected by predators. A combination of Dayuniis and Armaniis aspects is required to make this brew. The more Armaniis is used, the stronger are the brew’s effects. The more Dayuniis is used, the longer the brew lasts. Adding Byariis will corrupt the nature of the brew, turning it into the Masking Brew, which makes it harder for those afflicted to be detected by predators.
- The Weakbow Draught reduces archery skill, greatly reducing the bow shooting range of those afflicted. A combination of Freiwynn, Dayuniis, Ordaniis, and Armaniis aspects is required to make this draught. The more Freiwynn is used, the stronger are the draught's effects. The more Dayuniis is used, the longer the draught lasts. Adding Byariis will corrupt the nature of the draught, turning it into the Draught of Sagittarius, which allows those afflicted to see the path of an arrow fired from a bow.

**Comment by TheCyberBrick** [comment]
I'll leave this up to you artist people, this can all be done in the lang file I think

**Comment by TripleHeadedSheep** [comment]
Seems good, if you want to change it, go ahead I'd say. Maybe a bit too much 'afflicted'. Reminds me of hospitals and a certain Skyrim quest :P
