### ISSUE TITLE
[Suggestion] Weeping Blue Petal Salad and Mire Scramble

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#447]
Relatively simple food items to give Weedwood Bowls more uses. 

Weeping Blue Petal Salad: Crafted with a Weedwood Bowl and 6 Weeping Blue Petals. 6 hunger, moderate saturation, a very long Elixir of Ripening effect (or a short but very effective one).

Mire Scramble: Crafted with a Weedwood Bowl, Yellow Dotted Fungus, and a Cooked Mire Snail Egg. 12 hunger and extremely good saturation. Very healthy breakfast (especially when day/night cycle is added).

Yes I edited this to include the scramble you weren't tripping

**Comment by TheCyberBrick** [comment]
Sounds good. Please also add the appropriate labels :P

**Comment by WightofShadows** [comment]
er...I don't know if I have permission to :/

**Comment by TheCyberBrick** [comment]
Hm I thought you already had, now it should work though

**Comment by WightofShadows** [comment]
huh, still can't seem to. Think I need write permissions or something
