### ISSUE TITLE
[1.12.2] Black screen with shaders

### ISSUE THREAD

**Issue by TimeConqueror** [TheCyberBrick/The-Betweenlands#448]
*Forge: 14.23.1.2555
*Mod version: The Betweenlands v3.2.1 SNAPSHOT (Alpha) [1.12.2]
*Singleplayer

Hello,
Besides TheBetweenlands, I also have Optifine in my modpack. And I use Sildurs Shaders.
The problem: When I am in Betweenland dimension, the screen becomes black apart from sky.
![image](https://user-images.githubusercontent.com/25156941/34465160-ae3b3fc4-eeb2-11e7-8b36-6310decbf83d.png)
I also read issues about black screen and tried to turn off "Fast Render" in Optifine Settings and Betweenlands shaders in config but nothing helped me. Are there any ways that I would not need to disable Shaders?

Thank you in advance!
[fml-client-latest.log](https://github.com/Angry-Pixel/The-Betweenlands/files/1595578/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/Angry-Pixel/The-Betweenlands/files/1595579/fml-junk-earlystartup.log)

**Comment by GoryMoon** [comment]
If wanting to use optifine shaders, turning off BL shaders often work. If it doesn't there isn't much else to do then turning off shaders.
Haven't tested with sildurs shaders but know that some others work fine when turning off BL shaders.

**Comment by TimeConqueror** [comment]
Turning off BL shaders doesn't help.

**Comment by TheCyberBrick** [comment]
![image](https://i.imgur.com/JSloYjz.jpg)

I just tried it out with the latest version and Sildur's shader, seems to work fine for me. It kinda kills the mood of the mod though, but to each their own :)

![image](https://i.imgur.com/VkopCm1.png)
Did you double check if `Use shaders for rendering (this forces FBOs to be enabled)` is set to `false`?

If so, and it still happens, please try with Optifine and Betweenlands only (without any other mods) and see if it works then.

**Comment by TheCyberBrick** [comment]
~~Huh interesting. I used the latest dev build and it worked there, but just now I downloaded the latest public build and I get the problem you're having.~~

![image](https://i.imgur.com/bnxv8vv.png)

~~Not exactly sure why that is, but I guess it'll be solved in the next release :)~~

**Comment by TheCyberBrick** [comment]
~~Nope, never mind that. Seems like it happens when you start the game and directly go into a world in the Betweenlands. It doesn't happen if I go to the overworld first and then to the dimension, or is fixed by going to the overworld and back into the dimension.~~

**Comment by TheCyberBrick** [comment]
Nether before going to the overworld
![image](https://i.imgur.com/ngbTmdt.jpg)
Nether after going to the overworld
![image](https://i.imgur.com/svcGbNs.jpg)

That is without the Betweenlands installed. Note how similarly to the Betweenlands dimension the entity and portal lighting is broken before going to the overworld.  

I have a feeling that this is a bug in Optifine or Sildur's shaders. It seems like the shader always uses the time of day from the overworld, and since the Betweenlands doesn't have a day/night cycle (yet) the time of day may not be properly initialized by the shader until you go to the overworld and then back into the dimension.  

Right after starting the game and direclty going into a world in the Betweenlands this is how it looks with "Magnificent Atmospheric Shaders":
![image](https://i.imgur.com/SJOBEsm.png)
And this is how the exactly same case looks like with Sildur's shaders:
![image](https://i.imgur.com/NAHGlBL.png)

Since it seems to work with other shaders, and that Sildur's shaders exhibit bugs even in the Nether without the Betweenlands installed, I am quite sure that this is not a problem on our side

**Comment by TimeConqueror** [comment]
So I just have to wait for the next update and the bug will be fixed there, right? If so, thank you, I'll just wait :)

**Comment by TheCyberBrick** [comment]
No, I was mistaken there. Please read my comment right above. I think this is a bug of Optifine or Sildur's shaders

**Comment by TimeConqueror** [comment]
I just tested this. Yes, you are right. If I enter the game in BL dimension with enabled Sildurs Shaders, the screen will become black. If I enter the game in overworld and after that pass through portal to BL, everything will be fine.
I tried to turn shader off, and the result is white dense fog, which I can turning button "Fog" in Optifine Settings to "off". Also this dense white fog may appears, when I walk in Plains biome of BL dimension (near the portal), But if I fully disable fog, the event "Dense fog" can't be visible. (Whie dense fog and event "Dense Fog" have different meanings).
![image](https://user-images.githubusercontent.com/25156941/34470093-53b80fa8-ef3b-11e7-9ab7-9b7b9559c920.png)

**Comment by TheCyberBrick** [comment]
Was that in a Marsh? Some regions in the marsh biome can be very foggy

**Comment by TimeConqueror** [comment]
It was in Biome "Plains" as F3 showed, near my portal. And there are weedwood trees & dirty brown water there. This fog suddenly appears (when I walk in dimension), and after that moment it doesn't dissipate wherever you are. Turning off fog or entering overworld saves only.

**Comment by TheCyberBrick** [comment]
Huh, there is no "Plains" biome in the Betweenlands

**Comment by TimeConqueror** [comment]
Then how did this happen?) maybe it is a bug... I undestand that this is Swamplands, but F3...
![image](https://user-images.githubusercontent.com/25156941/34501061-49225268-f01e-11e7-9162-3f781d31c4f2.png)
There is another biome (all is fine);
![image](https://user-images.githubusercontent.com/25156941/34501104-80d4d406-f01e-11e7-95a0-3a010cd12baa.png)

**Comment by TimeConqueror** [comment]
The fog appears after 0:59 (In advance, I'm sorry for the lags)
https://youtu.be/2BcGE0aWgsQ

**Comment by TheCyberBrick** [comment]
Ah thanks for recording it! The fog might be the same problem as in another issue (#433), I'll look into it.

The plains biome definitely shouldn't be there, must be a conflict with another mod. Please try it without any of the other mods (except Optifine, won't matter as it doesn't affect biomes)

**Comment by TimeConqueror** [comment]
Plains :)
![image](https://user-images.githubusercontent.com/25156941/34503180-25b21be2-f028-11e7-8d05-7bcd05effde2.png)
![image](https://user-images.githubusercontent.com/25156941/34503252-67e489e6-f028-11e7-8c86-0fafd95d1efa.png)

**Comment by Los2tale** [comment]
if you want to use shader only in overworld but not appear in other dimention jusr create a folder name "world0" in shader folder then move everything in shader to this folder except a shaders.properties file 

ps.sorry for my bad english
ps2. still disable BL shader
ps3. this work for me i have a shader in overworld and keep mood of BL

**Comment by TimeConqueror** [comment]
@Los2tale , it doesn't work with Sildurs Shaders. In any world there is black screen)

**Comment by 0Navis0** [comment]
It doesn't work with BSL Shader neither, I get a black screen, whatever the shader version I use. I suspect the problem comes from the sky rendering.

**Comment by TheCyberBrick** [comment]
This is not a problem on our side. Many other dimensions such as the Erebus or Twilight Forest and *even the Nether sometimes* exhibit similar problems with shaders.
