### ISSUE TITLE
[Suggestion] Roots = Tentacles = Spoop

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#453]
Already has been suggested, just putting it here so it's not forgotten.

Essentially, make the Giant Roots' textures the tentacle texture during the Spook event.

Also still can't add labels sorry

**Comment by TheCyberBrick** [comment]
You need to accept the invite, lol

**Comment by WightofShadows** [comment]
Well I’m stupid

**Comment by TheCyberBrick** [comment]
This can be done in the assets, you can look at some other spoopy blocks like cattail, logs etc. for reference

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12/src/main/resources/assets/thebetweenlands/blockstates/cragrock.json

**Comment by TheCyberBrick** [comment]
![image](https://i.imgur.com/wspb4Gc.png)
