### ISSUE TITLE
Minecraft 1.10.2 (local and server), NVIDIA 210 graphic crash when changing dimension

### ISSUE THREAD

**Issue by pzlingo** [TheCyberBrick/The-Betweenlands#455]
Using latest forge (2511), problem only seen on NVIDIA 210 Graphics card.
When changing dimension, screen split into 4 and only screen left-bottom will render, but in strange manner. Rest of the screen is freezed. Not possible to play.

When restarting, on dimension load, screen will split again, no way to play.
When using command to tp into the tree, rendering problem persists. If I try to get back to main dimension, rendering problem persists.

**Comment by TheCyberBrick** [comment]
Which version of the mod were you using?
Have you tried disabling the Betweenlands shaders in the config?
