### ISSUE TITLE
ClassCastException when trying to fight the Whight Fortress Boss

### ISSUE THREAD

**Issue by lucidagrande** [TheCyberBrick/The-Betweenlands#456]
First of all this crash occurred for me and a friend on a forge server. Crashed on version 3.2.1. The crash were just on the client side. (The server didn't crash)

Minecraft Version: 1.12.2
Forge Version: 14.23.1.2582 (Client) 14.23.1.2586 (Server)
The Betweenlands Version: 3.2.1

Server details: Creeperhost server running Minecraft 1.12.2 with forge (see server above). As also said above, server didn't crash.

Description: Ticking entity
Why it crashed: java.lang.ClassCastException: java.lang.Integer cannot be cast to net.minecraft.util.math.Vec3d
Crash report: https://pastebin.com/aJjapers

It happened for us when we entered the boss room with the shockwave sword. He looks at us, then the screen goes to a loading screen, freezes and crashes.

**Comment by TheCyberBrick** [comment]
This seems to be the same as #443. Please try without MoCreatures
