### ISSUE TITLE
Shearing the top block of Weeping Blues drops both the flower and petals

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#461]
This is a fairly big deal, as it allows the player to farm infinite weeping blue petals very quickly at no expense but shear durability.

Before shearing at all.
![2018-01-22_13 24 06](https://user-images.githubusercontent.com/32495545/35237137-bee46d66-ff77-11e7-9f39-adc52ed9ee14.png)

After shearing the bottom half, it drops only the flower (as intended).
![2018-01-22_13 24 19](https://user-images.githubusercontent.com/32495545/35237139-bf100796-ff77-11e7-9743-23c03db41bf0.png)

But after shearing the top half, it drops both the flower and the petals, allowing for **infinite petal farming**.
![2018-01-22_13 24 36](https://user-images.githubusercontent.com/32495545/35237140-bf1e19da-ff77-11e7-9171-01a82650c3a3.png)

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/3d4f2590041fa889a85618f1fb58dd1bfdac460f

This is already fixed in the dev version
