### ISSUE TITLE
Skull Mask does not prevent Wights from possessing you

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#463]
#### Betweenlands version:

3.2.1-alpha-snapshot

#### Forge version:

14.23.1.2555

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

nopotionshift 1.2.0, Optifine 1.12.2 C8, The Betweenlands 3.2.1-alpha-snapshot, Hwyla/Waila 1.8.23, and XYZing 1.0.

#### How to reproduce: (  ͡° ͜ʖ ͡°)

1. Put on Skull Mask.
2. Fight Wight.
3. Get possessed.

#### Expected result:

The Wight to stay in physical form. The wiki states (under Skull Mask) that: "Wights will not be able to use their 'possession' attack on any player that is wearing the mask, making them easier to deal with."

#### Actual result:

It turned into its volatile form and "possessed" me

#### Pictures:

Picture of me being "possessed" in a creative test world.
![2018-01-22_19 27 25](https://user-images.githubusercontent.com/32495545/35251978-1ea05d80-ffac-11e7-831c-5da139168413.png)

**Comment by TheCyberBrick** [comment]
*( ͡° ͜ʖ ͡°)*

**Comment by TheCyberBrick** [comment]
Thanks for the bug reports by the way :)

**Comment by PetasiGit** [comment]
Yeah, no problem, just stuff I've stumbled across. I'm new to the mod so I test almost everything. Glad I didn't try this in my survival world, could've died lol.
