### ISSUE TITLE
Temple Brick Stairs blockstate file uses Betweenstone Bricks texture for one of the corners

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#466]
#### Betweenlands version:

3.2.1-alpha-snapshot

#### Forge version:

14.23.1.2555

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Mods are not the issue. See below.

#### Description of the problem
 This part of the blockstate is the issue, if you haven't fixed it already in the dev version.

"facing=east,half=bottom,shape=outer_left": {
      "model": "thebetweenlands:base_outer_stairs",
      "y": 270,
      "uvlock": true,
      "textures": {
        "all": "thebetweenlands:blocks/betweenstone_bricks"
      }

#### Pictures:

Just a minor error.
![2018-01-27_15 42 16](https://user-images.githubusercontent.com/32495545/35476426-95babea4-037d-11e8-996d-3b0649c70e8c.png)

**Comment by GoryMoon** [comment]
Already fixed c036139c05b2e17fcfae1036bff5223d3d78550d

**Comment by GoryMoon** [comment]
oh, my bad looks like I missed some, fixed the rest now in 3aedc9ab68d7624f52cd0dc1cad0dc7f07860828
