### ISSUE TITLE
Weird rendering stuff

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#468]
#### Betweenlands version:

3.2.1-alpha-snapshot

#### Forge version:

14.23.1.2555

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.2
Clumps 3.0.0
Friendly Fire 1.5.8
Waila/Hwyla 1.8.23
Keyboard Wizard 1.12.2-1.5.3-b1
Leaf Decay Accelerator 1.0.0.2
Mouse Tweaks 2.8
Ninja's Mods 1.12
nopotionshift 1.2.0
Optifine 1.12.2 C8 
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.2.1-alpha-snapshot
XYZing 1.0

#### How to reproduce: 

I'm not actually sure. This has happened multiple times now, on different days with more and less mods. I had Fast Render and Anisotropic filtering on in Optifine, which I know conflict with shaders, maybe it's part of this too?

#### Pictures:

Here you can see me in a tarred weedwood rowboat. The large shadow is a pot of chance and there's a dragonfly nearby which doesn't have its wings rendered. This also seems to affect the vanilla chests and shulker boxes, weedwood chests (turned invisible, no point in showing), and peat mummies.
![2018-01-27_20 21 35](https://user-images.githubusercontent.com/32495545/35478024-8ee86e0a-03a0-11e8-8981-50c170c2d44d.png)

**Comment by TheCyberBrick** [comment]
That is weird indeed, but I'm pretty sure it's not caused by the shaders. Could you try without the other mods and try to narrow down which combinations cause this? In this picture it looks like parts of the textures are missing, so maybe try removing Texture Fix first?

**Comment by PetasiGit** [comment]
It happened a few days before I had Texture Fix installed as well, but only with dragon flies and the boat, but the boat didn't turn invisible the texture just glitched out. (Those are what I saw, the other things could've been affected too.)

 At that time I think I only had Better Fps, Optifine, Hwyla, XYZing, and nopotionshift. Could it be any of those?

**Comment by PetasiGit** [comment]
I've narrowed it down to Optifine. With just The Betweenlands 3.2.1-alpha-snapshot there are no issues, but with Optifine 1.12.2 C8 and Betweenlands there are. I'll update this if I find the setting issue, have to trial and error it I guess.

Here's more pictures. 
![2018-01-31_12 45 49](https://user-images.githubusercontent.com/32495545/35643413-2d1f3c66-0694-11e8-8cc0-89f251ab9a27.png)
![2018-01-31_12 45 54](https://user-images.githubusercontent.com/32495545/35643367-1526a658-0694-11e8-8b69-ff8a64edae04.png)
![2018-01-31_12 53 46](https://user-images.githubusercontent.com/32495545/35643368-153621fa-0694-11e8-8be3-bddd0ce59c2a.png)
![2018-01-31_12 54 06](https://user-images.githubusercontent.com/32495545/35643369-1543f794-0694-11e8-8223-df0acb7c25f6.png)
![2018-01-31_12 55 54](https://user-images.githubusercontent.com/32495545/35643370-1550b664-0694-11e8-85c2-94f332f34a28.png)
![2018-01-31_13 12 14](https://user-images.githubusercontent.com/32495545/35643371-155baac4-0694-11e8-8064-2059be1b9796.png)

**Comment by PetasiGit** [comment]
It's Anisotropic Filtering. Without it on there are no issues, but with it enabled at all it seems to go 
wackadoo.

![2018-01-31_14 50 17](https://user-images.githubusercontent.com/32495545/35644172-41cda754-0696-11e8-8084-524110e599ee.png)

What I don't understand is why it messes with this mod so badly. I use anisotropic filtering because without it I get [weird dots and lines on my screen.](https://imgur.com/a/Mb6vu)

**Comment by TheCyberBrick** [comment]
Hm ok, thanks for tracking it down. I'll try it out at some point and see if I can narrow down what might be causing problems here

**Comment by PetasiGit** [comment]
It usually happens when you play for a while or when there's a lot of dragon flies being rendered. That's how I tested it, anyways, by spawning a ton of dragon flies.

**Comment by TheCyberBrick** [comment]
@okl1001 why did you close this? is this fixed now?

**Comment by PetasiGit** [comment]
It appears to be in 3.3.0. I can no longer replicate it by spawning lots of dragonflies. I haven't seen any of the issues since updating to the full release. And I've made sure to use the Anisotropic setting.
