### ISSUE TITLE
Lurker Skin Pouch can't be upgraded to more than 36 slots

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#469]
#### Betweenlands version:

3.2.1-alpha-snapshot

#### Forge version:

14.23.1.2555

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.2
Clumps 3.0.0
Friendly Fire 1.5.8
Waila/Hwyla 1.8.23
Keyboard Wizard 1.12.2-1.5.3-b1
Mouse Tweaks 2.8
Ninja's Mods 1.12
Optifine 1.12.2 C8
Placement Preview 1.12.2-0.3.2 
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.2.1-alpha-snapshot
XYZing 1.0

#### How to reproduce: 

Try to upgrade a lurker skin pouch with 36 slots.

#### Expected result:

To be able to upgrade the pouch to 45 and then 54 slots. The wiki states (in Lurker Skin Pouch) that: "When first crafted, Lurker Skin Pouches have only 9 item slots. However, they can be upgraded up to five times, each time adding an additional 9 slots to the pouch's storage, up to a maximum possible 54 item slots (the same as a double chest). " Unless the wiki is wrong (in which case it should be updated), I should be able to upgrade it two more times.

#### Actual result:

I was unable to upgrade it anymore.

#### Pictures:

![2018-01-28_12 46 55](https://user-images.githubusercontent.com/32495545/35485212-36ccafe4-042a-11e8-93ff-ff349b21b488.png)
![2018-01-28_12 47 02](https://user-images.githubusercontent.com/32495545/35485213-36ebc366-042a-11e8-9e9a-c6a2086dacd1.png)

**Comment by GoryMoon** [comment]
This is changed and you 36 slots is the max storage, so the wiki would need updating with that

**Comment by WightofShadows** [comment]
Updated.
