### ISSUE TITLE
Creative tab ordering is a mess

### ISSUE THREAD

**Issue by vadis365** [TheCyberBrick/The-Betweenlands#47]
The Creative tab is all jumbled up and out of order (for tools and armour).
I'm not sure if it is the way the items are registered using the reflection method.
If someone else could fix this it would be nice.
calling @SanAndreasP

**Comment by SanAndreasP** [comment]
"I'm not sure if it is the way the items are registered using the reflection method."

wat?

**Comment by SanAndreasP** [comment]
but yeah, I'll fix it.

**Comment by vadis365** [comment]
ok - thanks

**Comment by vadis365** [comment]
This seems to have been fixed - not sure how...

**Comment by MrCompost** [comment]
Don't jinx it

**Comment by SanAndreasP** [comment]
Reopen this, because the sorting is determined by (internal) item ID.
New worlds will have the correct ordering, while old worlds (when adding new items) will have them sorted like already registered -> newcomers
