### ISSUE TITLE
Crash minecraft server 1.7.10

### ISSUE THREAD

**Issue by oleg-rakitin** [TheCyberBrick/The-Betweenlands#472]
Hello!
I'm using your mod on the server!
When you kill the server, the server crashes.
I attach crash-log.
Please correct this as soon as possible!
Game version: 1.7.10
Kernel: Thermos-1.7.10-1614

https://pastebin.com/3iGHzNci

**Comment by PetasiGit** [comment]
inb4 "Sorry, we've moved on to the 1.12.2 version of the game and are no longer supporting older versions."
