### ISSUE TITLE
Ore dictionary screws up many recipes

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#474]
#### Betweenlands version:
Betweenlands 3.3.0 Snapshot

#### Forge version:
1.12.2-14.23.1.2589

## Description of the problem
The recently added ore dictionaries unfortunately cause a lot of problems and inconsistencies with recipes. For example, ~~attempting to craft a Sulfur Furnace just crafts a vanilla one,~~ you can craft vanilla wood stuff (including sticks) with rubber and giant root planks, and you can craft vanilla sugar and paper from swamp reed. There's probably more recipes affected similarly but those stood out the most.

Apparently there's no way to prioritize the Betweenlands stuff to craft over the vanilla stuff anymore, so to me it looks like the only options are to either add the Betweenlands recipes manually or remove the ore dictionary entirely. I don't mind Betweenlands stuff being able to be combined with vanilla stuff in crafting, it's just that you can craft vanilla stuff entirely out of Betweenlands stuff (and in some cases replacing Betweenlands stuff) that throws my sense of consistency for a loop.

**Comment by TheCyberBrick** [comment]
But it doesn't override any Betweenlands recipes, does it?
Of course it allows you to craft vanilla items from betweenlands items if the mod doesn't have an equivalent betweenlands variant, that's just how the oredict works. We could make the oredict a config option that is off by default.
Edit: If it doesn't override Betweenlands recipes it's not really a matter of prioritization and from what I've tested so far it seems all Betweenlands recipes take priority

**Comment by GoryMoon** [comment]
The ones that doesn't take priority are disabled like: weedwood planks, betweenstone and weedwood sticks

**Comment by TheCyberBrick** [comment]
Ah hmm, that sucks. I think the best solution then would be to remove all oredict and leave that up to MineTweaker and co. What do you think?

**Comment by WightofShadows** [comment]
Sounds fine. Yeah I know the dictionary works that way, just wished there was a way around that that didn’t remove all oredict recipes
