### ISSUE TITLE
Fallen Leaves can't be collected

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#477]
#### Betweenlands version:
3.3.0 Snapshot

#### Forge version:
1.12.2-14.23.1.2589

## Description of the problem
I remember in 1.7.10 it was possible to collect fallen leaves to place elsewhere with shears. It doesn't seem possible at all to obtain them in survival anymore though, even with shears or a Silk Touch tool. Would be nice to use for decorative purposes.

**Comment by TheCyberBrick** [comment]
3c0f980cc06411876dc7f27156c066ae893293e5
