### ISSUE TITLE
client fml crash report regard with Betweenlands BlockRegistry (3.2.1-alpha)

### ISSUE THREAD

**Issue by Meskino** [TheCyberBrick/The-Betweenlands#478]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SCFMLCorePlugin (StalkerCreepers-1.12.1 (1).jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.2.1-alpha-snapshot-universal.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.6.3.jar)
  Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  No More Glowing Pots (nomoreglowingpots-1.0.jar)
  TANLoadingPlugin (ToughAsNails-1.x.x-4.0.0.null-universal.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  LoadingPlugin (noRecipeBookv1.0.0_formc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/4/18 12:58 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)
Caused by: java.lang.NoClassDefFoundError: thebetweenlands/common/registries/BlockRegistry
	at thebetweenlands.common.registries.Registries.preInit(Registries.java:12)
	at thebetweenlands.common.TheBetweenlands.preInit(TheBetweenlands.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thebetweenlands.common.registries.BlockRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:425)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getMethodMap(FMLDeobfuscatingRemapper.java:402)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapMethodName(FMLDeobfuscatingRemapper.java:349)
	at org.objectweb.asm.commons.RemappingMethodAdapter.doVisitMethodInsn(Unknown Source)
	at org.objectweb.asm.commons.RemappingMethodAdapter.visitMethodInsn(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:51)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 146850296 bytes (140 MB) / 1274019840 bytes (1215 MB) up to 85899345920 bytes (81920 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C9_pre 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version              | Source                                             | Signature                                |
	|:----- |:--------------------- |:-------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2               | minecraft.jar                                      | None                                     |
	| UCH   | mcp                   | 9.42                 | minecraft.jar                                      | None                                     |
	| UCH   | FML                   | 8.0.99.99            | forge-1.12.2-14.23.2.2611.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.2.2611         | forge-1.12.2-14.23.2.2611.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | nocraftingbook        | 1.0.0                | minecraft.jar                                      | None                                     |
	| UCH   | mercurius_updater     | 1.0                  | MercuriusUpdater-1.12.2.jar                        | None                                     |
	| UCH   | uncraftingtable       | 1.8-beta6            | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
	| UCH   | craftstudioapi        | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar              | None                                     |
	| UCH   | animania              | 1.4.4                | animania-1.12.2-1.4.4.jar                          | None                                     |
	| UCH   | antiqueatlas          | 4.4.4                | antiqueatlas-1.12-4.4.4.jar                        | None                                     |
	| UCH   | antiqueatlasoverlay   | 1.2                  | antiqueatlas-1.12-4.4.4.jar                        | None                                     |
	| UCH   | armorchroma           | 1.3                  | armorchroma-1.3-1.12.2.jar                         | None                                     |
	| UCH   | atlcraft              | MC1.12-Ver1.9        | ATLCraftCandlesMod(MC1.12-Ver1.9) (1).jar          | None                                     |
	| UCH   | babymobs              | 1.5.5                | BabyMobs-1.12-1.5.5.jar                            | None                                     |
	| UCH   | baubles               | 1.5.2                | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UCH   | birdsnests            | 2.1.0                | BirdsNests1.12.2-2.1.0.jar                         | None                                     |
	| UCH   | bottledmilk           | 1.0.0                | BottledMilk-1.12-1.1.0.jar                         | None                                     |
	| UCH   | bullseye              | 3.0.3                | Bullseye-1.12-3.0.3 (2).jar                        | None                                     |
	| UCH   | carbonado             | 1.4.2                | carbonado-1.4.2-mc1.12.x.jar                       | None                                     |
	| UCH   | compot                | 1.1                  | CombinedPotions-1.12-1.1.jar                       | None                                     |
	| UCH   | consecration          | 0.0.5                | consecration-1.12.2-0.0.5.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | cosmeticarmorreworked | 1.12.2-v1            | CosmeticArmorReworked-1.12.2-v1.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCH   | creeperconfetti       | 1.4.2                | creeperconfetti-1.4.2.jar                          | None                                     |
	| UCH   | cyberware             | 0.2.10.6             | cyberware-1.12.2-0.2.10.6.jar                      | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCH   | cyclopscore           | 0.10.23              | CyclopsCore-1.12.2-0.10.23.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | disenchanter          | 1.5                  | disenchanter-[1.12]1.5 (2).jar                     | None                                     |
	| UCH   | dissolution           | 0.6                  | dissolution-1.12-0.6.jar                           | None                                     |
	| UCH   | doggytalents          | 1.14.2.314           | DoggyTalents-1.12-1.14.2.314-universal.jar         | None                                     |
	| UCH   | drones                | 0.3.0                | Drones-0.3.0.jar                                   | None                                     |
	| UCH   | dynamictrees          | 1.12.2-0.7.4         | DynamicTrees-1.12.2-0.7.4.jar                      | None                                     |
	| UCH   | everlastingabilities  | 1.3.9                | EverlastingAbilities-1.12.2-1.3.9.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | extraalchemy          | 0.3.6-release        | extraalchemy-0.3.6-release.jar                     | None                                     |
	| UCH   | ftfragileglass        | 1.8.5                | Fragile+Glass+and+Thin+Ice+1.12.2-1.8.5.jar        | None                                     |
	| UCH   | limelib               | 1.7.9                | limelib-1.12.2-1.7.9.jar                           | None                                     |
	| UCH   | furnus                | 2.1.5                | furnus-1.12.2-2.1.5 (1).jar                        | None                                     |
	| UCH   | galaxite              | 1.0.0                | galaxite-1.0.0-mc1.12.x.jar                        | None                                     |
	| UCH   | giacomos_exp          | 1.2.2                | GiacomosExperienceSeedling-1.12.2-1.2.2.jar        | None                                     |
	| UCH   | giacomosfoundry       | 1.3.13               | GiacomosFoundry-1.12.2-1.3.13.jar                  | None                                     |
	| UCH   | giacomos_maps         | 1.2.3                | GiacomosMaps-1.12.2-1.2.3.jar                      | None                                     |
	| UCH   | glass_shards          | 1.7                  | glass_shards_mc1.12-1.7.jar                        | None                                     |
	| UCH   | glitchcore            | @MOD_VERSION@        | GlitchCore-1.12.2-1.0.0-universal.jar              | None                                     |
	| UCH   | grapplemod            | 1.12-v10             | grapplemod-1.12-v10 (1).jar                        | None                                     |
	| UCH   | hammercore            | 1.9.6.3              | HammerCore-1.12.2-1.9.6.3.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | hardcoredarkness      | 2.0                  | HardcoreDarkness-MC1.12.2-2.0.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | ice_shards            | 1.5                  | ice_shards_mc1.12-1.5.jar                          | None                                     |
	| UCH   | llibrary              | 1.7.9                | llibrary-1.7.9-1.12.2.jar                          | None                                     |
	| UCH   | iceandfire            | 1.3.1                | iceandfire-1.3.1-1.12.2.jar                        | None                                     |
	| UCH   | improvableskills      | 3.1.2r               | ImprovableSkills_1.12.2-3.1.2r.jar                 | None                                     |
	| UCH   | jei                   | 4.8.5.147            | jei_1.12.2-4.8.5.147.jar                           | None                                     |
	| UCH   | jaff                  | 1.7_for_1.12         | JustAFewFish-1.7_for_1.12.jar                      | None                                     |
	| UCH   | lootbags              | 2.5.3b               | LootBags-1.12.2-2.5.3b.jar                         | None                                     |
	| UCH   | maille                | 2.0                  | Maille1.12.2-2.0.jar                               | None                                     |
	| UCH   | mobtotems             | 1.12.1-0.3.0         | mobtotems-1.12.1-0.3.0 (1).jar                     | None                                     |
	| UCH   | omlib                 | 3.0.0-138            | omlib-1.12.2-3.0.0-138.jar                         | None                                     |
	| UCH   | overlord              | 2.4.10               | Overlord-1.12.2-2.4.10 .jar                        | None                                     |
	| UCH   | harvestcraft          | 1.12.2o              | Pam's+HarvestCraft+1.12.2o.jar                     | None                                     |
	| UCH   | primitivemobs         | 1.1.5c               | primitivemobs-1.1.5c_beta.jar                      | None                                     |
	| UCH   | realistictorches      | 2.1.1                | RealisticTorches-1.12.2-2.1.1.jar                  | None                                     |
	| UCH   | xreliquary            | 1.12.2-1.3.4.733     | Reliquary-1.12.2-1.3.4.733.jar                     | None                                     |
	| UCH   | roots                 | 0.104                | roots-2-0.104.jar                                  | None                                     |
	| UCH   | subcommonlib          | 1.2.0.1              | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| UCH   | rpginventory          | 1.12.2               | rpginventory-1.12-5.3.0.0.jar                      | None                                     |
	| UCH   | runesofwizardry       | 1.12.2-0.8.8         | Runes-of-Wizardry-1.12.2-0.8.8.jar                 | None                                     |
	| UCH   | saltmod               | 1.12_e_              | SaltyMod_1.12.1_e_.jar                             | None                                     |
	| UCH   | scannable             | 1.6.2.13             | Scannable-MC1.12-1.6.2.13.jar                      | None                                     |
	| UCH   | sharpbone             | 1.0                  | SharpBone-1.12.2-1.0.jar                           | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCH   | signpost              | 1.07                 | signpost-1.12-1.07.jar                             | None                                     |
	| UCH   | simplecorn            | 2.3.7                | SimpleCorn1.12-2.3.7.jar                           | None                                     |
	| UCH   | simplemagnet          | 1.12.0-1.2.6         | simplemagnet-1.12.2-1.2.9 (2).jar                  | None                                     |
	| UCH   | simplytea             | 1.4                  | simplytea-1.4.jar                                  | None                                     |
	| UCH   | toughasnails          | 4.0.0                | ToughAsNails-1.x.x-4.0.0.null-universal.jar        | None                                     |
	| UCH   | slurp                 | 0.3                  | slurp-1.12-0.3 (1).jar                             | None                                     |
	| UCH   | sophisticatedwolves   | 3.12.0               | SophisticatedWolves-1.12.2-3.12.0.jar              | None                                     |
	| UCH   | soulshardstow         | 1.12-2.7.4-53        | SoulShards-TOW-1.12-2.7.4-53.jar                   | None                                     |
	| UCH   | spartanshields        | 1.4                  | SpartanShields-1.12.2-1.4.jar                      | None                                     |
	| UCH   | storageboats          | 3.0                  | storageboats-3.0.jar                               | None                                     |
	| UCH   | teletoro              | 1.12.2-26            | teletoro-1.12.2-26.jar                             | None                                     |
	| UCH   | texfix                | 4.0                  | TexFix+V-1.12-4.0.jar                              | None                                     |
	| UCE   | thebetweenlands       | 3.2.1-alpha-snapshot | TheBetweenlands-3.2.1-alpha-snapshot-universal.jar | None                                     |
	| UCH   | corerm                | 1.2h                 | TheCampingMod_2.3g.jar                             | None                                     |
	| UCH   | camping               | 2.3g                 | TheCampingMod_2.3g.jar                             | None                                     |
	| UCH   | totemic               | 1.12.2-0.10.1        | Totemic-1.12.2-0.10.1.jar                          | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| UCH   | uniquecrops           | 0.1.52               | uniquecrops-1.12-0.1.52.jar                        | None                                     |
	| UCH   | villagenames          | 2.0                  | VillageNames-1.12.2-2.0 (1).jar                    | None                                     |
	| UCH   | waddles               | 0.5.6                | Waddles-1.12.2-0.5.6.jar                           | None                                     |
	| UCH   | waterstrainer         | 3.2.0                | WaterStrainer-1.12-3.2.0 (2).jar                   | None                                     |
	| UCH   | waystones             | 4.0.20               | Waystones_1.12.2-4.0.20.jar                        | None                                     |
	| UCH   | wolfarmor             | 1.12.2-2.1.0-RELEASE | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar              | None                                     |
	| UCH   | naar                  | 1.0                  | Wood Armors - MC 1.12.1 (1.0).jar                  | None                                     |

	Loaded coremods (and transformers): 
SCFMLCorePlugin (StalkerCreepers-1.12.1 (1).jar)
  atomicstryker.stalkercreepers.common.SCTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.2.1-alpha-snapshot-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.6.3.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
No More Glowing Pots (nomoreglowingpots-1.0.jar)
  zabi.minecraft.nomoreglowingpots.PotionTransformer
TANLoadingPlugin (ToughAsNails-1.x.x-4.0.0.null-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPlugin (noRecipeBookv1.0.0_formc1.12.2.jar)
  com.ASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 7310 Graphics'
	OptiFine Version: OptiFine_1.12.2_HD_U_C9_pre
	Render Distance Chunks:8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.0
	OpenGlRenderer: AMD Radeon HD 7310 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by ChrissPz** [comment]
For more details...
BoP and CyclopsCore giving error in fml main/client  log.

**Comment by TheCyberBrick** [comment]
>Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
at org.objectweb.asm.ClassReader.readShort(Unknown Source)
at org.objectweb.asm.ClassReader.(Unknown Source)
at org.objectweb.asm.ClassReader.(Unknown Source)

Seems to be caused by some coremod
