### ISSUE TITLE
Suggestion: Better looking (?) Hearthgrove trees

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#480]
I know it's still in development, but they look a little blocky as they are right now.

I tried building some myself to see if I could improve them. Made them a bit fluffier. The two on the left are mine.
![2018-02-04_12 14 38](https://user-images.githubusercontent.com/32495545/35780273-dbd5f80c-09a6-11e8-8420-fd3121030a7e.png)
![2018-02-04_12 24 37](https://user-images.githubusercontent.com/32495545/35780274-dbf1d7f2-09a6-11e8-966d-81cc89dbcd55.png)
![2018-02-04_12 24 46](https://user-images.githubusercontent.com/32495545/35780275-dc021572-09a6-11e8-95f8-7ad0ec858365.png)

**Comment by TheCyberBrick** [comment]
That won't work, leaves need to be adjacent a log or to leaves connected to a log within 5 blocks

**Comment by PetasiGit** [comment]
Most of them are next to or close to logs. I'll try making one and then replacing the leaves with decayable ones.
![2018-02-04_12 45 57](https://user-images.githubusercontent.com/32495545/35780443-7a944852-09a9-11e8-8d56-216a67dce1bb.png)

**Comment by TheCyberBrick** [comment]
Diagonals don't count. I mean the idea is nice, but then we'd need to reimplement the decay logic for just this tree, and generating it like that also isn't an easy task

**Comment by PetasiGit** [comment]
Tweaked it, then replaced all leaves with decayable ones with a fill command. Sped up randomTickSpeed for a bit and the leaves seemed to stay. It's possible without diagonals.
![2018-02-04_13 01 15](https://user-images.githubusercontent.com/32495545/35780576-82e6a03e-09ab-11e8-9a92-e7d143075301.png)

**Comment by PetasiGit** [comment]
I made some that work with decayable leaves. [Here's the world save](https://www.dropbox.com/s/f60nrodt4plcqv3/Trees.zip?dl=0) with them so you can check them out yourself. It's currently frozen so that no leaves will decay and no hangers will grow.

![2018-02-04_18 57 01](https://user-images.githubusercontent.com/32495545/35783910-fad46f04-09dd-11e8-880f-f325c1289d06.png)

**Comment by vadis365** [comment]
Not atm - we are happy with them as they are and will not spend time on them.
