### ISSUE TITLE
Suggestion: Mud Brick Roof full block and slab to add more building possibilities + be consistent with Thatch

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#483]
Maybe something along the lines of these? It would require a change of the current recipe for Mud Brick Roofs. You could call them Mud Brick Roofing blocks or something like that. 

![2018-02-04_14 57 27](https://user-images.githubusercontent.com/32495545/35781744-08f804dc-09bc-11e8-9508-8075a91829a2.png)
![2018-02-04_14 56 51](https://user-images.githubusercontent.com/32495545/35781745-126e319e-09bc-11e8-90a8-02b371dc89c0.png)
![2018-02-04_14 57 06](https://user-images.githubusercontent.com/32495545/35781746-1997f478-09bc-11e8-9b84-814ac39f98d4.png)

**Comment by WightofShadows** [comment]
Good idea for after the release perhaps. I'd call the full blocks "Mud Brick Shingles" so as to not confuse the actual slope blocks being called roofs.
