### ISSUE TITLE
Game crashes when travelling in Valkyrien Warfare's ship (Chunk unloading issue)

### ISSUE THREAD

**Issue by RFShahrear** [TheCyberBrick/The-Betweenlands#487]
#### Betweenlands version:
3.2.1-alpha-snapshot-universal

#### Forge version:
1.12.2-14.23.1.2604

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
1. The Betweenlands
2. Valkyrien Warfare (version 1.12.2-v0.9_alpha-full)(build 129)
 Also can be reproduced using the curseforge release.

## Link to full crash log
https://gist.github.com/RFShahrear/1fc910ab5ea8d67e472b97ae6ca292ad

contains both server and client log, along with the crash report

#### How to reproduce:

1. Create a ship
2. Go till a chunk unloads.
3. wait while the ship jumps around crazily (you can't get off the ship at this state), before crashing

**Comment by TheCyberBrick** [comment]
We just released v3.0.0 (https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2529098) which removes that crash and made it a warning in the log instead. Please try with that new version

**Comment by RFShahrear** [comment]
Talk about timing. Yes, it seems to be working fine now. Thank you very much.

**Comment by TheCyberBrick** [comment]
Hehe yeah, it was minutes apart :P
Glad it's fixed.
