### ISSUE TITLE
Some basic (clean) foods should restore some decay

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#489]
FrontFlippingMan in the Discord pointed out that finding decay-restoring foods is sort of RNG. While I don't think it's that much trouble to find them, I do think it would help to integrate the decay mechanic a bit more into the overall experience by adding decay restoration to some common clean foods, albeit small amounts in most cases.

- Donuts, Cooked Meats and Kelp, White Pears, and seasonal foods: 1 decay each (1/2 ball)
- Jellos, Marshmallows and Mire Scramble: 2 decay each (Increase Sap Jello restoration in the process)
- Forbidden Fig: 10 decay

Maybe to counteract this a bit, decay could decrease slightly faster and/or cause more hinderances.

**Comment by TheCyberBrick** [comment]
Hm I don't quite see the problem here. Wherever you initially spawn (only Swamplands or Patchy Islands are allowed biomes for the portal), there's at least one sap tree within 100-200 blocks with almost certainty, and one of those trees gives you enough sap balls to last for days

**Comment by TheCyberBrick** [comment]
I'm not against adding other ways to heal decay, but I think it should be something different than just eating food. Especially since those "clean foods" aren't much easier to obtain than finding a sap tree in the first place.

**Comment by WightofShadows** [comment]
It was more of the fact that sap balls and petals are very specific things you find in order to keep an entire new mechanic at bay (which as it stands now is little different from hunger anyway). It was a quick way to integrate it more without adding whole new mechanics of its own, but if a different way could be successfully implemented I would definitely go for it instead.

**Comment by PetasiGit** [comment]
I think if anything else was added that restores decay that would diminish the entire point of the mechanic. Keeping the amount of solutions to a problem low makes it become a priority until later on. The wider you spread the solutions out, the easier it becomes. If decay is supposed to be a threat, it shouldn't be one that half the food items can cure.

**Comment by WightofShadows** [comment]
Again, the point of this solution was not to make restoring decay easier, but to make the mechanic itself more a part of the world. The amounts restored would be so minor that sap balls and petals would still be the only actually effective methods of restoring it. Anyway, there's likely a better solution out there, so I'll close this up.
