### ISSUE TITLE
Swamp Hag

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#49]
Nothing too special for the AI, it is essentially just a faster, stronger zombie. They drop Moss and Slimy Bones. They can also see the player from a much further distance, meaning they can stalk them for a long time.

**Comment by MrCompost** [comment]
They are too weak at the moment, lets make them a bit more dangerous >=D

**Comment by MrCompost** [comment]
Just noticed, it needs it's glowing texture too.

**Comment by vadis365** [comment]
done

**Comment by PCAwesomeness** [comment]
The Swamp Hag needs a new model.
