### ISSUE TITLE
Walk transition from solid block -> rubber block causes player Y to go up and down rapidly

### ISSUE THREAD

**Issue by OreCruncher** [TheCyberBrick/The-Betweenlands#490]
#### Betweenlands version:
3.3.0

#### Forge version:
14.23.1.2600

#### Singleplayer or Multiplayer:
Single

#### Installed mods:
Albedo 0.1.3
Dynamic Surroundings v3.4.9.3 (test version)
BoP 7.0.0
TaN 3.0.0
JEI 4.8.5.146

#### How to reproduce:
1. Stand on solid block, and then walk toward a rubber block.
2. Stop at the block transition.  You should experience the rapid bouncing.

#### Expected result:
No rapid spastic bouncing.

#### Actual result:
At the block edge the player Y will start bouncing up and down rapidly by a very small amount.  If you continue walking into the rubber block the bouncing will continue.  If you then move to a solid block it will stop.  Interesting thing is if you stand on a rubber block, and then walk onto a solid block the problem does not happen.

**Comment by PetasiGit** [comment]
I can't see the Y level in the coordinates changing at all. If you're referring to the visual effect of rapid bouncing, that seems to be a vanilla issue with slime blocks (which of course, rubber blocks are just a copy of).

**Comment by OreCruncher** [comment]
Just checked the Vanilla slime block and it does exhibit the same behavior.  You can go ahead and close this issue out if you need.  I will chase the issue down in the vanilla code.  Thanks!
