### ISSUE TITLE
Moss Beds don't break fully

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#496]
#### Betweenlands version:

3.3.0

#### Forge version:

Forge 1.12.2-14.23.1.2606

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.2
Clumps 3.0.0
FoamFix 1.12.2-0.9.0-Anarchy
Friendly Fire 1.5.8
Waila/Hwyla 1.8.23
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Mouse Tweaks 2.8
Nature's Compass 1.5.1
Ninja's Mods 1.12
Optifine 1.12.2 C8
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.3.0
XYZing 1.0

#### How to reproduce:

1. Place Moss Bed.
2. Break Moss Bed.
3. See that the head of the bed stayed.

#### Expected result:

To break the moss bed fully.

#### Actual result:

It broke the bottom half, gave me a Moss Bed item, and then I saw the top half remain. I broke that and it gave me another Moss Bed.

#### Pictures:

Here's a Moss Bed.
![2018-02-13_15 47 55](https://user-images.githubusercontent.com/32495545/36173017-ba6621e8-10d5-11e8-8318-1bd17011d5c0.png)

I broke the bottom half of it and the top is still left, but it's invisible. You can see I'm looking at it in the bottom right of the debug. 
![2018-02-13_15 48 02](https://user-images.githubusercontent.com/32495545/36173018-ba9cf498-10d5-11e8-9c78-637695bc56af.png)

I break that and get a second Moss Bed.
![2018-02-13_15 48 08](https://user-images.githubusercontent.com/32495545/36173019-bab0471e-10d5-11e8-9c12-83d35f80429b.png)

**Comment by TheCyberBrick** [comment]
I can't reproduce this with BL only, have you tried without the other mods?

**Comment by PetasiGit** [comment]
Just finished narrowing it down, turns out it's FoamFix 1.12.2-0.9.0-Anarchy. And it works with vanilla beds, too, so it has nothing to do with the BL. ~~Do you know where to report bugs for FoamFix?~~

edit: nevermind, I just downloaded 0.9.4 Anarchy and the bug is fixed.

**Comment by TheCyberBrick** [comment]
Ah nice, thanks
