### ISSUE TITLE
Mod icompatability with "Welcome to the Jungle"

### ISSUE THREAD

**Issue by McCarrick111** [TheCyberBrick/The-Betweenlands#497]
Red Sky rendering incompatibility with "Welcome to the Jungle" mod. Not looking for help, just letting you know about the conflict.

#### Betweenlands version:
3.3.0

#### Forge version:
1.12.2-14.23.1.2582

#### Singleplayer or Multiplayer:
Both

#### Installed mods:
Betweenlands + Welcome to the Jungle

## Description of the problem
Simple rendering conflict. For some reason the Betweenlands sky renders red (think like the Nether) with the mod "Welcome to the Jungle". I'm leaving this information with both mod authors. Turning Betweenlands shaders off via config doesn't change it.

There are no crashes or the like, but it is quite the eye sore.

#### How to reproduce:
Simply having both in your mods folder and visit the Betweenlands in any world.

#### Expected result:
Green lush rendered Betweenlands night sky.

#### Actual result:
Ugly flat red sky with barely visible Betweenlands night sky under it.

**Comment by pau101** [comment]
This isn't a conflict with anything on our side. It's just how Welcome to the Jungle is currently written to behave.

**Comment by McCarrick111** [comment]
Yea that was the impression I got, just wanted to be on the safe side and leave it with both of you folks. Thanks!

**Comment by pau101** [comment]
No problem
