### ISSUE TITLE
Wight

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#50]
Ok, these guys are awesome. They wander around the BL slowly with their heads hung low, staring at the ground. They are sensitive to sound, so if you just sneak past them they will ignore you. If you make noise by walking around or breaking things, they will notice you and attack. They drop Wight Hearts. They have a bunch of awesome sounds too :D

**Comment by MrCompost** [comment]
These require a MAJOR rework, see above. They also need to have their models scaled up in size in the code, so they are AT LEAST two blocks tall, maybe three.

**Comment by vadis365** [comment]
made it all over from scratch - have a look

**Comment by MrCompost** [comment]
Holy shit, thats amazing!

**Comment by MrCompost** [comment]
Of course I know its still a WIP, but I found a few bugs/ areas for improvement on top of the other stuff - 
Most importantly, for some reason they seem to randomly disappear, making the damage noise. I have no idea why it does this and I'm not exactly sure how to describe it. At first, it looked like it just fell through the ground.

Also, right now it can just 'forget' you as soon as you sneak after it attacks you. I think it should only lost interest when the player gets far away.

There is a point where the texture flickers between opaque and transparent and the animation spazzes out a bit.

**Comment by vadis365** [comment]
Sure - I didn't want to do any more on it until I spoke to you about it - I quite like the new look :)

**Comment by vadis365** [comment]
Tweaked the wight a bit - added head animation and smooth fade to the transparency.
Still needs a few tweaks but 2.30am with work the next day meant I had to stop for sleep.

**Comment by MrCompost** [comment]
2.30? Jesus dude, that's late. Thanks though :)
