### ISSUE TITLE
[1.12.2] Decay Meter's health lost breaks with items that boosts max health.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#501]
#### Betweenlands version:

TheBetweenlands-3.3.0-universal
TheBetweenlands-3.3.0-core

#### Forge version:

14.23.2.2612

#### Singleplayer or Multiplayer:

Happens in either Single-Player or Multiplayer.

#### Installed mods:

aether_legacy-1.12.2-v2.0
Baubles-1.12-1.5.2
baubley-heart-canisters-1.12.2-1.1.0b
Botania+r1.10-353
ScalingHealth-1.12-1.3.10-90

## Description of the problem
If your Health is increased by ways such as Life Shards from Aether Legacy (+1 Heart per shard, up to 10.), wearing the Ring of Odin from Botania (+10 Hearts when equipped.) or the Heart Amulet from Baubley Heart Canisters (Default +1 Heart per canister for 4 colors totaling +40. Value can be changed in config.) or increase health via Heart Containers from Scaling Health (Unlimited Hearts by default.) and you let the Decay Meter lower your health, it causes a glitch to the point where the Health Meter goes crazy. You can drop dead due to the health being glitched or you can have INSANE amounts of health.

I recall on a server that I played on not long ago and I had a Ring of Odin equipped from Botania and due to the decay meter lowering health, it bugged it out to the point that I had about 1000+ hearts. When Decay was restored the glitched health was kept and the only way to fix it was to /kill or get killed by... whatever. No other mods were added at the time that increased max hearts.
#### How to reproduce:

1. Gain more Hearts by either using Heart Containers (Scaling Health), equipping the Ring of Odin (Botania), wearing Heart Canisters (Baubley Heart Canisters), pretty much anything that increases your max health.
2. Go into the Between Lands dimension.
3. Let the Decay Meter run it's course.
4. Watch your health increase depending on the amount of extra hearts you gained per heart that is lost from the Decaying effect.
5. Restore Decay and let it run it's course again.
6. Gain even more health, repeat.

#### Expected result:

Decay Meter should lower max health when it gets too low. Since I have 20 Hearts which the extra 10 is from... say Ring of Odin. My health should lower to 13 Hearts if Decay Meter is empty. 23 if 10 Life Shards + Ring of Odin. When Decay is restored health should go back to 20, 30 etc.

#### Actual result:

Decay Meter lowers health but due to the item(s) like Life Shards and such, you GAIN health per heart that is lost depending on the amount of extra hearts. For example... Ring of Odin when equipped will apply it's +10 Heart Bonus for each heart that is lost due to the Decay Meter. Since your health caps at 3 with an empty Decay Meter and the Ring of Odin applying it's bonuses... your health will be at 73 max. Restoring Decay will bring it to 80 and letting Decay run out will give you 143 hearts, 150 if Decay is restored, etc.

#### Pictures:

![](https://cdn.discordapp.com/attachments/223194335372378132/407422853882052608/holyhearts2.PNG)
This was on a server with some other mods added but only one health boosting item was available and it was the Ring of Odin from Botania. Tinker's Construct changes the health meter to use colors instead of rows and as you can see... due to the Ring of Odin & Decay System together... leads to broken health.
![](https://cdn.discordapp.com/attachments/377171551155650560/415375446943727622/boostedhealthglitch.PNG)
Narrowing down the mods... for this image only Aether Legacy, Botania, Baubles and Betweenlands + Core are added. By the looks of it... it actually does lower max health due to the three hearts at the top of the rows but the Life Shards or Ring of Odin keeps applying it's health boost over each heart that is lost. If one were to restore the Decay Meter the glitched hearts stay and one can just let the Decay Meter run out again thus giving the player oh-so-much health, possibility unlimited.

**Comment by TheCyberBrick** [comment]
Thanks for the bug report!
I've tested the changes with the Ring of Odin and it should work fine now. Fix will be in the next update
