### ISSUE TITLE
Fluid block code needs updating (?)

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#502]
#### Betweenlands version:

3.3.0 dev-659

#### Forge version:

Forge 1.12.2-14.23.1.2606

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.2
Clumps 3.0.0
FoamFix 1.12.2-0.9.0-Anarchy
Friendly Fire 1.5.8
Waila/Hwyla 1.8.23
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Macro Key 1.1.6.3
Mouse Tweaks 2.8
Nature's Compass 1.5.1
Ninja's Mods 1.12
Optifine 1.12.2 C8
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.3.0 dev-659
XYZing 1.0

#### How to reproduce:

Here I've made three 3x3 cubes with a hole in the top of each. The left one has swamp water, 
the right one has vanilla water, and the middle one is empty. 

![2018-02-20_18 54 56](https://user-images.githubusercontent.com/32495545/36455900-4fb41a12-1670-11e8-8294-4fb160930f03.png)

I've now punched a hole in the side of each and let the water flow down.

![2018-02-20_18 55 10](https://user-images.githubusercontent.com/32495545/36455950-8752a650-1670-11e8-85a7-d7cfe2f2a25f.png)

After placing a block to obstruct the flow and waiting a bit, this is the result. As you can see, the betweenlands water is still somehow flowing, even though it's blocked off. The vanilla water is how it should behave.

![2018-02-20_18 55 42](https://user-images.githubusercontent.com/32495545/36455977-a7c8ac0e-1670-11e8-82db-401f61838cb0.png)

#### Expected result:

For the water flow to be cut off.

#### Actual result:

It still was somehow flowing.

**Comment by TheCyberBrick** [comment]
Seems to be a bug in net.minecraftforge.fluids.BlockFluidClassic or net.minecraftforge.fluids.BlockFluidBase

**Comment by PetasiGit** [comment]
So you can't do anything about it, or... ?

**Comment by TheCyberBrick** [comment]
There is a Forge PR pending that should fix this if/when it is accepted: https://github.com/MinecraftForge/MinecraftForge/pull/4763
It's not really a severe bug so I'll probably just wait for it to be fixed in Forge.

**Comment by vadis365** [comment]
Closing because it's not us.
