### ISSUE TITLE
Changing to spectator mode when wearing lurker skin armor causes you to fall through the world

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#507]
#### Betweenlands version:

3.3.1 dev-680

#### Forge version:

Forge 1.12.2-14.23.1.2606

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Chunk Pregenerator 1.12 1.7
Client Tweaks 3.1.2
Clumps 3.0.0
FastLadderClimbing 0.1-146
FoamFix 1.12.2-0.9.0-Anarchy
FPS Reducer 1.12.2 1.9
Friendly Fire 1.5.8
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Macro Key 1.1.6.3
Mouse Tweaks 2.8
Nature's Compass 1.5.1
Ninja's Mods 1.12
Optifine 1.12.2 C8
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.3.1 dev-680
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

1. Load up the game. (It only seems to happen the first time you switch to spectator per session)
2. Put on full lurker skin armor.
3. Go in water and float/hover.
4. Go into spectator mode and try to fly out of the water.
5. Now fly/swim down into the ground and watch yourself fall through the world into the void.

#### Expected result:

To not have the armor affect me at all in spectator mode.

#### Actual result:

This glitch.

**Comment by TheCyberBrick** [comment]
I was unable to reproduce this. Removed the effects when in spectator mode though so it shouldn't happen anymore either way
