### ISSUE TITLE
The Shockwave Sword doesn't destroy Primordial Malevolence energy fields

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#510]
**It could just be the wiki, though.**

#### Betweenlands version:

3.3.1 dev-680

#### Forge version:

Forge 1.12.2-14.23.1.2606

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Chunk Pregenerator 1.12 1.7
Client Tweaks 3.1.2
Clumps 3.0.0
FastLadderClimbing 0.1-146
FoamFix 1.12.2-0.9.0-Anarchy
FPS Reducer 1.12.2 1.9
Friendly Fire 1.5.8
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Macro Key 1.1.6.3
Mouse Tweaks 2.8
Nature's Compass 1.5.1
Ninja's Mods 1.12
Optifine 1.12.2 C8
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.3.1 dev-680
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

1. Try to use the shockwave attack to destroy an energy triangle thingy that the Primordial Malevolence
summons

#### Expected result:

For it to destroy the energy field. The wiki states (under Primordial Malevolence) that: 
"It will occasionally place an energy field on the ground level of the player. This spinning blue energy triangle will damage any players that walk into it, and it lasts for quite a few seconds before disappearing; **it can also be destroyed with the Shockwave Sword's shockwave attack.**"

#### Actual result:

It doesn't affect the energy field in any way.

**Comment by WightofShadows** [comment]
It was originally an oversight in the initial release, then someone noted how it was actually kind of useful to be able to use the shockwave to counter the attack so it was kept for the time being. Likely got changed down the line, probably during 1.10 since I didn't do much wiki editing for that update.

**Comment by PetasiGit** [comment]
Well I guess it's up to Cyber to decide whether it's a bug or a wiki thing. Once he decides this can be closed.
