### ISSUE TITLE
Weedwood boat visual glitch

### ISSUE THREAD

**Issue by SimulatorSia** [TheCyberBrick/The-Betweenlands#511]
#### Installed mods:

https://minecraft.curseforge.com/projects/hexxit-updated

#### Pictures:
https://imgur.com/a/DKDJ4

**Comment by SimulatorSia** [comment]
what the heck happened up there ^
I typed it all out >.>

Forge version: 2611
Betweenlands: 3.3.0
Latest Hexxit Modpack
Multiplayer with sponge installed

**Comment by pau101** [comment]
What armor are you wearing?

**Comment by pau101** [comment]
Nevermind, I'm able to reproduce without anything ![image](https://i.imgur.com/cOz8xOR.png)

**Comment by SimulatorSia** [comment]
One of the mods in the mod pack adds emotes. Maybe that mod is conflicting with the animation. because I also saw that when using the mod Carry On, your armor doesn't move with the arms like it's supposed to.

**Comment by pau101** [comment]
I've identified where the compatibility issue is, and it's from The Erebus. I have working correction to our code.

**Comment by pau101** [comment]
And for Carry On, yes there are many issues which can come from the rowboat like that, eventually those minor visual bugs will be resolved.

**Comment by SimulatorSia** [comment]
That was quick :o
