### ISSUE TITLE
Rubber Tree Logs are missing alternate textures

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#512]
#### Betweenlands version:
Betweenlands 3.3.1

#### Forge version:
1.12.2-14.23.2.2619

#### How to reproduce:

1. Place a rubber tree log that you have harvested from a natural log
OR
Look at a rubber tree log during the Spook event

#### Expected result:
The log should have a slightly altered texture when it is placed by the player (to indicate it cannot be tapped).
It also has a Spook event variant that I know at one point was used.

#### Actual result:
The log still uses the default texture.

#### Pictures:
![2018-03-03_22 33 03](https://user-images.githubusercontent.com/18041417/36942880-dfcd00d0-1f32-11e8-97f1-4ca826f2cdf5.png)
Normal log (left) vs. Placed log (right)

![2018-03-03_22 22 34](https://user-images.githubusercontent.com/18041417/36942885-efb716a2-1f32-11e8-8157-9e5c5b0d7c17.png)

**Comment by TheCyberBrick** [comment]
The spook variants probably won't come back due to the way the model system works
