### ISSUE TITLE
Bug/Suggestion: Sludges should only hide in dirt type-blocks

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#515]
#### Betweenlands version:

Release 3.3.1

#### Forge version:

Forge 1.12.2-14.23.2.2611 

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Chunk Pregenerator 1.12 1.7
Client Tweaks 3.1.2
Clumps 3.0.0
FastLadderClimbing 0.1-146
FoamFix 1.12.2-0.9.0-Anarchy
FPS Reducer 1.12.2 1.9
Friendly Fire 1.5.8
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Macro Key 1.1.6.3
Mouse Tweaks 2.8
Nature's Compass 1.5.1
Ninja's Mods 1.12
Optifine 1.12.2 C8
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.3.1
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

1. Spawn a Sludge or Smol Sludge in an area with no Mud blocks.
2. Wait a bit.
3. See that it eventually hides in any block, including solid stone.

#### Expected result:

For the Sludges to only hide in Mud blocks, as that's what the wiki says.

#### Actual result:

The Sludges hid in solid stone.

#### Pictures:

![2018-03-04_18 47 06](https://user-images.githubusercontent.com/32495545/36952388-3f1269e0-1fdd-11e8-936f-75beee8744db.png)

**Comment by WightofShadows** [comment]
The wiki means to say that they spawn inside mud blocks, not that they can only be inside mud blocks. I’ll double check to see where they spawn though. I’m pretty sure this isn’t a bug either way.

**Comment by PetasiGit** [comment]
They spawn on the surface as far as I can tell, and then they hide after a while. 

I'd say it'd make more sense if they could only hide in mud or dirt-type blocks. But even if it's not a bug it'd be a good improvement.

**Comment by WightofShadows** [comment]
Well some of them spawn directly on the surface, while others spawn buried. I'll change the wiki description to be more general.

Perhaps it would make more sense to limit the blocks but regardless it isn't a huge issue.

**Comment by PetasiGit** [comment]
Well I guess it's up to Cyber again.
