### ISSUE TITLE
minor thing concerning weedwood log bark variant grinding

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#519]
very very small thing not major not big deal no really

the weedwood log bark-only variant can't be ground into bark

![2018-03-05_10 46 35](https://user-images.githubusercontent.com/18041417/36993380-81b6f5a6-2062-11e8-8494-54a0281b3b09.png)
like this you know

not bug is very fine and okay just that it is bark so yeah

please don't smite me down, please don't bring the wraths upon me, okay thanks bye

**Comment by TheCyberBrick** [comment]
what did I just read

**Comment by WightofShadows** [comment]
a snippet of my true personality

**Comment by PetasiGit** [comment]
I noticed this before too and wasn't sure if it was intentional or not.

**Comment by TheCyberBrick** [comment]
▒▒▒▒▒▒▒▒▄▄▄▄▄▄▄▄▒▒▒▒▒▒▒▒
▒▒▒▒▒▄█▀▀░░░░░░▀▀█▄▒▒▒▒▒
▒▒▒▄█▀▄██▄░░░░░░░░▀█▄▒▒▒
▒▒█▀░▀░░▄▀░░░░▄▀▀▀▀░▀█▒▒
▒█▀░░░░███░░░░▄█▄░░░░▀█▒
▒█░░░░░░▀░░░░░▀█▀░░░░░█▒
▒█░░░░░░░░░░░░░░░░░░░░█▒
▒█░░██▄░░▀▀▀▀▄▄░░░░░░░█▒
▒▀█░█░█░░░▄▄▄▄▄░░░░░░█▀▒
▒▒▀█▀░▀▀▀▀░▄▄▄▀░░░░▄█▀▒▒
▒▒▒█░░░░░░▀█░░░░░▄█▀▒▒▒▒
▒▒▒█▄░░░░░▀█▄▄▄█▀▀▒▒▒▒▒▒
▒▒▒▒▀▀▀▀▀▀▀▒▒▒▒▒▒▒▒▒▒▒▒▒
