### ISSUE TITLE
Tar Beast

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#52]
Requires the new model. The individual bits of tar should be animated to look like its dripping, a moving like a thick liquid. Needs to have no knockback when you hit it. Should be A LOT stronger. Speed seems about right. They attack by spreading the Tar liquid from their bodies to get the player stuck. They can also 'suck it back up' if the player gets away, or when they die.

**Comment by vadis365** [comment]
The model had a million parts all named really vague, rotation points were a mess and some of the parts don't animate correct because of the way it has been made ;P
I can fix it so don't worry. Consider this WIP.

**Comment by MrCompost** [comment]
Sorry, that wasn't made by me or Lennart so I wasn't aware of the problem.

**Comment by vadis365** [comment]
Whoops - I owe Len an apology then - lol

**Comment by MrCompost** [comment]
XD

**Comment by MrCompost** [comment]
This thing is a mess. To be honest I think we should remove it for now and come back to it later because it'd have to be pretty much completely redone anyway.
