### ISSUE TITLE
Can't harvest Lichen or Moss using Syrmorite Shears (resolved)

### ISSUE THREAD

**Issue by Immaculala** [TheCyberBrick/The-Betweenlands#523]
TheBetweenlands-3.3.1-universal
MC 1.12.2 Forge 14.23.2.2611 Single Player 

I made a new game with just these basic mods and still had the problem.
Removing them one by one I found Superminer was the conflict (which means no more magnet, I'll have to run around to pick stuff up :( ) but suspect having Moss and Lichen etc., will be more important.
Other mods:
Hwyla-1.8.23-B38_1.12
InventoryTweaks-1.63
jei_1.12.2-4.8.5.147
journeymap-1.12.2-5.5.2
_**SuperMiner-2.6.34.336**_

I don't know how to mark this as resolved :(

**Comment by PetasiGit** [comment]
You can close it yourself by pressing the close button.

**Comment by Immaculala** [comment]
Doh! I'd looked everywhere but where the Close Button was lol
