### ISSUE TITLE
Slope textures are applied incorrectly when placed certain ways

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#525]
**This is probably due to #465**

#### Betweenlands version:

Release 3.3.1

#### Forge version:

Forge 1.12.2-14.23.2.2611 

#### Singleplayer or Multiplayer:

Singleplayer.

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Chunk Pregenerator 1.12 1.7
Client Tweaks 3.1.2
Clumps 3.0.0
FastLadderClimbing 0.1-146
FoamFix 1.12.2-0.9.4-Anarchy
FPS Reducer 1.12.2 1.9
Friendly Fire 1.5.8
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Macro Key 1.1.6.3
Mouse Tweaks 2.8
Nature's Compass 1.5.1
Ninja's Mods 1.12
Optifine 1.12.2 C8
StepUp 4.0-mc1.12
SwingThroughGrass 1.12.2-1.2.3
TapeMouse 1.1.3.17
Texture Fix 4.0
The Betweenlands 3.3.1
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

1. Place a slope facing the side.
![2018-03-07_17 52 28](https://user-images.githubusercontent.com/32495545/37123064-e551df84-2230-11e8-9048-ccc2ce1a36fb.png)

2. Place two more slopes facing forward to either side of it.
![2018-03-07_17 52 22](https://user-images.githubusercontent.com/32495545/37123088-fd7e9d36-2230-11e8-975d-aebb4b45b9b0.png)

#### Expected result:

For the texture to be applied normally.

#### Actual result:

It seems to rotate the texture 90 degrees clockwise.

#### More Pictures:

![2018-03-07_17 50 59](https://user-images.githubusercontent.com/32495545/37123146-24548ff6-2231-11e8-8ffe-79038c9ab088.png)
![2018-03-07_17 52 57](https://user-images.githubusercontent.com/32495545/37123157-2df326d0-2231-11e8-9dd6-e105625f4ca8.png)
![2018-03-07_17 53 03](https://user-images.githubusercontent.com/32495545/37123174-3a49b91c-2231-11e8-8433-9afd1a2fa909.png)
![2018-03-07_17 53 19](https://user-images.githubusercontent.com/32495545/37123187-416413be-2231-11e8-8b5b-0f590239d04c.png)

**Comment by TheCyberBrick** [comment]
Works as intended. That's just how the slopes can connect to allow for things such as this: 
![](https://i.imgur.com/0Vrz8vQ.png)
