### ISSUE TITLE
[Feature Request] Bucket Hiding in JEI

### ISSUE THREAD

**Issue by Darkosto** [TheCyberBrick/The-Betweenlands#528]
compatibility {
    # If fluids from other mods should show in BL buckets in the creative tab
    B:show_non_bl_fluids=false

Can this particular config option extend to JEI? I love that the buckets work with every liquid, but I would prefer not to have all of them showing :)

BL: 3.3.2
MC: 1.12.2
Forge: 2627

Thank you!
Darkosto

**Comment by TheCyberBrick** [comment]
This does work in JEI too :P
Or did you mean you want two seperate options, one for the creative menu only and one for JEI only?

**Comment by GoryMoon** [comment]
Jei takes what show in the creative tab so this config option should work the same, it worked like this when I implemented it

**Comment by Darkosto** [comment]
I fixed it on my end. I'm just going to close this.

**Comment by GoryMoon** [comment]
Ok, nice
