### ISSUE TITLE
Angler

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#53]
They swim around together, in groups of about 5. When they spot the player they will all rush to attack. Their hits don't do a lot of damage, but they hit rapidly. Plus, there's a bunch of them. They leap out of the water to attack too. When they bite, one of the anglerAttack sounds are used. They drop Angler Fangs and Angler Meat.

**Comment by vadis365** [comment]
Do we have angler fang and angler meat textures? 
They don't exist in code atm, if we do I'll add them.
Gave anglers a debug drop of lurker skin for the time being and fixed the armour textures for it ;)

**Comment by MrCompost** [comment]
Angler Meat is already implemented, for some reason Angler Fangs are not. Textures are already done.
