### ISSUE TITLE
Display bug in Herblore Book

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#530]
this managed to loop back to that silly ground weedwood bark thing and I probably caused this to happen

#### Betweenlands version:
3.3.3

#### Forge version:
1.12-14.23.2.2619

#### How to reproduce:
1. Have Ground Weedwood Bark discovered
2. Open the Herblore Book
3. Navigate to List of Ingredients under Ground Weedwood Bark

#### Expected result:
It displays the log/bark.

#### Actual result:
The Baaaad texture.

#### Pictures:
![2018-03-17_09 40 59](https://user-images.githubusercontent.com/18041417/37558085-c2abb624-29cb-11e8-9af4-2971db2ac871.png)

**Comment by TheCyberBrick** [comment]
>this managed to loop back to that silly ground weedwood bark thing and I probably caused this to happen

No idea what that's supposed to mean :P

**Comment by GoryMoon** [comment]
I fixed this in c9cb04264abdb4b317c9134045f7eb89ac7d02a5

**Comment by WightofShadows** [comment]
all good then
