### ISSUE TITLE
Workbench dupe

### ISSUE THREAD

**Issue by Reizenkun** [TheCyberBrick/The-Betweenlands#532]
#### Installed mods:
Apple Skin
Embers
FoamFix
Inventory Tweaks
Iron Chests
JEI
Journey Map
Just Enough Resources
Optifine C9
Toro Health
Twilight Forest
Skillable

#### How to reproduce:

Sorry, but my english writing level is "autistic screams", so i'm send video with dupe.

Video: https://www.youtube.com/watch?v=049Qu1zc9dM

**Comment by TheCyberBrick** [comment]
oh.

**Comment by TheCyberBrick** [comment]
Good catch! Thanks
