### ISSUE TITLE
green screen with optifine

### ISSUE THREAD

**Issue by 0Navis0** [TheCyberBrick/The-Betweenlands#533]
#### Betweenlands version:
3.3.3

#### Forge version:
14.23.2629

#### Installed mods:
OptiFine C9

## Description of the problem
I get green screen from the color of Betweenlands sky when OptiFine, even when no shaders are present, and Betweenlands shaders are turned off.

**Comment by TheCyberBrick** [comment]
A picture or even better a video would be helpful

**Comment by TheCyberBrick** [comment]
I've tested it with Optifine HD_U_C9 and I don't have any issues.
Does this only happen when you have Optifine installed?

**Comment by TheCyberBrick** [comment]
Ah ok figured it out. Optfine has an "internal" shader. If you go to the shaders menu you need to select "OFF" and then it should work.
I think I can fix this in the mod, but for now just set it to OFF.

**Comment by 0Navis0** [comment]
Yeah it's what I just said, even with internal shader, or the simplest shader, it doesn't work.

**Comment by TheCyberBrick** [comment]
You said
>even when no shaders are present

The "internal" shader *is* a shader

**Comment by TheCyberBrick** [comment]
Shaders generally don't work well in other dimensions (e.g. Twilight Forest too), some work and some don't. We don't plan on supporting all shaders, but I'll see what I can do

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/593dc5ff8aea1c37c80c3e614f33c7fb5d667ac3

Compatibility should be a bit better now, and it seems to work with the interal shaders too.
So until the new update you can set shaders to OFF as a workaround.
