### ISSUE TITLE
Pouch dupe

### ISSUE THREAD

**Issue by Reizenkun** [TheCyberBrick/The-Betweenlands#534]
(Sorry, but every time write information that does not change is already fed up)

Video: https://www.youtube.com/watch?v=8Jc2LIGTZvM

**Comment by TheCyberBrick** [comment]
You're good at finding these, aren't you :P
Thanks!

**Comment by Reizenkun** [comment]
In fact, I did not intentionally look for dupes/bugs, maybe this is my play style ¯\_(ツ)_/¯
(trying speak on english xD)
UPDATE
Eh... where \ in smile from my previous post? Nevermind, i'll pretend that it seemed to me...
https://i.imgur.com/4CJfaOZ.png

**Comment by TheCyberBrick** [comment]
That's probably just some markdown thing

**Comment by pau101** [comment]
Yep, you need to use two backslashes like `¯\\_(ツ)_/¯`.

¯\\_(ツ)_/¯
