### ISSUE TITLE
Cave Moss doesn't grow down

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#535]
I don't remember if Cave Moss ever did grow down naturally like Hangers or not, but I guess I was at least under the impression that it did when I originally made its wiki page. I think it would make sense either way, so that cave moss is renewable.

![2018-03-18_11 44 09](https://user-images.githubusercontent.com/18041417/37569619-5f69954a-2aa2-11e8-96ca-63fa78f50f91.png)

**Comment by TheCyberBrick** [comment]
They never grew, but it would make sense to add that

**Comment by pau101** [comment]
I would want naturally generated moss to not grow though (through use of a new blockstate property which would be set at the bottom block to not grow) otherwise caves would get messy.

**Comment by WightofShadows** [comment]
Well regular Moss and Hangers already do that, but Moss also dies out, so maybe Cave Moss could have a chance to die out as well. Although Cave Moss doesn't seem to spawn in very big clusters so I don't know if it really would get that messy.

**Comment by TheCyberBrick** [comment]
True, making the naturally generates ones not grow would be good
