### ISSUE TITLE
Pink square instead of Weedwood Log in Herblore Book

### ISSUE THREAD

**Issue by Reizenkun** [TheCyberBrick/The-Betweenlands#536]
#### Installed mods:
Apple Skin
Embers
FoamFix
Inventory Tweaks
Iron Chests
JEI
Journey Map
Just Enough Resources
Optifine C9
Toro Health
Twilight Forest
Skillable

## Description of the problem

Missing Weedwood Log texture in Herblore Book (#530 fix don't work(?))

#### Pictures:
![image](https://user-images.githubusercontent.com/25339917/37597043-d018b868-2b86-11e8-9061-f56292404f84.png)

**Comment by PetasiGit** [comment]
Just so you know, you can insert images directly into the post. No need to use imgur or anything.

**Comment by Reizenkun** [comment]
Oh, i don't know this. Thank!

**Comment by GoryMoon** [comment]
I know what the issue is, the other fix that was made was only for the detail page of the ingredient and not the index page. Will be fixing this soon
