### ISSUE TITLE
3rd person render bug with Astral Sorcery in Betweenlands

### ISSUE THREAD

**Issue by Reizenkun** [TheCyberBrick/The-Betweenlands#537]
#### Installed mods:
Apple Skin
Astral Sorcery
FoamFix
Inventory Tweaks
Iron Chests
JEI
Journey Map
Just Enough Resources
Optifine C9 (Also, without Optifine, bug don't disappear)
Toro Health
Twilight Forest
Skillable
ClientFixer (For Russian font in game)

## Logs
https://pastebin.com/wZUjApcd

#### How to reproduce:

1. Go to Betweenlands (In overworld all works fine)
2. Press F5, or sit in rowboat

#### Pictures:
![image](https://user-images.githubusercontent.com/25339917/37596998-b00bc998-2b86-11e8-879b-f561d42a2868.png)
![image](https://user-images.githubusercontent.com/25339917/37597004-b8ca7732-2b86-11e8-8d69-de883cd9a0ce.png)

**Comment by Saereth** [comment]
Astral sorcery has a config tweak to help with this, just add the betweenlands dimension to the weak render list, you dont see full constellation sky renders with it, but those are purely cosmetic and not essential to progression.
