### ISSUE TITLE
Rotten food turns into normal food after exiting Betweenlands

### ISSUE THREAD

**Issue by Reizenkun** [TheCyberBrick/The-Betweenlands#538]
#### Installed mods:
Apple Skin
Astral Sorcery
FoamFix
Inventory Tweaks
Iron Chests
JEI
Journey Map
Just Enough Resources
Optifine C9
Toro Health
Twilight Forest
Skillable
ClientFixer (For Russian font in game)

#### How to reproduce:

1. Get overworld food
2. Enter to Betweenlands
3. Look at rotten food
4. Exit to overworld
5. Now your food again normal

**Comment by TheCyberBrick** [comment]
It's not a bug. That's there so that if you enter the dimension without knowing that you won't lose all food

**Comment by Reizenkun** [comment]
Strange solution, can you add config parametr to disable rotten food recurect?

**Comment by TheCyberBrick** [comment]
Sure, but what do you gain from that? Making it not reversable doesn't make any sense to me gameplay wise. If you already know that food rots in the BL you obviously won't take any food into the dimension. If you do not know about it, it would happen exactly once and then never again.
The rotting mechanic isn't there to punish players for not knowing or forgetting about it.

**Comment by Reizenkun** [comment]
From my experience of administration servers in Russia, players will use this for saving/ignore food from Betweenlands, that is, when is hungry - players left to overworld, eat normal food and returned back to the Betweenlands. I know how stupid it sounds and that it's hard to believe it until you see, but they will always use any opportunity to "bypass the system" (in their opinion).

**Comment by TheCyberBrick** [comment]
Yeah, but what stops them from having a chest next to the portal in the overworld? :P 
Making it non reversible would't prevent that at all.
But I'll add a config either way :+1:

**Comment by Reizenkun** [comment]
Also, i do not know whether it is worth creating a new issue, is it normal that the battle with Primordial Malevolence does not work on Sponge? (Turrets don't shoot and blockades freeze you).
