### ISSUE TITLE
Primordial Malevolence broken on sponge

### ISSUE THREAD

**Issue by Reizenkun** [TheCyberBrick/The-Betweenlands#539]
#### Installed mods:
Apple Skin
FoamFix
Inventory Tweaks
Iron Chests
JEI
Journey Map
Just Enough Resources
Optifine C9
Toro Health
Twilight Forest
Skillable
ClientFixer (For Russian font in game)

## Description of the problem

Primordial Malevolence broken on sponge, strange wight teleportation (to blockades), turrets do not shooting and blockades can freeze player/malevolence and lag server. Also, without sponge all works fine.

(Video (Freeze): https://www.youtube.com/watch?v=EgMqT-MYzWk)

**Comment by TheCyberBrick** [comment]
Maybe try setting `max-bounding-box-size` in Sponge's `global.conf` to 0? 
I've read that this can cause problems with some mobs, but no idea if this is related to this problem at all.
I can do some testing tomorrow if I have time

**Comment by Reizenkun** [comment]
Unfortunately, this did not help :(

**Comment by Reizenkun** [comment]
I've solved this problem by changing `max-entities-within-aabb` in sponge config to `-1` and `max-bounding-box` to `0`, but it would be better to enable `auto-populate` and configure limit per entity individually.

**Comment by TheCyberBrick** [comment]
Thanks! I'll add it to the FAQ/Common Issues
