### ISSUE TITLE
Sludge

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#54]
Don't need a lot doing to them really, except when they move they leave a trail of Sludge blocks. Also when they spawn, they stay still within the block they spawned on, with just the top sticking out. They jump out and attack when they notice the player.

**Comment by MrCompost** [comment]
Ok, they also need the ability to swim and to not sink into mud.

**Comment by PCAwesomeness** [comment]
Also, they need to make slime sounds when jumping, hit, or killed.

**Comment by MrCompost** [comment]
They already do.

**Comment by PCAwesomeness** [comment]
OK, scratch that.

**Comment by MrCompost** [comment]
Spawning bit needs to be finished, then they are done.

**Comment by TripleHeadedSheep** [comment]
If spawning if the only bit, then I'm closing this sicne we already have an issue for spawning

**Comment by MrCompost** [comment]
No its a bit more complicated than that =P
