### ISSUE TITLE
Possible NPE on the server end

### ISSUE THREAD

**Issue by Sunconure11** [TheCyberBrick/The-Betweenlands#541]
#### Betweenlands version:

V 3.3.4

#### Forge version:

14.23.2.2631

#### Singleplayer or Multiplayer:

Multiplayer, vanilla forge

#### Installed mods:

Modpack is my own, https://minecraft.curseforge.com/projects/compitum-magia/files/2543538

#### How to reproduce:

1. Enter a server that's using my pack
2. ???
3. A fatal error has occurred, this connection is terminated

#### Expected result:

The ability to enter my own server fine

#### Actual result:

https://pastebin.com/QaEcSVEh

Possibly connected to this, as well: https://github.com/OreCruncher/DynamicSurroundings/issues/280

**Comment by TheCyberBrick** [comment]
I've added a != null check to all the packets just to be safe, but I don't think this should be necessary? Interesting that this has never happened before

**Comment by pau101** [comment]
This is unrelated to BL, no need to add a null check @TheCyberBrick. You see the vanilla packets having the same issue in that log. This is can happen when a connection is closed while there are packet tasks in the queue, consequently getting processed after close.

**Comment by Sunconure11** [comment]
Issue is still occurring. It turns out it's connected to tropicraft.

https://github.com/Tropicraft/Tropicraft/issues/254

**Comment by pau101** [comment]
The Betweenlands is not related to this issue.
