### ISSUE TITLE
Bug/Suggestion: An issue with Wights possessing Swamp Hags

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#543]
Not absolutely certain if it's a bug, so I'm going to write this as a *suggestion*.

# The darned issue.
Wights will possess Swamp Hags, no matter what. Even if you wear a Skull Mask or even if the Wight cannot actually see the hag, it will possess it. This is incredibly irritating, meaning there's no way to *prevent* them from making a turret if there's a hag nearby. 

Being killed in a box where you're supposedly safe while AFK is not fun or fair.

# How to fix it.
## There are a few ways.
- Make the Skull Mask prevent *all* possession. Probably not the best way to fix it.
- Make Wights need to have a line-of-sight to the hag they want to possess. Not through solid blocks, either. This is probably the best way.
- Make the Wight have to be aggro'd on to the player in order for it to possess something. This is different from the Skull Mask method. If you hit the Wight and there's a hag nearby, it could possess it.

k thats all

**Comment by TheCyberBrick** [comment]
> Make the Wight have to be aggro'd on to the player in order for it to possess something. This is different from the Skull Mask method. If you hit the Wight and there's a hag nearby, it could possess it.

:+1:
