### ISSUE TITLE
OpenGL constants

### ISSUE THREAD

**Issue by TheCyberBrick** [TheCyberBrick/The-Betweenlands#55]
I assume you wrote the wight renderer
Please use the opengl constants in future, makes it much easier to read. Maybe it's just your IDE that removes them

e.g.
GL11.glEnable(3042);
GL11.glBlendFunc(770, 771);

GL11.glEnable(GL11.GL_BLEND);
GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);

**Comment by vadis365** [comment]
Sure - sorry mate. It is WIP atm so I'll make it use the constants for ya :)
