### ISSUE TITLE
Suggestion: Weedwood Boats should be able to be tied to fences with reed rope

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#550]
It would prevent your boat from drifting *too* far, and would make for a nice detail. I imagine it'd be similar to the caving rope. Maybe even do something like [the Bedrock edition is doing.](https://www.reddit.com/r/Minecraft/comments/87yv8q/well_this_is_a_thing_now/)

## *But okl, that's what tarred boats are for!!1!*
Tarred boats don't just stop them from drifting away, they also make them easier to control. Tar drips can be hard to get in the early game, this would allow for an alternate (but less effective) solution for when you're first starting out.

**Comment by TheCyberBrick** [comment]
But that *is* what tarred boats are for. It's not that much work picking your boat back up, just one click really
