### ISSUE TITLE
Suggestion: Make Nibblesticks actually worth using at all

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#552]
Nibblesticks are a neat little item, with some unique mechanics. They give experience, and you get sick of them faster, so they're useful for lowering other foods' sickness levels.

One Nibbletwig tree will wield you around 32 Nibblesticks on average, so they're easy to get, too.

## But they have a problem.
They give so little experience that they're useless, and their higher sickness value is completely overshadowed by Chiromaw Wings. There's no reason to ever craft these things.

You can eat 10 of them before you max out their sickness value, and even then, they only give a little under 2 levels. From zero levels. That's insane!

### There are a few different ways.
**1.** Buff the amount of experience they give. Giving, say, one level regardless of your actual level (so basically /xp 1L). 
**2**. Make them not be affected by food sickness and buff their experience amount. Maybe one or two levels from zero (so basically /xp 16). 
**3.** Overhaul the mechanic of giving experience directly and instead make them do something else related to XP. Something like doubling all experience you receive for the next minute, or having them make your experience bar fill faster. (this is probably the worst way, FYI)

_k thats all_

**Comment by TheCyberBrick** [comment]
>1. Buff the amount of experience they give. Giving, say, one level regardless of your actual level (so basically /xp 1L).

1 whole level? That's crazy :P
The way XP works you'd get a *ton* of XP. That'd be absolutely broken and unbalanced.

>2. Make them not be affected by food sickness and buff their experience amount. Maybe one or two levels from zero (so basically /xp 16).

The reason why food sickness was added and increased in the first place was exactly to prevent it from being a good source of XP :P

>3. Overhaul the mechanic of giving experience directly and instead make them do something else related to XP. Something like doubling all experience you receive for the next minute, or having them make your experience bar fill faster. (this is probably the worst way, FYI)

Like the above, it was never intended to be a good and reliable XP source.

The reason we added this was that currently the Nibbletwig wood doesn't have any use. We *will* add building blocks for that wood once we've updated to 1.13.
We might increase  the XP it gives a little bit, but probably not much

**Comment by WightofShadows** [comment]
It’s also worth noting that nibbletwig trees are farmable, so basically nibblesticks provide an unlimited amount of XP. Sure, you don’t get much, but it is technically an infinite supply that doesn’t require fighting or exploring.

**Comment by PetasiGit** [comment]
>1 whole level? That's crazy :P
The way XP works you'd get a ton of XP. That'd be absolutely broken and unbalanced.

Perhaps a half or third of a level, then? Maybe it's unbalanced in the Betweenlands, but in the vanilla Overworld it's really weak.

>The reason why food sickness was added and increased in the first place was exactly to prevent it from being a good source of XP :P

I still don't think it should be entirely useless, though. 

And from WoS.

>It’s also worth noting that nibbletwig trees are farmable, so basically nibblesticks provide an unlimited amount of XP. Sure, you don’t get much, but it is technically an infinite supply that doesn’t require fighting or exploring.

Sure it's an infinite supply, but only in the Overworld. In the Betweenlands, food sickness prevents you from using them after you eat a few.

**Comment by WightofShadows** [comment]
Well you just need to eat other foods every once in a while, it’s not any less renewable because of that. Also there are Chiromaw Wings.

But sure, a bit more per stick wouldn’t hurt. It’s just not supposed to be a primary source of XP, more of a supplement.

**Comment by PetasiGit** [comment]
>Well you just need to eat other foods every once in a while, it’s not any less renewable because of that. Also there are Chiromaw Wings.

It's much less effective, though. Also, ".. that doesn’t require fighting..". 

>But sure, a bit more per stick wouldn’t hurt. It’s just not supposed to be a primary source of XP, more of a supplement.

I'm not saying that they should be _THE_ way to get XP, I'm just saying make them useful in the early game.

**Comment by TheCyberBrick** [comment]
>Perhaps a half or third of a level, then? Maybe it's unbalanced in the Betweenlands, but in the vanilla Overworld it's really weak.

No, giving levels will definitely not happen. The levels are logarithmic, i.e. the more XP you have the more it takes to level up. Giving any fraction of a level would completely break the whole system because it'd give way more XP at high levels.

**Comment by TheCyberBrick** [comment]
>Sure it's an infinite supply, but only in the Overworld. In the Betweenlands, food sickness prevents you from using them after you eat a few.

That's incorrect. Nibblesticks retain food sickness even in the overworld :P

**Comment by WightofShadows** [comment]
Chiromaws are nothing, and still aren’t required to kill anyways as per my previous point. It’s tedious without the wings but if you’re going out of your way to accrue great numbers of nibblesticks you’re not really making any use of the more obvious sources of XP.

There aren’t really any early game uses for XP in the Betweenlands either. The only things are the rings, which are definitely not early game.

**Comment by PetasiGit** [comment]
> No, giving levels will definitely not happen. The levels are logarithmic, i.e. the more XP you have the more it takes to level up. Giving any fraction of a level would completely break the whole system because it'd give way more XP at high levels.

Then how about only
>one or two levels from zero (so basically /xp 16).

It doesn't break the system and it declines in effectiveness the more levels you have. Useful in the early-mid game but not so great after you have a lot of levels.

>That's incorrect. Nibblesticks retain food sickness even in the overworld :P

TIL

And from WoS

>..aren’t required to kill anyways..

How else are you going to get Chiromaw Wings in the early game without killing Chiromaws? Sure, they drop without the player killing them but it still has to die.

>There aren’t really any early game uses for XP in the Betweenlands either. The only things are the rings, which are definitely not early game.

The rings of power/ascent can be obtained as loot from chests/item scrolls and chests. The ring of summoning only requires a bit of herblore, an animator, a life crystal, and a tar beast heart. It's not punching trees early game, but it's possible that you could obtain a ring before having full valonite (which would be end-game).

**Comment by TheCyberBrick** [comment]
Like I said we'll think about increasing it a bit, but it won't be much because that's how it's supposed to be. It isn't and will not be a big source of XP.

**Comment by WightofShadows** [comment]
You don’t need Chiromaw Wings to decrease food sickness. They expedite the process substantially but they aren’t literally required.

Finding rings in chests or item scrolls is very rare, and the chest has to be a certain type that itself isn’t common nor usually easy to get to. Herblore requires valonite for the sickle, tar beast hearts aren’t exactly a common drop (nor a common or easy mob to kill), the animator requires a good amount of Life Crystal charge and sulfur, and the dreadful mummy isn’t easy to fight at all (Elixirs of Strength aren’t OP anymore, or early game themselves for that matter).

They may not be very end game but they are far from early game.

**Comment by PetasiGit** [comment]
>It isn't and will not be a big source of XP.

Again, I'm just saying that they should give enough XP in the early game to actually want to use them.
They don't have to give a lot, just more than they do currently.

And from WoS:



>Finding rings in chests or item scrolls is very rare, and the chest has to be a certain type that itself isn’t common nor usually easy to get to. 

Shrines are fairly common if you look for them. Plus they generate in two biomes.

>Herblore requires valonite for the sickle...

...which you can get from Item Scrolls or dungeon Pots of Chance...

>...tar beast hearts aren’t exactly a common drop (nor a common or easy mob to kill)...

Sure, they're not a common drop, but they die to 4 poison arrows and a regular one.


>the animator requires a good amount of Life Crystal charge and sulfur...

Which one Life Crystal and ~3 veins of sulfur will provide.

 >and the dreadful mummy isn’t easy to fight at all (Elixirs of Strength aren’t OP anymore, or early game themselves for that matter).

You can kill it with two blocks and your fist.

>They **[the rings]** may not be very end game but they are far from early game.

That I will agree with, but it is possible to _get_ them early game.

My point is that it is possible to get something that requires XP from the Betweenlands in the early-mid game stage. And that the Nibblesticks themselves currently do not warrant usage whatsoever. They're a completely useless item, and I'd like to see them be a little more useful.

**Comment by TheCyberBrick** [comment]
A no is a no

**Comment by PetasiGit** [comment]
>You'll think about it.

**Comment by TheCyberBrick** [comment]
Well yeah, I said we might increase it *a little bit* :P
But it still won't be an all too useful or reliable XP source

**Comment by vadis365** [comment]
Closing this. It's entirely pointless and not worth any time to change a very minor mechanic when there are more important things to do. The usage has always been a temporary feature and as such planned to be changed to something not revealed here. No point changing it over and over.
Go mine stuff or kill mobs for XP, it's quicker.
