### ISSUE TITLE
Suggestion: Grinding Limestone into Limestone Flux should give multiple

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#553]
Another item with niche usage. I just can't be bothered to mine a stack of extra blocks just so I can _maybe_, _possibly_ increase my profits of mid-tier ores by one third or one half or whatever.

Simply making the Mortar and Pestle give 2-4 or 1-5 Flux per Limestone would make this feature actually worth using. The only reason anyone actually makes Flux currently is for bragging rights. 
"_I hAvE aLl BeTweNlAndS acHiEvEmeNtS_"

**Comment by TheCyberBrick** [comment]
Fair enough, makes sense 👍
