### ISSUE TITLE
mortar and pestal

### ISSUE THREAD

**Issue by ComaCanadian** [TheCyberBrick/The-Betweenlands#561]
#### Installed mods: 250 of them 
sevtech ages 3.0.4 
https://minecraft.curseforge.com/projects/sevtech-ages

## Description of the problem
The mortars GUI should (according to wiki), open with a right click. But it's set to shift and right click. Because Carry On is in the pack, you have to make sure you do this at max range so you don't accidentally pick it up

#### Expected result:
Right click to open GUI.

#### Actual result:
Having to shift right click.

**Comment by PetasiGit** [comment]
SevTech uses 3.3.4; this was just changed in 3.3.6, which was released yesterday.

**Comment by ComaCanadian** [comment]
nice, i'm sure darkosto will update it eventually
