### ISSUE TITLE
Underwater plants remove the source block they're in when broken

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#565]
#### Betweenlands version:

3.3.6

#### Forge version:

Forge 1.12.2-14.23.2.2611

#### Singleplayer or Multiplayer:

Both, but not multiplayer dependent (not a server issue).

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.6
Clumps 3.0.0
FoamFix 1.12.2-0.9.4-Anarchy
FPS Reducer 1.12.2 1.9
FTBLib 5.0.0.14
FTBUtilities 5.0.0.11
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Mouse Tweaks 2.8
Ninja's Mods 1.12
Optifine 1.12.2 D1
Ping! 3.0.9
TapeMouse 1.1.3.17
Texture Fix 4.0
Trade 1.0.4
The Betweenlands 3.3.6
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

1. Break an underwater plant.

![2018-04-07_17 54 05](https://user-images.githubusercontent.com/32495545/38460735-da6d3f12-3a8d-11e8-990c-c385403be2fb.png)

2. See that it removed the water block it was in. It's hard to see here, but the water is pushing me into the corner because the source block was removed.

![2018-04-07_17 54 18](https://user-images.githubusercontent.com/32495545/38460739-e7d588e4-3a8d-11e8-986a-1fa66f413e8e.png)

3. Replace it and the water comes back.

![2018-04-07_17 54 26](https://user-images.githubusercontent.com/32495545/38460741-f4f6d1a4-3a8d-11e8-940e-c86278e3e6c9.png)

#### Expected result:

To break the plant and have the water source remain.

#### Actual result:

The plant deletes the water source when broken.

**Comment by TheCyberBrick** [comment]
That's just how shears work, would need to implement an ASM patch which is just not worth the effort.

**Comment by PetasiGit** [comment]
Perhaps it's something to fix when 1.13 comes out. Works properly with the new vanilla coral.


![2018-04-08_15 15 19](https://user-images.githubusercontent.com/32495545/38471504-038b6d76-3b40-11e8-91cc-702ab6109eff.png)
![2018-04-08_15 15 28](https://user-images.githubusercontent.com/32495545/38471505-03cd3e4a-3b40-11e8-8a56-a41905b36cbf.png)

**Comment by TheCyberBrick** [comment]
Underwater plants will be revisited at that point anyways
