### ISSUE TITLE
Placing water inside of underwater plants deletes them

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#566]
#### Betweenlands version:

3.3.6

#### Forge version:

Forge 1.12.2-14.23.2.2611

#### Singleplayer or Multiplayer:

Both, but not multiplayer dependent (not a server issue).

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.6
Clumps 3.0.0
FoamFix 1.12.2-0.9.4-Anarchy
FPS Reducer 1.12.2 1.9
FTBLib 5.0.0.14
FTBUtilities 5.0.0.11
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Mouse Tweaks 2.8
Ninja's Mods 1.12
Optifine 1.12.2 D1
Ping! 3.0.9
TapeMouse 1.1.3.17
Texture Fix 4.0
Trade 1.0.4
The Betweenlands 3.3.6
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

1. Find an underwater plant.
2. Place a bucket of swamp water inside of it.
3. Voilà, no more plant!

#### Expected result:

For it to place the water, but not change anything. Basically for it to act like a water source block.

#### Actual result:

It deletes the plant.

**Comment by TheCyberBrick** [comment]
That's just how buckets behave? Does the same thing with any other plant

**Comment by PetasiGit** [comment]
I guess this is also something to fix when 1.13 comes out. Maybe it'll end up being a Forge thing.

Here's me emptying a water bucket into a vanilla coral without deleting it.

![2018-04-08_15 14 47](https://user-images.githubusercontent.com/32495545/38471518-41ab0b8e-3b40-11e8-9388-336965584cf4.png)
![2018-04-08_15 14 52](https://user-images.githubusercontent.com/32495545/38471519-41dd0d32-3b40-11e8-8862-ade07d5f1713.png)

**Comment by TheCyberBrick** [comment]
Nothing to fix here, it's not a bug. It's working as intended just like in vanilla
