### ISSUE TITLE
Game crashes when changing the game language and opening an Herblore Book

### ISSUE THREAD

**Issue by RisingInIris2017** [TheCyberBrick/The-Betweenlands#567]
#### Betweenlands version:

Release 3.3.6

#### Forge version:

14.23.2.2654

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Just Enough Items, 
the Betweenlands.

## Link to full crash log

[https://pastebin.com/qnEh2iz8](url)

#### How to reproduce:

1. Open an Herblore book.
2. Change the language to Chinese Simplified.
3. Reopen the book and the game crashes.

Besides, in another several tests, the steps below can also crash the game.
4. Restart the game after the Step 3. 
5. Change the language from Chinese Simplified to any another one. I chose the English(US), for example.
6. Reopen the Herblore Book. 
One crash-report created with the Steps 4-6: [https://pastebin.com/mX6qwwYb](url)

#### Expected result:

To change the game language without crashing the game.

#### Actual result:

After changing the language, the game kept running normally until I opened the Herblore book.

**Comment by RisingInIris2017** [comment]
If you finally determine that the cause of the error is the zh_CN.lang, I need some clues, which are about the reasons why this problem occurs, to amend the language file in order to avoid the problem.

**Comment by GoryMoon** [comment]
5abeec5212f01b82c6cbc5f8017121387a11489a fixes this

**Comment by RisingInIris2017** [comment]
Thanks for your great effort!
