### ISSUE TITLE
Shield Charge Crash

### ISSUE THREAD

**Issue by justinrusso** [TheCyberBrick/The-Betweenlands#569]
#### Betweenlands version:

3.3.6

#### Forge version:

14.23.2.2651

#### Singleplayer or Multiplayer:

Singleplayer

## Link to full crash log

https://pastebin.com/S9v3AQAX

#### How to reproduce:

Reference https://github.com/Darkosto/SevTech-Ages/issues/1584

The OP did not provide a crash log, though a commenter commented with one. They reproduced it in different ways, so I'm not sure if they're entirely related.

**Comment by pau101** [comment]
This has been corrected in https://github.com/Angry-Pixel/The-Betweenlands/commit/06b925fc476be7128b4bc7cf34d9100cd5e5ce44, releaes 3.3.7 will contain the fix.

**Comment by justinrusso** [comment]
Thanks for the heads up! 👍
