### ISSUE TITLE
Cave lighting issue

### ISSUE THREAD

**Issue by MaybeitsTreybelline** [TheCyberBrick/The-Betweenlands#571]
Hello, I was play your mod and in the caves I was having light update issues along with quite a lot fps drops. I have Optifine installed but it's not the problem 

Minecraft: 1.12.2
Betweenlands version: 3.3.7
Forge version: 14.23.2.2654
Optifine version: HD C9 Ultra

Here's some screenshots

![2018-04-09_23 05 08](https://user-images.githubusercontent.com/36465264/38641138-465877e6-3da4-11e8-8b97-10aaaa5dffe2.png)
![2018-04-09_23 05 49](https://user-images.githubusercontent.com/36465264/38641140-4664bdbc-3da4-11e8-8077-89b2a8dc883c.png)
![2018-04-11_16 01 58](https://user-images.githubusercontent.com/36465264/38641141-4671889e-3da4-11e8-9045-7ec3d8907f62.png)
![2018-04-11_16 02 20](https://user-images.githubusercontent.com/36465264/38641143-46820e30-3da4-11e8-8b17-cc6773e264fb.png)

**Comment by TheCyberBrick** [comment]
This is usually caused by "Force threaded chunk rendering" in Forge's config. It's not really a bug, just a tradeoff for improved performance.
