### ISSUE TITLE
Can't craft the Swamp Talisman

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#572]
#### Betweenlands version:

3.3.6

#### Forge version:

Forge 1.12.2-14.23.2.2611 

#### Singleplayer or Multiplayer:

Both, but not multiplayer dependent (not a server issue).

#### Installed mods:

Appleskin 1.12.21.0.9
B.A.S.E 1.12.2-3.5.1
Better Fps 1.4.8
Better Placement 1.0.0-1
Client Tweaks 3.1.6
Clumps 3.0.0
DeathLocation 1.12-1
FoamFix 1.12.2-0.9.4-Anarchy
FPS Reducer 1.12.2 1.9
FTBLib 5.0.0.14
FTBUtilities 5.0.0.11
Hot Swappable Armor 1.0
InventoryTweaks-1.64-dev
Keyboard Wizard 1.12.2-1.5.3-b1
Mouse Tweaks 2.8
Ninja's Mods 1.12
Optifine 1.12.2 D1
Ping! 3.0.9
Smooth Font 1.14.3
TapeMouse 1.1.3.17
Texture Fix 4.0
Trade 1.0.4
The Betweenlands 3.3.6
Waila/Hwyla 1.8.23
XYZing 1.0

#### How to reproduce:

Try to craft the Swamp Talisman.

#### Expected result:

To be able to craft the Talisman. 
http://the-betweenlands.wikia.com/wiki/Swamp_Talisman

#### Actual result:

I can't craft it.

#### Pictures:

![2018-04-11_16 37 00](https://user-images.githubusercontent.com/32495545/38642113-119193fa-3da7-11e8-817c-6e4e88c406b0.png)

**Comment by TheCyberBrick** [comment]
The crystal needs to have full 100% durability, did you check that?

**Comment by PetasiGit** [comment]
So you need to waste a wight's heart even if it's freshly mined from the ore?

**Comment by WightofShadows** [comment]
It shouldn’t be less than 100% if it’s freshly mined, that’s a different bug then I guess.

**Comment by PetasiGit** [comment]
It's always 99% when mined from the ore. I never used the life crystal that I tried to craft the talisman with.
