### ISSUE TITLE
Mod information is not able to display correctly

### ISSUE THREAD

**Issue by RisingInIris2017** [TheCyberBrick/The-Betweenlands#575]
#### Betweenlands version:

Release 3.3.7

#### Forge version:

14.23.2.2654

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

_Just Enough Items_, and _the Betweenlands_.

#### Pictures:

![](https://i.imgur.com/171Z0QU.png)

**Comment by TheCyberBrick** [comment]
Hm I must have messed up the file encoding somehow 🤔
