### ISSUE TITLE
RowboatHandler internal server error and crash

### ISSUE THREAD

**Issue by Waisse** [TheCyberBrick/The-Betweenlands#577]
#### Betweenlands version:
v3.3.7

#### Forge version:
14.23.2.2654

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
https://pastebin.com/ZKVTjYgX

## Link to full crash log
https://pastebin.com/pPqxDjXr

#### How to reproduce:
The game froze when I entered the rowboat, followed by an internal server error + CTD. I can't get out of the rowboat since the game crash whenever I load the world.

#### Expected result:
Using the rowboat.

#### Actual result:
CTD

**Comment by TheCyberBrick** [comment]
Update [CleanView](https://minecraft.curseforge.com/projects/cleanview)

**Comment by Waisse** [comment]
Removing Cleanview stopped the issue. Water looks funny now : 

https://i.imgur.com/JM2OpLN.png

I was using the latest Cleanview version on Curse : 1.12.2-v1a

**Comment by Waisse** [comment]
Latest Cleanview version doesn't fix the boat crash.
