### ISSUE TITLE
[1.12] Pitstone Slab's can't be destroyed/broken

### ISSUE THREAD

**Issue by wiloxe** [TheCyberBrick/The-Betweenlands#578]
#### Betweenlands Version:
3.3.6

#### Forge version:
Version 14.23.2.2651

#### Singleplayer or Multiplayer:
Both Singleplayer and Multiplayer

#### Installed mods:
This issue was found while playing the following Modpack "Sevtech" in version 3.0.6
https://minecraft.curseforge.com/projects/sevtech-ages

## Description of the problem
So it turns out that Pitstone Slab cannot be broken. Survival or creative, it dosesn't matter.

#### How to reproduce:
1. Go into either multiplayer or singleplayer.
2. Place Pitstone slab anywhere.
3. Try breaking it in either creative or non-creative mode.

#### Expected result:
When you break the slab you should get it should drop and won't reappear again after.

#### Actual result:
As you try to break it the slab will disappear for a split second then reappear in either upside down or normal placement.
If you destroy in singleplayer the slab will drop a slab for you but won't actually get removed.

**Comment by TheCyberBrick** [comment]
This seems to be something specific to SevTech and usually doesn't happen. It's probably some other mod changing the way slabs are broken, and I don't think our slabs do anything weird or special.

Issue on SevTech repo: https://github.com/Darkosto/SevTech-Ages/issues/1519

**Comment by dsmall3303** [comment]
My first guess would be KleeSlabs, as that allows the player to only break the top/bottom of a two-slab block when sneaking. Could there be some unintended interaction there?

**Comment by Jandakast** [comment]
I created this as an issue on the KleeSlabs tracker. This happens in a pack with just The Betweenlands and KleeSlabs installed. 

https://github.com/blay09/KleeSlabs/issues/17

**Comment by BlayTheNinth** [comment]
Fixed in latest KleeSlabs version.

**Comment by TheCyberBrick** [comment]
Thanks!
