### ISSUE TITLE
Suggestion: Crimson Gem buff

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#583]
Crimson Gems give strength and knockback. The problem with this is that you get the strength effect, but then you can't use it because your target has been flung half-way across the world.

Simply removing the knockback effect would make the Crimson Gem *way* better, because you could actually utilize the strength buff it gives. 

Currently the Aqua and Green gems overshadow the Crimson one because the knockback is so annoying. This buff would level the playing field, with each gem actually being viable in combat.

**Comment by theishiopian** [comment]
Another, perhaps more interesting option would be to make the knocked back enemies take fall damage from smashing into things. Kind of like smashing into a mountain with an elytra.

**Comment by TheCyberBrick** [comment]
I agree that knockback makes it a bit less useful than it could be, but at the same time I want to keep the knockback. Here's an idea:
When crimson procs the enemy starts glowing red for a few seconds, while glowing red:
1) takes more damage from any damage source
2) if attacker is sneaking and attacks is knocked back further

Like that you could decide to go for more damage or to knock the enemy back to get distance

**Comment by theishiopian** [comment]
I still think his point about knockback still stands, as knocking an enemy back knocks them out of range. Really, knockback is more a defensive strategy than an offensive one. I would suggest making the defensive gem (blue IIRC) inflict knockback when put on weapons.

**Comment by RisingInIris2017** [comment]
I think if Crimson is positioned as a an offensive gem applied on melee weapons, knockback may make it difficult to deal successive damage, which is a drawback when a player fight with a ranged attack mobs, such as Pyrads in BL or skeletons in the overworld. So I support okl's opinion. And I have an even more radical suggestion: when it is applied on weapons, it may cancel any knockback but deals large amount of damage, making players risk the chance of escape to kill enemies quickly,  just like a berserker.

**Comment by okl1001** [comment]
>When crimson procs the enemy starts glowing red for a few seconds, while glowing red:

takes more damage from any damage source
if attacker is sneaking and attacks is knocked back further
Like that you could decide to go for more damage or to knock the enemy back to get distance

>Really, knockback is more a defensive strategy than an offensive one. I would suggest making the defensive gem (blue IIRC) inflict knockback when put on weapons.

>...when it is applied on weapons, it may cancel any knockback but deals large amount of damage, making players risk the chance of escape to kill enemies quickly, just like a berserker.

I think any of these would be an improvement over what it currently does.

**Comment by PetasiGit** [comment]
I think any of these ideas would be an improvement over what it currently does.

**Comment by WightofShadows** [comment]
I feel that, with this and things like the shield charge, the knockback is nice but too powerful. Simply reducing the amount of knockback caused by a significant amount would allow the strength effect to still be utilized without giving too large a window of opportunity for extreme DPS. Either that or a simplified version of Cyber’s idea, where the strength buff is applied as usual and you have the option to deal knockback by holding shift within that same effect’s duration.

I would support aqua gems receiving the knockback effect instead, except then that would make its current weakness effect pretty much useless as well.
