### ISSUE TITLE
Adjust description of Arrow advancement for better clarity

### ISSUE THREAD

**Issue by justinrusso** [TheCyberBrick/The-Betweenlands#584]
The description states that the player needs to use all arrow types. But from experience, it seems to be that the player needs to *kill* a mob with the arrow, not just use it/hit something with it.

**Comment by TheCyberBrick** [comment]
👍

**Comment by TheCyberBrick** [comment]
I can't reproduce this. Works fine for me without killing the mob.
I'm assuming this is for SevTech so I'll try it there later today.

**Comment by justinrusso** [comment]
Maybe just some weirdness? I was watching Sevadus and he hit a mob with the last arrow needed and it didnt trigger by just hitting some mob, but he went and shot a snail with it (which one shot it) and it triggered.

**Comment by TheCyberBrick** [comment]
Works fine in SevTech too, was probably just some lag or something like that
