### ISSUE TITLE
Exposing LootTables to Mods like LootTweaker

### ISSUE THREAD

**Issue by KAfable** [TheCyberBrick/The-Betweenlands#585]
#### Betweenlands Version: 
3.3.7

#### Forge version:
2669

#### Single player or Multiplayer:
Both singleplayer and multiplayer.

#### Installed mods:
No official modlist yet, this is for the ATM's next upcoming progression pack. Relevant mods will be Betweenlands, CraftTweaker, and it's add onLootTweaker.

## Link to full crash log
N/A

#### How to reproduce:
Doing `/ct loottables dump` doesn't seem to recognize any of the loot tables or mob drops added by the BetweenLands. Leviathan details here https://github.com/PrinceOfAmber/ERZ/issues/13 (need to scroll down a bit) on registering the loot tables so they can be accessed / altered.

This would be useful for modpack creators to help with integration of BetweenLands in a pack, so Betweenlands mobs can drop different items, or can find loot from other mods inside the BetweenLands, eg needing to find a particular item in a Wight Fortress to progress in other magic mods.

**Comment by Saereth** [comment]
seconding this post, would be a huge help to pack makers

**Comment by TheCyberBrick** [comment]
Will do
