### ISSUE TITLE
Portals don't try to Sync up after being broken.

### ISSUE THREAD

**Issue by SyriiAdvent** [TheCyberBrick/The-Betweenlands#587]
Playing on Sevtech 3.0.6 and a Cursed Creeper nuked my Portal Tree when i was inside the Betweenlands. Now I have over 7 random trees across my area in overworld & Betweenlands from trying to sync up the portals........

**Comment by ouroborus** [comment]
They also don't always function as new either. Set up a tree in the overworld but it wouldn't go through. Set up another tree at the same location in the betweenlands but it doesn't function either. They should link up like nether portals do.

**Comment by TheCyberBrick** [comment]
The portals don't work the same way vanilla ones do. You can link two portals together with the Swamp Talisman if they're close enough to each other and not in the same dimension.

**Comment by ouroborus** [comment]
How close is "close enough"? How do you use the Talisman to link them?

**Comment by TheCyberBrick** [comment]
> How close is "close enough"?

1500 blocks at the moment, it'll be configurable in the next update though.

> How do you use the Talisman to link them?

Right-click on portals
