### ISSUE TITLE
Server crash: "BetweenlandsWorldStorage capability"

### ISSUE THREAD

**Issue by HatTrkPatrk** [TheCyberBrick/The-Betweenlands#590]
#### Betweenlands version:

3.3.7

#### Forge version:

forge-1.12.2-14.23.3.2655

#### Singleplayer or Multiplayer:

Multiplayer (Server), forge-1.12.2-14.23.3.2655

#### Installed mods:

https://pastebin.com/ivNyS81N

## Link to full crash log

https://pastebin.com/Hx5sfaZP

#### How to reproduce:

1. As op on the server, enter the world
2. Type /simpledimensions create
3. Create a new dimension, I named it "New Dimension" as a test

#### Expected result:

Not a crash

#### Actual result:

Server crashed. Log mentions that the new dimension doesn't have "BetweenlandsWorldStorage capability"

#### Pictures:

--------------

Additional info:
Not sure if this is a problem with Betweenlands or Simple Dimensions because I don't fully understand what the capability reference is. Figured this could be marked as a possible issue at least, and if it can be fixed terrific. Thank you.

**Comment by TheCyberBrick** [comment]
Thanks!

This was already reported on Simple Dimensions' issue tracker:
https://github.com/lumien231/Simple-Dimensions/issues/14

I'll keep this open for now in case somebody else runs into the same problem
