### ISSUE TITLE
Druid circles on a server

### ISSUE THREAD

**Issue by TripleZ0** [TheCyberBrick/The-Betweenlands#591]
This would be more likely a question than a bug report. 

Is there a way to reset these druid circles on a server?
The problem is that after someone used the druid altar the druids won't spawn anymore.
I would like to know if I can add more druid circles on a server or if I could reset them as a server admin?

Thank you.

**Comment by TheCyberBrick** [comment]
No, currently there's no way to reset the Druid Circle except creating a spawner for Dark Druids. It might make sense to add some way to reactivate the circle, especially for servers. I'll try to come up with something
