### ISSUE TITLE
[1.12.2] Twilight Forest Interaction - Portal Tree Location

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#593]
I'm working with Betweenlands as my starting dimension and having players travel from dimension to dimension as part of a mod pack.  One issue we are seeing is that if you setup the Betweenland configs to send the first portal tree you make to the Twilight Forest, it picks the wrong spots for placement of the tree portal in the twilight forest.

By wrong spot, I mean in biomes that the player can't visit yet due to TW's progression system.  Is there a way to change how the portal is generated and only spawn it in the twilight forest's starter biomes/zones?

**Comment by TheCyberBrick** [comment]
Hm yeah that should be doable. The portal already looks for suitable biomes in the Betweenlands so it should be easy to add a biome whitelist/blacklist for the other way. Biome white-/blacklist should be enough, right?

**Comment by MokahTGS** [comment]
Yes, if I can find the names of the Twilight forest biomes...is there a reliable way to get forge to output in-game names for biomes?

**Comment by TheCyberBrick** [comment]
https://github.com/TeamTwilight/twilightforest/blob/ac0005092d9ffafd4901891229467d6db5c7e7ca/src/main/java/twilightforest/biomes/RegistryBiomeEvent.java

They're all in there, just prepend "twilightforest:" to their names, e.g. "twilightforest:twilight_lake". If I remember correctly, you can also use NEI to dump a list of all biomes

**Comment by TheCyberBrick** [comment]
![](https://i.imgur.com/BfGFN1D.png)

**Comment by MokahTGS** [comment]
Awesome thanks!
