### ISSUE TITLE
My modpack crash when go to the betweenlands with version 3.3.8

### ISSUE THREAD

**Issue by Fireztonez** [TheCyberBrick/The-Betweenlands#594]
Hello,
In my modpack I made, my game crash and the Console show Unloading dimentions and everithing, when I try to go to the Betweenlands. I try multiple time, and each time I got the exact same issue... I just try to downgrade Betweenlands to the v. 3.3.7 and everithing look good, I try in my existing world, and the dimension load and work great, but with the 3.3.8 doesn't work...

Possibly is came from a compatibility issue with other mod, I don't know...

Version:
Minecraft: 1.12.2
Forge: 14.23.3.2678
Betweenlands : 3.3.8

Crash Log: https://gist.github.com/Fireztonez/c06372af38432b8c3c26c28769cce5dc

If you need other information, just tel me.
Fireztonez

**Comment by TheCyberBrick** [comment]
That is not the crash log. And it looks more like the crash is caused by TickDynamic
