### ISSUE TITLE
[1.12.2] Death In Other Dimensions does Not return you to the Betweenlands spawn point.

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#596]
#### Installed mods:
https://pastebin.com/c5nyk5Hi

#### How to reproduce:
Traveling to other dimensions and dying returns the player to the overworld spawn instead of the Betweenlands spawn.  This happens even if the player has set their spawn in the Betweenlands with a bed, set it with commands like /setworldspawn or any other method I've tried.

#### Expected result:
Dying in other dimensions returns you to your set spawn (bed) or world spawn  in the betweenlands.

**Comment by theishiopian** [comment]
This also seems to happen with the twilight forest, so it may just be a consequence of vanilla not being designed to allow you to sleep in other dimensions.

**Comment by TheCyberBrick** [comment]
I think he's talking about the "Start players in Betweenlands" option where players start out in the Betweenlands instead of the Overworld. TF portals don't work both ways in multiple dimensions IIRC.

@MokahTGS I can add another config to force respawn in Betweenlands if no spawn point was set

**Comment by MokahTGS** [comment]
Yes, that would be a preference.  The idea here is that the overworld does not exist.  Would this affect players who die in the nether, or Twilight Forest, etc?

**Comment by TheCyberBrick** [comment]
If no spawn point is set or the dimension does not let you respawn in it, then it would default back to Betweenlands

**Comment by MokahTGS** [comment]
Yay!
