### ISSUE TITLE
[1.12.2] Death and Losing Items - Question

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#597]
Does BL override KeppInventory rules?  We are finding in testing that some items in our items, but not all of them disappear when dying even when KeepInventory is set to true.  Is this something that BL does by design or is this a bug, or is there some other mod that is responsible?

We are trying to setup a mod pack and losing stuff in the inventory is making testing difficult.

**Comment by WightofShadows** [comment]
It is highly likely another mod is causing the problem. I have never lost any of my items while dying in the Betweenlands when keepInventory is on, and I've just tested to make sure.

**Comment by MokahTGS** [comment]
OK, the weird thing is that it only affects some items.  Tools and weapons are unaffected, as well as bags, and armor.  Torches, food, and random items in your inventory disappear.  Oddly there are random plants that seem unaffected as well.

**Comment by TheCyberBrick** [comment]
Sounds like the Aether II
> Look out! Its a hotfix!!
A new indev build has been released for 1.12.2 including campfires, fixes to separate inventories, **and a new inventory system which only drops materials when you die!**
https://minecraft.curseforge.com/projects/the-aether-ii/files/2557555
https://minecraft.curseforge.com/projects/orbis-api/files/2557551

**Comment by MokahTGS** [comment]
Yes, this was this issue.  Now I have to see if I can turn it off.  Very annoying.
