### ISSUE TITLE
[Suggestion/Request] Botania Integration 

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#600]
I'm wondering if you could add a few things for Botania integration that would help out mod packs.

Add swamp water as a usable water in the petal apothecary.  Currently I'm using a clunky "filtering" method using the Water Strainer mod and and iron bucket, which can only be gotten through loot bags.  Not ideal.  Maybe if you could put a bucket of swamp water in the purifier you could get a bucket of clean water.

Add sulfur as a burnable item for the endoflame flower.  Essentially sulfur is coal...it should be burnable by the endoflame. 

At any rate, I know this is not top priority, but it adds more to what you can do with your mod.  Currently I'm trying to have the player only be able to escape the betweenlands via the Gaia portal to the Erebus...they need to defeat the Gaia Guardian from Botania to make the portal.

**Comment by TheCyberBrick** [comment]
>Add swamp water as a usable water in the petal apothecary. Currently I'm using a clunky "filtering" method using the Water Strainer mod and and iron bucket, which can only be gotten through loot bags. Not ideal. Maybe if you could put a bucket of swamp water in the purifier you could get a bucket of clean water.

I think it's hardcoded to only accept the normal water fluid. If that's something you really need you have to ask the devs of Botania for a config.

> Add sulfur as a burnable item for the endoflame flower. Essentially sulfur is coal...it should be burnable by the endoflame.

Does that not already work? It *should* work with any fuel that's not in a container.

**Comment by MokahTGS** [comment]
Burning sulfur does work.   For some reason it didn't in my first test,  but it has for all subsequent tests.   I'll just figure a work around for the water.
