### ISSUE TITLE
Modpack downloading issues.

### ISSUE THREAD

**Issue by DanielMB62** [TheCyberBrick/The-Betweenlands#603]
I tried downloading all the mods 3 today and im starting to get the issue whenever the app starts downloading the betweenlands it just freezes and crashes giving me an error about the server being unavailable and sending me here to make a report.

In fact its happening with any modpack with this mod in it, i just dont understand how i can download larger mods but whenever i hit this specific one it just refuses to download.

**Comment by TheCyberBrick** [comment]
That's beyond our control, we're not the ones who made the app you're using. The mod is quite big and the file is bigger than most other mods, so it might take a while to download. You can try downloading it manually from curse and then put it in the modpack yourself, but then you need to make sure that it's using the correct config from the mod pack.
