### ISSUE TITLE
Overworld Beds reset

### ISSUE THREAD

**Issue by Gammaboy45** [TheCyberBrick/The-Betweenlands#607]
It seems that every time I come back from the Betweenlands after some time, my spawnpoint in the Overworld is reset to the world spawn. It may be because I reload Minecraft between that time, usually to fix major lag from excessive chunk loading, while exploring the Betweenlands

**Comment by TheCyberBrick** [comment]
That seems to be a vanilla bug. I'll create a bug report or PR for Forge
