### ISSUE TITLE
Feature Request: Compatibility with Tomb Many Graves 2 via API

### ISSUE THREAD

**Issue by M4thG33k** [TheCyberBrick/The-Betweenlands#608]
Hello!

I have recently made an update to Tomb Many Graves 2 which allows mod authors other than myself to add compatibility between their mod and mine. This update uses a new API I created; I have also (temporarily) created a plug-in to allow your mod to work with TMG using this API. I was hoping/wondering if you would consider using the API in order to take compatibility handling out of my hands in case future updates change the way things work for your mod? You can use the plug-in I created as an example, and I can answer any questions you may have.

Link to API project: https://minecraft.curseforge.com/projects/tombmanygraves-2-api

(A link to the specific plugin's project can be found on that page as well)

Thanks!
-M4thG33k

**Comment by GoryMoon** [comment]
I've added your plugin in 886854f3e0b2fb6c26d18a8cd7a0163105d45ff5 as a soft dependency
