### ISSUE TITLE
Betweenstone can create Stone tools

### ISSUE THREAD

**Issue by Gammaboy45** [TheCyberBrick/The-Betweenlands#609]
I can't tell if this is a bug or a feature that simply has not been accounted for, but crafting tools with Betweenstone yields regular stone tools (which are less effective in the Betweenlands)

**Comment by 63502** [comment]
I would guess this is an ore dictionary bug causing betweenstone to be registerd as a cobblestone equivalent somewhere. You aren't supposed to be able to craft tools out of betweenstone at all, as the second tier of betweenlands tools are made of slimy bone. 

Just for reference, The betweenlands tool tier equivalencies are as follows:

1. Weedwood - Wood
2. Slimy Bone - Stone
3. Octine/Symorite - Iron
4. Valonite - Diamond

**Comment by Gammaboy45** [comment]
Ah, I forgot about slimy bone.

**Comment by DLumina** [comment]
Well, in my JEI, the betweenstone is registered as an cobblestone equivalent. hope the author can fix it.

**Comment by TheCyberBrick** [comment]
Betweenstone is oredict'd as cobblestone which is intentional.
