### ISSUE TITLE
Crash while trying to go into Betweenlands dim

### ISSUE THREAD

**Issue by Pirog17000** [TheCyberBrick/The-Betweenlands#610]
#### Betweenlands version:
3.3.8

#### Forge version:
14.23.3.2655

#### Singleplayer or Multiplayer:
Server, Forge

#### Installed mods:
Betweenlands only.

## Link to full crash log
https://pastebin.com/6dt2EPdy

#### How to reproduce:

1. Give yourself OP
2. Create Portal Tree, walk through the portal
3. Game frozen, server died on trying to generate dimension

#### Expected result:
See new dimension with mod content

#### Actual result:
Crash.

**Comment by falkreon** [comment]
I ran into a similar issue, preventing a dedicated server from even starting-
https://gist.github.com/falkreon/cc5bf25e9fdd2f2d37cfa2dafabec85c
We seemed to be fine running Forge 14.23.4.2702, but when we updated to 2703 it died.
