### ISSUE TITLE
Torches remaining lit with cyclic mod

### ISSUE THREAD

**Issue by TheMingo888** [TheCyberBrick/The-Betweenlands#611]
## Description of the problem
When both Cyclic and the Betweenlands are installed, it is possible to bypass sulfur torches in favour of vanilla torches using two items that place torches in in the world for you.

#### How to reproduce:

1. Craft Cyclic throwing torches (cyclicmagic:ender_torch) or a torch launcher (cyclicmagic:tool_torch_launcher).
2. Enter the Betweelands
3. Use the two aforementioned items to place vanilla torches and watch them not become damp torches

#### Expected result:

The torches should become damp torches.

#### Actual result:

The torches remain regular vanilla torches and do not become damp.

**Comment by DLumina** [comment]
If a mod looks like OP, works like OP, then it is OP.
I do not expect so much when dealing with a mod which can /gamemode 3

P.S. If you really want to chanllenge yourself in betweenlands as designed to, I do not recommend you to install Cyclic.

**Comment by TheCyberBrick** [comment]
There's not much we can do about something like this. The torches are converted whenever a *player* places a torch. If something else, e.g. a projectile, places a torch we can't efficiently detect that. One solution would be to randomly check for blocks around the player and if it is a torch make it turn damp. Would not be instant like that but it should work.
