### ISSUE TITLE
Rowboat issue, when are you going to fix it?

### ISSUE THREAD

**Issue by TheFlie01** [TheCyberBrick/The-Betweenlands#614]
Title says it all, for info:

https://github.com/micdoodle8/Galacticraft/issues/3385

I am experiencing the same issue. Please don't be too lazy this time about this, The Betweenland is a nice addition to MC. Finish the coding before adding features.

**Comment by pau101** [comment]
This was resolved 20 days ago there hasn't been a new release yet. In the meantime you can try a [pre-release build](https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases), which are not stable so be sure to keep a world backup.
