### ISSUE TITLE
FPS tanking with latest update. Seems to be fireflies.

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#616]
#### Betweenlands version:
TheBetweenlands-3.3.8-universal

#### Forge version:
1.12.2  2702
#### Singleplayer or Multiplayer:

Single- have not tried multi yet.
#### Installed mods:
https://minecraft.curseforge.com/projects/ancient-towncraft

#### How to reproduce:

1.Run pack
2.Load world
3. can't move. on a GeForce GTX 770
#### Pictures:
![2018-05-21_14 46 02](https://user-images.githubusercontent.com/4427684/40332390-33a51622-5d11-11e8-9c06-e110cf0c83d5.png)
![2018-05-21_16 08 35](https://user-images.githubusercontent.com/4427684/40332400-3e2c76bc-5d11-11e8-8e29-475185ba46fa.png)
Laggoggles FPS report.
![2018-05-21_16 03 50](https://user-images.githubusercontent.com/4427684/40332403-408f005a-5d11-11e8-97de-832d8737371b.png)

Perhaps a new conflict with NeterEx?

**Comment by TheCyberBrick** [comment]
I don't quite understand those profiling results. If fireflies are 0.55% of one frame then how could that destroy the fps like that?
I'll try out the pack myself and see if I can reproduce it

**Comment by TheCyberBrick** [comment]
Is this still a thing in the latest version of your pack? I've just tried it and can't reproduce it. I haven't found anything unusual using a profiler either.
Does this happen all the time or just in specific situations?
