### ISSUE TITLE
[Suggestion] Decay bar conflicting with flight bar from botania

### ISSUE THREAD

**Issue by levilips123** [TheCyberBrick/The-Betweenlands#617]
those two bars are covering each other, I was wondering if you could make the decay bar go above the flight bar if I have my flugel tiara in the beweenlands so that they don't cover each other anymore. it is really annoying me . though I think it is a problem from their mod but I am not really sure. if it is, it would be highly appreciated if you or they made an "support" kinda thing .... I dunno. thanks for listening

**Comment by PetasiGit** [comment]
Doesn't Botania have config options specifically for moving the height of the bars?

**Comment by levilips123** [comment]
yes it does but it's only for how high I want the bar to be and how high I want it to be when the oxygen underwater bar appears. I can just move it over where the decay bar is but the thing is that the decay bar appears only in the betwenlands dimension which means that the flight bar which I will have more of the time on me will have the space for another bar between the hunger bar and itself. It just looks weird.

**Comment by PetasiGit** [comment]
There’s been a config option added for decay bar position since 3.4.7, gonna close because this is old.
