### ISSUE TITLE
Crash when placing Integraded Dynamic Variable Card into the Weedwood Crafting Table

### ISSUE THREAD

**Issue by Jandakast** [TheCyberBrick/The-Betweenlands#618]
#### Betweenlands version: 
The Betweenlands 3.3.8

#### Forge version:
Forge 2679 and 2702

#### Singleplayer or Multiplayer:
Single Player

#### Installed mods:
Originally reported in SevTech Ages but can be reproduced with just The Betweenlands and Integrated Dynamics installed.  https://github.com/DarkPacks/SevTech-Ages/issues/2596

Common Capabilities 1.4.0
Cyclops Core 0.11.6
Integrated Dynamics 0.11.12
JEI 4.9.1.189

## Link to full crash log
https://gist.github.com/Jandakast/665826264ddb5378ad1e815d2f98d3d0

#### How to reproduce:
1. Place Weedwood Crafting table
2. Place Integrated Dynamics Variable Card into table
3. Enjoy the crash

#### Expected result:
No crashing

#### Actual result:
Game crashes

**Comment by pau101** [comment]
This should be directed to CyclopsCore too as a model class from it is what is not supporting the method we use to render items for the workbench (which is rendering the model directly without going through override list).

We'll make a correction on our end which would resolve this issue but the underlying bug in CyclopsCore should be corrected.
