### ISSUE TITLE
[1.7.10]The Betweenlands Can't work with Optifine E7

### ISSUE THREAD

**Issue by jahtim** [TheCyberBrick/The-Betweenlands#625]
#### Betweenlands version:
TheBetweenlands-1.0.6-alpha-universal
1.7.10

#### Forge version:
1614(newest)

#### Singleplayer or Multiplayer:
Crush On startup

#### Installed mods:
The Betweenlands
Optifine E7
1.7.10

## Link to full crash log
https://gist.github.com/TataTawa/4de0a17c8782afc0ee1ec3e2fd5f6296

#### How to reproduce:
have the two mods together in the mods folder and start the game

#### Expected result:
the game started

#### Actual result:
the game failed to start

#### Pictures:
[13:58:50] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 18-6-3 下午1:58
Description: Initializing game

java.lang.VerifyError: Expecting a stackmap frame at branch target 35
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78473_a(F)V @31: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 00e4 b401 a8c6 024f 2ab4 00e4 b401
    0x0000010: b0c6 0245 2ab4 00e4 01b5 01e9 b801 ee99
    0x0000020: 0004 b12a b400 e4b4 01f2 b601 f88d 492a
0x0000030: b400 e42a b400 e4b4 01a8 2823 b601 fcb5

this is an fatal error

**Comment by PetasiGit** [comment]
1.7.10 is no longer supported by the devs, they've moved on to 1.12.2. They will *not* be fixing any bugs in older versions.

**Comment by jredfox** [comment]
they could do a backport alot of people stick with < 1.9. I even go far back playing as 1.2.5 and alpha versions since that's when mc was mc

**Comment by TheCyberBrick** [comment]
@jredfox of course we could, but I believe you're severely underestimating the amount of work required for that. Besides, it's not in my personal interest to backport to those old and outdated versions when we have cool new features in 1.12+

@TataTawa Optifine E7 is not supported in that version but using `OptiFine HD U D3` instead should work

**Comment by HRudyPlayZ** [comment]
Fixed in #1294.
