### ISSUE TITLE
Mire Snails

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#63]
Passive, slow creatures. They drop Snail Flesh and Mire Snail shells.

**Comment by MrCompost** [comment]
Can also 'stick' to the side of blocks.

**Comment by MrCompost** [comment]
You can breed them with Sludge Balls.

**Comment by MrCompost** [comment]
Still needs to be able to stick to the sides of blocks.

**Comment by TripleHeadedSheep** [comment]
Hatching fixed :D
I did a thing!

**Comment by MrCompost** [comment]
Holy moly :D

**Comment by vadis365** [comment]
Closing this for now - will take a long time to make the code for these to do what I want.
Will re-open at some point.
