### ISSUE TITLE
Future Features: What we have so far

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#630]
I figured I would compile a list of the additions and changes that have been definitely planned and/or in the making for a while now, to make it easier to remember everything when we do start working on features beyond the current. There are probably other ideas yet to come, including some of my own. Feel free to add to this list if I forgot something~

**Already in Progress -**
- [ ] Poop Dungeon - Blocks and structure generation in progress
- [ ] Planks for Hearthgrove and Nibbletwig - Mostly implemented, still needs doors/trapdoors

**Short Term Plans (next major update?) -**
- [ ] Loot Balancing - High Priority
- [ ] Poop Dungeon Mobs - Crypt Crawlers, Worms, etc.
- [ ] Puffins - Model done
- [ ] Little Root Guys - Model done
- [ ] Scabyst Decorative blocks - Textures done
- [ ] Amate Paper Blocks - Textures done
- [ ] New Loot Items (stuff in unused folder in resources) - Many textures done
- [ ] New Armour textures + Armour upgrading mechanic?
- [ ] Herblore Rune stuff (I don't really know the details of that lol)
- [ ] Volarkite (mayyyybe?)
- [ ] Chirpsects - Model Done

**Long Term Plans (eventually, hopefully, maybe) -**
- [ ] Tribes
- [ ] New biomes and everything that comes with them (won't spoil the plans here)
- [ ] Stalker
- [ ] Mud Golem - Model done
- [ ] Boulder Sprite - Model Done
- [ ] Anadia
- [ ] Ancient Temples (+Guardians, Idols, etc.) - Models 5/6 done
- [ ] Prime Wight stuff obviously - Model done
- [ ] Unused items (Rubber/Tar shields, Scout, Shadow Staff, etc.)
- [ ] We should probably review the other suggestions already posted as issues here and decide which ones we wanna use
- [ ] HL Crystal Ball thing that predicts events
- [ ] Some kind of ingame guide thing. Maybe not the original Guide Book, something less obvious perhaps

**Comment by RisingInIris2017** [comment]
can't wait for the improved herblore mechanics. nice job! :P

**Comment by TripleHeadedSheep** [comment]
Edited: Added which models are done, added Chirpsect, mention of biomes, Tribes

**Comment by TripleHeadedSheep** [comment]
Also, this list is quite incomplete, but I can;t be bothered to look up everything and add it at the moment ;)

**Comment by levilips123** [comment]
I like how those sound . especially the long term ones . nice :D

**Comment by alxcool** [comment]
... About the new biome, I've encountered Marsh0 and Marsh1... The variation between both is small but make a world of difference. If this is not too hard to implement, could you do some variation for both swamland and Patchy Island in the same style. No need to implements news blocks mobs or items... Just a different disposition of what already exist^^

Difference between both marsh, is the length or size of the dirt path between hole of water. Simply having larger path of dirt, mud, peat create a world of difference... Thk you guys for that!

**Comment by TheCyberBrick** [comment]
Merged into #707
