### ISSUE TITLE
Crash upon loading into world

### ISSUE THREAD

**Issue by Rongmario** [TheCyberBrick/The-Betweenlands#632]

**Comment by GoryMoon** [comment]
You only have the core jar and not the main mod jar.
Usually happens when removing the mod and forgetting about removing the core jar.

**Comment by Rongmario** [comment]
Sorry wrong paste! https://paste.ee/p/lfCKV

Is Betweenlands only using the Dim ID in the config (20?) because I've already excluded that from Cubic Chunks, still wondering why it crashes?

EDIT: If it looks like it's purely Cubic Chunks' fault, please close issue :)
