### ISSUE TITLE
Blood Snails

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#64]
Slow hostile creatures. They have a weak attack but can poison the player with red projectiles, as if squirting it's blood at you. Drops Snail Flesh and Blood Snail Shells.

**Comment by MrCompost** [comment]
Can also 'stick' to the side of blocks.

**Comment by MrCompost** [comment]
Still needs blood projectile and the ability to stick to the side of blocks.

**Comment by TripleHeadedSheep** [comment]
Also, they have a new model

**Comment by vadis365** [comment]
Closing this for now - will take a long time to make the code for these to do what I want.
Will re-open at some point.
