### ISSUE TITLE
mekanism mod conflict crashes

### ISSUE THREAD

**Issue by Maditox** [TheCyberBrick/The-Betweenlands#641]
#### Betweenlands version:

3.3.8
#### Forge version:

14.23.4.2705
#### Singleplayer or Multiplayer:

multiplayer
#### Installed mods:

its a big modpack but the problem is with mekanism
(the mod pack is all the mods 3)https://minecraft.curseforge.com/projects/all-the-mods-3
## Link to full crash log

https://gist.github.com/Maditox/2f5d1f7338be593dbe86a06dd8a5d403

#### How to reproduce:

placing any mekanism machine on a weedwood crafting table causes a crash. i first discovered it with the personal chest but have found that the basic bin also causes crashes. im going to assume all machines have similar issues
1. place a mekanism personal chest on a weedwood crafting table
2. crash

**Comment by pau101** [comment]
This is reoccurence of https://github.com/Angry-Pixel/The-Betweenlands/issues/618, it has been resolved, but hasn't gotten into a release yet unfortunately.
