### ISSUE TITLE
Decreased slimy bone ore gen

### ISSUE THREAD

**Issue by TripleHeadedSheep** [TheCyberBrick/The-Betweenlands#654]
If I remember correctly the Slimy Bone Ore was purely added so that players can progress in peaceful mode.
Right now it is so common though, that it almost completely removes the challenge of killing your first hags to get the tools. I think we can force players more to go hag killing for the bones if we decrease the Slimy Bone Ore gen. the ore become useless anyways after getting a bone pick.

 If someone is in peaceful, they have enough 'safe' time to find their ores anyways.

**Comment by MokahTGS** [comment]
I think this may have been decreased a little too much.  Testing a survival setup and have found only 1 ore block after 30 minutes of searching.

This may be an interaction with the add-on mod Betweenlands Ores.
