### ISSUE TITLE
Trying to add a custom portal but it's not working

### ISSUE THREAD

**Issue by thedragonslayr** [TheCyberBrick/The-Betweenlands#656]
I'm trying to understand what I'm doing wrong. I want to be able to enter the nether from the between lands so I edited the config.

I'll copy the part of the config I changed.

    # Custom saplings or blocks can be specified here to work with the Swamp Talisman. Syntax is "modid:blockname:meta/dim", meta can be * for wildcard, if no meta is provided 0 is used. The dimension ("dim") specifies to which dimension the portal will lead to
    S:portal_dimension_targets <
        minecraft:obsidian:-1
     >

    # Betweenlands portals will only work in these dimensions
    I:portal_dimension_whitelist <
        0
        -1
        1
        20
     >

Did I miss anything, because when I click, and I also tried to shift click, on an obsidian block with the talisman. Nothing happened.

what am I doing wrong

**Comment by TheCyberBrick** [comment]
Your entry should look like this: `minecraft:obsidian:*/-1`.
There should be an error in the log that tells you if and why an entry is incorrect.
