### ISSUE TITLE
crsh updating screen events

### ISSUE THREAD

**Issue by kuroyure** [TheCyberBrick/The-Betweenlands#663]
#### Forge version:14.23.4.2729

singleplayer

#### Installed mods:
list in the crash

## Link to full crash log
https://pastebin.com/CXv2AWYV

#### How to reproduce:
1.install all the mods present on crash
2 open jei search and search stones
3. click u over cobblestone

#### Expected result:
no crash

#### Actual result:
crash

**Comment by pau101** [comment]
There will be a dev release that includes the patch soon.

**Comment by pau101** [comment]
Here you go (and have a world backup): https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases/tag/dev-1.12-dev-876-10.07.2018
