### ISSUE TITLE
Crash when entering portal

### ISSUE THREAD

**Issue by PetasiGit** [TheCyberBrick/The-Betweenlands#664]
#### Betweenlands version:

3.3.9

#### Forge version:

14.23.4.2730

#### Singleplayer or Multiplayer:

Both

#### Installed mods:

AppleSkin 1.0.9
Armor Sound Tweak 2.0.3
B.A.S.E 3.7.0
BetterFps 1.4.8
Better Placement 1.0.0-1
BlockRenderer 1.0.0
Botania r1.10-354
Client Tweaks 3.1.6
FoamFix 0.9.9.1
FPS Reducer 1.12.2-1.9
FTBLib 5.0.2.11
Hot-Swappable Armor 1.0
Hwyla 1.8.23-B38
Inventory Tweaks 1.64-dev+release.110.
JEI 4.9.1.175
Keyboard Wizard 1.5.3-b1
Mouse Tweaks 2.8
Ninja's Mods 1.12
Optifine E1
skylands 1.5.5
Smooth Font Core 1.14
TapeMouse 1.1.3.17
TextureFix 4.0
The Betweenlands 3.3.9
XYZing 1.0

## Link to full crash log

[crash-2018-07-11_15.05.25-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2185878/crash-2018-07-11_15.05.25-client.txt)

#### How to reproduce:

1. Enter portal tree portal.
2. The view flips upside-down (seems like the shader effect of the portal lags) and then it crashes.

#### Expected result:

To not crash.

#### Actual result:

Crashed.

**Comment by pau101** [comment]
Thanks for this report, but it'll be best to report this issue to OptiFine as well.

It appears the new E1 release introduced a new `SmartAnimations` class which intercepts all texture binds while not being implemented to honor opengl spec in regards to texture names.

In this specific circumstance our code is faulted with initialization logic leading to -1 be passed in when it shouldn't. However, this crash can come from other causes, simply anything that would lead to a texture name generated over 2<sup>31</sup>-1. The code just needs to work with the values as unsigned.

**Comment by sp614x** [comment]
Fixed in latest preview E2
