### ISSUE TITLE
Betweenlands messed up my entire game!!!

### ISSUE THREAD

**Issue by Amborg22** [TheCyberBrick/The-Betweenlands#665]
I found the betweenlands mod very fascinating and decided to check it out. However, I removed other mods I had in my own survival world and left the following in the game. After checking it out, I decided to return to my original world be removing the betweenlands mod (only) and adding the other mods I had in. HOWEVER, anytime I attempted to log into a new or previous world, it crashed. I never entered those worlds for it to do that. I am very angry and want to access my Minecraft game again without this "final release mod" messing up my entire game and I went as far as to make a GitHub account ONLY to report this crash. PLEASE do something about this error or I will never download a mod from the mod creator again. ADDITIONAL NOTE: I even redownloaded Minecraft forge in the hopes to fix everything; that did NOT work.

#### Betweenlands version:
TheBetweenlands 1.12.2 v3.3.8

#### Forge version:
Forge-1.12.2-14.23.4.2705

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods: (all 1.12.2)
CodeChickenLib
iChunUtil
jei
Morph
Not Enough Items
Betweenlands

## Link to full crash log:

---- Minecraft Crash Report ----

**WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 7/11/18 9:42 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: thebetweenlands/client/ClientHooks
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1076)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thebetweenlands.client.ClientHooks
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PlazMatter_2000'/2191, l='MpServer', x=-188.50, y=70.00, z=226.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-192,64,228), Chunk: (at 0,4,4 in -12,14; contains blocks -192,0,224 to -177,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 112 game time, 112 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityPlayerSP['PlazMatter_2000'/2191, l='MpServer', x=-188.50, y=70.00, z=226.50], EntityLatchedRenderer['unknown'/2193, l='MpServer', x=-188.50, y=70.00, z=226.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/2193, l='MpServer', x=-188.50, y=70.00, z=226.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 370343536 bytes (353 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version          | Source                                          | Signature                                |
	|:--------- |:----------------- |:---------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2           | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp               | 9.42             | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99        | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.4.2705     | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | aether_legacy     | 1.12.2-v2.0      | aether_legacy-1.12.2-v2.0.jar                   | None                                     |
	| UCHIJAAAA | codechickenlib    | 3.1.5.331        | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux      | 2.0.1            | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore          | 4.3.8            | CoFHCore-1.12.2-4.3.8.29-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld         | 1.1.1            | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCHIJAAAA | ichunutil         | 7.1.4            | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | jei               | 4.9.2.196        | jei_1.12.2-4.9.2.196.jar                        | None                                     |
	| UCHIJAAAA | mantle            | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJAAAA | morph             | 7.1.2            | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UCHIJAAAA | nei               | 2.4.1            | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | tconstruct        | 1.12.2-2.10.1.87 | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHIJAAAA | thermalfoundation | 2.3.8            | ThermalFoundation-1.12.2-2.3.8.22-universal.jar | None                                     |
	| UCHIJAAAA | thermaldynamics   | 2.3.8            | ThermalDynamics-1.12.2-2.3.8.16-universal.jar   | None                                     |
	| UCHIJAAAA | thermalexpansion  | 5.3.8            | ThermalExpansion-1.12.2-5.3.8.38-universal.jar  | None                                     |
	| UCHIJAAAA | twilightforest    | 3.7.424          | twilightforest-1.12.2-3.7.424-universal.jar     | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 615'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 615 GL version 4.5.0 - Build 22.20.16.4749, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz**

#### How to reproduce:

1. Add the mod in Minecraft.
2. Activate Minecraft launcher.
3. Start a new world.
4. Get off of Minecraft completely.
5. Remove mod from Minecraft.
6. Launch Minecraft again (with same launcher).
7. Attempt to play a new world or old world.

#### Expected result:
I should have been able to successfully play any new or old Minecraft world that has never had this mod in it already.

#### Actual result:
Any new world or world that I have already made will immediately cause my game to crash.

**Comment by pau101** [comment]
You need to remove the betweenlands core jar (TheBetweenlands-3.3.8-core.jar) from your mods directory.

**Comment by TheCyberBrick** [comment]
This will be fixed in the next update 👍 
You'll still have to remove the file pau101 mentioned though.

**Comment by hannahzari** [comment]
Hi! I am having this same exact issue, how do I fix this??

**Comment by theishiopian** [comment]
Did you not read what they said? delete the core jar file. should be located under .minecraft/mods/memory_repo/betweenlandsversion

**Comment by LordDecay26** [comment]
665th issue... hmmm, i wonder what the 666th issue was. :>
