### ISSUE TITLE
Bizarre Graphical Bug When using the Weedwood Rowboat

### ISSUE THREAD

**Issue by Convergence2738** [TheCyberBrick/The-Betweenlands#666]
#### Betweenlands version:

3.3.10

#### Forge version:

Forge1.12.2-14.23.4.2732

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
See attached txt

[New Text Document (6).txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2191101/New.Text.Document.6.txt)

#### How to reproduce:
Get in a Weedwood Rowboat and row around

#### Expected result:

You don't get graphical glitches and your armor doesn't glitch off you

#### Pictures:
Pictures illustrate the bug better then any words
![20180711095029_1](https://user-images.githubusercontent.com/36319508/42670260-454361ca-8649-11e8-8412-2fc18a31257f.jpg)
![20180711095022_1](https://user-images.githubusercontent.com/36319508/42670276-538024bc-8649-11e8-9276-cd616293a1f8.jpg)

**Comment by pau101** [comment]
This is a duplicate of #511 and there's not a new release of Erebus yet which includes the fix for this.

**Comment by Convergence2738** [comment]
Seriously? That's hilarious. It's not a particularly dangerous bug, but it is visually annoying. Good to know the source though.
