### ISSUE TITLE
Items disappear in the Animator

### ISSUE THREAD

**Issue by DocteurSamo** [TheCyberBrick/The-Betweenlands#668]
#### How to reproduce:

1. Put sulfur, Life crystal and/or any item that can be animate in the appropriate slot 
2. Save and quit normally and get back to the world
3. The item should have disappear from the Animator

**Comment by WightofShadows** [comment]
There have since been updates to the Betweenlands that have fixed this issue. The latest version is 3.3.10

**Comment by TheCyberBrick** [comment]
Yes, this was fixed in the latest version. There's also a report on SevTech Ages' issue tracker so if you want to keep track of this please go there: https://github.com/DarkPacks/SevTech-Ages/issues/2906
