### ISSUE TITLE
Tree Portal Errors

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#669]
Hi there, I've noticed something crucial when creating Tree Portals, They roots of the portal can replace unbreakable blocks such as bedrock, this is highly problematic.
Also if this is fixed but cannot detect what is an unbreakable block I suggest a config file to set what blocks cannot be replaced by Tree Portal Blocks

version: TheBetweenlands-3.3.10

Example Screenshot:

![2018-07-24_19 12 08](https://user-images.githubusercontent.com/40124890/43157862-153daf54-8f76-11e8-8445-50662bb12d5d.png)

**Comment by UnlimatedStone9** [comment]
Thanks for fixing this!

**Comment by TheCyberBrick** [comment]
No problem. I'll try to get an update out today.

**Comment by UnlimatedStone9** [comment]
Great, No rush of course! :P
