### ISSUE TITLE
Mod conflicts.

### ISSUE THREAD

**Issue by LucyFirr** [TheCyberBrick/The-Betweenlands#670]
Versions
Betweenlands version: 3.3.10

Forge version: 14.23.4.2729 (I think...  I am just testing a pack i never put it together, sorry)

Singleplayer or Multiplayer: singleplayer, not tested multiplayer

Installed mods: stellar API 1.12.2
Link to full crash log: Game doesnt crash.

How to reproduce:
1. Install both the betweenlands and stellar API
2. Die
3. Glitch out

Expected result:
I expected to die and just respawn.

Actual result:
Everything spazzes out, and then you begin to teleport back and forth between where you die and the spawnpoint, Only visually though, you stay where you died. I was punching hags while freaking out and it seems to work fine, but you cannot move, or see, or really do anything at that point.

I would post screenshots but they really don't look like alot, sorry.

**Comment by LucyFirr** [comment]
Nevermind, i am just stupid.

**Comment by TheCyberBrick** [comment]
:thinking:
