### ISSUE TITLE
Game crashes on load

### ISSUE THREAD

**Issue by DanielP12** [TheCyberBrick/The-Betweenlands#671]
#### Betweenlands version:

TheBetweenlands-3.3.10-universal.jar

#### Forge version:

forge-1.12.2-14.23.4.2739-universal.jar

#### Singleplayer or Multiplayer:

Happens before the game loads.

#### Installed mods:

None.

## Link to full crash log

https://pastebin.com/HhwDjWzs

#### How to reproduce:

1. Start Minecraft with only The Betweenlands mod.
2. Game crashes on ModelLoader phase after PreInitialization.

#### Expected result:

Expected the game to start normally.

#### Actual result:

Game crashed.

**Comment by TheCyberBrick** [comment]
Are you using a resource/texture pack?

**Comment by DanielP12** [comment]
I'll check, thanks!
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
07/26/18,
5:43:50 PM
