### ISSUE TITLE
Weedwood and syrmonite doors have their bottom halves replaced with a simple oakwood door

### ISSUE THREAD

**Issue by Barerock** [TheCyberBrick/The-Betweenlands#672]
#### Betweenlands version:
3.3.10

#### Forge version:
14.23.4.2705

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
[TBLTXTFILE.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2237166/TBLTXTFILE.txt)
I have no idea if this worked.
And yes I have coroutil installed, and I read in the issues list that it has been having incompatibility issues. Not sure if it causes this problem though...

## Description of the problem
Both the weedwood and the syrmonite door have their bottom half replaced with the bottom half of a vanilla oak wood door.

#### How to reproduce:
1. Place either door
2. Observe door
3. Scream in outrage at the fact that I can't fix any of the graphical issues I have with this mod.

#### Expected result:
I expected to have a nice blue door to protect me from fire spitting swamp leaf things. And Frogs.

#### Actual result:
I did not have a nice blue door. Or a nice off green, brown door, but horrible monstrosities that hurt my eyes to look at.

#### Pictures:
I think you can imagine what it looks like, I won't put you through the pain.

**Comment by TheCyberBrick** [comment]
Hey, thanks for contacting us. I am unable to reproduce this at all with the Betweenlands mod alone and I'm pretty certain that this is some other mod causing the problem. Have you tried with only the Betweenlands mod?
