### ISSUE TITLE
Crash After Looking in 'Just Enough Items' (JEI) mod for Cobblestone Uses

### ISSUE THREAD

**Issue by Wasthereonce** [TheCyberBrick/The-Betweenlands#674]
#### Betweenlands version:

3.3.10

#### Forge version:

14.23.4.2739

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

List in crash report: https://pastebin.com/UD3XVpG9

## Link to full crash log

https://pastebin.com/UD3XVpG9

#### How to reproduce:

1. Look up Cobblestone in the mod 'Just Enough Items'
2. Right Click the Cobblestone in the menu

It also occurs with Minecraft's Iron Doors and Basic Capacitor Banks from the mod 'Ender IO'

#### Expected result:

I expected to click the cobblestone and see what the uses for the item was.

#### Actual result:

I crashed with a crash report detailing the error, with this particular line referring to The Betweenlands' Mortar item.

ava.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block thebetweenlands:mortar, it is not an allowed value

**Comment by pau101** [comment]
Thanks for the report! We have this issue resolved internally as reported by #663, where you can also access a link to a dev build that includes the patch.
