### ISSUE TITLE
Crash The-Betweenlands 1.0.6 + OptiFine_1.7.10_HD_U_E7

### ISSUE THREAD

**Issue by SkySem** [TheCyberBrick/The-Betweenlands#675]
**## Versions
#### Betweenlands version:
1.0.6

#### Forge version:
10.13.4.1614 [1.7.10]

#### Singleplayer or Multiplayer:
Singleplayer [crash client]

#### Installed mods:
(( Betweenlands 1.6.0 ))
OptiFine_1.7.10_HD_U_E7

## Link to full crash log
[(Crash log *click*)](https://pastebin.com/KmgWcXVY)

#### How to reproduce:
Setting TheBetweenlands 1.0.6 with OptiFine_1.7.10_HD_U_E7 causes crash.

#### Expected result:
A game with shaders built into Optifine

#### Actual result:
crash

#### Pictures:
--**

**Comment by TheCyberBrick** [comment]
Hey, thanks for taking the time to report this! Unfortunately we do not support any version below 1.12.2 anymore. However, this looks like it might just be an incorrect potion ID, maybe try resetting the config or change the potion/elixir IDs in the Betweenlands config manually. If I remember correctly all potion IDs must be below 128.

**Comment by SkySem** [comment]
Another error when changing the id effects. what to do?
 [here](https://pastebin.com/i2Vsyx8d)

**Comment by TheCyberBrick** [comment]
Use `OptiFine HD U D3`

**Comment by HRudyPlayZ** [comment]
Fixed in #1294
