### ISSUE TITLE
Possibly rare Harlequin toad bug

### ISSUE THREAD

**Issue by Caopr** [TheCyberBrick/The-Betweenlands#679]
#### Betweenlands version:
3.3.11

#### Forge version:
1.12.2-14.23.4.2717

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
[Modlist.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2254879/Modlist.txt)

#### How to reproduce:
I was riding a harlequin toad on the surface when I got hit by one of those tiny crab things. Suddenly im dragged thru the stone-50 or so underground in some water with my toad suffocated in a wall. Seems to be a wonky physics just felt like letting you guys know just incase.

P.s. I had just gotten him I was going to name him pickles

P.s.s Thank you for the amazing mod

**Comment by Caopr** [comment]
Happened again with a wight. this time it threw me under the map and right into voidcraft

**Comment by TheCyberBrick** [comment]
Poor pickles :(
I'll try reproducing it but so far I haven't run into this problem myself.
