### ISSUE TITLE
Biome generation is messed up

### ISSUE THREAD

**Issue by vadis365** [TheCyberBrick/The-Betweenlands#68]
Sam is aware of the problem - I'm just putting this here to highlight it.
Biomes generate east/west in small strips (every - so - often) on the edges of chunks.
Basically borked ;P

**Comment by MrCompost** [comment]
yeah I noticed =P
Also, I've not actually been able to find any Weedwood trees.

**Comment by vadis365** [comment]
They DO gen (the giant ones) but only on islands... look at the console output and there is a debug that gives you the location of a newly gen'd tree.

**Comment by MrCompost** [comment]
Ah, ok then.
