### ISSUE TITLE
The Betweenlands/ Roots 2 Incompatible Structures

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#680]
I was playing on a server set up for the Modpack  "Mage Renaissance" When I came across a Dark Druid Circle with a structure from Roots 2 obstructing the altar and spawner making the circle redundant and also impossible to break the terrain around, this is obviously a conflict of structures between The Betweenlands and Roots 2 and was wondering was there a way to fix this occurance?, thanks again   
- UnlimatedStone9

The Betweenlands Version: 3.3.10
Roots Version: 0.104
Forge Version:
#### Forge version: 14.23.4.2739
![2018-08-05_10 33 15](https://user-images.githubusercontent.com/40124890/43684648-e9bcaf22-989b-11e8-8079-5f9bd5ff281e.png)

**Comment by TheCyberBrick** [comment]
Thanks for the report. There's not much we can do about this because it looks like the Roots 2 structure generated into ours. I'll just remove the block protection for this structure so that it could be removed if this happens, it's not necessary anyways.
