### ISSUE TITLE
Suggestion : Review Loot Tables and Item Scroll's rewards ± bug?

### ISSUE THREAD

**Issue by alxcool** [TheCyberBrick/The-Betweenlands#681]
SIngle player minecraft 1.12.2 Forge 2705
Respectively TBetL 3.3.10 / 3.3.11 for my map.

Is it possible that there is a misunderstanding on how probability work in loot tables?

I was reading the following topics :
http://the-betweenlands.wikia.com/wiki/Loot_Tables
http://the-betweenlands.wikia.com/wiki/Item_Scroll
https://github.com/Angry-Pixel/The-Betweenlands/issues/524

Then It gave me the idea to run a test about stats, to know if I was able to obtain while playing  as much music disc than what I was supposed to, according to item's weight; by using item scroll.

Result, is more detailed on issue 524. The answer is yes, I could obtain as many music disc than what I am supposed to. That mean I have to loot 143 dungeon chests, in order to get 1 music disc, or I could get 2 music disc after animating 200 items scroll.

Is it possible that I am not calculating item weight the same way than some others? As example, on the item scroll page I could read that music disc have a weight number of 2. In my opinion, this 2 doesn't mean 2%, but ratter does mean 2 divided by the total of every weight... That mean 2/195 (1%). Same logic apply for the loot table about dungeon chest. In this one, a music disc weight 2 but the total is higher, that mean 0.7%.

So my question is, I'm I bad at math, or is the players supposed to open 143 chests + 200 item scroll in order to earn 3 of the 14 available music disc? Also if you carefully read my comment on issue 524, looting a music disc won't prevent the player from looting 3 time the same; in a row!

In vanilla minecraft,music disc are quite easier to loot or to farm. So I suggest to increase the % in item scoll and in chests to 3%.

**Comment by TheCyberBrick** [comment]
Yes, you're correct, they're weights and not percentages. Reworking the loot tables is already on our todo list.

**Comment by TheCyberBrick** [comment]
I'll close this here as it's already on our TODO list.
