### ISSUE TITLE
Incompatibility with LLibrary

### ISSUE THREAD

**Issue by Sunconure11** [TheCyberBrick/The-Betweenlands#682]
#### Betweenlands version:

The Betweenlands v3.3.11

#### Forge version:

14.23.4.2747

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

The modpack is public, but this pack is mine, and it occurred in a build I have yet to release, so it would not be replicable.

## Link to full crash log

https://pastebin.com/n1gtZwzc

#### How to reproduce:

1. Open up a world
2. ???
3. Crash

#### Expected result:

No crash

#### Actual result:

A crash

**Comment by pau101** [comment]
Thanks for reporting! However, this is an issue within LLibrary unrelated to us.
