### ISSUE TITLE
Custom Tree Portals - The End - No Tree and not in the right spot

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#683]
#### Betweenlands version:
3.3.11

## Description of the problem
Recently you added the ability to have custom tree portals (Thank you!) by right clicking a block with the talisman to go to any dimension defined in the config.  So far everything works as it should except when trying to make a tree that goes to the end dimension, you end up on an obsidian platform somewhere in the outer isles and not next to or on the dragon island.

#### Expected result:
Making a tree portal to the end creates a tree portal on top of the obsidian platform next to the ender dragon island in the end.

**Comment by MokahTGS** [comment]
Picture of the issue: https://www.dropbox.com/s/e2xvtbrm7sy2gn6/end1.jpg?dl=0

**Comment by alxcool** [comment]
Sorry to bother asking, but what are the coordinates of the starting point?, So far your picture give the coordinates of the destination points. I would like to know if there is some logical between both points. As example when I travel from the overworld to the nether, both destination and starting points are the same, if we forget or neglect that nether's portal spawn in a factor of 8*x, 8*y of the starting point. Ex. If I have Overworld (coordinates 100, 72, 100)... I will end up to (nether 800, 72, 800). My best guess is, that your starting point in the betweenland destination match the destination one in the end dimension. like as example, from betweenlands (coordinates -725, 120 ,159) to end (coordinates -725, 120, 159).

If my guess is accurate, are you about to suggest a different behavior? like
A) Suggest to fix end coordinate to always be near end's world spawn
B) Suggest to multiply destination coordinate in a similar way to the way it work in the nether?, like per 4x?

Note : As a small suggestion while waiting for things to be different, I may suggest as starting point to try to be offset by 1100... that way, whenever you start from (-1100, 0), (1100, 0), (0, -1100), or (0, 1100), the end's destination point would always be near one of the end's islands / end's city / end's tower. If you ratter like to have a portal around the center, you could try to a starting point ± 300 from point (0,0)... Careful not to forget that betweenlands water height is around 120, who is different than, water height level from the overworld!

**Comment by MokahTGS** [comment]
I'm sorry I deleted that test world so I can't get those coordinates for you.  I'd like the tree to always spawn near the dragon island.  Just like how you spawn if you had gone through the stronghold gate

**Comment by TheCyberBrick** [comment]
The platform not generating at the main island was a bug and will be fixed in the next version.
The reason I made it generate an obsidian platform is that whenever somebody creates a new portal it'd end up generating right on top of other portal trees and when leaving through the ender portal it'll respawn you at your spawn point instead of a portal.
Is there a specific reason why you need to have a portal tree spawn on top of the obsidian platform?

**Comment by MokahTGS** [comment]
No, as long as the tree generates, then the player would have the tree to stand on.  The only issue I could see is the ender dragon flying through the tree and destroying blocks.

**Comment by TheCyberBrick** [comment]
Hm but do you really need to have a portal generate? It'd make things quite messy when multiple people create portals to the end

**Comment by TheCyberBrick** [comment]
I've added it to the config as "Generate Portal Tree in End". It's off by default so you'll have to enable it first.

**Comment by MokahTGS** [comment]
if the player jumped into the end portal after killing the dragon, what would happen?  Would they go to the spawn point in the Betweenlands?

**Comment by TheCyberBrick** [comment]
Depends on whether you've set "Start in Betweenlands" to true or not

**Comment by MokahTGS** [comment]
Yes, that is the intention.
