### ISSUE TITLE
[Question] Adding Loot to the Primordial Malevolence  

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#684]
I'm trying to add an item as custom loot to the primordial Malevolence for a mod pack and I'm not sure what creature to add the loot too.  There seems to be several parts to this boss.  What is the name of the final creature that dies so that I can add loot to it.

For example, I'm doing the same thing with the Dreadful Peat Mummy and have this in the InControl loot scripts:

  {
    "mob": "thebetweenlands:dreadful_mummy",
    "player": true,
    "item": "variedcommodities:orb_broken",
    "nbt": { "display": { "name": "Broken Shadowy Soul" }}
  },

This drops that item, every time the dreadful peat mummy is killed.  Just not sure what the actual PM mob is called.

**Comment by GoryMoon** [comment]
The Primordial Malevolence id is `thebetweenlands:fortress_boss`
