### ISSUE TITLE
The Betweenlands causing crash with Adv Rocketry when using a Guidance computer.

### ISSUE THREAD

**Issue by myles438a** [TheCyberBrick/The-Betweenlands#685]
#### Betweenlands version:
3.3.10

#### Forge version:
forge version 14.23.3.2715

#### Singleplayer or Multiplayer:
Multiplayer - Vanilla

#### Installed mods:
mods link - https://rawgit.com/AllTheMods/ATM-3/master/modlist.html
Modpack is called All the mods 3.

## Link to full crash log
https://pastebin.com/uDESyqX7

#### How to reproduce:
Step One -  Shift + Right click on Advanced Rocketry Rocket.
Step Two -  Click the computer block in the top left.
Step Three - Try escaping out of that GUI.
Step Four - Game Crash.

#### Expected result:
Should be able to leave GUI successfully and not crash.

#### Actual result:
Game crashes completely as you try to leave GUI.

The mod creator for Adv Rocketry said the following "That appears to be an issue with betweenlands expecting the rocket world to have a betweenlands capability when it does not, then failing to handle that case."

However it's not really clear which mod is causing the issue.

**Comment by pau101** [comment]
Thanks for the report! This appears to an error within Advanced Rocketry. Their `ProviderDummy` is constructed such that it remains in an invalid state from being a capability provider which has not gone through capability initialization.

**Comment by myles438a** [comment]
Perhaps you guys want to chat with the dev on Adv Rocketry then and get to the bottom of it, because you're both saying its an issue with the other mod.. and this doesn't help users at all.

https://github.com/zmaster587/AdvancedRocketry/issues/1358#issuecomment-411266847
