### ISSUE TITLE
java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

### ISSUE THREAD

**Issue by matyklug18** [TheCyberBrick/The-Betweenlands#686]
## Versions
1.12.2
#### Betweenlands version:
3.3.11

#### Forge version:
14.23.4.2747

#### Installed mods:
https://pastebin.com/RjF8wR6R

## Link to full crash log
https://pastebin.com/Pb8pT3XV

## Description of the problem
i have massive modpack, so i do not have enough potion ids
if this mod extends potion ids, i can install it. or if there is another mod that does it, please give me link
#### How to reproduce:

1.
2.
3. etc...

**Comment by GoryMoon** [comment]
We don't extend potion ids and don't know of any mod that extends that.
