### ISSUE TITLE
Unable to run Just Enough Resources profile command, CTD

### ISSUE THREAD

**Issue by dsmall3303** [TheCyberBrick/The-Betweenlands#688]
#### Betweenlands version:

3.3.10

#### Forge version:

14.23.4.2739 

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

https://pastebin.com/iFjUqJmG

## Link to full crash log

https://pastebin.com/5HiN0iaJ

#### How to reproduce:

1. Create new world
2. generate some chunks
3. execute /profile [chunks|stop] [all]

#### Expected result:

With the input of /profile 5, I would expect Just Enough Resources to generate a profile of ore generation based on the closest 5 chunks.

#### Actual result:

No profile was generated, and the game crashed to desktop

#### Note:
I noticed that the error thrown by this seems to be similar to https://github.com/Angry-Pixel/The-Betweenlands/issues/685 as well as https://github.com/zmaster587/AdvancedRocketry/issues/1358. Could there be a link?

**Comment by pau101** [comment]
Thanks for the report! This appears to be another case of way2muchnoise/JustEnoughResources#152, which has been just resolved.
