### ISSUE TITLE
Mortar cannot be used bug

### ISSUE THREAD

**Issue by WeedTasteGood** [TheCyberBrick/The-Betweenlands#690]
#### Installed mods:
TheBetweenlands-3.3.11-universal
OptiFine_1.12.2_HD_U_E2
BiomesOPlenty-1.12.2-7.0.1.2399-universal
Uncrafting-Table-Mod-1.12.1 (1)
Waila-Harvestability-Mod-1.12
Hwyla-Mod-1.12.1
SuperMiner-Mod-1.12.1 (1)
NetherEx-Mod-1.12.2
Roguelike-Dungeons-Mod-1.12.2
Natures-Compass-Mod-1.12
VoidCraft-Mod-1.12.2
TamModized-1.12.1
ChestTransporter-1.12.2-2.8.8
Iron-Chests-Mod-1.12.2
Orbis-API-1.12.2
Industrial-Craft-2-Mod-Experimental-1.12.1
backpacks+1.12.2+-+3.4.4
More-Furnaces-Mod-1.12.1
CXLibrary-1.12.1
ToroCrafts-Damage-Indicators-Mod-1.12.2
AbyssalCraft-1.12.2-1.9.4.9
BetterFps-Mod-1.12.2
jei_1.12.2-4.9.1.168
Xaeros_Minimap_1.14.9.1_Forge_1.12
DynamicLights-1.12.1 (1)

#### Actual result:There's no animations showing,and so items cannot be grounded
At first,there was animations showing items getting grounded,and so I indeed got grounded items.But at second try,I could't grind any items with my mortar anymore.My pestle is still inside and at full durability.I am sure that I put items that can be grounded such as moss.Please fix this bug.

**Comment by GoryMoon** [comment]
Can you include a screen shot of the GUI of the mortar?
