### ISSUE TITLE
A way to make a safe base maybe ?

### ISSUE THREAD

**Issue by Illand** [TheCyberBrick/The-Betweenlands#691]
Hey !

I've discovered this mod with Sevtech, and while it's fun, it's also caused me a fair bit of grief. Heavy Rain destroying crops was an unpleasant surprise, but I can understand, it happens in the real world. Wights going ghost and killing me was painful, but hey it's supposed to be challenging. There is, however, something that greatly aggravates me : mobs spawning in my fully enclosed, fully lit up base.

So if we could have a way to stop mob spawning in a small region, maybe with something dropped from the Primordial Malevolence (a fragment of its evil, or even it's eye, that keeps the fauna at bay for instance) it'd be pretty awesome. Not something that can keep gigantic tracts of land spawn free or stops any mobs from coming into the zone of course, but at least something to make a reasonnably sized zone safe from spawns.

I know the concept of this mod is an expedition in hostile territory, but the inability to actually have a secure base is taking away from my enjoyment of the mod, and I feel it'd be a waste if I just never came back to it after finishing the quests in the modpack.

Sorry if I'm asking for too much, but I truly love building bases and having mobs spawn inside makes me think I failed my base design. It's slightly maddening ^^"

**Comment by vadis365** [comment]
http://the-betweenlands.wikia.com/wiki/Repeller

**Comment by Illand** [comment]
I am aware of this block, but nowhere does it mention blocking spawning inside the field. I saw an item in another mod that repelled mobs, but didn't stop spawning. It led to some very annoying complications (flying pigmen are a hazard, wear your Nether Security Equipment at all times kids !)

Additionnally, with the ridiculously long aggro range of the wights, the Repeller presents a very, very incomplete protection.

**Comment by WightofShadows** [comment]
I've never seen hostiles spawn inside the field myself, but they will be pushed out of it if they are in it at all, which essentially means they can't exist inside of it unless they're pushed up against a wall and unable to be a threat.

Regardless of how complete it is, the Repeller will no doubt improve your base conditions. I would say it's fair if there are some minor faults to it though; in the Betweenlands you shouldn't get _too_ comfortable.

**Comment by Illand** [comment]
I guess. Well, let's consider this subject closed then.
