### ISSUE TITLE
[Enhancement/Improvement] Stereo Audio Issue

### ISSUE THREAD

**Issue by TechnoMysterio** [TheCyberBrick/The-Betweenlands#692]
This isn't so much a bug, but more of an issue relating to the audio within the mod.

Many of the sounds for the mod are in stereo, although not all. Stereo sounds in Minecraft are always played in both ears, regardless of whether the sound source is to the side, in front, or in any direction around the player. 

This becomes a problem when the sound in question plays from a position in the world, such as when it's coming from a mob, or a machine, or anything of the sort. Since it plays in both ears no matter what, the sound never plays directionally, so if a mob is coming toward you from the left, it won't sound like such, as it just plays in both ears.

This is relatively minor, but it can become quite annoying for a player, especially with louder or more repetitive sounds, since it is always played the same way every time. It would also help to guide or warn players of important things, such as a hostile mob approaching, since directional audio can guide the player to where something is coming from.

Stereo sounds, however, are generally fine for things like music, ambience, or larger events that need more impact, or that happen around the player. An example of this in vanilla would be the Wither summoning sound.

With what I've talked about in mind, I'd recommend going over the sounds in the mod and converting ones which should be more directional (mobs, crafting blocks, footsteps) to mono. Not only would this improve the mod's audio in-game (which is already excellent), but it would also cut down on the filesize of the mod, as converting a stereo sound to mono effectively halves its filesize.

Apologies for the long winded explanation, but I've done sound design for Minecraft mods before, and this is often overlooked in them, so I figured I'd let you know about it.

**Comment by TheCyberBrick** [comment]
Hm interesting, was not aware of this. We'll look into it, thanks!
