### ISSUE TITLE
any help for #spongeforge team to solve the mod compatibility issue? 1.12

### ISSUE THREAD

**Issue by lllMohandarlll** [TheCyberBrick/The-Betweenlands#693]
[issue #2304 on spongeforge github, all the version info and stuff are found here](https://github.com/SpongePowered/SpongeForge/issues/2403)

**Comment by TheCyberBrick** [comment]
Is this still a problem? Our custom mob spawner doesn't really do anything special, the spawn checks are pretty much the same as vanilla, it's just the distribution that is different.

**Comment by lllMohandarlll** [comment]
Well, the issue is still open and I haven't tryied the new beta of spongeforge yet, but as far as I see in the patch notes, no one of the releases has something mentioning this issue or an entitity fix...

By the way, could possibly be something about light level? Maybe spongeforge classificate all hostiles as the same and force them in a low light level, while in the betweenlands the lightlevel check is usually high as you can see in the top left corner of the screenshot reported in the linked issue..

Idk, you may should talk with them instead, I'm not a dev of spongeforge, neither the betweenlands, and also pretty bad at coding..
even if I have to admit that seems like spongeforge team is not so very collaborative... '-'
