### ISSUE TITLE
Shallowbreath Infusion colours not working

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#694]
#### Betweenlands version:
3.3.11

#### Forge version:
1.12.2-14.23.4.2707

#### How to reproduce:
1. Get an infuser to fully evaporate

#### Expected result:
The Shallowbreath spawned should be the same colour that the Infusion originally was.

#### Actual result:
No colours changed. It's just the normal green

#### Pictures:
![2018-08-24_13 50 04](https://user-images.githubusercontent.com/18041417/44609284-df283300-a7ab-11e8-85e6-a9072b78ae55.png)

**Comment by GoryMoon** [comment]
Can't replicate this. At what stage of the infusion did it evaporate?

![2018-08-26_15 28 05](https://user-images.githubusercontent.com/987002/44628677-fcdcd000-a944-11e8-818f-399403943d56.png)

**Comment by WightofShadows** [comment]
Oh you know what, it might've been me misunderstanding when the colour change actually occurs. I just left it without stirring at all and so the infusion hadn't completed when it evaporated.
