### ISSUE TITLE
Oli ! We need a list of Items and blocks

### ISSUE THREAD

**Issue by vadis365** [TheCyberBrick/The-Betweenlands#7]
We need a list of blocks and items (preferably as 2 different issues).
Each list should have what items/blocks, that should be added and which creative tab they are added to
A name, texture and short description of each thing's property would be good
Fine tweaks can be added later.
There are 5 creative tabs:
Items
Blocks
Gear (armour, weapons, tools. etc.).
Plants
Special Items
Once the basics are done then work can begin on other stuff that will need these Blocks and Items.

**Comment by MrCompost** [comment]
Well, I thought this time we should just add them as we go along, instead of all at once (if thats what you mean to do). That way, we dont end up with a ton of useless unfinished stuff.

**Comment by vadis365** [comment]
If you do it that way - nothing will happen
You need blocks for world gen, portal etc.
You need items to do stuff with and that mobs drop
If you add a little here and there, which is the easy option, it will just slow everything down to a snail's pace. Adding in stuff a bit at a time means going over the code all the time to add this and that to stuff. If the lot can be added early then things will progress a lot quicker. imho.

**Comment by MrCompost** [comment]
I know man, I'll explain properly later on Skype.
