### ISSUE TITLE
Mods folder confusion

### ISSUE THREAD

**Issue by poxy100** [TheCyberBrick/The-Betweenlands#700]
After installing the mod, and playing it, along with other mods, I decided that because the base metals mod interferes with BOP's world generation, I wanted to teperarily remove the mod to generate another world. however, upon doing so, loading, or generating a world will crash the game giving the unexpected error:

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: World MpServer (net.minecraft.world.WorldProviderSurface) does not have BetweenlandsWorldStorage capability

-Or-

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: thebetweenlands/client/ClientHooks

Even when removing the betweenlands mod, all other mods, and or even using a fresh forge&liteloader game version, the game will still refuse to load worlds, giving the same errors.

**Comment by pau101** [comment]
When you are removing all mods are you deleting the `mods/` directory, or is it at least truly empty?

**Comment by poxy100** [comment]
I emptied everything out of the folder except for sub folders that I put older version mods into.

Edit: turns out the mod creates a sub folder for the mod, and I confused it for an old folder. The problem stopped once I deleted it.
