### ISSUE TITLE
Special Ruins variant

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#701]
For a while there's been a variant of Marsh Ruins in the code that has stuff like weedwood, climbing ropes and uniquely angry betweenstone in it, but I've never seen it spawn. I'm not sure if it's just extremely rare or if there's a bug making it unable to spawn at all. I've searched about 9 marshes now, some of them massive, and never found one. Very curious about it.

**Comment by TheCyberBrick** [comment]
wtf I didn't even know that existed
![](https://i.imgur.com/EE28myI.png)

**Comment by TheCyberBrick** [comment]
It's probably not generating due to too strict placement checks
