### ISSUE TITLE
Running into some strange worldgen with Astral Sorcery

### ISSUE THREAD

**Issue by Saereth** [TheCyberBrick/The-Betweenlands#705]
#### Betweenlands version:

v3.3.11 MC 1.12.2

#### Forge version:

14.23.4.2749

#### Singleplayer or Multiplayer:

Single player and multiplayer

#### Installed mods:

https://pastebin.com/Xg04VXbS

## Link to full crash log

This is not a crash

#### How to reproduce:

1. Create a new world and allow Astral sorcery to worldgen in between lands
2. Create a portal to between lands
3. Be dissapointed

Also opened an issue with Astral Sorcery https://github.com/HellFirePvP/AstralSorcery/issues/867

#### Expected result:

Tree portal not generate on top of Astral sorcery structures (maybe a check for valid ground to spawn in on?)

#### Actual result:

Tree spawned on top of AS worldgen

#### Pictures:

![image](https://user-images.githubusercontent.com/9200909/45447860-dfc33380-b69e-11e8-8b44-4cc8adec3e0b.png)

**Comment by Saereth** [comment]
Not sure how you would best want to approach this issue but maybe lowering the y height here
https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12/src/main/java/thebetweenlands/common/world/gen/feature/structure/WorldGenWeedwoodPortalTree.java#L44-L46
or even checking for specific betweenlands blocks to be valid start points for the tree generation. 

Ideally in this situation the tree portal would be offset to the side. Or perhaps maybe a smaller default style portal like a nether portal if the generator fails its first attempt to find a valid position? Tricky issue I'm sure.

**Comment by TheCyberBrick** [comment]
Am I right in the assumption that this happens very rarely? :P  
 I'm pretty sure the portal does check for valid ground (some kind of grass, dirt or similar block) and whether there's enough space for the portal.  There actually are 2 fallbacks when the portal fails generating, but in this case it didn't fail generating because there was enough space and the top of that structure seems to be covered with our grass/dirt.

**Comment by TheCyberBrick** [comment]
Also, finding a location for the portal is already slow enough as is, I don't really intend to make it even slower for some rare edge cases. If I do find an error somewhere in the checks I'll fix it though 👍

**Comment by Saereth** [comment]
this happens almost every time reproducibly. which I think also has to do with astral sorery's worldgen, there is almost always an AS structure or several generated immediately upon creating the portal/generating that entry chunk, any insight by chance @HellFirePvP ?

**Comment by TheCyberBrick** [comment]
🤔

**Comment by HellFirePvP** [comment]
From at least the screenshot i may guess it spawns a ancientshrine, the large structure, spawns a desert shrine on top of that, which generates some "disguise" blocks (top-block of current biome) on top of itself. Those are then valid blocks for the tree to spawn on.
