### ISSUE TITLE
Some very odd biome generation

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#709]
#### Betweenlands version:
1.12.2 (dev snapshot 974)

#### Forge version:
1.12.2-14.23.4.2758

#### Singleplayer or Multiplayer:
SP

#### Installed mods:
BetterFPS-1.4.8
Dynamic Surroundings-1.12.2-3.4.9.15
Foamfix-0.10.1-1.12.2
FPSReducer-1.12.2-1.10.2
Hwyla-1.8.26-B41_1.12.2
Itemzoom_1.12.1-1.10
Jei_1.12.2-4.11.0.212
Journeymap-1.12.2-5.5.2
JustEnoughResources-1.12.2-0.8.9.48
Optifine_1.12.2_HD_U_E2
SoundFilters-0.10_for_1.12
SwingThroughGrass-1.12.2-1.2.3
TexFix+V-1.12-4.0
Wawla-1.12.2-2.5.257

(probably don't need alot of these mods anymore but I'm unsure if I'll be able to reproduce this either way)

#### How to reproduce:
1. Just wander bout the Betweenlands. Might be a rare glitch

#### Expected result:
Some normal biome gen.

#### Actual result:
A weird blotch of vanilla Ocean, next to an extremely small bit of Sludge Plains, in the middle of Deep Waters. I don't think any of the mods I have installed could cause biome ID conflicts so this is pretty odd. It may be rare enough to be negligible but thought it'd be worth reporting

#### Pictures:
![2018-09-17_19 19 39](https://user-images.githubusercontent.com/18041417/45660911-f6f38e00-baaf-11e8-8d91-ffe93a53d099.png)

**Comment by TheCyberBrick** [comment]
I think I've seen this before in other versions too. Do you have the seed and position?
Not sure why it would happen, but looks like a biome wasn't set and so ocean was used as default (id 0)

**Comment by WightofShadows** [comment]
The seed is 4833148357538229778 and it's at about X 425 Z 490
