### ISSUE TITLE
Ambient sounds/music 

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#71]
The 8 songs play whenever in the BL. 
The swamp ambience plays when above the surface and the cave ambience plays when below.

**Comment by PCAwesomeness** [comment]
A gift for you to convert the music into .ogg...

http://online-audio-converter.com/

**Comment by PCAwesomeness** [comment]
Close this, please.

**Comment by MrCompost** [comment]
What...? No.

**Comment by SanAndreasP** [comment]
ambience sounds added
