### ISSUE TITLE
Compost Bin not working properly

### ISSUE THREAD

**Issue by LadyVipera** [TheCyberBrick/The-Betweenlands#712]
Minecraft Version: 
1.12.2
Betweenlands version:
 3.3.12 
Forge version:
 1.12.2-14.23.4.2759

 Singleplayer or Multiplayer:

The issue appears to occur in Singleplayer, I am unaware if it happens in Multiplayer.

#### Installed mods:
Baubles 1.12-1.5.2
Mantle 1.2-1.3.2.24
Placebo 1.12.2-1.4.1
Plant-Mega-Pack-Mod -1.12.2 (Further information on version unknown)
worldedit-forge-mc1.12-6.1.8-dist

## Description of the problem

Clicking on the compost bin with an empty hand, regardless of gamemode (Creative or Survival) will not open the compost bin. On one occasion when the bin did open, it was impossible to insert compostable items or close it.

#### How to reproduce:
1. Place the compost bin on top of mud brick (You never know if the surface is causing it)
2. Right click the compost bin
3. If the glitch occurs, even if the box highlighted is clearly the compost bin, it will not open. If it does open, it will not permit the player to insert items for compost or close the bin.

#### Expected result:

The expected result was that the compost bin would open or close when right-clicked with an empty hand, and allow the player to insert items that can be used to make compost.

#### Actual result:

The compost bin would not open, except in a single case, where it opened, but would not permit the player to insert any items. It also would not close once opened, regardless of where it was clicked.

**Comment by GoryMoon** [comment]
You left click to open the compost bin

**Comment by LadyVipera** [comment]
Okay, sorry for creating an issue on something that isn't a problem. It just doesn't work in creative because that breaks the block. Survival is fine.
