### ISSUE TITLE
Feature request - config option to require a swamp talisman for first portal usage from betweenlands.

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#713]
On our multiplayer Ancient TownCraft server where players start in The Betweenlands, new players are exiting using other peoples portals without experiencing the amazing thing that is Betweenlands.  

I would like a config option to require them to be holding a swamp talisman to use the portal for the first time.

**Comment by MokahTGS** [comment]
There is a mod called Restricted Portals that has this functionality.
