### ISSUE TITLE
Betweenlands Morph = Death within Seconds

### ISSUE THREAD

**Issue by Amborg22** [TheCyberBrick/The-Betweenlands#715]
**Betweenlands version**: 3.3.12-universal

**Forge version**: 14.23.4.2705

**Singleplayer or Multiplayer**: Singleplayer

**Installed mods:**
CodeChickenLib
gravestone
iChunUtil
jei
Mantle
Morph
NotEnoughItems
TConstruct
TheBetweenlands
Xaeros_Minimap

**Description of the problem**: Morphing into any betweenlands HOSTILE mob causes death within seconds.

**How to reproduce**:
1. Kill a hostile betweenlands mob (e.g. pyrad, swamp-hag).
2. Select its morph.
3. Morph into it.
4. If different morph isn't selected soon, death will occur.

**Expected result**:
Morph will take place and no death would occur upon change.

**Actual result**:
Within the time of under 10 seconds of damage, immediate death to player morphed into hostile betweenlands mob would occur, with the text box stating "[player name] was slain by [hostile mob]".

**Additional Notes**: 
-Not yet tested in creative mode.
-If requested to add versions of each mod, please ask. Thank you.

**Comment by TheCyberBrick** [comment]
I cannot reproduce this with the latest Betweenlands and Morph.

**Comment by TheCyberBrick** [comment]
Any update on this? I've tried with BL, TCon, Morph, iChunUtil, CodeChickenLib, Mantle and Gravestone installed and still can't reproduce

**Comment by Amborg22** [comment]
I apologize I have been really busy lately, but I will try to contact
tomorrow

**Comment by Amborg22** [comment]
![screenshot 1](https://user-images.githubusercontent.com/41134857/46706300-54838200-cbf9-11e8-982d-eb08e8b8684a.png)

This shows the version of each mod used.
