### ISSUE TITLE
No Oxygen in Betweenlands while Advanced Rocketry is installed.

### ISSUE THREAD

**Issue by MintBeeps** [TheCyberBrick/The-Betweenlands#717]
#### Betweenlands version:

Version 3.3.12

#### Forge version:

Forge 1.12.2 14.23.4.2745

#### Singleplayer or Multiplayer:

Multiplayer, but could also be singleplayer

#### Installed mods:

Its specifically between rocketry and Betweenlands so: Advanced Rocketry

#### How to reproduce:

1. Install Betweenlands and Advanced rocketry
2. Enter the Dimension of betweenlands to receive no oxygen and suffocate

#### Expected result:

Breathing just fine in atmosphere of dimension

#### Actual result:

Constantly dying due to lack of oxygen

#### Pictures:

https://imgur.com/a/WEF6Y8y

**Comment by TheCyberBrick** [comment]
I'm pretty sure that's just a matter of configuration, e.g. see https://github.com/zmaster587/AdvancedRocketry/issues/933 (no idea how up to date that still is). Either way, this is not a problem on our side because vanilla doesn't have a concept of oxygen in dimensions.

**Comment by MintBeeps** [comment]
Aha, I found the issue, thanks for referencing that one as digging into one of their world files showed that Advanced rocketry added the same Dimension ID as a moon (20) As thats what was causing the issue with no oxygen. Seems fixable by just changing the setting in xml file and reloading though, thanks again!

**Comment by TheCyberBrick** [comment]
Alright, no problem!
