### ISSUE TITLE
Suggestion: updrafts

### ISSUE THREAD

**Issue by theishiopian** [TheCyberBrick/The-Betweenlands#718]
This is a suggestion pertaining to volarkites, for whenever they are re-implemented. 

The volarkite is essentially an elytra for the betweenlands. It provides no thrust, but gives enough lift to allow gliding. However, there is a fundamental issue with this, and that is that without a very tall structure, its impossible to use. In the overworld, this isn't a problem, because the terrain is so hilly. The betweenlands, however, is mostly flat. There are structures such as massive trees or towers that are tall enough to jump off of, but they're pretty rare. As such, to use the volarkite, the player will usually have to build tall ugly towers to jump off of. 

A possible solution to this is to add updrafts. These would act like bubble columns in the vanilla game post 1.13, but for air instead of water. If the player enters them, they will fall slower. Fly into them with a volarkite and you will be launched upwards. The updrafts would also affect items and mobs, with mobs falling slower or flying upwards depending on their mass. Instead of a particle effect, you could use your fancy world shader to render a heat ripple effect. 

As for where updrafts come from, my immediate thought was lava, but the betweenlands seems pretty volcanically dead. Fortunately, decaying matter also creates heat, and the betweenlands has plenty of that. Maybe there could be piles of compost in the world, the remnants of ancient tree stumps and mega-flora. These could also serve as a natural source of compost for farming, as well as a  place for interesting mobs to spawn. Worms perhaps? Or maybe macroscopic bacteria.

**Comment by TheCyberBrick** [comment]
I like that, reminds me of LoZ Breath of the Wild :)
Marshes occasionally have natural fires, those could create an updraft too

**Comment by theishiopian** [comment]
Oh yeah, I forgot about those!
