### ISSUE TITLE
Root item texture

### ISSUE THREAD

**Issue by WightofShadows** [TheCyberBrick/The-Betweenlands#723]
An item texture for twisty roots, like was added with stalactites/life crystal ore. Will attempt to make a texture and upload it here later in case you need it.

Edit:   
![woahitsarootitem](https://user-images.githubusercontent.com/18041417/46883499-165bad80-ce07-11e8-8683-b2991ba57e05.png)               ¯\\_(ツ)_/¯

**Comment by TheCyberBrick** [comment]
Oh cool, thanks!
