### ISSUE TITLE
Changes on the horizon

### ISSUE THREAD

**Issue by theishiopian** [TheCyberBrick/The-Betweenlands#727]
No this isn't about upcoming new features, which from what I can tell are coming up dandy. No, this issue is  literally about the horizon.

When playing the betweenlands, the most immersion breaking thing is the horizon line, and how the land abruptly ends. In vanilla, the varied terrain helps break this up, but the betweenlands is mostly flat. The effect is even worse when the rift event is active, because the rift just highlights the abrupt edge of the land.

The ideal solution would be to massively increase the render distance. Unfortunately, the optimal draw distance for realism is about 5 kilometers, which is something I doubt is even possible in minecraft without a rewrite of the whole game to support LOD features such as octrees. However, it is possible to fake it.

What I'm envisioning is a shader effect that renders beyond whatever the current draw distance is. The effect would render thick fog, possibly with the occasional vague silhouette of a tree or crag in the far distance, fading in or out with the player's movement. The idea is to cover up the edge of the rendered terrain, and to give a sense of mystery to the surrounding world, encouraging exploration and mapping.

A further improvement I'd like to see is that the rift shouldn't spawn on the horizon, as it looks silly imo.

**Comment by TheCyberBrick** [comment]
Sounds nice, but is probably pretty tricky to pull off. At least without it looking silly.
Maybe at some point but probably not anytime soon, there's too many other cool things we have planned that are more than just a visual :)

>A further improvement I'd like to see is that the rift shouldn't spawn on the horizon, as it looks silly imo.

I have to disagree there, I like it when you can e.g. occasionally see a full sunrise or sunset through the rift. Besides, you should be able to change that yourself with a resource pack (see [rifts.json](https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/resources/assets/thebetweenlands/textures/sky/rifts/rifts.json))

**Comment by theishiopian** [comment]
The sunrises are kinda neat, I do agree. A less severe fix would be to make the rifts cull below the horizon line. In fact, just a basic horizon graphic would go a long way. Either way, I appreciate all the work you guys already put into the mod, it looks incredible. I just feel that there are a few holes in the experience that need papering over.

**Comment by TheCyberBrick** [comment]
I'll close this because it can be done in resource packs. E.g. change all rifts to only spawn at a pitch > 50° and have one variant that can spawn on the horizon but has the lower end of the texture cut off.

**Comment by theishiopian** [comment]
fair enough.
