### ISSUE TITLE
Unstackable Buckets

### ISSUE THREAD

**Issue by Idonith** [TheCyberBrick/The-Betweenlands#730]
#### Betweenlands version:
1.3.12

#### Forge version:
14.23.4.2705

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
TheBetweenlands-3.3.12-universal
journeymap-1.12.2-5.5.2
OptiFine_1.12.2_HD_U_C9
Waystones-Mod-1.12.1

## Description of the problem
Empty buckets (both weedwood and syrmorite verieties) do not stack with other empty buckets of the same type unless they both held the same last liquid. For example, an empty weedwood bucket that was just used to place swamp water will not stack (in the inventory or on a shelf) with an empty weedwood bucket that last held an infusion.

#### How to reproduce:
1. Fill a bucket with any liquid (e.g. tar).
2. Fill another bucket with different liquid (e.g. rubber).
3. Empty both buckets.
4. Attempt to stack the emptied buckets on a shelf or in an inventory.

#### Expected result:
The empty buckets of the same type stack up to 16 in a single inventory slot or a single shelf slot.

#### Actual result:
The buckets are treated as seperate items and will not stack.

**Comment by TheCyberBrick** [comment]
Thanks.
I remember this already being a problem a while ago but I guess I forgot about it :P
Newly crafted buckets weren't stackable with buckets that had liquid in them at some point.
