### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by theishiopian** [TheCyberBrick/The-Betweenlands#731]
The log said to report this, so here it is. Occurs while wandering around the betweenlands. Happens semi-frequently, which means that its probably an uncommon worldgen feature causing the issue. 

Installed mods:
Forge-14.23.5.2768
BetterFps-1.4.8
foamfix-0.10.2-1.12.2
FullscreenWindowed-1.12-1.6.0
jei_1.12.2-4.8.5.147
TheBetweenlands-3.3.13-universal

Log:
https://pastebin.com/ByaZzwP5

**Comment by TheCyberBrick** [comment]
We cannot change this for the time being without rewriting major parts of our worldgen. And that's *definitely* not happening before 1.13. :P

**Comment by theishiopian** [comment]
Fair enough. I actually had the same issue with a mod of mine a while back. The fix was pretty easy in my case, but bl adds a lot of fancy structures, Including some bigger than one chunk, so I can see the difficulty.
