### ISSUE TITLE
Game crashed when I entered another portal

### ISSUE THREAD

**Issue by BugmanBugman** [TheCyberBrick/The-Betweenlands#732]
#### Betweenlands version:

The Betweenlands v3.3.13

#### Forge version:

1.12.2 - 14.23.5.2770

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

https://pastebin.com/Zc1rNeEH

## Link to full crash log

https://hastebin.com/izafawedoc.rb

#### How to reproduce:

1. Go to Betweenlands exit
2. Create the first portal from Cavern II
3. Enter the portal and it crashes 

#### Expected result:

I expected to go to the Cavern Dimension when I stepped in the portal

#### Actual result:

I stepped in the portal and my game froze and crashed

**Comment by TheCyberBrick** [comment]
Most likely same as #777.
