### ISSUE TITLE
Possible crash with Project-Red

### ISSUE THREAD

**Issue by barcharcraz** [TheCyberBrick/The-Betweenlands#737]
#### Betweenlands version:
3.4.0

#### Forge version:
2772

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
A Huge quantity, will reproduce with a minimal set later

## Link to full crash log
https://paste.dimdev.org/anoxuhofip.mccrash

# Description:

Crash on startup with above stacktrace

**Comment by barcharcraz** [comment]
I am playing with the following configuration files: https://github.com/barcharcraz/minecraftfiles/tree/regular-world

**Comment by barcharcraz** [comment]
https://paste.dimdev.org/ifoqenavuj.mccrash

That's a crash with just the betweenlands and project-red installed (it also has Vanilla fix, but I can repro without that and it's just to be able to upload the crash log automatically)

Attached you can find a pack export of the crashing combination of mods (can be imported into curse or multimc)

[more_stable-1.0.zip](https://github.com/Angry-Pixel/The-Betweenlands/files/2517156/more_stable-1.0.zip)

**Comment by GoryMoon** [comment]
Looks like an issue on the Project-Red side.
Also looks like it's been fixed for a while now but not released yet. https://github.com/MrTJP/ProjectRed/issues/1407 https://github.com/MrTJP/ProjectRed/commit/2001af649bc0c844593c405822a3249d21e00c74
