### ISSUE TITLE
[1.12.2] Damage sources from 'onFire', 'inFire', and 'lava' deals only 1/2 heart damage with Betweenlands installed.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#741]
Minecraft: 1.12.2
Forge: 14.23.5.2769

Mods:
TheBetweenlands-3.4.0-universal

-----

For some reason... damage from these sources... 'onFire', inFire, and 'lava' and all reduced to 1 (Half a heart of damage.) when Betweenlands is installed.

You can't really tell with 'onFire' & 'inFire' damage sources but with 'lava' damage source you can notice it as normally being in lava deals 4 (2 Hearts of damage). This can cause some issues with damage scaling from mods like ScalingHealth which alters the damage taken depending on the difficulty.

An example... setting those three damage sources to 1000.0 with 200 difficulty via ScalingHealth. Without Betweenlands installed... ANY of those three damage sources is instant death due to the high damage being dealt but with Betweenlands installed... the damage is reduced to 1 despite it being scaled so high.

Here's an image of me being in lava. Left is without Betweenlands, Right is with Betweenlands. Torohud mod is being used as it shows number particles for damage/heal.
![](https://cdn.discordapp.com/attachments/377171551155650560/505502870750363663/damageinlava.PNG)
No form of defense is used in the images... 0 armor, no Resistance effects, etc.

**Comment by TheCyberBrick** [comment]
Looks like that's been a thing for ~~over~~ almost 2 years now and nobody ever noticed 🤔 
Thanks!

**Comment by SonicX8000** [comment]
Whoa... over 2 years? I could see it being under the radar if the player had some sort of defense like armor/protection/fire protection etc so it could easily go unnoticed due to those reducing the damage quite a bit.

I wouldn't of noticed it myself but when using ScalingHealth with it's damage source scaling... I was wondering why Fire/Lava wasn't doing that much damage at high difficulties.

Is it possible that other damage sources may be affected? I only noticed it with those three sources as far as I'm aware.

**Comment by TheCyberBrick** [comment]
Meant to write *almost* not *over* :P
Nope, only fire/lava type damage was affected.
