### ISSUE TITLE
[1.12.2] [3.4.0] Tree Spirit boss won't take melee damage if more than 2-3 blocks away

### ISSUE THREAD

**Issue by blacknight7890** [TheCyberBrick/The-Betweenlands#742]
#### Betweenlands version:
3.4.0

#### Forge version:
Forge1.12.2-14.23.5.2772

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
AppleSkin-mc1.12-1.0.8
AutoRegLib-1.3-14
Baubles-1.12-1.5.2
CosmeticArmorReworked-1.12.2-v1
ExpandedArcanum-1.0.1
Hwyla-1.8.26-B41_1.12.2
ImmersiveEngineering-0.12-86
immersivepetroleum-1.12.2-1.1.9
InventoryTweaks-1.63
jei_1.12.2-4.8.5.147
journeymap-1.12.1-5.5.0
JustEnoughPetroleum-0.1
MouseTweaks-2.8-mc1.12.1
QuickLeafDecay-MC1.12-1.2.3
Thaumcraft-1.12.2-6.1.BETA26
ThaumicInventoryScanning_1.12.2-2.0.10
ThaumicJEI-1.12.2-1.4.0-14
thaumicperiphery-0.3.0
TheBetweenlands-3.4.0-universal
TombManyGraves-1.12-4.2.0

#### How to reproduce:

1.Find a Tree Spirit boss.
2.Melee attack it from over 2-3 blocks away.

#### Expected result:
The spirit takes damage from the attack. You can normally melee hit mobs within your mining range, including bosses.

#### Actual result:
The spirit does not take damage from the attack. You need to be within 2-3 blocks of the entity to deal any melee damage.

#### Extra notes:
The lesser tree spirits have this issue as well. Ranged weapons seem to have a range restriction as well, however its range is far greater and spans most of the tree's island. I assume this to be in place so you can't just snipe it from afar, might be the source of the melee issue.

#### Pictures:
Boss does not take melee damage at this range:
![2018-10-26_18 33 48](https://user-images.githubusercontent.com/30190786/47595618-3d5dc780-d94f-11e8-9868-4f4b08f775e5.png)
Boss does take melee damage at this range (movement on X axis):
![2018-10-26_18 33 53](https://user-images.githubusercontent.com/30190786/47595675-726a1a00-d94f-11e8-91e3-6e9c2afc0eee.png)

**Comment by TheCyberBrick** [comment]
Hmm, seems it's because vanilla does a check on the server side that fails if the entity is "not visible" (i.e. the center is obstructed). Even though unintentional, I like that you have to get close to fight it. There's still the option of using projectile weapons anyways.
Also, mining reach ≠ attack reach and keep in mind that the attack reach in survival mode is actually only 3 blocks so the difference in survival mode is much less than in creative mode.
