### ISSUE TITLE
[1.12.2] [3.4.0] Question about Menhirs and wayfinders.

### ISSUE THREAD

**Issue by 63502** [TheCyberBrick/The-Betweenlands#743]
I love the new waystone system, except for one little problem. I can't seem to find out how to obtain a Bone Wayfinder in survival. Is it some kind of loot? Taking into account how common Menhirs are and how a wayfinder can only hold one location at a time, will they be craftable or be item scroll loot at any point?

**Comment by TripleHeadedSheep** [comment]
Bone Wayfinders are loot items. Our wiki is not yet up to date with the newest update, but we hope to have that covered soon. If you have more questions, please join our Discord: https://discordapp.com/invite/cMrr7Dr

It is better to ask such questions there as you get a faster reply and so our github doesn't get cluttered with questions about gameplay ;)
