### ISSUE TITLE
[Suggestion] dreaful peat mummy can climb walls and break blocks

### ISSUE THREAD

**Issue by uwillnotbespared** [TheCyberBrick/The-Betweenlands#745]
The Dreaful Peat Mummy is a pretty cool boss fight UNLESS you nerd pool up placing a liquid at the bottem of the nerd pool build slabs with 1 block of space between the top of nerd pool and the slabs to make sure you cannot be pushed down from the nerd pool spawn the dreadful peat mummy and load it with arrows

you get my point?

the battle can be cheated easily it cannot break or climb blocks and its sludge projectile is as effective as a snowball (its no good against the nerd pool its wayyyyyyyy to slow to kill you that is if it can even get you)

I suggest that if a player is nearby the Dreaful Peat mummy will be able to climb walls and break blocks if its required to reach the player

i mean you could still break the base of the nerd pool but itll still make the battle harder to cheat right now its only anti-cheat mechanic is that it is bucket only proof i suppose you could consider making it arrow proof however i will still quite easily be able to cheat it

**Comment by TheCyberBrick** [comment]
Sure, can do. There'll always still be ways to cheese the fights though :P

**Comment by PetasiGit** [comment]
The dreadful can break (and place, if necessary) blocks as of 3.6.0, a lot less cheese-able now. Closing this.
