### ISSUE TITLE
Seasonal events difficult to turn off *during* a seasonal event.

### ISSUE THREAD

**Issue by FakenameBill** [TheCyberBrick/The-Betweenlands#747]
I grew tired of the Halloween "spook" event, mostly because it was messing up textures, but when I tried to turn it off in the config I found it to be way more difficult than it should have been. After much trial and error, I managed to turn it off using the following steps:

1. Set computer clock back several months
2. Start Minecraft and load up a Betweenlands world, then quit
3. Set seasonal events option in the config to false
4. Start Minecraft and load up a betweenlands world, then quit
5. Set computer clock to the correct date

I haven't looked at the source code, but from the effects I'm seeing it looks like setting the seasonal events option to false only prevents the seasonal event state from *changing,* meaning setting the option to false during a seasonal event permanently locks the game in that seasonal state. I confirmed this by setting the clock back several months while the option was set to false, and the game stayed in the Halloween "spook" state. It also looks like upon startup, the game sets the seasonal state *before* it registers a change in the config option, because when I tried skipping step 4, the "spook" event was turned on even though I had opened the world without the spook event immediately earlier and the config option was set to false.

Maybe this could be fixed by adding a small snippet of code that runs during startup and sets the seasonal event state to normal if the config option is set to false?

**Comment by TheCyberBrick** [comment]
There's a command for that: "/blevent off thebetweenlands:spook", but I guess making it turn off when disabled in the config would make sense.
