### ISSUE TITLE
Client Crashes when attempting to view items in JEI.

### ISSUE THREAD

**Issue by KelleyEngineering** [TheCyberBrick/The-Betweenlands#749]
#### Betweenlands version:
3.4.0

#### Forge version:
forge-1.12.2-14.23.5.2768.

#### Singleplayer or Multiplayer:
Single Player

#### Installed mods:
 grimpack                    6.0.0.1
 jei                               4.12.1.217                         
 thebetweenlands       3.4.0

## Link to full crash log
https://pastebin.com/bceRfeNF

## Description of the problem
I did not have this issue with BetweenLands 3.3.12. Today when I updated to version 3.4.0, I started 
having client crashes when attempting to view anything from the GrimPack mod in JEI. 
JEI and GrimPack do not have updates available. 
**I downgraded BetweenLands to 3.3.13 and 3.3.12 and this issue did not occur again.**

The Specific error is:
net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock

#### How to reproduce:
1. Look for something for GrimPack in JEI. (version 3.4.0 of BetweenLands)
2. client crashes

#### Expected result:
Be able to view objects from GrimPack in JEI

#### Actual result:
Client Crashes instead

#### Pictures:
N/A

**Comment by King-of-Huaji** [comment]
Oh.

**Comment by GoryMoon** [comment]
Fixed in dev

**Comment by BugmanBugman** [comment]
> Fixed in dev

Is there a link to download the dev version?

**Comment by GoryMoon** [comment]
We are about to release 3.4.1 soon but this dev build is the latest https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases/tag/dev-1.12-fixes-1241-01.11.2018
