### ISSUE TITLE
Request Authorized Transfer

### ISSUE THREAD

**Issue by King-of-Huaji** [TheCyberBrick/The-Betweenlands#750]
Hi!
I'm a Chinese Minecraft Player,I think your mod The Betweenlands is very awesome!!It is my favourite Minecraft Mod.Can I post them to a Chinese Minecraft Forum(https://www.mcmod.cn) to share your work with more players?I'll mark you as the author.
Thank you bery much,I hope to hear from you soon.
A Chinese Player

**Comment by GoryMoon** [comment]
From the looks of it, it's already posted on that forum.
