### ISSUE TITLE
Crash Potentially Caused by Conflict with Flan's Mod

### ISSUE THREAD

**Issue by korlandril** [TheCyberBrick/The-Betweenlands#751]
#### Betweenlands version: 

3.4.0

#### Forge version:

2768

#### Singleplayer or Multiplayer:

Crash happens doing the same action in Singleplayer and Multiplayer. Server being used is SpongeForge 1.12.2-2768-7.1.2

#### Installed mods:

https://pastebin.com/aXfe5qVb

## Link to full crash log

https://github.com/FlansMods/FlansMod/issues/965

#### How to reproduce:

problem is described here:
https://github.com/FlansMods/FlansMod/issues/965

Shooting a mob with an explosive weapon crashes the server and the client. This happens in the Overworld.

**Comment by TheCyberBrick** [comment]
I'm pretty sure that's not a problem on our side. Had a quick look at it and it looks like FlansMod's custom gun damage source is what causes the crash.
Will have a better look at it tomorrow.

**Comment by GoryMoon** [comment]
Fixed on other mods side
