### ISSUE TITLE
Excessive knockback

### ISSUE THREAD

**Issue by Idonith** [TheCyberBrick/The-Betweenlands#752]
DISCLAIMER: I am only 60% sure that this is a bug. It might be intentional, in which case I would ask to have it changed.
#### Betweenlands version:
3.4.0
I had the same problem in previous versions as well.

#### Forge version:
1.12.2-14.23.5.2768

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods (other than The Betweenlands and Forge):
journeymap-1.12.2-5.5.2
OptiFine_1.12.2_HD_U_C9

## Description of the problem
When attacking any Betweenlands mob with a Betweenlands sword equipped with a crimson middle gem, if the gem activates on the blow, the mob is knocked way back. Additionally, if the crimson middle gem activates on the killing blow, the mob is still nocked back right before dying, so all the experience and items, if any, are left far away.

Upon testing swords on swamp hags, I have found that when a crimson middle gem activates, weedwood swords knock back the hags 10 blocks.
Bone swords: 9 blocks
Octine swords: 13 blocks
Valonite swords: 16 blocks (In survival I once knocked a wight's soul/volatile head form substantially further, which prompted this report, but I have been unable to reproduce this specifically.)

These values are unchanged when in water and quick testing shows that all non-boss Betweenlands mobs are knocked back roughly the same amounts excepting the flying mobs, which I did not test.

#### How to reproduce:
1. Equip any Betweenlands sword (not a vanilla one) with a crimson middle gem.
2. Attack any Betweenlands mob with the sword until the crimson middle gem activates.
3. (optional) Kill a Betweenlands mob on a blow that activates the crimson middle gem and watch your loot and experience fly away.

#### Expected result:
The mob is knocked back a few blocks more than the standard knockback (two blocks) from a strike. Maybe six or seven blocks.

#### Actual result:
See my description, but with a Valonite sword that activates a crimson middle gem, a mob is knocked back roughly sixteen blocks.

**Comment by Terenx** [comment]
I think this is intentional, because last time I checked it worked with any middle gem, and the exp might fly away, but loot drops where it is killed, so your loot is still where it died, plus the kb can really save you or at least give you a good laugh

**Comment by TheCyberBrick** [comment]
This is actually something that was discussed before, i.e. knockback being more a defensive thing than offensive. There were a few suggestions but none that I found fitting or satisfying imo. I'll close this here but if you have suggestions please head over [here](https://github.com/Angry-Pixel/The-Betweenlands/issues/583) and let us know :)
