### ISSUE TITLE
JustEnoughResources (JER) crashes during /profile if The Betweenlands is installed

### ISSUE THREAD

**Issue by enricotagliavini** [TheCyberBrick/The-Betweenlands#753]
This is probably a cross mod issue requiring some collaboration between the two mods involved for the best solution. I already reported the bug to the JustenoughResources developer and he asked me to also post the issue in this tracker. Original issue can be found at https://github.com/way2muchnoise/JustEnoughResources/issues/167

#### Betweenlands version:
3.3.13

#### JER version:
0.8.5.27

#### Forge version:
1.12.2-14.23.5.2768

#### Singleplayer or Multiplayer:
Both in Single Player and Multiplayer. Tested with vanilla server + forge only, not sponge.

#### Installed mods:
This bug can be reproduce with only JEI, JER and The Betweenlands installed without any other mod.

## Link to full crash log
[crash-2018-10-29_19.14.28-server.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2536535/crash-2018-10-29_19.14.28-server.txt)

#### How to reproduce:

1. Install JEI, JER and TBL mods
2. Start a new test world
3. run the JER command: /profile 10

#### Expected result:
Game should not crash and JER should be able to profile the The Betweenland dimension

#### Actual result:
Game crashes

**Comment by GoryMoon** [comment]
Already fixed on JERs side, read my comment there.
