### ISSUE TITLE
[1.12.2] Crash on Load

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#754]
#### Betweenlands version:
3.4.0

#### Forge version:
2768

#### Singleplayer or Multiplayer:
SP

#### Installed mods:
https://pastebin.com/wubsDrnJ

## Link to full crash log
https://pastebin.com/MWF7YqyB

## Description of the problem
Crash loading game.

**Comment by MokahTGS** [comment]
Rolled back a version and no crash.

**Comment by GoryMoon** [comment]
Duplicate of #737. This was already reported to Project Red
