### ISSUE TITLE
algae + flower pot = crash

### ISSUE THREAD

**Issue by aycfes** [TheCyberBrick/The-Betweenlands#760]
#### Betweenlands version:

3.4.0

#### Forge version:

1.12.2-14.23.5.2768

#### Singleplayer or Multiplayer:

single 

#### Installed mods:

i don't have the time (or patience) to transcribe all of the mods, so i just got the list from the crash log.
[mods.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2550670/mods.txt)

## Link to full crash log

[crash-2018-11-05_18.48.34-client.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/2550622/crash-2018-11-05_18.48.34-client.txt)

#### How to reproduce:

1. get algae
2. get a mud brick pot
3. put them together
4. profit

#### Expected result:

i honestly don't know, maybe nothing, maybe a missing texture, a little bit of grass, etc

#### Actual result:

the game crashed and continued doing so as soon as i opened the world

**Comment by TheCyberBrick** [comment]
Fixed in 3.4.1
