### ISSUE TITLE
Crash server (java.lang.NullPointerException: Exception ticking world)

### ISSUE THREAD

**Issue by avescarelo** [TheCyberBrick/The-Betweenlands#769]
#### Singleplayer or Multiplayer:
Multiplayer, Sponge version: 2768-7.1.5-RC3506

#### Installed mods (server):
Antique Atlas, AppleCore, AutoRegLib, Carry On, Cases, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, Earthworks, Example Mod, Fast Leaf Decay, JurassiCraft, Just Enough Items, LLibrary, Ore Veins, Quark, Rough Mobs 2, Rustic, Spice of Life: Carrot Edition, SpongeForge, The Betweenlands, Wearable Backpacks

## Link to full crash log
[https://gist.github.com/pingvikin/9a05ef5e262dab6f17a2661cafadb5a4](https://gist.github.com/pingvikin/9a05ef5e262dab6f17a2661cafadb5a4)

#### How to reproduce:

1. Player joined in the Between world 
2. Server chashed

## Some console spam:
[https://gist.github.com/pingvikin/f66313bd66a9cec8e29fe96bbe71a6f3](https://gist.github.com/pingvikin/f66313bd66a9cec8e29fe96bbe71a6f3)

**Comment by TheCyberBrick** [comment]
Hm, that looks like a SpongeForge problem, please report it there: https://github.com/SpongePowered/SpongeForge/issues.
Thanks.
