### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by agentwolf88** [TheCyberBrick/The-Betweenlands#773]
#### Betweenlands version:
latest

#### Forge version:
2775

#### Singleplayer or Multiplayer:
Multiplayer

https://paste.ee/p/LFeWA

**Comment by theishiopian** [comment]
Looks like a problem with the heavyweight elixer. For some reason, an inWater check took a full minute.

**Comment by GoryMoon** [comment]
It's pretty weird that `inWater ` would take so long as the method just returns a boolean, could be that some mod replaces the method or something.
Going to change so the check if the elixir is active first before `inWater` so it's only checked when needed.
