### ISSUE TITLE
Betweenlands mobs in overworld

### ISSUE THREAD

**Issue by Meatshackles** [TheCyberBrick/The-Betweenlands#775]
#### Betweenlands version:
MC1.12.2, Betweenlands 3.4.1

#### Forge version:
14.23.5.2796

#### Singleplayer or Multiplayer:
Happens in both

#### Installed mods:
Screenshot below

## Description of the problem
Harlequin Toads spawning in the over world
Issue only happens in certain biomes, screenshot shows roofed forest
Only seen toads so far, unsure if it happens with other mobs yet
I'm sure its some other mod causing the issue but no clue which, possibly issue with biome bundle/OTG id suspect. Couldn't find any known issues like this
 

#### Pictures:
https://imgur.com/2bJTy25 - modlist
https://imgur.com/Ce2iQ5Z - toads spawning

**Comment by TheCyberBrick** [comment]
Yes, this is caused by another mod. None of our entities normally spawn in the overworld except for Dark Druids. You can most likely change this in biome bundle's configs.
I'm assuming the modpack's author intentionally made them spawn there (unless you made the pack yourself of course).
