### ISSUE TITLE
[Suggestion]: Percentage Health lost via Decay.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#776]
Would it be possible to altar the health lost if decay is low enough to be percentage-wise instead of just -14 Health (-7 hearts) at 0 decay?

Reason being is that the player can increase their maximum health via certain modifiers so... I can have like 100 max health and a -14 max health due to the Decay lost doesn't seem like much as that leaves me with 86 max health.

If percentage is possible... per decay thershold, lower the max health by -10%, up to -70% at 0 decay. At 20 health... becomes 6 health and if scaled to 100 max health... it'll be 30 max health at 0 decay which can pose a threat, especially if paired with a damage source scaling mod.

**Comment by TheCyberBrick** [comment]
Might implement it as config option. Shouldn't be difficult to implement with attribute modifiers
