### ISSUE TITLE
BetweenlandsWorldStorage capability causing my game to crash

### ISSUE THREAD

**Issue by BugmanBugman** [TheCyberBrick/The-Betweenlands#777]
## Versions#### Betweenlands version:
The Betweenlands v3.4.1 

#### Forge version:
1.12.2 - 14.23.5.2796

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
https://hastebin.com/jozeqowake.rb

## Link to full crash log
https://hastebin.com/licipiwice.rb

## Description of the problem
Happens out of no where, I'm not even sure why. I believe it has to do something with NetherEX but otherwise i'm not sure. This isn't the first time it's happened, but i'm having trouble pinpointing why it's happening

**Comment by GoryMoon** [comment]
Can't reproduce it in dev with some short testing, does it happen randomly or consistently all the time?
It should not happen from a quick look on their code.

**Comment by TheCyberBrick** [comment]
This probably doesn't have to do with NetherEx because @Velocihater also had the same crash with Cavern 2 and there's nothing wrong with the code there either. Probably some other mod causing it.
