### ISSUE TITLE
An abnormal way to get Pot of Chance

### ISSUE THREAD

**Issue by RisingInIris2017** [TheCyberBrick/The-Betweenlands#778]
#### Installed mods:
The Betweenlands 3.4.1
Erebus 1.0.23
Waila & WailaHarvestability

#### How to reproduce:

1. Find or place a Pot of Chance.
2. Right-click it with Wand of Animation from Erebus, then it will become a mob and drop all loots in it.
3. Kill the mob, and the mob will drop a Pot of Chance item.
4. Place it again, and it will generate new loots.
5. Do 1-4 again and again to get lots of loots.

#### Pictures:

![](https://i.loli.net/2018/12/23/5c1ef69902622.png)

![](https://i.loli.net/2018/12/23/5c1ef69a288eb.png)

![](https://i.loli.net/2018/12/23/5c1ef699ecc87.png)

**Comment by vadis365** [comment]
Hello,
In the last release of Erebus there is a config file to blacklist blocks for the Wand of animation.
Add the loot pots to the list if you want to disable this.
Cheers,
Me.

**Comment by RisingInIris2017** [comment]
Thanks for your advice! :)
