### ISSUE TITLE
Server crash - Rowboat EntityDamageSource

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#780]
#### Betweenlands version:

TheBetweenlands-3.4.2-universal.jar

#### Forge version:

14.23.5.2781

#### Singleplayer or Multiplayer:
Multiplayer
#### Installed mods:
https://minecraft.curseforge.com/projects/ancient-towncraft/

## Link to full crash log
https://gist.github.com/ProsperCraft/35c2c99347dcbdec3818ed84e73c53b5

**Comment by theishiopian** [comment]
Looks like a conflict with mowzies mobs. What exactly was happening when this happened?

**Comment by ProsperCraft** [comment]
https://paste.fedoraproject.org/paste/Na~7Ytak1Po5proNpj1tAA
Here is another server crash.

When players are playing on the server, its a bunch of players, and nobody admits to having a boat, seems like this happened on an old update with the boat as well.

**Comment by GoryMoon** [comment]
It's nothing to do with having a boat or not, it's related to a handler that prevents damage from below a boat when determining where the source of the damage and if it's against a boat it crashes.
I've added some more protection against invalid damage sources that some mods create.
It will be available in the next release.
