### ISSUE TITLE
Server crash on SpikeWave Event

### ISSUE THREAD

**Issue by DracoC2M** [TheCyberBrick/The-Betweenlands#783]
#### Betweenlands version:
3.4.3

#### Forge version:
14.23.5.2768

#### Singleplayer or Multiplayer:
Multiplayer (Server FML Forge mit Multicraft)

#### Installed mods:
 minecraft 1.12.2 
 mcp 9.42 
 FML 8.0.99.99 
 forge 14.23.5.2768 
 randompatches 1.12.2-1.12.0.1 
 baubles 1.5.2 
 extrautils2 1.0 
 flyringbaublemod 0.3.1_1.12-d4e654e 
 biomesoplenty 7.0.1.2399 
 bookshelf 2.3.559 
 chisel MC1.12.2-0.2.1.34 
 codechickenlib 3.2.2.353 
 cosmeticarmorreworked 1.12.2-v3 
 cucumber 1.1.3 
 thedalekmod (Update 48.7) 
 jei 4.13.1.225 
 darkutils 1.8.219 
 props 2.6.2 
 dldungeonsjbg 1.11.5 
 endercore 1.12.2-0.5.43 
 enderio 5.0.39 
 enderiointegrationtic 5.0.39 
 enderiobase 5.0.39 
 enderioconduits 5.0.39 
 enderioconduitsappliedenergistics 5.0.39 
 enderioconduitsopencomputers 5.0.39 
 refinedstorage 1.6.12 
 enderioconduitsrefinedstorage 5.0.39 
 enderiointegrationforestry 5.0.39 
 enderiointegrationticlate 5.0.39 
 ftblib 5.4.0.73 
 enderiomachines 5.0.39 
 enderiopowertools 5.0.39 
 enderstorage 2.4.5.135 
 exnihilocreatio 1.12-0.2.4 
 excompressum 3.0.26 
 ftbutilities 5.3.0.69 
 hud 1.3.9 
 inventorytweaks 1.63+release.109.220f184 
 ironbackpacks 1.12.2-3.0.8-12 
 ironchest 1.12.2-7.0.54.838 
 journeymap 1.12.2-5.5.3 
 jmfixer 1 
 justenoughdimensions 1.6.0-dev.20180619.124018 
 lostcities 2.0.12 
 malisiscore 1.12.2-6.4.0 
 malisisdoors 1.12.2-7.3.0 
 mantle 1.12-1.3.3.39 
 mcjtylib_ng 3.0.7 
 mob_grinding_utils 0.3.13 
 mtlib 3.0.5 
 mysticalagriculture 1.7.0 
 mysticalagradditions 1.2.10 
 natura 1.12.2-4.3.2.65 
 naturescompass 1.5.1 
 nmsot 1.2.2-mc1.12.2 
 nutrition 3.1.0 
 oreexcavation 1.4.133 
 oeintegration 2.3.4 
 omlib 3.0.1-162 
 openmodularturrets 3.0.1-264 
 parry 1.0 
 placebo 1.5.0 
 plants2 2.10.3 
 quickleafdecay 1.2.4 
 refinedstorageaddons 0.4.3 
 rftools 7.59
 shadowmc 3.8.0 
 valkyrielib 1.12.2-2.0.19.1 
 simplegenerators 1.12.2-2.0.19.1 
 theoneprobe 1.4.25 
 tp 3.2.31 
 unloader 1.2.0 
 universalmodifiers 1.12.2-1.0.16.1 
 wanionlib 1.12.2-2.2 
 worldedit 6.1.10-SNAPSHOT 
 thebetweenlands 3.4.3 
 unidict 1.12.2-2.9.2 

## Link to full crash log
https://gist.github.com/DracoC2M/b43d341bcb1c9500e154346e63552129

#### How to reproduce:
1. Go to Betweenlands
2. Find a Spirit Tree
3. Let it attack you with SpikeWave

The crashlog tells me, that the EntitySpikeWave was cast on EntityCyberman from The Darlek Mod.
But there is no Cyberman or any other Entity from this mod in this Dimension. 

#### Expected result:
Everything should work fine ;-)

#### Actual result:
The Server crashes instantly. Every time I log into the Server, it will crash again.

**Comment by GoryMoon** [comment]
Report this to the `The Darlek Mod` as this is an issue on their side.

**Comment by TheCyberBrick** [comment]
Yes, this seems to be a problem with The Darlek Mod.
