### ISSUE TITLE
[request] Rain blocks standalone

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#786]
I just ran into the first rain I've seen in the mod, and I really like the actual rain blocks placed on the ground. Would it be possible to have this as a standalone mod for use in other dimensions?

**Comment by TheCyberBrick** [comment]
You're in luck, this exists already ;)
https://minecraft.curseforge.com/projects/puddles

**Comment by ghost** [comment]
Sorry for the delay in reply, work sucks. I have looked at the mod mentioned and the puddles don't really fit with minecraft, and don't look nearly as nice as the ones from this mod.

**Comment by TheCyberBrick** [comment]
They're pretty much the same though, no? Ours just have some more thickness and a very slightly different texture.
You should be able to change the model and texture of those puddles yourself with a resource pack ;)
See [Puddles block model](https://github.com/mc-jt9/Puddles/blob/master/src/main/resources/assets/puddles/models/block/puddle.json), [Creating a resource pack](https://minecraft.gamepedia.com/Tutorials/Creating_a_resource_pack) and [Block models](https://minecraft.gamepedia.com/Model).
