### ISSUE TITLE
Game Crash on load

### ISSUE THREAD

**Issue by Gryffen1971** [TheCyberBrick/The-Betweenlands#791]
I tried to load my Mod-Pack with you mod and "Project Red" Mods (All of them) and the game crashes on Load at Step 5 of 7. When i disable "The Betweenlands" or "Project Red" Mods and start loading the game it completes it loading process

#### Betweenlands version:

TheBetweenlands-3.4.4-universal.jar

#### Forge version:

forge-14.23.5.2811

#### Singleplayer or Multiplayer:

SinglePlayer

#### Installed mods:

Here is the Link:  https://docs.google.com/document/d/1YMN7keX0k9hfq2btK4RCeIAhXb4aSXnV2ORAvF7RUkY/edit?usp=sharing

## Link to full crash log

Here's the Link:  https://docs.google.com/document/d/1dCaqC8zaloN2cE_ZR0ilXZk9Xy7YX4d8Fe76XEWXJzo/edit?usp=sharing

#### How to reproduce:

1. Install "SkyCrane Magic, Mech and Tech Mod Pack
2. Install Project Red (All Mods)
3. Enable all Mods
4. Start Loading Minecraft

#### Expected result:

Game loading Crashes on Step 5 of 7

#### Actual result:

Game crashes on load on Step 5 of 7

#### Pictures:

I have posted a report(issue) with the "Project Red" team

**Comment by GoryMoon** [comment]
Duplicated of #772
This has been fixed on their side since last summer but never publically released.
Either remove the relocation part or `downgrade ProjectRed to 4.9.0.086` or use a dev version from the maven [repo](http://chickenbones.net/maven/mrtjp/ProjectRed/)

**Comment by Gryffen1971** [comment]
ok thanks. I did find the mod that was the problem from Project Red and removed it and now everything loads with the current public release on curseforge.
