### ISSUE TITLE
Compatibility Issue With Fossils and Archaeology - Crash

### ISSUE THREAD

**Issue by MokahTGS** [TheCyberBrick/The-Betweenlands#792]
Getting a crash with the 1.12.2 version trying to launch it within a mod pack.

Forge 2811
FossilArch 8.0.0
LLib 1.7.17-1.12.2
TheBetweenlands-3.4.4

Full mod list: https://pastebin.com/5qPRKz0R

Crash Log: https://paste.dimdev.org/ifoximudeb.mccrash

Issue was reported to the Fossil Team but I'm not sure if there's something that can be done on this end.

https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1124

**Comment by TheCyberBrick** [comment]
This is a problem on F/A's side. I've posted a comment with a potential solution there.

**Comment by MokahTGS** [comment]
Looks like they have a handle on this issue: 
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/commit/526a91feb9365e31532bfb15c66cb2cb4a31d2c8
