### ISSUE TITLE
Wight Fortress -> Cannot defeat boss.

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#794]
#### Betweenlands version:

The Betweenlands v3.4.4 + Server 3.4.4

#### Forge version:

Minecraft Forge 1.12.2 - 14.23.5.2814

#### Singleplayer or Multiplayer:

Multiplayer Server utilitising SPONGEFORGE 1.12.2-14.23.5.2768-7.1.6-RC3583

#### Installed mods:

https://www.technicpack.net/modpack/one-life-popular-smp.1297373

## Link to full crash log

https://paste.dimdev.org/amerocoren.mccrash

#### How to reproduce:

1. Fight your way up the Wight Fortress
2. Get to the Eye (that teleports you to final boss)
3. Stare at the eye (that teleports you to final boss)
4. Crash, become depressed.
5. Can't join server back because it will just continually crash.
6. Reset your position, do /back and it doesn't spawn the boss but teleports you??

#### Expected result:

to be teleported up to the top and fight the boss like that mfkin king

#### Actual result:

Stare at the eye, fucking crash.

#### Pictures:

unneeded.

**Comment by ghost** [comment]
Upon trying to spawn the "Primordial Malevolence" using the spawn egg it causes a new crash log seen below.

https://paste.dimdev.org/eyewilogex.mccrash

**Comment by TheCyberBrick** [comment]
Thanks for the report.  
This is not a problem on our side, it's caused by another mod. I suspect it's MoCreatures because that mod is known to cause this exact problem for several mods.
