### ISSUE TITLE
Compatibility with Better Foliage

### ISSUE THREAD

**Issue by Vionai** [TheCyberBrick/The-Betweenlands#797]
It seems theres a bit of an incompatibility with better foliage, by that I mean it tries to render stuff and errors out when it tries.... It does not seem to impact playability and ultimately the items are still there so nothings NOT rendering, but maybe look into it?

#### Betweenlands version:

1.12 (I think, I just downloaded this yesterday so its the most recently released version)

#### Forge version:

Not sure, my hubs set it up for me.

#### Singleplayer or Multiplayer:

Both

## Link to full crash log

No crash, just some Lua errors

#### How to reproduce:

1. Better foliage with your mod 
2.
3. etc...

#### Expected result:

https://imgur.com/a/NU8cH2v 

#### Actual result:

https://imgur.com/a/NU8cH2v

#### Pictures:

https://imgur.com/a/NU8cH2v

**Comment by theishiopian** [comment]
try turning off rounded logs in better foliage settings (press f8) and see if that helps.

**Comment by TheCyberBrick** [comment]
Not sure why that is, most of our logs use regular vanilla-like block models. You can try reporting this to Better Foliage as there's not much we can do on our side.
