### ISSUE TITLE
[Suggesion] Sulfur Ore Glowing

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#799]
There has been a little detail I've always felt necessary however was never introduced, Sulfur Ore, just like the sulfur torch, which produces light when you quite literally only combined sulfur with a stick
Why not have a slight glow of light seep out from the cracks in the ore? It would make caves a little more immersive and would much improve venturing through them, it would also assist in locating the ore, which is common anyways so it's not like it's showing something very rare off

That's just my suggestion, take it as you will, with a grain of sa- silt, silt...

**Comment by TheCyberBrick** [comment]
Hm I'm not sure. Coal doesn't glow in vanilla either but torches do ;)
Since sulfur is very common the caves would probably also become too bright in my opinion.

**Comment by UnlimatedStone9** [comment]
This is of course entirely up to you, however I thought that a very slight glow might make things look a little nicer and wouldn't add too much light to caves, similar to how magma has a light level of 0/1? Only glows where it is so it's not very bright, but perhaps a little lighter
And yes I know coal doesn't glow because of how it's not lit however aren't Betweenlands torches a little less realistic than a burning piece of coal?

It could also be a configuration option disabled by default, just a suggestion

**Comment by UnlimatedStone9** [comment]
For example magma has a very slight light around it, it's not a lot to make caves too bright/prevent mob spawning but it's light enough to add a little more detail to the cave
![image](https://user-images.githubusercontent.com/40124890/53702450-f9983480-3dfe-11e9-8c6f-4458747b26f8.png)

**Comment by TripleHeadedSheep** [comment]
I get the idea but personally I don't see this working very well.
As for the logic of it, sulfur doesn't glow but the torches do because they are lit on fire (just like the coal torches work).

Sulfur is a very common ore and it would make the caves too lit (hue hue). Octine already glows, which is nice enough. Having the caves being too lit up makes them easier than we intend them to be.

**Comment by UnlimatedStone9** [comment]
That's completely fine, it is of course up to you, the developers and all, just my little idea to take with a grain of sa- silt...

**Comment by PetasiGit** [comment]
Not gonna be added it seems, so closing this.
