### ISSUE TITLE
I can't leave the portal

### ISSUE THREAD

**Issue by Zarpyk** [TheCyberBrick/The-Betweenlands#800]
#### How to reproduce:

1. Join to the dimension

#### Expected result:

Don't insta teleport

#### Actual result:

Insta teleport

#### Pictures:

[Gif](https://i.gyazo.com/df5e7386eedcd2c3b3bb7bdc89e11472.mp4)

**Comment by UnlimatedStone9** [comment]
You're in creative mode, this is a vanilla Minecraft FEATURE, not a bug, this happens with the Nether Portal in creative mode, you should know this

**Comment by GoryMoon** [comment]
^ as said above.
Just break the tree between the portals to get out in creative.
