### ISSUE TITLE
[Lighting Bug] Chunks do not update properly

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#801]
#### Installed mods:

The Betweenlands: v3.4.4
BetterFPS: 1.4.8
BetweenOres: 1.1.3
Charset-Immersion: 0.5.5.5
Charset-Lib: 0.5.5.6
CodeChickenLib: 1.12.2-3.2.2.353
Fast Leaf Decay: v14
FoamFix: 0.10.3-1.12.2
ImmersiveEngineering: 0.12-89 
ImmersivePetroleum: 1.12.2-.9
ImmersivePosts: 0.0.4-01
ImmersiveTech: 1.12-1.3.10
Just Enough Items: 1.12.2-4.13.1.255
Not Enough Items: 1.12.2-2.4.2.240
PrimalCore: 1.12.2-0.6.104
Questionably Immersive: 1.12.2-0.1.0

## Description of the problem

Basically when venturing into a new chunk that is dark (Like in a cave or something) the lighting does not update correctly, it requires a manual update, like with a torch during the old beta days, I'm constantly manually fixing it with Sulfur Torches

#### How to reproduce:

Load any dark area in a chunk like in the caverns underground, update the light manually using something that emits light

#### Expected result:

Lighting should automatically fix itself to be accurate to its environment (Another torch in a chunk next to it should light the one nearby but does not

#### Actual result:

Chunk stayed dark, it can occasionally fix itself but it's very finicky

#### Pictures:
![image](https://user-images.githubusercontent.com/40124890/53658121-e135e780-3c4f-11e9-95fb-fa2f8e76c034.png)
![image](https://user-images.githubusercontent.com/40124890/53658138-e8f58c00-3c4f-11e9-99a3-f2ed2ab471be.png)

**Comment by TheCyberBrick** [comment]
It's not really a bug but a side effect of Forge's forced multithreaded chunk rendering (in Forge's config: Client Settings -> Force threaded chunk rendering). It increases performance while rendering chunks but as a tradeoff you sometimes get glitches like what you've found there, especially when lots of chunk updates are happening. If you want you can disable that setting in Forge's config but you might get more lag spikes.

**Comment by HakkaTjakka** [comment]
Offline light glitch fixer 1.12.2

Hi. I've been searching to fix the light glitch in 1.12.2 and can not find a fix or mod, only for spigot server (in game).

So i added an option to my 1.12.2 region file creator / editor for just loading, recalculating the block- and skylight, and save it again. It seems to work ok.

I only have the source code for Linux (Ubuntu) adapted to this, if you need the Windows version you need to adapt the Windows src version (root). On request i can do this for you.

https://github.com/HakkaTjakka/CAVES/tree/main/Linux_ShaderTest_v1.1
