### ISSUE TITLE
Repeated console errors involving advancements and recipes

### ISSUE THREAD

**Issue by NEXUS2345** [TheCyberBrick/The-Betweenlands#809]
#### Betweenlands version:
3.4.4

#### Forge version:
Forge 1.12.2 14.23.5.2815

#### Singleplayer or Multiplayer:
SpongeForge multiplayer with Velocity proxy server

#### Installed mods:
All The Mods 3 version 5.12.0
Plugins:
AurionVoteListener
Capacitor (custom plugin for server management and a bunch of other stuff)
CatClearLag
Command Utils
Command Signs
FastAsyncWorldedit
GriefPrevention
LuckPerms
MMCReboot
MMCRestrict
Nucleus
Nuvotifier
Prism
TotalEconomy
UniverseGuard

## Stacktrace of issue
https://gist.github.com/NEXUS2345/6b87641cf2a3a0714844fd32b5ce2870

#### How to reproduce:
Unsure how to reproduce at this time. Appears to happen only when the Betweenlands dimension is loaded.

**Comment by GoryMoon** [comment]
This has nothing to do with the betweenlands. 
From the looks of it, the recipe for paper is changed/removed and thus printing errors in the log.
Probably a change in the modpack.
