### ISSUE TITLE
Suggestion: Use of 1.13 vanilla fluids?

### ISSUE THREAD

**Issue by FoxSamu** [TheCyberBrick/The-Betweenlands#811]
In the release of Minecraft 1.13, fluids were added as something else than a block (though they are stored as a block). This allows blocks to create an 'underwater' state property, instead of using another block for underwater, making them waterlogged. This also allows mods to create and register custom vanilla-style fluids. Forge 1.13 still has the old 'forge-fluid' system, which is used by the 1.13 port of the betweenlands. This will need another block instead of another state for waterlogged blocks. Another fact is that there are a lot of bugs in the forge fluid system (for example: #502), compared to vanilla's fluids...
Maybe it's still coming but just as suggestion, could the betweenlands use custom vanilla fluids in 1.13, instead of Forge's 'fake-fluids' (they aren't even real fluids)? I managed to do this in my mod test so I bet this is possible...

**Comment by GoryMoon** [comment]
Very much of the 1.13 port is still WIP so anything could change.
The fluids in Forge for 1.13 is also on hold for 1.14 for from what I've seen in the Forge discord.

We will probably use the vanilla ones when we work more on the port, currently we are finishing up some 1.12 features before we go back to it.

**Comment by TheCyberBrick** [comment]
Yes.
