### ISSUE TITLE
Crash with Simple Dimensions

### ISSUE THREAD

**Issue by xGarionx** [TheCyberBrick/The-Betweenlands#812]
#### Betweenlands version:

v3.4.6

#### Forge version:

forge-14.23.5.2815

#### Singleplayer or Multiplayer:

Single Player

#### Installed mods:

https://minecraft.curseforge.com/projects/the-ancient-cake

Currently at Version Alpha 0.8.0 the issue however is present under all versions. 

## Link to full crash log

https://pastebin.com/bVnDjUJm

#### How to reproduce:

1. startup Simple Dimension Creation
2. Create Dimension (with several tries i can rule out that it is a specific setting)
3. Crash

#### Expected result:

A dimension created by simple Dimensions

#### Actual result:

The opposite x'D (sry couldnt resist).
In General the modpack needs simple Dimension if anyhow possible, but i dont want to miss Betweenlands it's a beautiful mod. Hope this can be fixed .

**Comment by GoryMoon** [comment]
This is an issue with Simple Dimensions, this has been reported before.
There is a fix made by someone 1.5 year ago but it's not merged https://github.com/lumien231/Simple-Dimensions/issues/14
