### ISSUE TITLE
[1.12.2] Config option to move the Decay Bar HUD.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#813]
![](https://cdn.discordapp.com/attachments/377171551155650560/556005715815301151/decaytoughnessbarissue.PNG)

Some mods add in some bars such as Silent's Gems' Chaos Bar or "Overpowered Toughness Bar" which adds in a toughness bar. The Decay Bar doesn't see these bars so it hides behind the bar that's rendered there. In the image above there's the Armor Toughness Bar from "Overpowered Toughness Bar" and if you look closely the Decay Bar is hiding behind it.

If going underwater... the Decay Bar moves up but then the Air Bar hides behind the Decay Bar although you can't really see it.

Would it be possible to add in a config option to move the Decay Bar HUD around? Also... if you're able to move the Bar... disable the 'bump' that occurs if another bar appears, such as the Air Bar when in water. Say for example I move the Decay Bar to something suitable and whenever I go underwater the Decay Bar get's bumped up which would be strange.

**Comment by TheCyberBrick** [comment]
Hi, I've just implemented this feature in the dev build. A new release should hopefully be available soon.
The new options allow you to offset the bar, e.g.  ![](https://i.imgur.com/UCu9Te2.png),
or move it somewhere else, e.g. top left corner of the window etc.
