### ISSUE TITLE
Very Dense Fog Will Not Go Away

### ISSUE THREAD

**Issue by Barerock** [TheCyberBrick/The-Betweenlands#814]
Versions:
TheBetweenLands: 3.4.6
Forge: 14.23.5.2779
Singleplayer
Installed Mods:
https://imgur.com/9g9lttK

No Crash Log
Description: This issue is VERY similar to the Black Fog incompatability with shaders, and I suspect it is related. One day I accidentally made a world that started in the Between Lands instead of the overworld. I was experimenting, you see. Well I played for a while with no issues until I realized that glass textures were really screwed up, and switched textures a bunch. Fast forward like three hours and my original world has become invisible! I haven't been to the Between Lands in that world, so I was confused. Fast forward five or four months of no game time and I'm back here. My world is still invisible (despite updating a lot of my mods and removing problematic ones) and I've tested with and without Optifine and BetweenLands. Starting a new world results in this in the Overworld: https://imgur.com/Pbtd3vF

I've petitioned Reddit and they say I should repair my profile using the Twitch Client; but my textures are fine, it's the rendering that's the issue.
EDIT: The world isn't invisible I just figured. I'm in a massive tower with few windows, so the thick fog just makes it look invisible, since it covers all surfaces.

Expected result:
I expected the shaders or rendering to properly switch between worlds, since I turned BetweenLands shaders off for normal rendering. I've also turned the Optifine shaders completely off.

Actual result:
Everything turned foggy in all worlds

Shamelessly Quick Update: Removing Optifine AGAIN seemed to fix it.... Not sure why. If you and the Optifine dev can fix whatever is causing this issue, it'd be super dope. Keep up the good work my dude!

**Comment by PetasiGit** [comment]
Optifine is notorious for causing issues with the mod, gonna close this since you figured it out.
