### ISSUE TITLE
Unbreakable boss of Wight Fortress

### ISSUE THREAD

**Issue by YOKOGAMA** [TheCyberBrick/The-Betweenlands#816]
#### Betweenlands version:
TheBetweenlands-3.4.6-universal

#### Forge version:
spongeforge-1.12.2-2768-7.1.5

#### Singleplayer or Multiplayer:
Multiplayer Sponge

#### Installed mods:

![image](https://user-images.githubusercontent.com/40151801/54676515-e7faa080-4b11-11e9-83da-a77c62a941ab.png)

## Link to full crash log
no crash log

#### How to reproduce:

When you fight with the boss on the top of Wight Fortress, the green bullets it fires must be snagged by the player with a sword and shot back at the boss, but there is no green bullets at all, and you cannot hit the boss.

#### Pictures:

![image](https://user-images.githubusercontent.com/40151801/54676880-c0f09e80-4b12-11e9-9818-a35f4583f4e0.png)

**Comment by TheCyberBrick** [comment]
Were you in survival mode?
Could also be caused by Sponge, please try it without Sponge if possible.

**Comment by YOKOGAMA** [comment]
Yes, I and my friends were in  survival mode.
I wanted to try without Sponge, But I couldn't find boss quickly. I'll try to find him and report the results.

**Comment by YOKOGAMA** [comment]
I tried with the same mods but without the sponge. Everything works. Is it possible to fix a bug for a sponge?

**Comment by TheCyberBrick** [comment]
Alright, thanks for testing it out. Sponge does change quite a few things about mob spawning, but I don't really know how it works exactly and why it wouldn't working this particular case here. Would probably be best to report it to Sponge.
