### ISSUE TITLE
[Overwrting] [Bug] Fossils and Archeology overwrites Thebetweenlands tar.

### ISSUE THREAD

**Issue by Carvercarver1** [TheCyberBrick/The-Betweenlands#818]
V: 1.12.2

Forge: 2772.

Title says it all.

**Comment by TheCyberBrick** [comment]
No, title does not say it all. Besides, I don't think there's any problem with F&A replacing our Tar fluid, that's just how Forge fluids work. If there is a problem please create a proper report, thanks.
