### ISSUE TITLE
Ticking Entity Fortress Boss Causes Crash - Unable to Fight Fortress Boss At All

### ISSUE THREAD

**Issue by timeherald** [TheCyberBrick/The-Betweenlands#822]
#### Betweenlands version:

3.4.6

#### Forge version:

forge-14.23.5.2811

#### Singleplayer or Multiplayer:

Multiplayer forge

#### Installed mods:

Large list. Please view: https://paste.dimdev.org/ejatutadel.mccrash

## Link to full crash log

Please view https://paste.dimdev.org/ejatutadel.mccrash

#### How to reproduce:

1. Simply got in range of, and viewed fortress boss
2. error occurred and player kicked

It looks like the fortress boss tried to use the thaumcraft taint modifier, or the ice and fire siren modifier (under entity NBT). I'm not sure if these are incompatibilities on the part of The Betweenlands, or the other mods.

**Comment by timeherald** [comment]
Any updates or thoughts on this? Unable to move on further with this mod, since players can't fight the fortress boss.

**Comment by TheCyberBrick** [comment]
Yes, sorry for the late answer.
This is a known issue caused by MoCreatures and there's unfortunately nothing we can do. If you want you can voice your concern on MoCreatures' issue tracker where this problem had already been reported a year ago.
