### ISSUE TITLE
ItemEquipmentHandler consuming excessive CPU usage

### ISSUE THREAD

**Issue by Yamza** [TheCyberBrick/The-Betweenlands#823]
#### Betweenlands version:
TheBetweenlands-3.4.6-universal

#### Forge version:
forge-14.23.5.2825

#### Singleplayer or Multiplayer:
Multiplayer(Server)

#### Installed mods:
ATM3: Remix 1.3.0 https://minecraft.curseforge.com/projects/all-the-mods-3-remix

#### How to reproduce:
1. None. I don't believe any players even entered the dimension.

#### Pictures:
https://i.imgur.com/oUF9RwW.png

#### Profile:
https://sparkprofiler.github.io/#KLAhzK8Nu3

**Comment by GoryMoon** [comment]
Fixed in b6939a6c193f79b89df80941f663aa844e71d6c9
