### ISSUE TITLE
Gl11 is called Everywhere instead of GlStateManager

### ISSUE THREAD

**Issue by jredfox** [TheCyberBrick/The-Betweenlands#826]
Example: https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/java/thebetweenlands/client/render/model/entity/ModelMireSnailEgg.java

Why is this an issue. GlStateManager caps the current state if it's enabled or disabled. Then it says if the state isn't the current state set that open gl value. Yours is out of sync with a minecraft default. Also I don't think you should be disabling blend after rendering an entity

**Comment by TheCyberBrick** [comment]
*Everywhere*. Yes, absolutely *everywhere*.
Thanks, though.
