### ISSUE TITLE
Buckets not stacking - nbt issue

### ISSUE THREAD

**Issue by jonqrandom** [TheCyberBrick/The-Betweenlands#827]
i'm still seeing the issue noted in #730, buckets aren't stacking depending on whether they've contained a liquid or not; for clarity, buckets that have had different liquids but are now empty _do_ stack, it's just new buckets not stacking with used ones.

**Comment by TheCyberBrick** [comment]
That happened when removing Solid Rubber from a Syrmorite Bucket. That is fixed in dev now, new release should hopefully be soon.
