### ISSUE TITLE
Food sickness in the overworld?

### ISSUE THREAD

**Issue by Shakaykay** [TheCyberBrick/The-Betweenlands#829]
As title says. I was wondering if there is a way to/if you could implement a way to put food sickness in other dimensions via a whitelist or something. I'm making a modpack with TaN and food funk, and also want people to mind eating too much of the same thing in dimensions other than the betweenlands.

EDIT: I should also state that i am beginner level in .json, i've done as much as custom recipes in craft tweaker, and editing already templated fields for arc furnace recipies in advanced rocketry and whatnot.

**Comment by TheCyberBrick** [comment]
Yes, I've just implemented this in the current dev build. Should be available soon.

**Comment by TheCyberBrick** [comment]
Update will be release later today.
