### ISSUE TITLE
Stuck in the Spawn Tree

### ISSUE THREAD

**Issue by katubug** [TheCyberBrick/The-Betweenlands#830]
#### Betweenlands version:
TheBetweenlands-3.4.6-universal

#### Forge version:
forge-1.12.2-14.23.5.2838-universal

#### Singleplayer or Multiplayer:
Multiplayer, Forge server.

#### Installed mods:
https://minecraft.curseforge.com/projects/enthusiasticraft/relations/dependencies (I'm the modpack author so feel free to ask me questions)

#### How to reproduce:

1. Place Sapling
2. Right Click with Swamp Talisman
3. Tree appears with you inside.
4. Attempt to exit tree via portal, get sent immediately to The Betweenlands.
5. Attempt to exit the spawn tree in the Betweenlands, get sent immediately back to Overworld.
6. Repeat.

#### Expected result:
I expected to be able to walk out of the tree via the portals and only get teleported if I stayed within the portal block for a while.

#### Actual result:
Immediately upon touching the portal, it sends me to the opposite dimension. As such, there is no way to exit the spawn tree aside from chopping through it (which I'd rather not do, as it's very pretty).

I've temporarily bypassed this on the server by breaking out, replacing the blocks, and then setting down a Waystone outside the tree in the Betweenlands. However, I assume this isn't intended behavior?

**Comment by GoryMoon** [comment]
This is intended, this only happens when you are in creative.

When you are in survival you have to stay in the portal for a little while before you get teleported.
This is similar to how vanilla nether portals work.

**Comment by katubug** [comment]
Ah, my mistake then. Thank you for clarifying, and I apologize for the
false alarm.
