### ISSUE TITLE
[Feature Request/Suggestion] Way to add mod pack name to title screen

### ISSUE THREAD

**Issue by Winddbourne** [TheCyberBrick/The-Betweenlands#832]
I love the Betweenlands title screen you've created it's very atmospheric and amazing; sort of like the dimension itself.  

I don't even mind giving the mod pride of place on the title screen though they'll have to either go through the tutorial I'm setting up or figure out how to get there by screwing up but . . . I would like to be able to put the name of the mod pack below the Betweenlands logo in some nice font, perhaps colored red for more atmosphere.

**Comment by TheCyberBrick** [comment]
Hi,
thanks!

>I would like to be able to put the name of the mod pack below the Betweenlands logo in some nice font, perhaps colored red for more atmosphere.

I'm pretty sure you can do that with a resource pack. You can edit this file: https://github.com/Angry-Pixel/The-Betweenlands/blob/1.12-dev/src/main/resources/assets/thebetweenlands/textures/gui/main/logo.png and then ship it in a resourcepack with your modpack.
