### ISSUE TITLE
[Suggestion]Hopper items into and out of the compost bin

### ISSUE THREAD

**Issue by f03n1x** [TheCyberBrick/The-Betweenlands#836]
I sort of expected this to work already but just being able to hopper in some swamp reeds saves a bit of time when I forget to add things into the compost bin, would be cool if it was added in, I don't think it'd take too long to implement (unless there is some issue with needing to open the compost bin, first put items in, close the lid and pull items out).

On a side note really love the mod, I'm playing a modpack where you start off in the betweenlands and it has been quite fun so far, you've definitely outdone yourselves creating a whole new way of surviving in minecraft thanks for all your hard work! 👍

**Comment by imdutch21** [comment]
There is actually a way to put items in to the compost bin with hoppers, though I just tested and it is not working at the moment (It just deletes the items). You put the hopper on top of a compost bin, open the lid and then the items will flow into the compost bin. You have to still manually open and close the lid of the bin though.
