### ISSUE TITLE
More Shader Problems

### ISSUE THREAD

**Issue by Tilt-github** [TheCyberBrick/The-Betweenlands#841]
#### Betweenlands version:

3.4.9

#### Forge version:

14.23.5.2831

#### Singleplayer or Multiplayer:

singleplayer

#### Installed mods:

All mods in https://minecraft.curseforge.com/projects/roguelike-adventures-and-dungeons/files/2720877 (version 1.2.6 of the modpack).
Note: Version 1.2.6 of the modpack includes version 3.4.6 of Betweenlands. But I first tried updating Betweenlands to version 3.4.9 to no avail. The problem remains exactly the same when running either 3.4.6 or 3.4.9 w/ this modpack.

#### How to reproduce:

1. Optifine installed with shaders set to OFF. And Betweenlands shaders set to On or OFF in its config from in-game.
2. Optifine installed with shaders set to internal. Betweenlands shaders set to  OFF in its in-game config.
3. Optifine installed with shaders set to internal. Betweenlands shaders set to  ON in its in-game config.

#### Expected result:

The game displays everything correctly.

#### Actual result:

1. When getting on a boat, the screen freezes on the last displayed contents right before right-clicking on the boat to get on it. I hear the game sounds normally as the game continues playing, but the screen is frozen until I get off the boat by clicking CTRL at which time the screen resumes displaying the game normally.

2. When getting on a boat the game renders the 3rd person mode correctly but when clicking Esc to display the GUI nothing is displayed even though I can still manage to click the GUI buttons if I know where to place the mouse. Only by clicking Esc again to return to the game does the screen resumes displaying the game correctly again.

3. NOTHING displays in the betweenland dimension. From the moment I try to enter the dimension from the portal the screen freezes on the last displayed content and is no longer updated even though the game continues playing normally w/ the screen frozen. I have to completely get out of Minecraft and back on in order to either set Optifine shaders to OFF OR the Betweenland shaders config option to false in order to play the game again.

**Comment by TheCyberBrick** [comment]
Hey,
I'm unable to reproduce 1. and 2. with OptiFine 1.12.2 HD U E3. The weedwood rowboat works fine in both cases for me. It's likely an incompatibility with another mod in that mod pack, in which case doing a binary search would probably be the best way to find out which combination causes the problem.
Problem 3. is known and the solution is to either completely disable OptiFine's shader or the Betweenlands shader. Can't have both active at the same time.

**Comment by DerangedLazyArtist** [comment]
This can be caused by having optifine's anti-aliasing on. Turning it off should fix the problem.
