### ISSUE TITLE
Bug with Optifine

### ISSUE THREAD

**Issue by terrybougard** [TheCyberBrick/The-Betweenlands#843]
#### Betweenlands version:

TheBetweenlands-3.4.9-universal.jar

#### Forge version:

forge 1.12.2-14.23.5.2784

#### Singleplayer or Multiplayer:

Multiplayer

#### Installed mods:

OptiFine_1.12.2_HD_U_E3.jar

#### How to reproduce:

1. Optifine shader were set to internal
2. and going in or spawning in the betweenlands

#### Expected result:

Normal screen size, as usual.
Note: Monitor Resolution is in 3440 x 1440

#### Actual result:

Screen becomes 1/4 of the original size and it is positioned on the lower left.
But when I go back to the original dimension overworld, screen is normal again.

**Comment by TheCyberBrick** [comment]
You need to either fully disable OptiFine's shaders (set to OFF), or disable the Betweenlands shaders (in the mod config). Can't have both enabled at the same time. Alternatively you can configure both mods such that there's always only one shader active per dimension.

**Comment by terrybougard** [comment]
hi! TheCyberBrick

I want to try to disable  betweenlands shader , is this the one?

B:dimension_shader_only=false
or  
B:use_shader=false

but actually they are all false by default.

thanks

**Comment by TheCyberBrick** [comment]
Hm, ok, that's strange. I don't have that problem with the same OptiFine version. And usually `use_shader` value is `true` by default, are you sure they are actually `false` and you're not looking at an unused copy of the file?

**Comment by terrybougard** [comment]
yes its all false by default.

**Comment by TheCyberBrick** [comment]
Hmm I'll need to do some further testing then, because it works fine for me with that OptiFine version on full HD. Need to find a way to run it at higher resolution :P  
What's your graphics card?

**Comment by terrybougard** [comment]
Geforce rtx 2060On Jun 22, 2019 6:37 PM, TheCyberBrick <notifications@github.com> wrote:Hmm I'll need to do some further testing then, because it works fine for me with that OptiFine version on full HD. Need to find a way to run it at higher resolution :P
What's your graphics card?
