### ISSUE TITLE
Client crash rowboat UnsupportedOperationException

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#846]
#### Betweenlands version:

3.4.8

#### Forge version:

2838

#### Singleplayer or Multiplayer:
Client on Multiplayer

#### Installed mods:
https://minecraft.curseforge.com/projects/ancient-towncraft/

## Link to full crash log
https://gist.github.com/ProsperCraft/3b7d8ecca6173992d06eec127ec4fa32

#### How to reproduce:

Client crash when clicking on a placed betweenlands boat.

**Comment by ProsperCraft** [comment]
Players are still reporting this happening.
https://paste.dimdev.org/goleyivuwi.mccrash

**Comment by TheCyberBrick** [comment]
@pau101 what do you reckon we should do here? Mostly regarding the boat type, the other methods could just return some arbitrary 0 value.

**Comment by pau101** [comment]
It finally happened, surprising it took this long. I'll work on it.

**Comment by TheCyberBrick** [comment]
Haha :P
Thanks!
