### ISSUE TITLE
Server crash - NPE - NBTTagCompound.setUniqueId

### ISSUE THREAD

**Issue by ProsperCraft** [TheCyberBrick/The-Betweenlands#847]
#### Betweenlands version:

TheBetweenlands-3.4.9-universal

#### Forge version:

forge-1.12.2-14.23.5.2838-universal.jar

#### Installed mods:
https://www.curseforge.com/minecraft/modpacks/drtardis-2-new-adventures

## Link to full crash log

1. I suspect this was due to me putting on the bark amulet from the spirit tree then looking at a tardis door.
2.
3. etc...

**Comment by TheCyberBrick** [comment]
Crash log?

**Comment by ProsperCraft** [comment]
Wow I must have been tired...

https://gist.github.com/ProsperCraft/0da5ffaf27d725aab56889380b205281

**Comment by TheCyberBrick** [comment]
Ah ok :P
Thanks
