### ISSUE TITLE
Client/Server Crash - All the mods + additions, WorldGenRubberTree

### ISSUE THREAD

**Issue by rgooch42** [TheCyberBrick/The-Betweenlands#848]
This looks to be a near-identical crash report to closed report https://github.com/Angry-Pixel/The-Betweenlands/issues/825. Primary error seems to be:

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)
Caused by: java.lang.IllegalAccessError
	at net.minecraft.util.math.BlockPos$MutableBlockPos.<init>(SourceFile:276)
	at net.minecraft.util.math.BlockPos$MutableBlockPos.<init>(SourceFile:267)
	at thebetweenlands.common.world.gen.feature.tree.WorldGenRubberTree.<init>(WorldGenRubberTree.java:18)
	at thebetweenlands.common.registries.BlockRegistry.<clinit>(BlockRegistry.java:305)
	at thebetweenlands.common.registries.Registries.preInit(Registries.java:11)
	at thebetweenlands.common.TheBetweenlands.preInit(TheBetweenlands.java:126)`

However, while I thought it might be an issue with Dynamic trees, https://github.com/Angry-Pixel/The-Betweenlands/issues/825 did not seem to have it. Searching has not resulted in a fix, though I did implement the ProjectRed update as indicated in the other active crash reports. No resolution.

Please let me know if there is anything else I can do to help resolve.

#### Singleplayer or Multiplayer:

Both

#### Installed mods:

https://paste.dimdev.org/oxetobuleg.rb

## Link to full crash log

https://paste.dimdev.org/ipefekizex.rb

#### How to reproduce:

1. Install listed mods
2. Run game, either on client launcher or server.
3. ...
4. No profits.

#### Expected result:

Client or Server Initialization

#### Actual result:

Crash

**Comment by rgooch42** [comment]
As I look at this, I'm starting to wonder if it's a Biomes a Plenty issue... Doing some more testing.

**Comment by rgooch42** [comment]
Nope, that's not it. If I remove it, I get worldgen issues from somewhere else. I'm hoping that if I/we can track this back, it will help someone else.

**Comment by GoryMoon** [comment]
It's an issue with FoamFix, follow the fix here https://github.com/asiekierka/FoamFix/issues/200

**Comment by rgooch42** [comment]
You are my hero. Thank you. Hopefully the next person who runs into this will get this page on google. Changing the config\foamfix.cfg file to read this way solved the problem:
`coremod {
    B:forceDisable=true
}`

This was NOT a Betweenlands issue. Sorry for the false alarm.
