### ISSUE TITLE
Crash while game is starting

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#856]
Crash Log: https://pastebin.com/GusyDAjf

#### Betweenlands version:
3.4.10

#### Forge version:
14.23.5.2838

Crashes when the game is starting up.

**Comment by GoryMoon** [comment]
You have mods that add to many potions, either remove some or install [JEID](https://www.curseforge.com/minecraft/mc-mods/jeid) to extend the number of potions you can have,
