### ISSUE TITLE
"Missing sound for event" "Starting up SoundSystem... Exception caught during firing event" Crash on Startup (2/7)

### ISSUE THREAD

**Issue by jacobmix** [TheCyberBrick/The-Betweenlands#859]
Starting up SoundSystem...
[18:28:02] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Post@3f02280d:
java.lang.NullPointerException: null
#### Betweenlands version:
TheBetweenlands-3.4.10-universal.jar

#### Forge version:
forge-14.23.5.2838

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
If the log below isn't good enough let me know.

## Link to full crash log
https://pastebin.com/hpjpZRiV
Another but they look the same: https://pastebin.com/HeukpgZD

#### How to reproduce:

1. Start Minecraft from the launcher (With the 350+ mods i got)
2. Wait a little bit.
3. Crash before it get's past "initializing mods phase 1" (2/7)

#### Expected result:
Able to load into game.

#### Actual result:
I crash.

**Comment by TheCyberBrick** [comment]
That's caused by FoamFix. See https://github.com/asiekierka/FoamFix/issues/200 for solution.
