### ISSUE TITLE
weedwood jukebox bug

### ISSUE THREAD

**Issue by Daejangnamu** [TheCyberBrick/The-Betweenlands#860]
#### Singleplayer or Multiplayer:
Multiplayer (Catserver core: https://github.com/CatServer/CatServer)

#### Installed mods:
OptiFine, journeymap, JEI, TheBetweenlands

## Link to full crash log
no crash

## Description of the problem

https://youtu.be/HBWbZq-DXsM

1.Put the record in the weedwood jukebox.
2.Even if you right-click, the record will not drop.
3.If you break the weedwood jukebox, it will play until the end of the music.

**Comment by Daejangnamu** [comment]
> ## Versions
> #### Betweenlands version: 3.4.9
> #### Forge version:14.23.5.2838
> #### Singleplayer or Multiplayer:
> Multiplayer
> 
> #### Installed mods:
> OptiFine, journeymap, JEI, TheBetweenlands
> 
> ## Link to full crash log
> no crash
> 
> ## Description of the problem
> #### How to reproduce:
> 1.Put the record in the weedwood jukebox.
> 2.Even if you right-click, the record will not drop.
> 3.If you break the weedwood jukebox, it will play until the end of the music.

**Comment by TheCyberBrick** [comment]
Thanks for reporting.
This does not happen with a regular "vanilla" forge server. Please report this to CatServer and link to this issue.
