### ISSUE TITLE
Radial Equipment Menu dupe

### ISSUE THREAD

**Issue by Daejangnamu** [TheCyberBrick/The-Betweenlands#861]
Betweenlands version: 3.4.9
Forge version:14.23.5.2838
Singleplayer or Multiplayer:
Multiplayer (Catserver core: https://github.com/CatServer/CatServer)

Installed mods:
OptiFine, journeymap, JEI, TheBetweenlands

Link to full crash log
no crash

Description of the problem
https://youtu.be/9f3OavVIVoQ

die wearing equipment, items will be replicated. (amulet, pouch, rings...)

**Comment by TheCyberBrick** [comment]
Thanks for reporting.
This does not happen with a regular "vanilla" forge server. Please report this to CatServer and link to this issue.
Here's what I think is going on: In the video you've linked it seems that after dying the selected hotbar slot is reset to what it was before death. That means that CatServer probably restores the player state to what it was *before* death (which includes equipment items!). This is not standard Forge behaviour and mods expect player data to be destroyed after death (which is the reason for the existence of <code>PlayerEvent.Clone</code> -> mods get the choice of restoring the lost data or not).
