### ISSUE TITLE
About TheBetweenlands items?

### ISSUE THREAD

**Issue by AntsandIce** [TheCyberBrick/The-Betweenlands#862]
TheBetweenlands Version3.4.9
Forge version:14.23.5.2838
Singleplayer or Multiplayer:
Multiplayer (Catserver core: https://github.com/CatServer/CatServer)

https://paste.ubuntu.com/p/Nw5vmd45vD/ This is the crash report.
About TheBetweenlands items? 
When players get around here, they Client break down.

**Comment by TheCyberBrick** [comment]
This development build contains the fix: https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases/tag/dev-1.12-fixes-2083-25.08.2019
