### ISSUE TITLE
[suggestion] Animated Tar beast heart can find Tar Pool

### ISSUE THREAD

**Issue by AntoineDada** [TheCyberBrick/The-Betweenlands#864]
The idea is pretty simple :The closer you get to a tar pool while holding a animated tar beast heart, the faster the heart will beat and the louder the sound will be.

It can be really nice for finding Underground Tar Dungeon

**Comment by PetasiGit** [comment]
Old issue, but since 3.7.0, wights transform into tar beasts when they touch tar, so it’s significantly easier to farm tar items. With that said, I’m going to close this as I assume that’s kinda the idea with locating tar pool dungeons to make a farm.
