### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by Waffleshanker** [TheCyberBrick/The-Betweenlands#865]
Versions
Betweenlands version:
The Betweenlands-3.4.10 (1.12.2)

Forge version:
Forge 1.12.2-14.23.5.2838

Singleplayer or Multiplayer:
Singleplayer

Installed mods:
In crash log

Link to full crash log
https://paste.dimdev.org/zuzirusegi.mccrash

Description of the problem
How to reproduce:
Startup game

Expected result:
Game startup

Actual result:
Crashes

Pictures:
None

**Comment by GoryMoon** [comment]
You are out of ids, either remove some mods or use a mod like https://www.curseforge.com/minecraft/mc-mods/jeid
