### ISSUE TITLE
Crash when crafting symorite bucket

### ISSUE THREAD

**Issue by LuciaCHuygens** [TheCyberBrick/The-Betweenlands#866]
Hello,

for me the game crashes as soon as I try to craft a symorite bucket in a weedwood crafting table.
Edit: It also happens with the vanilla crafting table.

#### Betweenlands version:
TheBetweenlands-3.4.9-universal.jar

#### Forge version:
14.23.5.2838

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
https://pastebin.com/6C4gXMwU (whole list)

It is this modpack: https://www.curseforge.com/minecraft/modpacks/attack-of-the-s-team
I added: 
+ UndergroundBiomes
+ Streams (+ Farseek)
+ Better Foliage
+ AE2
+ Fast leaf decay
+ Embersified
+ Mystical Mechanics (Addon for Embers)
+ Redwoods (Fir trees + Redwood from ExtrabiomesXL)
+ Waystones
+ OptiFine
+ EmberRoot Zoo

I removed: Netherportalfix

## Link to full crash log
https://pastebin.com/dT7vrVzL

#### How to reproduce:
1. Go to the Betweenlands
2. Make a weedwood crafting table
3. Try crafting a symorite bucket in the weedwood crafting table

#### Expected result:
Getting a symorite bucket without crashing the game.

#### Actual result:
Loading screen of death + crash after a few seconds.

**Comment by GoryMoon** [comment]
This seems to be an issue on [Stupid Things](https://www.curseforge.com/minecraft/mc-mods/stupid-things) end.
The return value of `Universalbucket.getFluid(ItemStack container)` is nullable which means that they can return null, a null check is needed in their code.
