### ISSUE TITLE
Weedwood bow incompatible with Roots 3 Quiver

### ISSUE THREAD

**Issue by SeriousCreeper** [TheCyberBrick/The-Betweenlands#867]
#### Betweenlands version: 
3.4.10

#### Forge version:
14.23.5.2838

#### Singleplayer or Multiplayer:
Only tested in Singleplayer so far

#### Installed mods:
Roots 3.0.7
Full Modlist: https://pastebin.com/EPjf35kU

#### How to reproduce:
The Roots 3 quiver can store several stacks of arrows that are being used while shooting a bow. 
However, if you use the betweenlands bow, after shooting once, the quiver gets deleted. According to nooby who is working on Roots 3, it's because the quiver is marked as infinite, which may not get checked by the weedwood bow itself? 

I tried it with other modded bows and so far they all seem to work properly.

#### Expected result:
Shooting the weedwood bow using a roots 3 quiver should just reduce the arrow amount inside the quiver, not delete the quiver.

#### Pictures:
Video of it happening during a stream (when i say "your quiver/bow", im refering to the roots stuff, as the roots 3 dev was in chat at that time) https://clips.twitch.tv/InspiringSmellyGoshawkDBstyle

**Comment by TheCyberBrick** [comment]
v3.4.12 has the fix for this
