### ISSUE TITLE
Compatible with Biome Bundle?

### ISSUE THREAD

**Issue by thedahminator** [TheCyberBrick/The-Betweenlands#869]
This is more of a question. I can not find the alter to get the items required to access the betweenlands. Does biome bundle stop the generation of the  between land alter or just harder to find

**Comment by TheCyberBrick** [comment]
The druid circle generates in any overworld biome that is tagged as "swamp". If biome bundle properly tags their swamp biomes as such then it should generate (if there's enough space).  
If you have trouble finding the druid circles you can try to increase their spawn rates by **lowering** the "Frequency of Druid Circles" number in the Betweenlands config,
