### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to register dimension for id 20, One is already registered

### ISSUE THREAD

**Issue by SomeCurlyHelper** [TheCyberBrick/The-Betweenlands#871]
So I've tried to change the ids of it and nothing changed

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2019-08-28 14:56:08 NZST
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 20, One is already registered
    at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
    at thebetweenlands.common.TheBetweenlands.preInit(TheBetweenlands.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 275992952 bytes (263 MB) / 1073741824 bytes (1024 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 146 mods loaded, 146 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version                  | Source                                             | Signature                                |
       |:----- |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCH   | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
       | LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
       | LCH   | LambdaLib|Core       | 0.1.7                    | minecraft.jar                                      | None                                     |
       | LCH   | micdoodlecore        |                          | minecraft.jar                                      | None                                     |
       | LCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCH   | dimensions1122       | 1.12.2                   | 101+Dimensions+(1.12.2)+(3).jar                    | None                                     |
       | LCH   | deconstruction       | 3.0.4                    | [MC1.12.2]DeconTable-3.0.4.jar                     | None                                     |
       | LCH   | abilstones           | 12.2.0.1                 | Ability.Stones.12.2.0.1.jar                        | None                                     |
       | LCH   | lambdalib2           | 0.1.7                    | LambdaLib-1.12.2.jar                               | None                                     |
       | LCH   | academy              | 1.1.0                    | AcademyCraft-Mod-1.12.2.jar                        | None                                     |
       | LCH   | actuallyadditions    | 1.12.2-r149              | ActuallyAdditions-1.12.2-r149.jar                  | None                                     |
       | LCH   | aether_legacy        | 1.12.2-v1.4.1            | Aether-Legacy-Mod-1.12.2.jar                       | None                                     |
       | LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCH   | jei                  | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                          | None                                     |
       | LCH   | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | LCH   | botania              | r1.10-360                | Botania-Mod-1.12.2.jar                             | None                                     |
       | LCH   | craftstudioapi       | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCH   | harvestcraft         | 1.12.2zb                 | HarvestCraft-Mod-1.12.2.jar                        | None                                     |
       | LCH   | twilightforest       | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar        | None                                     |
       | LCH   | animania             | 1.6.2                    | animania-1.12.2-1.6.2.jar                          | None                                     |
       | LCH   | antiqueatlas         | 4.5.1                    | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCH   | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCH   | placebo              | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
       | LCH   | apotheosis           | 1.10.3                   | Apotheosis-1.12.2-1.10.3.jar                       | None                                     |
       | LCH   | appliedenergistics2  | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCH   | artifacts            | 1.12.2-1.1.0             | Artifacts-1.12.2-1.1.0.jar                         | None                                     |
       | LCH   | autonetworklib       | 1.0.35                   | Auto-Network-Lib-1.12.2.jar                        | None                                     |
       | LCH   | autoreglib           | 1.3-26                   | AutoRegLib-1.3-26.jar                              | None                                     |
       | LCH   | backpack             | 3.0.2                    | Backpacks-Mod-1.12.2.jar                           | None                                     |
       | LCH   | mcmultipart          | 2.5.2                    | MCMultiPart-2.5.2.jar                              | None                                     |
       | LCH   | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | sonarcore            | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                     | None                                     |
       | LCH   | bagelsmore           | 2.0.1                    | bagelsmore-1.12.2-2.0.1.jar                        | None                                     |
       | LCH   | overlord             | 2.4.14                   | Overlord-Mod-1.12.2.jar                            | None                                     |
       | LCH   | guideapi             | 1.12-2.1.8-63            | Guide-API-1.12.2.jar                               | None                                     |
       | LCH   | bloodmagic           | 1.12.2-2.3.2-100         | Blood-Magic-Mod-1.12.2.jar                         | None                                     |
       | LCH   | bookshelf            | 2.3.585                  | Bookshelf-1.12.2.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | controlling          | 3.0.7                    | Controlling-3.0.7.jar                              | None                                     |
       | LCH   | corpse               | 1.12.2-1.0.0             | Corpse-Mod-1.12.2.jar                              | None                                     |
       | LCH   | cxlibrary            | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                         | None                                     |
       | LCH   | cyclopscore          | 1.4.0                    | CyclopsCore-1.12.2-1.4.0.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCH   | darkutils            | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | dmonsters            | 1.7                      | Deadly-Monsters-Mod-1.12.2.jar                     | None                                     |
       | LCH   | dmcweapons           | 1.0.7                    | Devil-May-Cry-Weapons-Mod-1.12.2.jar               | None                                     |
       | LCH   | dimdoors             | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                     | None                                     |
       | LCH   | patchouli            | 1.0-19                   | Patchouli-Mod-1.12.2.jar                           | None                                     |
       | LCH   | divinefavor          | 1.0.533                  | Divine-Favor-Mod-1.12.2.jar                        | None                                     |
       | LCH   | dldungeonsjbg        | 1.12.9                   | DoomlikeDungeons-1.12.9-MC1.12.2.jar               | None                                     |
       | LCH   | gottschcore          | 1.8.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.8.0.jar      | None                                     |
       | LCH   | dungeons2            | 1.7.1                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar        | None                                     |
       | LCH   | eleccore             | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                        | None                                     |
       | LCH   | ebwizardry           | 4.1.4                    | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar     | None                                     |
       | LCH   | everlastingabilities | 1.5.1                    | Everlasting Abilities Mod 1.12.2.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | forgelin             | 1.8.2                    | Shadowfacts-Forgelin-1.12.2.jar                    | None                                     |
       | LCH   | mantle               | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                           | None                                     |
       | LCH   | tconstruct           | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                   | None                                     |
       | LCH   | exnihilocreatio      | 1.12.2-0.4.5             | exnihilocreatio-1.12.2-0.4.5.jar                   | None                                     |
       | LCH   | extrautils2          | 1.0                      | Extra-Utilities-Mod-1.12.2.jar                     | None                                     |
       | LCH   | extra_spells         | 1.0.7                    | ExtraSpells-1.12.2-1.0.7.jar                       | None                                     |
       | LCH   | eyesinthedarkness    | 0.0.5                    | EyesInTheDarkness-0.0.5.jar                        | None                                     |
       | LCH   | fakeores             | 1.9.1                    | Fake-Ores-2-Mod-1.12.2.jar                         | None                                     |
       | LCH   | familiarfauna        | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
       | LCH   | fastladder           | 1.1.1                    | FastLadder-mc1.12.2-f14.23.5.2768-v1.1.1.jar       | None                                     |
       | LCH   | firstaid             | 1.6.7                    | First-Aid-Mod-1.12.2.jar                           | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LCH   | foamfix              | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | LCH   | forbidden_arcanus    | 1.12.2-1.1.3             | Forbidden-Arcanus-Mod-1.12.2.jar                   | None                                     |
       | LCH   | galacticraftcore     | 4.0.2.233                | GalacticraftCore-1.12.2-4.0.2.233.jar              | None                                     |
       | LCH   | generaldisasters     | 1.0                      | generaldisasters-1.0.jar                           | None                                     |
       | LCH   | globe                | 0.0.1                    | Globe-1.12.2-0.0.1.jar                             | None                                     |
       | LCH   | grapplemod           | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                        | None                                     |
       | LCH   | ichunutil            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | gravitygun           | 7.0.0                    | Gravity-Gun-Mod-1.12.2.jar                         | None                                     |
       | LCH   | guilttrip            | 7.0.0                    | Guilt-Trip-Mod-1.12.2.jar                          | None                                     |
       | LCH   | hammercore           | 2.0.4.8                  | HammerCore-1.12.2-2.0.4.8.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | huds                 | #VERSION#                | Huds-1.12.2-1.0.3.jar                              | None                                     |
       | LCH   | icbmclassic          | 1.12.2-3.3.0.63          | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
       | LCH   | infernalmobs         | 1.7.6                    | Infernal-Mobs-Mod-1.12.2.jar                       | None                                     |
       | LCH   | inventorytweaks      | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | inventorypets        | 2.0.2                    | inventorypets-1.12-2.0.2.jar                       | None                                     |
       | LCH   | ironchest            | 1.12.2-7.0.67.844        | Iron-Chests-Mod-1.12.2.jar                         | None                                     |
       | LCH   | jjraces              | 1.0.7                    | JJ-Races-Mod-1.12.2.jar                            | None                                     |
       | LCH   | shadowmc             | 3.8.0                    | ShadowMC-1.12.jar                                  | None                                     |
       | LCH   | leveluphp            | 1.12.2-1.4.0             | Level-Up-HP-Mod-1.12.2.jar                         | None                                     |
       | LCH   | levelup2             | ${version}               | Level-Up-Mod-1.12.2.jar                            | None                                     |
       | LCH   | librarianlib         | 4.17                     | LibrarianLib-1.12.2.jar                            | None                                     |
       | LCH   | lsc                  | 0.6.1.0-alpha            | Loot-Slash-Conquer-Mod-1.12.2.jar                  | None                                     |
       | LCH   | lootbags             | 2.5.8.5                  | LootBags-Mod-1.12.2.jar                            | None                                     |
       | LCH   | lucky                | 7.5.0                    | Lucky-Block-Mod-1.12.zip                           | None                                     |
       | LCH   | speedsterheroes      | 1.12.2-2.1.4             | SpeedsterHeroes-1.12.2-2.1.4.jar                   | None                                     |
       | LCH   | lucraftcore          | 1.12.2-2.4.6             | LucraftCore-1.12.2-2.4.6.jar                       | None                                     |
       | LCH   | lycanitesmobs        | 2.0.0.3 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.0.3.jar                   | None                                     |
       | LCH   | magicarsenal         | MC1.12_ver1.2.5          | MagicArsenal-MC1.12_ver1.2.5.jar                   | None                                     |
       | LCH   | mcjtylib_ng          | 3.5.3                    | McJtyLib-1.12.2.jar                                | None                                     |
       | LCH   | sgs_metals           | 3.0.3                    | Metals-mc1.12.2-f14.23.5.2768-v3.0.3.jar           | None                                     |
       | LCH   | millenaire           | Millénaire 7.2.1         | millenaire-1.12.2-7.2.1.jar                        | None                                     |
       | LCH   | mobends              | 0.24                     | mobends-0.24_for_MC-1.12.jar                       | None                                     |
       | LCH   | extracreatures       | 1.0.3b                   | More-Creatures-Mod-1.12.2.jar                      | None                                     |
       | LCH   | morefurnaces         | 1.10.5                   | More-Furnaces-Mod-1.12.2.jar                       | None                                     |
       | LCH   | msmlegacy            | @VERSION@                | More-Swords-Legacy-Mod-1.12.2.jar                  | None                                     |
       | LCH   | mousetweaks          | 2.9                      | Mouse-Tweaks-Mod-1.12.2.jar                        | None                                     |
       | LCH   | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | mowziesmobs          | 1.5.3                    | Mowzies-Mobs-Mod-1.12.2.jar                        | None                                     |
       | LCH   | mutantmobs           | 1.0.0                    | Mutant-Mobs-Mod-1.12.2.jar                         | None                                     |
       | LCH   | orecore              | 1.4.1                    | Ore-Core-Mod-1.12.2.jar                            | None                                     |
       | LCH   | oreexcavation        | 1.4.137                  | Ore-Excavation-Mod-1.12.2.jar                      | None                                     |
       | LCH   | pattysmoretools      | 1.12.2-1.7               | PattysMoreTools-2-Mod-1.12.2.jar                   | None                                     |
       | LCH   | placeableitems       | 3.3                      | placeableitems-3.3.jar                             | None                                     |
       | LCH   | portality            | 1.0-SNAPSHOT             | Portality-Mod-1.12.2.jar                           | None                                     |
       | LCH   | projecte             | 1.12.2-PE1.4.0           | ProjectE-Mod-1.12.2.jar                            | None                                     |
       | LCH   | psi                  | r1.1-72                  | Psi-Mod-1.12.2.jar                                 | None                                     |
       | LCH   | pymtech              | 1.12.2-1.0.2             | PymTech-1.12.2-1.0.2.jar                           | None                                     |
       | LCH   | reccomplex           | 1.4.8.1                  | RecurrentComplex-1.4.8.1.jar                       | None                                     |
       | LCH   | roguelike            | 1.8.0                    | Roguelike-Dungeons-Mod-1.12.2.jar                  | None                                     |
       | LCH   | ruins                | 17.2                     | Ruins-Mod-1.12.2.jar                               | None                                     |
       | LCH   | silentlib            | 3.0.13                   | Silent-Lib-1.12.2.jar                              | None                                     |
       | LCH   | scalinghealth        | 1.3.37                   | Scaling-Health-Mod-1.12.2.jar                      | None                                     |
       | LCH   | shadowlegacy         | 1.0.0                    | Shadow-Legacy-Mod-1.12.2.jar                       | None                                     |
       | LCH   | somanyenchantments   | 0.4.3                    | So-Many-Enchantments-Mod-1.12.2.jar                | None                                     |
       | LCH   | tammodized           | 0.15.6                   | TamModized-1.12.2.jar                              | None                                     |
       | LCH   | thaumicjei           | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                     | None                                     |
       | LCH   | thaumicenergistics   | 2.2.2                    | thaumicenergistics-2.2.2.jar                       | None                                     |
       | LCH   | thaumicequivalence   | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar                | None                                     |
       | LCH   | thaumicperiphery     | 0.3.1                    | thaumicperiphery-0.3.1.jar                         | None                                     |
       | LCH   | theoneprobe          | 1.4.28                   | The-One-Probe-Mod-1.12.2.jar                       | None                                     |
       | LCH   | tinkersarsenal       | 0.5                      | tinkersarsenal-0.5.jar                             | None                                     |
       | LCH   | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | LCH   | treasure2            | 1.5.1                    | Treasure2-mc1.12.2-f14.23.5.2768-v1.5.1.jar        | None                                     |
       | LCH   | xat                  | 0.17                     | Trinkets-and-Baubles-Mod-1.12.2.jar                | None                                     |
       | LCH   | unforgivingvoid      | 1.0.2                    | Unforgiving-Void-Mod-1.12.2.jar                    | None                                     |
       | LCH   | vanillafix           | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCH   | visuals              | 7r                       | Visuals-1.12.2-7r.jar                              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | voidcraft            | 0.26.10                  | VoidCraft-Mod-1.12.2.jar                           | None                                     |
       | LCH   | worleycaves          | 1.4.1                    | worleycaves-1.4.1.jar                              | None                                     |
       | LCH   | wowweapons           | 0.0.4                    | WoW-Weapons-Mod-1.12.2.jar                         | None                                     |
       | LCH   | xaerominimap         | 1.16.3                   | Xaeros-Minimap-Mod-1.12.jar                        | None                                     |
       | LCH   | zaraklib             | 0.0.4                    | ZarakLib-1.12.2.jar                                | None                                     |
       | LCH   | jurassicraft         | 2.1.23                   | JurassiCraft-1.12.2-2.1.23.jar                     | None                                     |
       | LCH   | snowrealmagic        | 0.3.2                    | SnowRealMagic-0.3.2.jar                            | None                                     |
       | LCE   | thebetweenlands      | 3.4.7                    | TheBetweenlands-3.4.7-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LC    | weeping-angels       | 1.12.2-37                | weeping-angels-37.jar                              | None                                     |
       | LC    | eleccoreloader       | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                        | None                                     |
       | LC    | librarianliblate     | 4.17                     | LibrarianLib-1.12.2.jar                            | None                                     |
  Loaded coremods (and transformers): MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      CorePlugin (LambdaLib-1.12.2.jar)
                                        cn.lambdalib2.render.mc.PipelineTransformer
                                        cn.lambdalib2.registry.impl.RegistryTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      HCASM (HammerCore-1.12.2-2.0.4.8.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Snow! Real Magic! Core Mod (SnowRealMagic-0.3.2-coremod.jar)
                                        snownee.snow.asm.ASMTransformer
                                      ApotheosisCore (Apotheosis-1.12.2-1.10.3.jar)
                                        shadows.ApotheosisTransformer
                                      Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.6.jar)
                                        lucraft.mods.lucraftcore.core.LCTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      pymtech (PymTech-1.12.2-1.0.2.jar)
                                        lucraft.mods.pymtech.core.PymTechClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      LibrarianLib Plugin (LibrarianLib-1.12.2.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.7-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11020.2003' Renderer: 'Radeon RX 570 Series'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 386 names; 456 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Visuals (visuals) @7r
  Suspected Mods: The Betweenlands (thebetweenlands)

**Comment by SomeCurlyHelper** [comment]
I've tried deleting the configs, I've also tried to change the Ids but nothing changed at all. Can someone please help

**Comment by TheCyberBrick** [comment]
Please update to the latest version (currently v3.4.11) and try again. Setting the dimension ID works fine for me.
