### ISSUE TITLE
[1.12.2] 'tar' conflict with 'Fossils Archeology Revival'.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#872]
Refer'd Issue:
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1281

Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 4
fossilsarcheology-8.0.2
jei_1.12.2-4.15.0.279
llibrary-1.7.17-1.12.2
TheBetweenlands-3.4.11-universal

-----

A bit of a conflict occurs with the 'tar' due to both mods having the same fluidname: 'tar'. Fossils Archeology overwrites the Betweenlands Tar as seen in this image.
![](https://cdn.discordapp.com/attachments/377171551155650560/616357933839679518/tarconflict1.PNG)

If I remove Fossils Archeology, the Betweenlands Tar returns, perhaps due to having the same fluidname.
![](https://cdn.discordapp.com/attachments/377171551155650560/616358268096217128/tarconlict2.PNG)

-----

Since the Betweenlands mod is like a swamp-like theme. I wonder if altering the fluidname to 'swamptar' could be a suggestion so both mods could be compatible. Unless it could cause stuff to break or something.

**Comment by TheCyberBrick** [comment]
That's expected behaviour. If multiple fluids with the same name exist then Forge picks one and uses only that one for the world.

**Comment by SonicX8000** [comment]
I'm aware of the fluidnames but the tar between the two mods are different with how they work.

Fossils' Tar spawns in Tar Slimes while I think Betweenlands Tar spawns in Tar Beasts. They also have different 'swim' properties if one happened to fall into them.

Unless both mobs can spawn from the same fluidname or something... I've only noticed Tar Slimes so far.

**Comment by TheCyberBrick** [comment]
Ah, I assumed the Tar Beasts would spawn normally because the issue you linked to states that spawning still works:
> So far, it does not seem to cause any issues with tar beast spawning (when generating chunks), or tar jar spawning. But it does alter the physics so it matches Fossils tar instead of betweenlands, which is an issue for players fighting tar beasts.

Are you sure they actually do not spawn?

**Comment by SonicX8000** [comment]
Trying to find a Sludge Plains Biome just to see if they spawn or not. I did find a pool of tar which I think is in a Swamplands Biome.

Some notes, the tar that spawns in the Betweenlands Dimension will have "Betweenlands" physics, meaning you can sorta 'swim' in it and if you go under... you suffer damage.

If you pick the Betweenlands tar with a bucket and place it down... the Tar that gets placed is converted to "Fossils" physics where it acts like quicksand and you can barely move in it, you're able unable to 'swim' in it to escape from it so it's pretty much a deathtrap if you have no means of escape.

They both have the same texture but their physics are different.

*EDIT*
Found a Sludge Plains Biome along with a tar pool, currently waiting at the pool to see if any Tar Beasts spawn. If I may ask... how often would they spawn?

*EDIT 2*
Been waiting for few minutes, haven't seen any of them spawn yet.

**Comment by SonicX8000** [comment]
I see that Betweenlands got an update. 

"TheBetweenlands-3.5.0-universal"

The conflict still occurs between the two mods and I think Tar Beast spawning is still not occurring although I'll have to wait a few minutes at the tar pools in Betweenlands to confirm that.

The only time I've seen Tar Beasts spawn is in those Tar Pools hidden in the underground caves within the Betweenlands Dimension however those come from a mob spawner crystal buried within the tar.

**Comment by TheCyberBrick** [comment]
If the spawning doesn't work then I definitely need to fix it if it doesn't work at all. However since it's working fine with the spawners I'd expect it to also work as regular spawns. They're quite rare though and the player needs to be at least 24 blocks away for mobs to spawn.

**Comment by TheCyberBrick** [comment]
I've just generated a new world (with F&A) and Tar Beasts are spawning properly.
The world generated tar **block** is actually still Betweenlands tar so spawning works as it should and the movement is also the same as BL tar, just the appearance is different (because it is dictated by the fluid). Tar placed by buckets however will be F&A tar.

**Comment by SonicX8000** [comment]
Ah, you had to be a couple blocks away for them to spawn... that would be why I didn't get any of them to spawn naturally.

**Comment by TheCyberBrick** [comment]
; )
Regardless of that they're still quite rare so it can take a while for them to spawn
