### ISSUE TITLE
Datawatcher incompatibility "EntityFortressBoss"

### ISSUE THREAD

**Issue by PT400C** [TheCyberBrick/The-Betweenlands#873]
Hey,

this seems to be a datawatcher having issues with an other mod's datawatcher. Afaik the names of these should be unique and so they might interfere - eventually crash due to an incompatible type and an equal name.

https://pastebin.com/hEdtRHd3

**Comment by TheCyberBrick** [comment]
This seems to be caused by MoCreatures and CustomMobSpawner. I've reported it to the author's issue tracker a while ago but it wasn't addressed yet unfortunately.
