### ISSUE TITLE
[Suggestion] Config option for Decay and Corrosion in other dimensions

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheCyberBrick/The-Betweenlands#877]
I'm a cruel person when it comes to modpacks, and something I'd love to work with is the option to enable player decay and tool corrosion in other dimensions.
That's it. Thanks!

**Comment by UnlimatedStone9** [comment]
Additionally, if possible an option for what items/foods can be eaten to combat decay, like sap, I think that could be useful alongside this.

**Comment by MikeDB-wtf** [comment]
Nasty idea. I'm adding my vote to support "Exporting" these mechanics.

**Comment by UnlimatedStone9** [comment]
Why thank you @AlexaDTink, It's something I've wanted for a while for my own modpacks, hopefully it can be integrated at some point.

**Comment by TheCyberBrick** [comment]
Should be simple for decay. For corrosion of BL tools in other dimensions too, but we can't make other non-BL tools corrode.

**Comment by UnlimatedStone9** [comment]
Non Betweenlands tools can't corrode in other dimensions or at all?

**Comment by TheCyberBrick** [comment]
Done.

> Non Betweenlands tools can't corrode in other dimensions or at all?

At all
