### ISSUE TITLE
Wight and Shallowbreath Kind of Break Performance

### ISSUE THREAD

**Issue by PiordaNautor** [TheCyberBrick/The-Betweenlands#880]
Versions
TheBetweenlands-3.4.11-universal.jar
forge-14.23.5.2847
Singleplayer

Installed mods:
https://pastebin.com/GrMDsL00

Description:
Looking at a Wight or Shallowbreath severely decreases framerate, despite some attempts to lower the graphic settings.
How to reproduce:
Simply spawn a Wight or Shallowbreath

Expected result:
Usual framerate performance.
Actual result:
Lots of lag.

**Comment by TheCyberBrick** [comment]
"Lots of lag" is relative. Please post two pictures of the F3 debug screen ingame, one before lag and one after.  
It's expected that the shader effects used by Wights and Shallowbreaths have *some* impact on performance, especially with graphics cards that have low bandwidth.  
I plan on redoing the shaders at some point to improve performance, but the priority for that is rather low.

**Comment by PiordaNautor** [comment]
I initially wrote down that the gist phrase "Lots of lag" was a severe decrease in framerate. Although I have alleviated it by adding more RAM to my game, the loss of frames is still enough of a nuisance.

![frametest](https://user-images.githubusercontent.com/55087535/64916069-96cb1280-d72a-11e9-8714-e68dee3aff0f.png)
![frametest2](https://user-images.githubusercontent.com/55087535/64916070-9a5e9980-d72a-11e9-83c2-51457b1c1e1d.png)

Sorry for the delay.

**Comment by TheCyberBrick** [comment]
No worries, thanks.
The reason it tanks your performance so much is that your game is running on an Intel integrated graphics card which is quite weak when it comes to shaders.  
If you have a dedicated graphics card you need to make minecraft use it. For an nvidia card see: https://www.minecraftforum.net/forums/support/java-edition-support/2902923-optifine-uses-integrated-graphics-instead-of.  
If you don't have a dedicated grpahics card you should just disable the shaders in the Betweenlands config, that should also fix the performance drop, but you won't see some of the fancy effects anymore
