### ISSUE TITLE
Tamed Spirit Tree Names Disappear on Relog (Singleplayer)

### ISSUE THREAD

**Issue by 9RFCat9** [TheCyberBrick/The-Betweenlands#884]
#144  Versions
#### Betweenlands version:

3.4.11

#### Forge version:

release 1.12.2-forge1.12.2-14.23.5.2768

#### Singleplayer or Multiplayer:

Singelplayer

#### Installed mods:

AppleSkin-mc1.12-1.0.9
jei_1.12.2-4.15.0.268
keywizard-1.12.2-1.5.6
OptiFine_1.12.2_HD_U_E2
TheBetweenlands-4.4.11-universal
ToroCrafts-Damage-Indicators-Mod-1.12.2
TUMAT-1.12.x-1.12.0

## Description of the problem
I was making a test base in Creative to get used to this mod, its recipes, etc. and I wanted to see if you can name Tamed Spirit Trees (The ones you grow from saplings.) I used a renamed Nametag on the face entity and it worked, even when the face moved to a different part of the tree. However, when I quit my game and re-opened the world, the face's name had disappeared.
#### How to reproduce:

1. Start a new Creative world with default world generation, structures and cheats on (not sure if this makes a difference, but want to be thorough so that's what I did)
2. Spawn in a Spirit Tree using a sapling and Ground Dried Swamp Reed.
3. Rename a Nametag in an anvil (My tree was named Irontwig)
4. Apply the Nametag to the Tamed Spirit Tree Face.
5. Exit the game and quit from Minecraft.
6. Open the launcher again and re-open Minecraft.
7. Log into the Creative world again.

#### Expected result:

I expected to log back in and find nothing changed.

#### Actual result:

The tree's face when I looked at it with my damage indicator mod said "Tamed Spirit Tree Face" and the tag above it had vanished. I had no idea relogging could even do this, please fix as soon as you have time.

**Comment by TheCyberBrick** [comment]
I can't reproduce this, seems to work reliably for me. Have you tried without the other mods installed to rule out that it's a mod incompatibility issue?
