### ISSUE TITLE
[1.12.2] Ring of Power oddity.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#885]
Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 1
TheBetweenlands-3.4.11-universal

-----

Unsure if intended but it seems that any Unbreaking Enchantments won't work on the Ring of Power. For a test I equipped two Rings of Power but one of them has an "Unbreaking III" enchantment and let them sit for awhile. Here's what the durability shows...

Note: *I tried to equip/unequip them at the same time.*

No Enchantment
1530 / 1800

Unbreaking III
1529 / 1800

This also occurs with the Ring of Summoning but not the Ring of Ascent & Recruitment since they use XP directly, unless they automatically drain your XP to keep the Ring charged or something.

Certain other items like the Item Magnet & Bark Amulet the Unbreaking Enchantment does appear to work with those.

-----

One more thing to mention is that if the Ring of Power reaches 0 durability and they're still equipped... they still apply the damage boost. Some tests using a Diamond Sword on Cyclic's Target Dummy with Damage Indicators...

2x Ring of Power with Durability
14 Damage

2x Ring of Power with NO Durability
14 Damage

**Comment by TheCyberBrick** [comment]
> One more thing to mention is that if the Ring of Power reaches 0 durability and they're still equipped... they still apply the damage boost.

Huh, you're right. That's quite an oversight, thanks :P

> Unsure if intended but it seems that any Unbreaking Enchantments won't work on the Ring of Power.

That's intentional. The item isn't really damaged, the bar is just used as a means of showing how much charge is left.

**Comment by SonicX8000** [comment]
Ah, would it be possible to have the Ring of Power charges become used as you damage mobs instead of the charges draining just for being equipped? The charges & repair costs could be changed for balancing reasons.

No, it's not because I forget to unequip the ring or something, nope.

**Comment by TheCyberBrick** [comment]
Hm yeah, maybe

**Comment by TheCyberBrick** [comment]
After thinking about it some more I think that it's ok that it constantly uses XP when equipped since it's such a powerful item. However the ring now also gives the player a slight speed boost when worn to better reflect that the ring is always active (i.e. is just giving the player a general boost in strength, including mobility)
