### ISSUE TITLE
Suggestion: Undead ghouls or zombies should attack villagers

### ISSUE THREAD

**Issue by kihgy** [TheCyberBrick/The-Betweenlands#887]
Any ghouls or zombies in the Betweenlands should attack villagers, like vanilla zombies

**Comment by TheCyberBrick** [comment]
But... we don't have any ghouls, nor any villagers in the dimension :P
Do you mean mobs like the Swamp Hag should attack regular vanilla villagers? (If so, why? They don't ever naturally meet)

**Comment by MikeDB-wtf** [comment]
I somewhat agree on the grounds that zombies hate where they [might have] come from and swamp hags are the closest betweenlands equivalent. It falls apart a bit when you consider that zombies did not come from villagers but ... whatever ...

They *could* retain some kind of hate if you consider them to be a reborn undead but I'm not seeing the lore for that. On the other hand, why should villagers (and not players) be safe in a corrupted dimension? Much like an immune system, perhaps swamp hags should attack anything "unusual"? Thereby providing a consistent mechanic.

**Comment by theishiopian** [comment]
If you just want a swamp hag mob that attacks villagers, you can make one with customNPCS.

**Comment by PetasiGit** [comment]
Closing, these mobs never naturally meet, as Cyber said.
