### ISSUE TITLE
Game gets stuck when entering the BL

### ISSUE THREAD

**Issue by Shattered2909** [TheCyberBrick/The-Betweenlands#889]
#### Betweenlands version:

v3.4.12 (Minecraft 1.12.2)

#### Forge version:

forge-14.23.5.2838

#### Singleplayer or Multiplayer:

Singleplayer

## Link to full crash log

text file attached

#### How to reproduce:

Whenever I enter the Betweenlands, it gets completely stuck, the log keeps telling me this:
[10:13:36] [Server thread/WARN]: The Betweenlands loaded a new chunk [-125, -95] in dimension 20 (betweenlands) while populating chunk [-124, -94], causing cascading worldgen lag.
[10:13:36] [Server thread/WARN]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

#### Expected result:

Should load properly but doesnt...

#### Pictures:

[mods.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/3680090/mods.txt)

![2019-10-02_10 18 17](https://user-images.githubusercontent.com/35029480/66028748-04828700-e4fe-11e9-9875-788d495a6d69.png)

**Comment by TheCyberBrick** [comment]
Probably this: https://github.com/Angry-Pixel/The-Betweenlands/issues/527. Please try the workaround in the linked issue (blacklisting mobs in Epic Siege etc)

**Comment by Shattered2909** [comment]
Ohhh I thought the issue was fixed completely... will try the workaround in a bit, then say what happened!

**Comment by Shattered2909** [comment]
Where do I get the names of all these mobs?

**Comment by Shattered2909** [comment]
Maybe it is better to remove ESM. At least for now.

**Comment by TheCyberBrick** [comment]
The report on ESM's issue tracker wasn't closed and there are similar other reports there unrelated to BL that are still open, so I'd assume it hasn't been fixed yet.  
You can use commands to get a list of entity names. Type `/summon thebetweenlands:` and then autocomplete with TAB, that should list all BL entities.
