### ISSUE TITLE
ID Conflict despite NotEnoughIds

### ISSUE THREAD

**Issue by EightBlade** [TheCyberBrick/The-Betweenlands#892]
#### Betweenlands version:
3.4.12

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
See crash log.

## Link to full crash log
https://paste.dimdev.org/ladejadizu.mccrash

## Description of the problem
Start the game and get a crash while Forge loads.

#### Expected result:
The game to run.

#### Actual result:
See above.

**Comment by pau101** [comment]
Thanks for reporting!

Unfortunately, NEID does not extend the biome id limit, just items and blocks. We are unable to do anything on our end.
