### ISSUE TITLE
Turn off druid circle generation

### ISSUE THREAD

**Issue by Charnuz** [TheCyberBrick/The-Betweenlands#894]
I would like the ability to turn off generation of druid circles, but unfortunately setting the `druid_circle_frequency` to 0 throws an IllegalArgumentException.

**Comment by TheCyberBrick** [comment]
`druid_circle_frequency` is a bit a misnomer because it's quite the opposite of a frequency. Lower values increase spawn rate and higher numbers decrease it. If you set it to the highest allowed number it should not spawn anymore.
