### ISSUE TITLE
[Suggestion] For Boats

### ISSUE THREAD

**Issue by JasonPra** [TheCyberBrick/The-Betweenlands#896]
Perhaps a type of light like a lantern of sorts you can attach to the boats?

**Comment by TheCyberBrick** [comment]
IIRC that was/is planned. We have a weedwood lantern model that will hopefully be added at some point, and we also wanted to make it possible to add the lantern to the front of the weedwood rowboat.

**Comment by JasonPra** [comment]
Awesome! That Would be soooo Cool! :D

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
