### ISSUE TITLE
Start up crash with Botania

### ISSUE THREAD

**Issue by Locomotivers** [TheCyberBrick/The-Betweenlands#897]
#### Betweenlands version:

3.4.13

#### Forge version:

forge-14.23.5.2838

#### Singleplayer or Multiplayer:

Single Players
#### Installed mods:

https://hastebin.com/akipelibot.md

## Link to full crash log

https://paste.dimdev.org/jafotobaze.mccrash

#### How to reproduce:

1. Start the game

#### Expected result:

Game should be loaded fine

#### Actual result:

Lands at crash page

#### Pictures:

![image](https://user-images.githubusercontent.com/7984445/67338836-f1107d80-f4f7-11e9-8e4a-8c9ab799f6c5.png)

**Comment by TheCyberBrick** [comment]
> java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

You have too many modded blocks.
