### ISSUE TITLE
[1.12.2] Extreme Worldgen Lag with Epic Siege Mod

### ISSUE THREAD

**Issue by EndangeredProdigy** [TheCyberBrick/The-Betweenlands#898]
#144  Versions
#### Betweenlands version:
Betweenlands Version 3.4.13

#### Forge version:
14.23.5.2831

#### Singleplayer or Multiplayer:
Singleplayer.  Have not tested Multiplayer.

#### Installed mods:
EpicSiegeMod-13.165
TheBetweenlands-3.4.13

## Link to full crash log
https://pastebin.com/WWqbESDM

#### How to reproduce:
The Betweenlands will not generate past the initial chunk.  Only the chunk containing the portal and a small amount around it will generate.  Massive lag happens immediately and eventually the game will crash.  All you have to do is:

1. Have both Epic Siege Mod and Betweenlands installed
2. Create a Betweenlands Portal and enter it.

#### Expected result:
The world will not generate and the game will eventually crash

**Comment by TheCyberBrick** [comment]
See https://github.com/Angry-Pixel/The-Betweenlands/issues/527#issuecomment-372027463.
Unfortunately ESM still hasn't fixed the problem so you need to blacklist our mobs.
