### ISSUE TITLE
Stage 2

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#9]
Remember, everything from the previous stage needs finishing first!
The dimension itself
Basic swampy dimension terrain gen + caves
Betweenstone, Swamp Dirt, Swamp Grass
Dark green water/sky

**Comment by SanAndreasP** [comment]
Y U NO make milestone ;P

**Comment by TheCyberBrick** [comment]
The only thing that's missing now is the custom skybox, the basic terrain generation, caves and blocks are done.
