### ISSUE TITLE
[1.12] Crash upon entering Betweenlands

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [TheCyberBrick/The-Betweenlands#900]
## Versions
1.12
## Betweenlands version:

3.413

#### Forge version:

14.23.5.2836

#### Singleplayer or Multiplayer:

SSP

#### Installed mods:

Enigmatica 2 Modpack (Non-Expert): https://www.curseforge.com/minecraft/modpacks/enigmatica2

+Integrated Dynamics
+Universal Remote

+PLant Mega Pack
+Fossils and Archaeology Revival
+Silent's Gems

## Link to full crash log

https://gist.github.com/ErnestoPeroPezzi/56ca58f463e739812f94ef7c5a4b5b93

#### How to reproduce:

Going into The Betweenlands with a Universal Remote (https://www.curseforge.com/minecraft/mc-mods/universal-remote) Inside an Iron Backpacks backpack

#### Expected result:

The game to not crash

#### Actual result:

The game crashed

**Comment by pau101** [comment]
Thanks for reporting!

Unfortunately, Universal Remote is known to have serious mod compatibility issues and this problem has previous been reported as orbwoi/UniversalRemote/issues/26. Our team can resolve this crash but expect a lack in functionality of our dimension as a consequence of Universal Remote's invasiveness.

**Comment by pau101** [comment]
This has been fixed in dev, you can expect it to be in the next update!

**Comment by ErnestoPeroPezzi** [comment]
Fantastic! Thank you for the quick response and all the good work all of you do! :)
