### ISSUE TITLE
Elixir of Starvation can cause negative saturation

### ISSUE THREAD

**Issue by sam-kirby** [TheCyberBrick/The-Betweenlands#903]
#### Betweenlands version:

Issue present in b75dd137493012dbed60d1b1d56bf8587829ed2f

#### Forge version:

14.23.5.2347

#### Singleplayer or Multiplayer:

Single and Multi (Forge)

#### Installed mods:

No other mods required, though AppleSkin used to monitor hunger/sat values in F3 screen. Confirmed present without.

## Link to full crash log

No Crash

#### How to reproduce:

1. Give player Elixir of Starvation when player has hunger greater than 10x their saturation
2. Observe player's saturation going negative.

#### Expected result:

Hunger and Saturation decrease to zero.

#### Actual result:

Hunger goes to zero, saturation is free to go below. If the player eats to survive, they will lose saturation faster than they can gain it. Player can end up with saturation substantially below zero requiring much food to bring it above.

#### Possible fixes
1. Use exhaustion to bring hunger down
2. Add checks to ensure saturation does not go negative/go too far negative.

**Comment by TheCyberBrick** [comment]
Hm yeah that's not intentional haha.
Will change it to use exhaustion. Thanks 👍

**Comment by TheCyberBrick** [comment]
Fixed in the new update
