### ISSUE TITLE
[Suggestion] Spectres and Aminita mushrooms

### ISSUE THREAD

**Issue by theishiopian** [TheCyberBrick/The-Betweenlands#906]
Currently, decay doesn't really feel sinister enough. Sure, it reduces your health, but other than that all it really does it grant hallucinations. What if those hallucinations were hostile, and could actually hurt you?

The spectre is a transparent black mob with a ragged appearance that has a tendency to fade in and out of existence. Spectres spawn near players with low decay meters, and only those with low decay can see them. The lower your decay, the easier they are to see. Spectres become hostile to players with very low decay, though they deal only one heart of damage and only have 6 health, to make sure decayed players have a chance of fighting them. 

Spectres drop ectoplasm, a material that can be used in herblore, or can be eaten to make yourself ethereal. Ethereal players cant break blocks and deal reduced damage, but take massively reduced damage in return, as well as reduced knock-back. Non-magical projectiles pass through ethereal players. 

But what if you want to get ectoplasm without decaying yourself? Thats where aminita mushrooms come in. These red mushrooms with white spots are quite rare, and when eaten add an effect that mimics the effect of low decay, reducing your health and spawning spectres. The trick here is that while the effect is active, ectoplasm cant be dropped, or it disappears. It also vanishes if the player dies, like the curse of vanishing, and cannot be placed into inventories other than your own. Thus, if the spectres kill the player, they have to start over.  Once the effect ends, the ectoplasm becomes a normal, dropable and transferable item again. The idea is that the player has to conquer their delusions to win the prize.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
