### ISSUE TITLE
[Suggestion] Small creatures such as root sprites and sporelings should be capturable with the net, and move about in your inventory.

### ISSUE THREAD

**Issue by theishiopian** [TheCyberBrick/The-Betweenlands#910]
Also other tiny mobs as per #544. Basically anything non-hostile and small should be capturable in a net (except greeblings, because music should always be free). Perhaps there should be a "mob" item that takes on the model of whatever mob it is, and stores its stats. You could even make it move around in the player's inventory and eat food like this mod does: https://www.curseforge.com/minecraft/mc-mods/inventoryneko

To keep them from eating your food, you could put them into a jar crafted from silt glass.

**Comment by theishiopian** [comment]
As a supplementary suggestion, gecko cages could also have an inventory where creatures can move around, and you can put food and test items into them to feed them to the gecko/creature.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
