### ISSUE TITLE
Gecko Duplication

### ISSUE THREAD

**Issue by TheVoidShifter** [TheCyberBrick/The-Betweenlands#912]
#### Betweenlands version: 

3.5.0

#### Forge version: 

14.23.5.2768

#### Singleplayer or Multiplayer:

Unknown

#### Installed mods:

- The Betweenlands
- Chunk Animator
- ToroHealth Damage Indicators
- Phosphor Lighting Engine
- MultiMine
- Just Enough Items
- ItemPhysic
- Dynamic Trees
- Continuous Music

#### How to reproduce:

1. Catch a Gecko and put it in a cage
2. Break the cage with a Swift Pick

#### Expected result:

Cage item drops and Gecko is freed

#### Actual result:

Cage item dropped and Gecko is freed and duplicated

#### Pictures:

https://imgur.com/a/mvT5D3p

**Comment by GoryMoon** [comment]
This is an issue caused by MultiMine.
It's fixed in dev.
