### ISSUE TITLE
Game crash when you pickup the falling rotten planks in Sludgeon tower

### ISSUE THREAD

**Issue by VioletWyvern** [TheCyberBrick/The-Betweenlands#913]
It looks like falling rotten planks has some issue when you break and pick it up,   If you do so,   It will
crashing the game and get this error log:

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block thebetweenlands:log_rotten_bark_carved_9, it is not an allowed value

**Comment by GoryMoon** [comment]
You did not fill out the issue template, closing. 
Read "Creating Issues" on the front page (https://github.com/Angry-Pixel/The-Betweenlands)

From what you have posted, I have feeling it might be the same issue causing #914 but I don't know for sure as I don't have enough info.
