### ISSUE TITLE
Strange crash on game startup!

### ISSUE THREAD

**Issue by SirAron111** [TheCyberBrick/The-Betweenlands#914]
#### Betweenlands version:
The Betweenlands v3.5.1

#### Forge version:
14.23.5.2847 

#### Installed mods:
Dimension Zero Modpack updated the Betweenlands mod from The Betweenlands v3.4.13 to The Betweenlands v3.5.1and it happened.

## Link to full crash log
https://paste.dimdev.org/xeyupakode.mccrash

#### How to reproduce:
Strange crash on game startup!
I don’t know what’s causing it but since I updated the game simply crashes on startup never even getting to the menu.

1. Simply add the mods newest version to the Modpack stated above and remove the old version.
2. Crash!

#### Expected result:
Game normal startup

#### Actual result:
Crash!

**Comment by theishiopian** [comment]
Foamfix is sticking its fingers where they don't belong, try removing that.

**Comment by GoryMoon** [comment]
It's not foamfix that causes this issue, it's iguana tweaks that cause it.
This is fixed on our end in dev.

**Comment by SirAron111** [comment]
That’s good to hear. Since I use both mods to fix many other issues! Not all mods are as well balanced and designed as yours and the foamfix fixes a lot of the minor ones and the iguana one intentionally hooks into a lot of stuff giving those values like giving armors weight or other make life harder things. Thx for the fast work I will test it once it is out. But if its something to point out to the other mod devs I may do so. I just suck at finding out what mod does what in these logs I can’t code at all. I just know I updated X mod and suddenly something doesn’t work so ye.

**Comment by theishiopian** [comment]
Ah ok, I saw foamfix in the crash stack, guess I didnt read far enough.
