### ISSUE TITLE
Betweenlands Poison Ivy Damaging All Player Bodyparts with FirstAid

### ISSUE THREAD

**Issue by RWGryphon** [TheCyberBrick/The-Betweenlands#918]
#### Minecraft version:
1.12.2

#### Betweenlands version:
The Betweenlands 3.5.1 Universal 

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer. Untested for Multiplayer.

#### Installed mods:
firstaid-1.6.10.jar
TheBetweenlands-3.5.1-universal.jar

## Description of the problem

Betweenlands Poison Ivy damages all Player body parts instead of spreading damage each tick across Player's body parts.

#### How to reproduce:

1. Go into the Betweenlands and find any patch of poison ivy.
2. Walk into the poison ivy repeatedly until afflicted.

#### Expected result:
Expected poison ivy's status effects to damage Player bodyparts at half-a-heart per tick on a random part per tick.

#### Actual result:
All Player bodyparts were affected at once. Instead of alternating between parts, all bodyparts take the allotted half-heart of damage, resulting in near-lethal health loss (generally half-a-heart left on all bodyparts.)

**Comment by TheCyberBrick** [comment]
There is no concept of body parts in vanilla/forge code. All it does is giving the player or mob the poison potion effect. So if those body parts require special damage handling then that needs to be done by the body part mod.
If you report this to the body part mod feel free to link to this issue so the dev can get in contact if necessary

**Comment by RWGryphon** [comment]
Thank you, I have written a issue post to FirstAid with a link to this post.
