### ISSUE TITLE
Cannot blacklist items in The Betweenlands config to be effected by weakness

### ISSUE THREAD

**Issue by nonlineargoblin** [TheCyberBrick/The-Betweenlands#921]
#### Betweenlands version:
The Betweenlands v3.4.13 

#### Forge version:
1.12.2-14.23.5.2844

#### Singleplayer or Multiplayer:
Mulitplayer server using spongeforge

#### Installed mods:
https://docs.google.com/document/d/1kfklHf_6BsbfbTLLedGygE2FOgy0ZqQHRSXWXmEIt6M/edit?usp=sharing

#### How to reproduce:

We're trying to make it so that the tools and weapons in tinker's construct will be weakened in the between lands. Right now we have our config file weakness blacklist entered like this:

 S:tool_weakness_blacklist <
        tconstruct:shovel
     >
We're using the shovel to test if it effects the tools, when we get it to work we'll add more entries to the list

#### Expected result:
All tinker's construct tools added to the blacklist will be effected by weakness when a player enters the dimension

#### Actual result:
None of the tinkers construct tools added to the list are effected by weakness

**Comment by TheCyberBrick** [comment]
Try using `tconstruct:shovel:*`. Without specifying damage it defaults to 0 damage/metadata, but tools can be damaged.

**Comment by SSKirillSS** [comment]
**Tested with:**
_spongeforge-1.12.2-2838-7.1.7-RC3948
TheBetweenlands-3.5.2-universal
TConstruct-1.12.2-2.13.0.171
Mantle-1.12-1.3.3.55_

Everything works fine.

**Comment by nonlineargoblin** [comment]
ff

**Comment by nonlineargoblin** [comment]
Hi guys thanks for your feedback, I've tried to re-edit the config file after updating the servers version of betweenlands to 3.5.2. However I believe we're still having the same problem as before. Below I provided the line that contains the blacklist for the weakness in our config file:

    S:tool_weakness_blacklist <
        tconstruct:shovel:*
     >

**Comment by TheCyberBrick** [comment]
I've tried it myself and it works for me. Check the logs and make sure the config has no errors and is loaded properly.
Here's what I tested with, both are weakened as expected:
```
    S:tool_weakness_blacklist <
        tconstruct:rapier:*
        tconstruct:shovel:*
     >
```

**Comment by TheCyberBrick** [comment]
Hm have you tested this also in single player?
