### ISSUE TITLE
Version 3.5x breaks water rendering in shaders

### ISSUE THREAD

**Issue by cheshyrp** [TheCyberBrick/The-Betweenlands#922]
#### Betweenlands version:

v3.5.1

#### Forge version:
forge-14.23.5.2838

#### Singleplayer or Multiplayer:

Single and multiplayer on the built-in local server

#### Installed mods:
https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons

#### How to reproduce:
Install Optifine and Sildur's Vibrant shaders pack from https://sildurs-shaders.github.io/downloads/
Look at water on the surface world and dive beneath it.

#### Expected result:
You should be able to see clearly underwater, nor should odd textures appear on the surface reflection.

#### Actual result:
 A strange sparkling pattern appears on the water surface. Go underwater and the screen turns opaque blue, making it impossible to see. This did not occur in v3.4 of Betweenlands.

**Comment by cheshyrp** [comment]
Addendum: even with Optifine shaders disabled I can't see anything in the Betweenlands dimension. Everything is solid black except the portal animation. Fast Render is disabled, as are shaders in the Betweenlands config. The only thing that works is downgrading to v3.4.

**Comment by cheshyrp** [comment]
Did some further testing, uninstalled Optifine, and had a friend with a clean install of Roguelike Dungeons & Adventure join my server. Her Betweenlands screen was solid black as well, and Optifine wasn't installed. The latest version of Betweenlands is either badly broken, or incompatible with something else in the RAD mod pack.

**Comment by OHKOBunny** [comment]
Im' having this problem too, I spent 10 hours tracking down which mod was doing this and then another 2 tweaking stuff to see if it could work but nah. The shader settings in the betweenlands config don't affect anything.

**Comment by TheCyberBrick** [comment]
I don't quite understand how you all (from the other linked issue) come to the conclusion that the BL shaders can't be turned off? I'm testing it now and disabling BL shaders in the config does indeed turn them off (i.e. shader sky is gone, no more firefly lighting etc). Am I missing something obvious?

**Comment by TheCyberBrick** [comment]
I can reproduce the problems you're having with the optifine shaders though. It may have to do with the new particle renderer

**Comment by TheCyberBrick** [comment]
Ok figured it out. It's caused by the new ring of dispersion overlay

**Comment by cheshyrp** [comment]
Thank you, Cyber. There's also the issue of the black screen, but I'll comment on that in a separate issue. Any idea how long it takes these commits to reach Curse/Twitch?

**Comment by TheCyberBrick** [comment]
Depends on how severe the problems are and whether there are other things that also need to be fixed. I'll probably make a new build later today
