### ISSUE TITLE
Compost bin, duplication item

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#924]
Hi, sorry my english.

If you break a working compost bin, items in it will drop in huge quantities.

![2019-11-14-00-32-45](https://user-images.githubusercontent.com/57269692/68789175-017aca80-0656-11ea-9156-07f290219bc9.gif)

Minecraft: 1.12.2
Forge: 14.23.5.2847
The BetweenLands: 3.5.1
Mods:
![изображение](https://user-images.githubusercontent.com/57269692/68791445-633d3380-065a-11ea-9c2d-a2c0ee4caba4.png)

**Comment by theishiopian** [comment]
Can confirm, this issue is very reproducible. It seems to give you exactly 64 times the items you put into it. Works with any compostable item.

**Comment by theishiopian** [comment]
Works regardless of whether you start breaking it from open or closed.

**Comment by theishiopian** [comment]
Confirmed in fresh development environment using the 3.5.1 release

**Comment by theishiopian** [comment]
Seems to be the result of a hack that was implemented for hopper compat not interacting well with the InventoryHelper's method of dropping items

**Comment by theishiopian** [comment]
Proposed solution: replace `breakBlock` in `BlockCompostBin` with the following:
```
@Override
	public void breakBlock(World worldIn, BlockPos pos, IBlockState state) {
		TileEntity tileEntity = worldIn.getTileEntity(pos);
		
		if (tileEntity instanceof IInventory) {
			
			//InventoryHelper.dropInventoryItems(worldIn, pos, (IInventory)tileEntity);
			TileEntityCompostBin bin = (TileEntityCompostBin)tileEntity;
			NonNullList<ItemStack> inventory = bin.getInventory();
			for(ItemStack stack : inventory)
			{
				ItemStack buffer = stack;
				buffer.setCount(1);
				
				bin.getWorld().spawnEntity(new EntityItem(bin.getWorld(), bin.getPos().getX(), bin.getPos().getY(), bin.getPos().getZ(), buffer));
			}
			worldIn.updateComparatorOutputLevel(pos, this);
		}

		super.breakBlock(worldIn, pos, state);
	}
```
Requires a getter for the field `inventory` in TileEntityCompostBin of course.
