### ISSUE TITLE
Universal Remote Incompatibility

### ISSUE THREAD

**Issue by cheshyrp** [TheCyberBrick/The-Betweenlands#925]
#### Betweenlands version:

v3.5.1

#### Forge version:

14.23.5.2838

#### Singleplayer or Multiplayer:

Single and multiplayer

#### Installed mods:

I'm running Rogulike Adventures & Dungeons. This problem occured when I added **Universal Remote**.

#### How to reproduce:

Add **Universal Remote** to any mod pack that includes The Betweenlands, then enter the dimension. 

#### Expected result:

Blocks should render normally.

#### Actual result:

Everything is solid black, including the avatar. Parts of the sky (Northern lights?) are visible, as is the portal effect if you can find it to return home.

**Comment by TheCyberBrick** [comment]
What's that Dynamic Storage mod you mention? Do you mean Refined Storage?
I've just tested BL 3.5.1 with Refined Storage 1.6.15 and I can't reproduce this problem.

**Comment by TheCyberBrick** [comment]
Also please send us a picture showing the problem.

**Comment by cheshyrp** [comment]
Sorry, I meant **Refined Storage**. Attaching before and after screenshots now. I would have been faster, but it takes at least 5 minutes to load the game after a mod change. Apparently it's the mod I always pair with it (**Universal Remote**) that's causing the problem. Odd, as a mod that only adds a single tool shouldn't mess with rendering. Whereas Refined Storage _does_ tweak rendering to support cable covers. *boggle*

![Betweenlands Normal](https://user-images.githubusercontent.com/22087066/68891491-e7d99180-06ee-11ea-883f-a42b0eaa0324.png)
![With Universal Remote](https://user-images.githubusercontent.com/22087066/68892067-1e63dc00-06f0-11ea-8d65-b8db6eb3c0eb.png)

**Comment by TheCyberBrick** [comment]
The incompatibility with Universal Remote is known and has been reported to the author a while ago but unfortunately was never fixed.
