### ISSUE TITLE
[Suggestion] - Mob stats multiplier config option

### ISSUE THREAD

**Issue by SSKirillSS** [TheCyberBrick/The-Betweenlands#926]
I propose adding options to increase/decrease the overall level of health, damage, defense and other indicators of mobs. This would be convenient enough for modpacks, the concept of balance of which differs from vanilla.
The logic is pretty simple: default metric * metric from the configuration file (The default config option value, of course, is 1.0).

**Comment by TheCyberBrick** [comment]
I think this is outside the scope of configuration of the mod. Vanilla already offers systems for such things ([mob attributes](https://minecraft.gamepedia.com/Attribute)). [In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control) enables you to change mob attributes on spawn.
