### ISSUE TITLE
Rotten bark is uncraftable in survival

### ISSUE THREAD

**Issue by probleyes** [TheCyberBrick/The-Betweenlands#928]
#### Betweenlands version:
3.5.2

#### Forge version:
Minecraft Version: 1.12.2 forge-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
The Betweenlands, Betweenlands Storage Addon, JEI, Ore Excavation.

## Description of the problem
The rotten bark you collect from the rotten logs can't be crafted into rotten planks. Rotten planks can only be crafted with rotten bark that has a metadata of 0, when the bark you get from the logs has a metadata of 12.

#### How to reproduce:
1. Get bark from one of the naturally spawning rotten logs and try to craft it into planks, you can't!
2. Spawn in bark from the creative menu and try to craft it into planks, you can!

#### Expected result:
I expected my pretty planks god dammit!

#### Actual result:
No planks!

#### Pictures:
![noplank](https://user-images.githubusercontent.com/17963605/69013011-721d3200-0949-11ea-9c70-d3c6c873c47d.PNG)
![yesplank](https://user-images.githubusercontent.com/17963605/69013012-734e5f00-0949-11ea-9f57-bb38a6c358cd.PNG)

**Comment by WightofShadows** [comment]
I've added a (possibly temporary) workaround for the recipe. I'm not sure why there even is a difference with the bark, you can't use metadata 12 bark as fuel or compost either. The generation might have to be changed for a full fix

**Comment by WightofShadows** [comment]
Looking at the gen ingame, the fallen logs in Swamplands biomes use data 12, but the trees in sludge plains and the sludgeon still use data 0

**Comment by TheCyberBrick** [comment]
🤔

**Comment by TheCyberBrick** [comment]
> Not sure why changing data to 32767 doesn't work here like with the others

Works fine for me.
But what I'll do is to make the blocks always drop the 0 meta item, since there is no difference between the 12 and 0 meta block (unlike for weedwood e.g.)

**Comment by TheCyberBrick** [comment]
Hm actually might just leave it as is and only do the recipe fix. Maybe we'll at some point add different bark textures like for weedwood

**Comment by TheCyberBrick** [comment]
> you can't use metadata 12 bark as fuel or compost either

Huh? Using it for compost or fuel works for me
