### ISSUE TITLE
DrZharks MoCreatures Incompatibility

### ISSUE THREAD

**Issue by JaselUmena** [TheCyberBrick/The-Betweenlands#930]
#### Betweenlands version:

3.5.1

#### Forge version:

forge-14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, vanilla server. (Could not reproduce in single player).

#### Installed mods:

Mod list: [https://pastebin.com/aDdCa0K4](url)
Modpack link: [https://github.com/HeartlessAUS/Crisps-of-the-Multiverse/releases](url)

## Link to full crash log

[https://pastebin.com/Guq7MWrk](url)

## Description of the problem

A client side crash occurs whenever a player triggers the "eye" that teleports the player to the top of the fortress and starts the boss fight agains the Primordial Malevolence. Players may rejoin the server and there is enough time to teleport them away from the source of the problem, but they will crash again if they approach the triggered boss fight.

#### How to reproduce:

1. Reach the fortress and obtain the shockwave sword.
2. Enter the final floor and stare into the "eye" thing (Crash can happen at any time after the bossfight triggers).
3. Additionally, approach the area where the fortress is once the boss is active to crash without staring at the eye.

#### Expected result:

Boss spawns, bossbar is visible, the area darkens and boss music plays.

#### Actual result:

The game crashes client side, but the server is completely fine.

#### Pictures:

Unable to provide any meaningful pictures, as they are all just a frozen screen before crashing.

**Comment by TheCyberBrick** [comment]
This is caused by DrZharks MoCreatures. Has been reported a long time ago but unfortunately has not been fixed yet.
