### ISSUE TITLE
Depth fog go away [Suggestion]

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#931]
I'd like to have a block that can dispel depth fog when the player is around it, as it there are various builds I'd like to try to build underground, but the depth fog makes it impossible to actually do so since I can't admire it at all from a distance.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
