### ISSUE TITLE
[Suggestion] Weeping Blue Petals heal geckos

### ISSUE THREAD

**Issue by Wraithskaar** [TheCyberBrick/The-Betweenlands#933]
I'd like to keep my cute, poor geckos from dying while testing ingredients.  Feeding them weeping blue petals could reduce or eliminate the effects of testing; or give a percentage chance of reducing the effects of testing.

P.S.  I *LOVE* this mod!!!  Keep up the fantastic work!

**Comment by WightofShadows** [comment]
You can use Sap Spit to heal them inside cages.

**Comment by Wraithskaar** [comment]
Welp, that is good to know.  Still loving the mod!  Enjoyed the spook event and now liking the winter event.

**Comment by TheCyberBrick** [comment]
This just gave me an idea. At the moment collecting sap spit is quite elaborate, I think. What if we made tamed spirit tree faces drop sap spit when you feed them e.g. compost (maybe with a chance)? Could be a nice renewable but slightly worse alternative to scabyst that can be farmed at your base.
