### ISSUE TITLE
[Suggestion] [Contribution] Decay ring.

### ISSUE THREAD

**Issue by Carvercarver1** [TheCyberBrick/The-Betweenlands#935]
"Decay ring".

This may seem as a basic generic suggestion for something against decay, but no. It's not that. 

Decay Ring is, basically, a ring which covers you in irremovable decay of the last stage while it is on, but grants buffs to resistance and attack damage. Logically, makes you immune to decay that way. Alternatively, it can be a clone of ring of recruitment coating effect around the player but more decayed and green, and quite probably giving an impression that the user is riddled with decay and desease.

Technically... it may be as well as just applying potion effects of decay and resistances. And maybe some speed to compensate for slowing down. Additionally, player can be made immune to knockback as a part of severing or supressing player's pain receptors entirely (or by producing too much endorphine which also supresses pain too much).
 In core of it, it can be, basically, a copy of decay effect and RoR ring with counter buffs or effects applied in the simullar nature as the ring of power.
Preferrably, this ring should work outside of TBL dimension too, but with a twist... if you bring this to overworld, it will make you a moving snow golem, but instead of leaving slow, you will corrupt the land instead.

As for "da lore" or any assets... I have one or two strict ideas. Basically, it may look like a harmless iron-ish or silver ring, with a tiiiiiiny bit of green decay on it. I can make a texture for either as a contribution.

As for the actual lore behind the item, I have that too. 
Either it was supposed to protect from decay but got corrupted like everything else, or was made by some mad/insane magicians, or just... there - it grants user those abilities I listed. Basically, bearer of decay or master of decay. 
Oh, and apparently you become so contagious and toxic that entities around you, which do not belong to you or attacked by you (or anything except players), get poisoned or get some of the nasty BL brew effects.

Possible bad side effect - you cannot properly swim, do not benefit from healing potions, and sap ball or anything that works against decay... will damage you instead. Basically, effects of the healing revert to damaging effect.

Again - I can make a texture for that, that's for sure. Still open to instructions. Also this will be the one of a few ways to directly weaponize the decay, and, as a consiquence, render you resistant to decay (for obvious reasons).

**Comment by theishiopian** [comment]
Much better :)

**Comment by TheCyberBrick** [comment]
Some sort of decay ring is already planned :P

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
