### ISSUE TITLE
Infusions never finish.

### ISSUE THREAD

**Issue by 63502** [TheCyberBrick/The-Betweenlands#937]
#### Betweenlands version:

3.5.4

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Tested in survival instance with more mods, but reproduced with Forge and Betweenlands independently in a bug test instance.

## Link to full crash log

N/A

#### How to reproduce:

Attempted with a Brew of Healing (only sap spit) and with the Draught of the Sagittarius (only bottled aspects).

1. Set up 2 infusers with peat, water, and an octine block to auto ignite moss.
2. Light fire with moss and allow to boil.
3. Add ingredients when steam shows. Based on observations, the amount and number of ingredients added doesn't seem to matter.
4. Attach life crystal and start the auto stir process. Based on observations, the infuser recognizes the aspect combinations as valid _(green color in infuser after large steam cloud and ingredients become irretrievable)_ after 30 sec to 1 min. Brew then becomes indigo again after 5-10 sec.
5. Wait. 

#### Expected result:

Brew completion within ??? min.
_The wiki had no answers on how long the process is supposed to take, and I couldn't locate that bit of info anywhere else either._

#### Actual result:

**4 hours, 4 fully charged life crystals per infuser, 8 white maned lynels, and half of the champions ballad DLC in Zelda: Breath of the Wild later...**

Nope, sorry. Nothing.

Continue repetition of step 5.

**Comment by 63502** [comment]
This was originally #934 , but after further testing I decided to open a bug report instead.

**Comment by TheCyberBrick** [comment]
Sorry, a bit late, but this is working as expected. The sudden steam cloud, sound and colour change is the indicator for when the infusion is done. When it's done you can fill buckets with it by shift-right-clicking on the infuser. Waiting too long causes the infusion to go bad (changes colour to brow).
