### ISSUE TITLE
UPDATE TO MINECRAFT 1.15, THE 1.12 VERSION IS THE PAST!

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#938]
#### How to reproduce:

1.
2.
3. etc...

**Comment by theishiopian** [comment]
As obvious of a troll this is, its made even funnier by the fact that 1.15 isn't even out yet XD

**Comment by ghost** [comment]
xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
