### ISSUE TITLE
[Suggestion] Ring of Gathering manual teleportation control

### ISSUE THREAD

**Issue by Uub112** [TheCyberBrick/The-Betweenlands#941]
Ring of Gathering would possibly be more convenient if you could have a manual means to summon tame mobs into the ring, on account of these things:

1. Currently, tamed creatures that don't automatically teleport to your location (things like horses or toads) are a bit clunky to recover with the ring because you would have to travel sufficiently far away from them (chunk unloaded?) to get them to go into the ring, and then summon from the ring. 

2. The ring is a bit superfluous in most situations with mobs that _do_ automatically teleport to your location as well, because as long as you get near enough to a block where they can teleport without unloading the chunk they were in (which is pretty difficult to avoid if you're not in water or air for long-distance travel) they'll just do so anyways. It would also be quite handy for withdrawing tamed mobs that are attacking, but in a situation where you don't want them attacking.

**Comment by TheCyberBrick** [comment]
Yeah that's something I have planned. It'll probably use a keybind like the Ring of Summoning does.

> The ring is a bit superfluous in most situations with mobs that do automatically teleport to your location as well, because as long as you get near enough to a block where they can teleport without unloading the chunk they were in (which is pretty difficult to avoid if you're not in water or air for long-distance travel) they'll just do so anyways.

The ring allows you to revive pets that have died while having the ring equipped.

**Comment by Uub112** [comment]
True, the pet revival feature is great, really makes the risk for bringing pets worth it.
I just meant that the process of recovering pets that teleport to you with the ring is only really situational right now, but it already is nice to not lose pets to chunk unloading while flying and such.
Fantastic mod by the way, keep up the great work!
