### ISSUE TITLE
Custom Shaders creates clones of player, lens, worm holes, and braziers when entering sludgeon.

### ISSUE THREAD

**Issue by SamuraiShogun1102** [TheCyberBrick/The-Betweenlands#943]
I use sildur's enhanced shaders, whenever I enter the sludgeon when the shaders on, there are clones on my screen, braziers are glitched, lens holes are visible through blocks.

**Comment by TheCyberBrick** [comment]
That's caused by Optifine or your shaders. Some of our renderers depend on certain rendering features that Optifine/shaders break or disable. Not much we can do about that unfortunately.

**Comment by DarianLStephens** [comment]
I'm not currently using Optifine or by extension shaders, and am currently experiencing this odd issue as well.
Are there any mods known to cause this besides Optifine?
![2020-05-31_22 52 46](https://user-images.githubusercontent.com/15375876/83355839-3efe3580-a3a5-11ea-82e3-15476fae0e62.png)

I can also see the tunnel effect that worms emerge from through the vast majority of blocks:
![2020-06-01_01 09 17](https://user-images.githubusercontent.com/15375876/83355867-6ce37a00-a3a5-11ea-9e63-a37adf4640a8.png)
![2020-06-01_01 07 39](https://user-images.githubusercontent.com/15375876/83355874-740a8800-a3a5-11ea-8550-4c0a59c926c8.png)

**Comment by DarianLStephens** [comment]
Seems like ShootIt was causing the problem, some way, somehow.
EDIT: Not entirely, something's making the fog interact weirdly, so I can't see the braziers in the crystal without standing behind them.
Will keep hunting.
EDIT 2: Okay, I don't know what changed, but I'm not able to reproduce this issue outside of my actual survival world.
EDIT 3: Finally got it; it was ArmorChroma, and it only affects the crystal when you're wearing a piece of enchanted armor. Weird!

**Comment by DarianLStephens** [comment]
NOPE!
I got ahead of myself; the issue is with enchanted armor period.
Most likely something weird with trying to render the player's enchanted armor (Possibly other items as well) in the crystal.
