### ISSUE TITLE
Boat broke my world

### ISSUE THREAD

**Issue by FamicomPlayer** [TheCyberBrick/The-Betweenlands#945]
#### Betweenlands version:
3.5.4

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Backpacks
Just Enough Items
Xaeros Minimap
Dynamic Lights
Inventory Tweaks
Damage Indicators
Optifine
The Betweenlands

#### How to reproduce:

1.Try to sat in the boat
2.World is broke

#### Expected result:
Sat in the boat

#### Actual result:
When i sat in the boat, game freezes and my world was broken when i tried to load it

**Comment by GoryMoon** [comment]
Need a crash and/or log to see what's wrong.
Upload the log from when it happens if the game doesn't crash, otherwise upload the crash report and post the link to it.

**Comment by FamicomPlayer** [comment]
> Need a crash and/or log to see what's wrong.
> Upload the log from when it happens if the game doesn't crash, otherwise upload the crash report and post the link to it.

How upload the log?

**Comment by FamicomPlayer** [comment]
``

> Need a crash and/or log to see what's wrong.
> Upload the log from when it happens if the game doesn't crash, otherwise upload the crash report and post the link to it.

I have latest.log and debug.log , which from them me need to upload?

**Comment by GoryMoon** [comment]
Should be enough with the `latest.log`, but `debug.log` could be useful.
So both could work.
