### ISSUE TITLE
Wight standing on top of you

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#946]
TheBetweenlands-3.5.4

#### Forge version:

1.12.2-forge1.12.2-14.23.5.2836

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

1.12
memory-repo
OpenTerrainGenerator
CodeChickenLib-1.12.2-3.2.2.353
DynamicSurroundings-1.12.2-3.5.4.3
Emoticns-0.2.1-1.12.2
Foamfix-0.10.9-1.12.2
jei_1.12.2-4.15.0.277
mod_voxelMap_1.7.1_for_1.12.2.litemod
Optifine_1.12.2_HD_U_E3
OreLib-1.12.2-3.5.2.2
Phosphor-1.12.2-0.2.2+build43
TheBetweenlands-3.5.4

## Link to full crash log

N/A

#### How to reproduce:

1.Spawn wight, let it possess you
2. Go to creative mode, get a wights bane
3. Kill the wight while in creative mod
4. Go back to survival mode

#### Expected result:

A ded wight

#### Actual result:

The wight will not be target-able and after a while it will stand on top of you

**Comment by TheCyberBrick** [comment]
Can't reproduce this (disregarding the fact that wight's bane doesn't even kill instantly in creative mod).
