### ISSUE TITLE
Fireflies disappear when you get too far away from them, leaving only the light they give off.

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#95]

**Comment by SanAndreasP** [comment]
So should they remove the light when despawning or should they not despawn at all?

**Comment by MrCompost** [comment]
They shouldn't despawn at all imo

**Comment by iLexiconn** [comment]
Say hello to the lag

**Comment by PCAwesomeness** [comment]
Do bats despawn?

**Comment by MrCompost** [comment]
Yes they do. Not sure why that's relevant though =P

**Comment by PCAwesomeness** [comment]
That's because all ambient mobs, IMO, should have some similarities to the bat (flying around, some can land on blocks, despawning after you go away from them for a long period of time).
