### ISSUE TITLE
Shield Breaking Interactions

### ISSUE THREAD

**Issue by orian34** [TheCyberBrick/The-Betweenlands#953]
#### Betweenlands version:
TheBetweenlands-3.5.4

#### Forge version:
1.12.2
forge-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands, Akashic Tome, Appleskin, Astral Sorcery, AutoRegLib, Baubles, Better Advancements, Better FPS, Bountiful Baubles, Chocolate Quest Repoured, CodeChicken Lib, ConnectedTexturesMod, Dimensional Doors, Dynamic Surroundings, Ender Storage, Fast Leaf Decay, Fossils and Archeology Revival, Gravestone Mod, Iron Chests, Iron Backpacks, JEI Villagers, Journey Map, Just Enough Resources, Librarian Lib, LLibrary, Mantle, Millénaire, More Creeps and Weirdos Revival, Mouse Tweaks, Nature's Compass, Neat, OreLib, Patchouli, Serene Seasons, Shadowfact's Forgelin, The One Probe, The Twilight Forest, Trinkets and Baubles, Villager Market, Waystones.

## Description of the problem
You can't shift right click with a bucket to empty the infuser if you have a shield in the offhand.
Having a shield also seems to break the gecko cage, forcing a double use, meaning you'll never see the "more aspects to be found" messages.
You're forced to remove it. It made me lose 2 hours not understanding how brewing was supposed to work despite looking at the wiki. 

1.Infuse a potion.
2.Try to use bucket by shift clicking th filled infuser.
3.Nothing happens because you're holding a shield.
4. Try again without the shield, it works.
Conclusion: Shield breaks the infuser gathering action?

1.Feed a gecko any ingredient with a shield in the offhand.
2.You see the "gecko is already resting from previous try"
3.Feed without the shield.
4.See the normal "has still aspects" or "found all aspects" message.
Conclusion: The shield bugs the feeding process and makes a double use?

**Comment by TheCyberBrick** [comment]
That's vanilla behaviour. Try clicking a lever with a vanilla shield in the offhand while sneaking, it won't work either ;)
I've addressed the gecko cage problem by adding those important messages also to the chat so they can't be missed.

**Comment by orian34** [comment]
Damn, the shield bug sucks. At least the gecko part will work properly, but the infuser still is a hindrance
