### ISSUE TITLE
Empty Alcoves Still Show Items

### ISSUE THREAD

**Issue by orian34** [TheCyberBrick/The-Betweenlands#955]
#### Betweenlands version:
TheBetweenlands-3.5.4

#### Forge version:
1.12.2
forge-14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Betweenlands, Akashic Tome, Appleskin, Astral Sorcery, AutoRegLib, Baubles, Better Advancements, Better FPS, Bountiful Baubles, Chocolate Quest Repoured, CodeChicken Lib, ConnectedTexturesMod, Dimensional Doors, Dynamic Surroundings, Ender Storage, Fast Leaf Decay, Fossils and Archeology Revival, Gravestone Mod, Iron Chests, Iron Backpacks, JEI Villagers, Journey Map, Just Enough Resources, Librarian Lib, LLibrary, Mantle, Millénaire, More Creeps and Weirdos Revival, Mouse Tweaks, Nature's Compass, Neat, OreLib, Patchouli, Serene Seasons, Shadowfact's Forgelin, The One Probe, The Twilight Forest, Trinkets and Baubles, Villager Market, Waystones.

## Description of the problem
Alcoves without a jar still show items inside when using a wayla mod like the One Probe.
Breaking the alcove after beating the boss(to remove protection) only destroys it without dropping anything. Meaning the items don't actually exist?

**Comment by TheCyberBrick** [comment]
You're only supposed to be able to obtain the alcove's items by breaking its urns. The fact that alcoves without urns have items in them is just a side effect of them being considered the same thing and thus also being filled with loot.
