### ISSUE TITLE
[Suggestion]Infusion Info

### ISSUE THREAD

**Issue by orian34** [TheCyberBrick/The-Betweenlands#957]
Everything can be figured out more or less by exploring or following the achievements, all except the infusion. There is nothing at all explained on how it works, at all. Even the herblore book only has potion recipes, not even how to make it. 

It would be great to have more achievements and hints at how to do stuff. Like having the infuser "Needs to be heated" tooltip or stuff like that.

I'm sure you can figure out something.

**Comment by orian34** [comment]
Here's a wee bit of a plan to give ideas:
First, as said above, a tooltip info on the items like the repeller and infuser.
Maybe "Can ward off danger by dipping a precious item in corrupt liquid."(repeller), "Needs to be heated."(infuser)
Then, you can also increase the Herblore tab of the BL achievements(you could make an Infusion tab, but like, there's already a lot of them, lol).
This one could be added to the Crafting tab for rubber, branching off: 
[Bouncing Off] "Harvest some rubber with a bucket and heat it to obtain rubber balls."
There could be a third branch after the "I'm a Druid" achievement, starting off with some elixir making, [Stirring The Pot] "Fill a bucket of brew made by mixing up ingredients in the infuser."
It can branch off with two after that one:
A hidden one [Boiling Point] "Let a brew completely evaporate and deal with your mistake."
An easy one [A Dripping Matter] "Fill a distiller with a bucket of infusion and then wait."
branching off again into two:
A challenge one [Master Apothecary] "Make every kind of infusions."
A simple one followed by another [Step Towards Success] "Fail brewing an infusion and salvage the remains."
[Mysterious Plant] "Fill a Censer with an aspect to grow aspectrus fruits on a rubber fence."

**Comment by TheCyberBrick** [comment]
We do plan to have an ingame guide book at some point and this will definitely be addressed there.
