### ISSUE TITLE
[Nerf]Seeping Sap Dropped By Friendly Masks

### ISSUE THREAD

**Issue by orian34** [TheCyberBrick/The-Betweenlands#958]
The friendly masks spawned by the spirit trees you plant also drop sap, which is pretty unbalanced considering how strong the sap is, and how you can simply slaughter the masks for free sap farming.
I think they shouldn't drop the sap.

**Comment by TheCyberBrick** [comment]
How so? Spirit tree saplings are a somewhat rare item... The tree only drops one, or 2-3 (iirc) when you strengthen it by placing some wisps on the stone circles. Killing the tamed faces for a couple of sap spit seems like a major waste to me :P

**Comment by orian34** [comment]
Don't they respawn? If they don't, then it's all good then

**Comment by TheCyberBrick** [comment]
No, they don't ;)
