### ISSUE TITLE
Traveller's Log: Tar Boat

### ISSUE THREAD

**Issue by orian34** [TheCyberBrick/The-Betweenlands#959]
I love the principle of using tar on your boat, but aside the wiki, I would never had the idea to do it.
Although I really like how you can drop hints for stuff to be done in achievements, I think there's potential to hint at it by using a page to be found in ruins or so, maybe specifically sludge plains?
Both could be done I guess, but an in game hint for it would be awesome!

**Comment by WightofShadows** [comment]
I think it'd be kinda weird to have an entire lore page dedicated to the learning of one mechanic like this, but that said, we did have a guide book planned at some point. Perhaps certain "advanced" tips including this one could be found as pages and added to the original book.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
