### ISSUE TITLE
[Suggestion] Primordial Shielding

### ISSUE THREAD

**Issue by KamiSami** [TheCyberBrick/The-Betweenlands#961]
Hi, when i fought Primordial Malevolence, I had a thought after receiving the ring it drops as reward, what if the ring reward would be something like "Primordial Shielding"? Just like boss's ability, a shield surrounds you making you invulnerable at cost of constant fast EXP drain? Which also just like boss, repels attackers. Maybe the ring of recruiting would suit some other boss better that relies more on summoning a lot of mobs in waves? Ah well, not sure if this suggestion is overpowered, but I always personally found all boss abilities in all games interesting and even more so if one can have them in control, to gain abilities of bosses, since often the player in games is one with not that great or flashy attacks or abilities like bosses d-.. Sorry i started rambling, uhm.. Yeah, the Primordial Shielding suggestion, I am curious what you may think of it.

**Comment by TheCyberBrick** [comment]
Hm that sounds interesting :P
I'm just not sure what kind of item it could be. As a "regular" shield item it'd probably be overshadowed by the syrmorite and valonite shields that have the charge ability.  
It could be an additional ability of the Ring of Recruitment. The primordial malevolence has the ability to spawn the triangle thing that steals health from the player and heals the PM when the player steps on it. Maybe the ring of recruitment could do something similar to recruited mobs and then create a shield at the cost of the recruited mobs' health?

**Comment by theishiopian** [comment]
Make it a portable repeller like thing that you strap to you back.

**Comment by TheCyberBrick** [comment]
Done :)
