### ISSUE TITLE
[1.12.2] Game Crashes if you equip two Rings of Power.

### ISSUE THREAD

**Issue by SonicX8000** [TheCyberBrick/The-Betweenlands#963]
Report:
https://pastebin.com/ndfKxKj7

Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
jei_1.12.2-4.15.0.291
TheBetweenlands-3.5.4-universal

-----

I managed to get lucky and scored two of these rings so... I go ahead and equipped the first ring... then went to equip the second ring and... game crashes.

In older versions you can wear two Rings of Power to get their effects but a Speed Bonus was later given to these rings, could that be related to it crashing?

*EDIT*
You can still get the Speed Boost if the Ring has no charge.

**Comment by TheCyberBrick** [comment]
oops
