### ISSUE TITLE
Walkways rendering strangely with 2x resolution texture pack

### ISSUE THREAD

**Issue by capt-slowpoke** [TheCyberBrick/The-Betweenlands#964]
#### Betweenlands version:

3.5.5

#### Forge version:

14.23.5.2838

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

Betweenlands 3.5.5
Foamfix 0.10.5

## Link to full crash log

No crash

#### How to reproduce:

Resized the walkway texture to 256x256 from its original 128x128 image; 
in game they now have invisible faces and z-fighting on others as if something is badly misaligned
 This exact texture pack worked correctly in the last version I played, which was before the sludgeon was introduced. 

#### Expected result:

Texture pack worked fine previously, I resized the walkway texture to 256x256 from 128x128 and had no issues

#### Actual result:

Walkways are now rendering with transparent faces and z-fighting on certain faces as well. 
#### Pictures:

![](https://cdn.discordapp.com/attachments/287943066944274433/661331353148719140/2019-12-21_21.47.58.png)
![walkway](https://user-images.githubusercontent.com/8922919/72227080-0e387380-355e-11ea-97c4-d43c7f99504c.png)

Texture pack file: 

[Blockheads - Betweenlands.zip](https://github.com/Angry-Pixel/The-Betweenlands/files/4051734/Blockheads.-.Betweenlands.zip)

**Comment by TheCyberBrick** [comment]
Thanks, this was a small bug introduced with the new(ish) texture packer that reduces the texture memory BL block models use.
