### ISSUE TITLE
Crash loop with barrishee

### ISSUE THREAD

**Issue by sossololpipi** [TheCyberBrick/The-Betweenlands#966]
#### Betweenlands version:

3.5.5-universal , on Windows, on 1.12.2

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

singleplayer. using the Minetogether mod, but I don't think that makes a difference.

#### Installed mods:

I have no idea how to write each 200 mods individually within a reasonable time; I'm just gonna say what things were active during the crash loop occurance. The Betweenlands (unsurprisingly), Monk Mod and Minetogether. Minetogether is just a chat mod; it shouldn't have done much. I was using the Mech & Magic modpack with The Betweenlands added.

## Link to full crash log

[crash-2020-01-16_17.41.29-server.txt](https://github.com/Angry-Pixel/The-Betweenlands/files/4074157/crash-2020-01-16_17.41.29-server.txt)

#### How to reproduce:

1. enter sludgeon with level 18 monk powers, a duration 3 power 2 elixir of toughskin and a lot of pears and weeping blue petals
2. get jumpscared by barrishee
3. as a reflex, whack the barrishee with a white pear
4. crash.

#### Expected result:

to be able to whack the barrishee to death

#### Actual result:

mmmm crash

#### Pictures:

I have none

**Comment by theishiopian** [comment]
looks like the AI is getting lost.
