### ISSUE TITLE
No clue what this is

### ISSUE THREAD

**Issue by ghost** [TheCyberBrick/The-Betweenlands#968]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-01-23 07:00:54 EST
Description: Exception in server tick loop

java.lang.RuntimeException: World New Dimension (lumien.simpledimensions.server.WorldProviderSimpleDimension) does not have BetweenlandsWorldStorage capability
    at thebetweenlands.common.world.storage.BetweenlandsWorldStorage.forWorld(BetweenlandsWorldStorage.java:231)
    at thebetweenlands.common.handler.EnvironmentEventHandler.onWorldTick(EnvironmentEventHandler.java:29)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_867_EnvironmentEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 4562789872 bytes (4351 MB) / 10569646080 bytes (10080 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 43 mods loaded, 43 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                   | Source                                                    | Signature                                |
       |:------ |:-------------------- |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                    | minecraft.jar                                             | None                                     |
       | LCHIJA | mcp                  | 9.42                      | minecraft.jar                                             | None                                     |
       | LCHIJA | FML                  | 8.0.99.99                 | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
       | LCHIJA | forge                | 14.23.5.2847              | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
       | LCHIJA | techguns_core        | 1.12.2-1.0                | minecraft.jar                                             | None                                     |
       | LCHIJA | securitycraft        | v1.8.15                   | [1.12.2]+SecurityCraft+v1.8.15.jar                        | None                                     |
       | LCHIJA | aoa3                 | 3.2.1                     | AoA3-3.2.1.jar                                            | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCHIJA | jei                  | 4.15.0.291                | jei_1.12.2-4.15.0.291.jar                                 | None                                     |
       | LCHIJA | quark                | r1.6-177                  | Quark-r1.6-177.jar                                        | None                                     |
       | LCHIJA | autoreglib           | 1.3-32                    | AutoRegLib-1.3-32.jar                                     | None                                     |
       | LCHIJA | betternether         | 0.1.8.6                   | betternether-0.1.8.6.jar                                  | None                                     |
       | LCHIJA | bookworm             | 1.12.2-2.3.0              | bookworm-1.12.2-2.3.0.jar                                 | None                                     |
       | LCHIJA | casinocraft          | v06                       | CasinoCraft_1.12.2_v06.jar                                | None                                     |
       | LCHIJA | coloredredstone      | 1.3.2                     | Colored+Redstone-1.3.2.jar                                | None                                     |
       | LCHIJA | customnpcs           | 1.12                      | CustomNPCs_1.12.2-(01Oct19).jar                           | None                                     |
       | LCHIJA | ptrmodellib          | 1.0.4                     | PTRLib-1.0.4.jar                                          | None                                     |
       | LCHIJA | props                | 2.6.3                     | Decocraft-2.6.3_1.12.2.jar                                | None                                     |
       | LCHIJA | cfm                  | 6.3.1                     | furniture-6.3.1-1.12.2.jar                                | None                                     |
       | LCHIJA | personal_server      | 1.0.0                     | gvcvbvbbvcb.jar                                           | None                                     |
       | LCHIJA | incontrol            | 3.9.16                    | incontrol-1.12-3.9.16.jar                                 | None                                     |
       | LCHIJA | justenoughdimensions | 1.6.0-dev.20191019.172643 | justenoughdimensions-1.12.2-1.6.0-dev.20191019.172643.jar | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | jeid                 | 1.0.3-48                  | JustEnoughIDs-1.0.3-48.jar                                | None                                     |
       | LCHIJA | kathairis            | 1.12.2-1.6.0-beta         | Kathairis-1.12.2-1.6.0-beta.jar                           | None                                     |
       | LCHIJA | libraryex            | 1.0.12                    | LibraryEx-1.12.2-1.0.12.jar                               | None                                     |
       | LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT     | malisiscore-1.12.2-6.5.1.jar                              | None                                     |
       | LCHIJA | malisisdoors         | 1.12.2-7.3.0              | malisisdoors-1.12.2-7.3.0.jar                             | None                                     |
       | LCHIJA | testdummy            | 1.12                      | MmmMmmMmmMmm-1.12-1.14.jar                                | None                                     |
       | LCHIJA | moarsigns            | 6.0.0.11                  | MoarSigns-1.12.2-6.0.0.11.jar                             | 5a57c7d1420cf4c58f53ea2a298ebef8215ede63 |
       | LCHIJA | morecommands         | 2.1.1                     | MoreCommands_2.1.1_mc1.12-1.12.2.jar                      | None                                     |
       | LCHIJA | moreplayermodels     | 1.12.2                    | MorePlayerModels_1.12.2-(05Dec19).jar                     | None                                     |
       | LCHIJA | neat                 | 1.4-17                    | Neat+1.4-17.jar                                           | None                                     |
       | LCHIJA | netherex             | 2.0.15                    | NetherEx-1.12.2-2.0.15.jar                                | None                                     |
       | LCHIJA | reborncore           | 3.16.4.478                | RebornCore-1.12.2-3.16.4.478-universal.jar                | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | simpledimensions     | 1.3.1                     | SimpleDimensions-MC1.12-1.3.1.jar                         | None                                     |
       | LCHIJA | techguns             | 2.0.2.0                   | techguns-1.12.2-2.0.2.0_pre3.1.jar                        | None                                     |
       | LCHIJA | twilightforest       | 3.10.1013                 | twilightforest-1.12.2-3.10.1013-universal.jar             | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-SNAPSHOT           | VanillaFix-1.0.10-99.jar                                  | None                                     |
       | LCHIJA | variedcommodities    | 1.12.2                    | VariedCommodities_1.12.2(21nov19).jar                     | None                                     |
       | LCHIJA | worldhandler         | 2.2.2                     | WorldHandler-1.12.2-2.2.2.jar                             | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCHIJA | woc                  | 0.5                       | WorldOfChemistry-0.5.jar                                  | None                                     |
       | LCHIJA | xaerominimap         | 1.19.7                    | Xaeros_Minimap_1.19.7_Forge_1.12.jar                      | None                                     |
       | LCHIJA | xaeroworldmap        | 1.5.4                     | XaerosWorldMap_1.5.4_Forge_1.12.jar                       | None                                     |
       | LCHIJA | thebetweenlands      | 3.5.6                     | TheBetweenlands-3.5.6-universal.jar                       | 38067d6878811efb38b6a045521cfd80b9b60b38 |
  Loaded coremods (and transformers): JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
                                        techguns.core.TechgunsASMTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.16.4.478
              Runtime Debofucsation 1
              RenderEngine: 1
  Suspected Mods: The Betweenlands (thebetweenlands)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Nessark'/18, l='New World', x=36.98, y=121.00, z=-250.66]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by theishiopian** [comment]
please do not post crash reports directly into issues, provide a pastebin link instead.

Looks like the betweenlands is incompatible with simple dimensions, something to do with not being able to add a capability to the dimension.

**Comment by TheCyberBrick** [comment]
Yep, that's an incompatibility with Simple-Dimensions. This has already been reported to Simple-Dimensions a long time ago

**Comment by TheCyberBrick** [comment]
Apparently there exists a jar file with the fix on this PR: https://github.com/lumien231/Simple-Dimensions/pull/13. Use at your own risk, that file is not provided by the original author.
