### ISSUE TITLE
Food should turn into 'Rotten Food' when you go through the portal.

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#97]
Basically, all consumable items apart from potions.  Rotten food causes poison when eaten.

**Comment by SanAndreasP** [comment]
Do you want to have it like "All food items turn into one 'Rotten Food Piece' item" or like "All Food turns into one item with different 'rotten' textures"?

**Comment by MrCompost** [comment]
Well I was just thinking of having them turn into one Rotten Food item.
