### ISSUE TITLE
[1.12] Random crash for seemingly no reason

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [TheCyberBrick/The-Betweenlands#970]
#### Betweenlands version:

3.413
#### Forge version:

14.23.5.2836

#### Singleplayer or Multiplayer:

SSP

#### Installed mods:

Enigmatica 2 Modpack (Non-Expert): https://www.curseforge.com/minecraft/modpacks/enigmatica2
+Integrated Dynamics
+Plant Mega Pack
+Fossils and Archaeology Revival
+Silent's Gems
+Metallurgy
+Shincolle (yes there's a 1.12 version)

## Link to full crash log

https://paste.dimdev.org/xatujunuki.mccrash

#### How to reproduce:

1. Doing various things in the Overworld
2. Crash
3. etc...

#### Expected result:

No crash

#### Actual result:

Happens seemingly randomly, just crashing with no set reason at odd times

**Comment by GoryMoon** [comment]
This has been fixed in 3.5.5+, update the pack or the mod if you have added it yourself.
