### ISSUE TITLE
[1.12.2] Sound library is not OpenAL library

### ISSUE THREAD

**Issue by pimalel233** [TheCyberBrick/The-Betweenlands#971]
#### Betweenlands version:
TheBetweenlands-3.5.6-Universal.jar

#### Forge version:
Forge 14.23.5.2838

#### Singleplayer or Multiplayer:
When launching the game, before opening up SP or MP

#### Installed mods:
https://pastebin.com/CU89aSvR

## Link to full crash log
No crash

#### How to reproduce:
Just run the game and check the logs ->
[00:23:00] [Client thread/ERROR] [thebetweenlands.client.audio.SoundSystemOpenALAccess]: Sound library is not OpenAL library
I am guessing some mod add checks or something as when run with Forge+Betweenlads only I did not notice the error

#### Expected result:
I guess no information about the error?

#### Actual result:
[00:23:00] [Client thread/ERROR] [thebetweenlands.client.audio.SoundSystemOpenALAccess]: Sound library is not OpenAL library

Question is, it is something that can be safely ignored?

**Comment by TheCyberBrick** [comment]
Yep, you can ignore it. This is caused by an incompatibility with one of your sound mods. The only slight problem you may run into is that greebling's music may not be synced up.
