### ISSUE TITLE
(Suggestion)Make Hag Dance Make Hags Dance Since It's Called Hag Dance, and Ought to Cause an Outbreak of Hag Dancing

### ISSUE THREAD

**Issue by JimmothyTheGreat** [TheCyberBrick/The-Betweenlands#972]
Whenever the Hag Dance music disc is played near a swamp hag, they should become very docile, and begin to dance. Why? Well, I cite the title.

**Comment by PetasiGit** [comment]
Dancing mobs are an overly suggested idea for mods. Kinda makes the vanilla parrots less special if other mobs can dance too, don’t you think? I’m gonna close this because it’s a bit silly and I don’t think it will be added.
