### ISSUE TITLE
Crashes before title screen

### ISSUE THREAD

**Issue by Severynn99** [TheCyberBrick/The-Betweenlands#973]
#### Betweenlands version:

3.5.6

#### Forge version:

1.12.2-14.23.5.28.47

#### Singleplayer or Multiplayer:

Before starting to play, but intended singleplayer

#### Installed mods:

https://paste.dimdev.org/raw/olicunojak

## Link to full crash log

https://paste.dimdev.org/izuyasafow.mccrash

#### How to reproduce:

1. Open minecraft launcher with many mods
2. Click play
3. Let game load
4. Crashes before fully loaded

#### Expected result:

Letting me play minecraft, but it doesn't even get to the title screen

#### Actual result:

Crashes before it reaches the title screen

#### Pictures:

Proof of it being this mod
![](https://cdn.discordapp.com/attachments/620555714921889792/675445102377828353/Betweenlands_Crash.png)

**Comment by pau101** [comment]
Thanks for reporting!

This crash indicates you are playing with too many mods creating more than the supported number of blocks. Nothing we can resolve on our end.

**Comment by Severynn99** [comment]
Ah :/ So if this mod is removed, I can play? That sucks, I really like the mod. But thank you

**Comment by pau101** [comment]
I don't know how many blocks over the maximum this mod set is over, but any mod bringing the block total over max could be removed.

**Comment by Severynn99** [comment]
Is there any way to check that?

**Comment by pau101** [comment]
Just trial and error.

**Comment by Severynn99** [comment]
I believe I fixed it! I added the mod 'NotEnoughIDs' and it runs now. Basically it ups the block ID limit

**Comment by pau101** [comment]
That is an option too. Glad this was resolved.
