### ISSUE TITLE
[Suggestion] /locate command for Betweenlands Dungeons.

### ISSUE THREAD

**Issue by westleysminion** [TheCyberBrick/The-Betweenlands#977]
The vanilla minecraft /locate command but for BL dungeons. Like /locate WightFortress and it'll tell you the coordinates of said Wight Fortress.

**Comment by TheCyberBrick** [comment]
Unfortunately this is not possible with the current implementation. Maybe future versions (for 1.15+) will have this feature, because we'll have to rewrite world gen anyways.
