### ISSUE TITLE
Sporelings

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#98]
Passive mob, spawns only on shelf fungus. Always runs away quickly from the player. Gives off colourful 'spore-like' particles (yeah I dunno how to describe this, just be creative). Drops Spores when killed.

**Comment by vadis365** [comment]
Easy - can port the code from Erebus - they are pretty much the same.

**Comment by MrCompost** [comment]
Ok cool. Are there any other things that could easily be ported over from the Erebus or the old BL?

**Comment by PCAwesomeness** [comment]
Is the Sporeling 100% done?

**Comment by MrCompost** [comment]
Ok, Sporeling works great. Just needs to be faster (probably twice the speed it is now) and it should be finished.
