### ISSUE TITLE
"Ticking Player" Crash Softlocked Me Out Of My World

### ISSUE THREAD

**Issue by UndyneTheFreddyKiller** [TheCyberBrick/The-Betweenlands#980]
Betweenlands version: 3.5.6
Forge version: 14.23.5.2847
Singleplayer or Multiplayer: Singleplayer
Installed mods:
Aether Legacy (1.4.4), Twilight Forest (3.10.1013), Optifine
Link to full crash log: https://docs.google.com/document/d/1B9F93lAkxkwk-S_OIG1aWGHvrQb0XzGJkDYdw6nGb8k/edit?usp=sharing

Description of the problem: The game suddenly crashed while I was walking through the betweenlands dimension (specifically patchy islands biome). Attempting to reload the world causes the game to crash again, making me unable to get back into my world.

Crash report mentions the amate map, which I was using as guidance. World had been corrupted once before but the only effect that caused was rifts where old and new chunks were being generated. I was thoroughly playing through both Aether and Twilight Forest fine after the corruption occurred and had also managed to make progress in Betweenlands as well.

Betweenlands had been running fine aside from a few lag spikes now and then. I was trying to gather plants and this crash came out of nowhere.

How to reproduce:
1. Enter Betweenlands dimension
2. Explore the area
3. Game suddenly closes at random without notice
4. Attempt to load the world again
5. Game crashes again
6. Repeat steps 4 and 5 for infinity

Expected result: World loads fine and I'm able to keep playing
Actual result: Game is stuck in a crash loop softlocking me out of my world

If you have already had this issue or have a solution for it, please let me know.

**Comment by TheCyberBrick** [comment]
This does not look like a BL bug.
It's likely the result of the previous world corruption you mentioned.
There's not much you can do except trying to save your world by using some program like MCEdit to remove nearby chunks around the player or the entire region the player is in.
