### ISSUE TITLE
[SUGGESTION] Portal Redesign

### ISSUE THREAD

**Issue by Shazuli** [TheCyberBrick/The-Betweenlands#982]
***Hi***

This issue might sound a bit rude, but that was not the intention and just to clarify the point.

Right now, you get to the Betweenlands by using the Swamp Talisman on a Sapling which will spawn a Portal Tree. But the way it works feels really minuscule compared to the rest of the mod. The tree is obnoxiously large, you spawn it by using it on a sapling like Bonemeal and has an instant transformation from 1x1x1 to 19x19x19. It really doesn't fit in together with the rest of this awesome mod.

I won't just complain, I'm going to list a few other possible ways to get there/assemble the portal.

## 1. Organic Portal Frame (make it smaller)
The first is to keep the tree design, but make it less obnoxiously large. The new smaller tree has more twists and the portal blocks spawn directly inside of it, the frame *is* the tree.
![2020-02-23_20 49 14](https://user-images.githubusercontent.com/9884180/75164947-e40fcf00-5721-11ea-9e55-6ed2b257aee1.png)

## 2. Corrupted Nether Portal (even smaller)
Another suggestion for a portal frame:
The lore of the Betweenlands was that the druid opened a Nether Portal inside of the Betweenlands and due to unknown factors corrupted him and his followers to creatures of the night. The Prime Wright like you guys wrote made the Betweenlands the way it is now, shouldn't it make sense for a Nether Portal to be the key to the Betweenlands? Maybe throwing the Swamp Talisman into a valid Nether Portal will turn it into a portal to the Betweenlands. This change could be animated with a gradual colour tint from purple to green while the Obsidian frame around it gets replaced with a corrupted variant of itself suitable for the new portal blocks.
## 3. One Way Trip
Getting there is simple, leaving is another matter. The Swamp Talisman is a key to there, not the other way around. When clicked on a flat wall the Swamp Talisman will insert itself into the wall, turn, and disappear. Shortly after a green rift will open allowing for the player to enter. When spawning in there you can see the rift open behind you, allowing a short window for you to return back to the Overworld before it closes forever. Leaving after the rift has closed can only be done with another Swamp Talisman, but they only exist in the Overworld so you have to get it from the Prime Wright for the "Primal Swamp Talisman" which is re-usable. Additional Swamp Talismans can't be brought through the rift. They will drop out of the player's inventory on the ground or be destroyed. The Primal Swamp Talisman is the only exception.
Or maybe instead of the Swamp Talisman being destroyed on use it will remain intact allowing for infinite use. A config option could make the Swamp Talisman unusable in the Betweenlands with a message or toast notification "Something is preventing the Talisman to work" or along that line. When defeating the Prime Wright you can use your original Swamp Talisman on something there (ex. death animation) to turn it into the upgraded Primal Swamp Talisman or simply allowing it to open portals without interference.

Hopefully you guys don't get the wrong idea what I'm trying to explain. I just think the portal is the weakest part of this mod and has a lot of potential to be better.

**Comment by WightofShadows** [comment]
Hi! I appreciate you trying to not come off as rude, and I'll try to do the same in response. Note I'm a wiki admin for the mod and not its only voice, so don't take my opinion as the final say :P

Personally, I'm not entirely sure how the Portal Tree is "minuscule" compared to the rest of the mod, or how these suggestions make it "not minuscule." I can understand the sentiment behind the tree being too big, but to me that makes entry grand and fittingly nature-based, and it provides a relatively safe starting space when you first enter the dimension. If you need the space, you could make the tree in an unused part of your world, mine up the blocks necessary to make the smaller portal and take them back to where you want to reconstruct it.

As for lore reasons, we usually prefer gameplay over lore connections when we design content. As such, I think simply turning a Nether portal into a Betweenlands one would be rather lackluster, as it would emulate the same simple frame appearance that so many other dimension mods share. Even when taking lore into account I don't think the Betweenlands was supposed to be inherently connected to the Nether. It existed before any "corruption" occurred and this portal seems more fitting to what the Betweenlands originally was (and still, in large part, is). This kinda ties into how lots of people view the mod as being a "horror mod" when in fact horror is just one aspect of a very lively world connected to plant and animal life, botany, etc.

For the one way trip thing, that could be an interesting config option to add for the hardcore people, but forcing a one-way experience onto players would likely serve to frustrate more than excite. Having the option to go back is also a large part of how modpacks work, or simply playing with other mods and being able to access their content.

Anyway, that's my take. Admittedly we could have gone even more creative with the portal (someone in our team thought up the idea of liquid portals, but I'm pretty sure the programming requirements for that would be ridiculous!), and I won't rule out the possibility of expanding upon it in the future.

**Comment by Shazuli** [comment]
> Hi! I appreciate you trying to not come off as rude, and I'll try to do the same in response. Note I'm a wiki admin for the mod and not its only voice, so don't take my opinion as the final say :P
> 
> Personally, I'm not entirely sure how the Portal Tree is "minuscule" compared to the rest of the mod, or how these suggestions make it "not minuscule." I can understand the sentiment behind the tree being too big, but to me that makes entry grand and fittingly nature-based, and it provides a relatively safe starting space when you first enter the dimension. If you need the space, you could make the tree in an unused part of your world, mine up the blocks necessary to make the smaller portal and take them back to where you want to reconstruct it.
> 
> As for lore reasons, we usually prefer gameplay over lore connections when we design content. As such, I think simply turning a Nether portal into a Betweenlands one would be rather lackluster, as it would emulate the same simple frame appearance that so many other dimension mods share. Even when taking lore into account I don't think the Betweenlands was supposed to be inherently connected to the Nether. It existed before any "corruption" occurred and this portal seems more fitting to what the Betweenlands originally was (and still, in large part, is). This kinda ties into how lots of people view the mod as being a "horror mod" when in fact horror is just one aspect of a very lively world connected to plant and animal life, botany, etc.
> 
> For the one way trip thing, that could be an interesting config option to add for the hardcore people, but forcing a one-way experience onto players would likely serve to frustrate more than excite. Having the option to go back is also a large part of how modpacks work, or simply playing with other mods and being able to access their content.
> 
> Anyway, that's my take. Admittedly we could have gone even more creative with the portal (someone in our team thought up the idea of liquid portals, but I'm pretty sure the programming requirements for that would be ridiculous!), and I won't rule out the possibility of expanding upon it in the future.

Ah, whoops, "minuscule" might have been the wrong word to explain it. With "minuscule" I mean the portal tree doesn't seem to be on the same level as the rest of the mod, and in trying to do so is way too large and complicated (branches generating in complex shapes for example) for what it does. My suggestions are just examples of ways to improve it. Two are plain vanilla style portals with frames (the tree design and corrupted Nether portal idea) while the third is a more creative and complicated solution.
I wouldn't say my ideas are good and better than the original portal tree, I just feel like the current portal tree could be improved upon and my listed ideas are just, in my opinion, ways to improve it.

**Comment by vadis365** [comment]
Thank you for your suggestion - it has been closed, but not forgotten, in order for us to be able to manage our issue tracker for bugs.
