### ISSUE TITLE
Game crash when put an edge plant on puddle

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TheCyberBrick/The-Betweenlands#987]
#### Installed mods:

1. AppleSkin-mc1.12-1.0.9
2. Baubles-1.12-1.5.2
3. BetterAdvancements-1.12.2-0.0.17.75
4. CarryOn+MC1.12.2+v1.12.1
5. ChickenChunks-1.12.2-2.4.1.73-universal
6. CodeChickenLib-1.12.2-3.2.2.353-universal
7. CoFHCore-1.12.2-4.6.3.27-universal
8. CoFHWorld-1.12.2-1.3.1.7-universal
9. FasterLadderClimbing-1.12-0.1-146
10. foamfix-0.10.9-1.12.2
11. forge-1.12.2-14.23.5.2847-universal
12. GlobalGameRules-1.12.2-2.2.7
13. good-nights-sleep-1.12.2-v0.2.2
14. InputMethodBlocker-1.11-1.12.2-2.2-SNAPSHOT
15. InventoryTweaks-1.64+dev.146
16. ironchest-1.12.2-7.0.72.847
17. jei_1.12.2-4.15.0.293
18. journeymap-1.12.2-5.5.9
19. JustEnoughCharacters-1.12.0-3.4.2
20. MouseTweaks-2.10-mc1.12.2
21. NaturesCompass-1.12.2-1.6.2
22. OreExcavation-1.4.143
23. realfilingcabinet-1.12-0.2.0.20
24. RedstoneFlux-1.12-2.1.0.6-universal
25. <b>TheBetweenlands-3.5.7-universal</b>
26. theoneprobe-1.12-1.4.28
27. ThermalDynamics-1.12.2-2.5.5.21-universal
28. ThermalExpansion-1.12.2-5.5.4.43-universal
29. ThermalFoundation-1.12.2-2.6.3.27-universal
30. ThermalInnovation-1.12.2-0.3.3.12-universal
31. topaddons-1.12.2-1.12.0
32. torohealth-1.12.2-11
33. touhoulittlemaid-1.12.2-1.1.10-beta
34. twilightforest-1.12.2-3.10.1013-universal
35. VanillaFix-1.0.10-98

## Link to full crash log

https://gist.github.com/mcBegins2Snow/6e5aeefbea52c433e45a6699fb4726f5

## Description of the problem
Game crash when put an edge plant and the top has a puddle.
#### How to reproduce:

1.Rain in the Betweenland or put a puddle on the grass block in creative.
2.Let the grass block cover the puddle.
3.Put a block next to the puddle.
4.Try to right click the puddle to put an edge mushroom on it.

#### Expected result:

The edge mushroom has put successfully.

#### Actual result:

Game crash.

#### Pictures:

![2020-03-02_14 58 51](https://user-images.githubusercontent.com/37864486/75652661-97367600-5c96-11ea-90e6-41d59e68ab5a.png)

**Comment by TheCyberBrick** [comment]
Thanks 👍
