### ISSUE TITLE
Dragonfly 

### ISSUE THREAD

**Issue by MrCompost** [TheCyberBrick/The-Betweenlands#99]
Passive mob. Acts kinda like bats - flies around, and sometimes lands on blocks. Flies away when disturbed, also like bats. Drops Dragonfly Wings when killed.

**Comment by PCAwesomeness** [comment]
Will the dragonfly be silent or will it make a sound that sounds like a mix of fly buzzing and helicopter rotors when in the air?

**Comment by PCAwesomeness** [comment]
What still needs to be done with the Dragonfly?
