### ISSUE TITLE
Drag clicking to split items in Dual Furnace wipes furnace inventory

### ISSUE THREAD

**Issue by braingkk** [TheCyberBrick/The-Betweenlands#992]
MC: 1.12.2
ModVersion: 3.5.7
Forge 14.23.5.2847

Happens both in singleplayer and multiplayer
Tested with just betweenlands on a clean instance
Crashlog: N/A

When drag clicking items into a **_FUELED_** dual sulfur furnace, you will get kicked out of the GUI and the inventory will be cleared.

Reproduction steps:
1) place a Dual Sulfur Furnace.
2) place some sort of fuel in the fuel slots.
3) click drag something to be smelted between the two valid destination slots.
4) get kicked out of the GUI and lose all contents of the furnace.

Expected: 
Stack should split and smelt properly.

Actual:
furnace inventory wiped.

Video: https://youtu.be/DgUjX8JxBI0

**Comment by TheCyberBrick** [comment]
Good catch, thanks for the report.
