### ISSUE TITLE
I need help with my RAD modpack and The Betweenlands.

### ISSUE THREAD

**Issue by boylookinglikeanoob** [TheCyberBrick/The-Betweenlands#994]
I don't see why I need to write a bug report if I don't even know what happened but I have a crash report which should tell you why The Betweenlands is causing my game to crash. https://paste.dimdev.org/aqohulixop.mccrash

**Comment by braingkk** [comment]
looks like you have more than 4096 items in your modpack, which w/o one of the mods that increase item limit will make your pack not work.

[just Enough ID's ](https://www.curseforge.com/minecraft/mc-mods/jeid) is a commonly used mod for the fix, tho there are others.

**Comment by TheCyberBrick** [comment]
^
Yep, that's it.
