### ISSUE TITLE
decay bar missing in game screen, yet decay system works in the betweenlands.

### ISSUE THREAD

**Issue by adamhur** [TheCyberBrick/The-Betweenlands#999]
#### Betweenlands version:

twilightforest-1.12.2-3.9.984-universal

#### Forge version:

forge-1.12.2-2838-7.1.9

#### Singleplayer or Multiplayer:

Multiplayer

#### Installed mods:

twilight forest,
spongeforge

## Link to full crash log

it is not crashing, the decay bar is missing on the screen.

#### How to reproduce:

1.the decay bar is missing on the screen.
2.but decay system works totally fine.
3. etc...

**Comment by WightofShadows** [comment]
Uhh...do you have Betweenlands installed at all?
